[[using.build-systems]]
= 构建系统

强烈建议你选择一个支持 xref:using/build-systems.adoc#using.build-systems.dependency-management[依赖管理] 并且可以使用发布到 Maven Central 仓库的构件的构建系统。
我们建议你选择 Maven 或 Gradle。
虽然可以让 Spring Boot 与其他构建系统（例如 Ant）一起工作，但它们并不是特别受支持。



[[using.build-systems.dependency-management]]
== 依赖管理

每个 Spring Boot 版本都提供了一个它支持的依赖项精选列表。
实际上，你不需要在构建配置中为这些依赖项中的任何一个提供版本，因为 Spring Boot 会为你管理这些。
当你升级 Spring Boot 本身时，这些依赖项也会以一致的方式升级。

注意：如果你需要这样做，你仍然可以指定版本并覆盖 Spring Boot 的建议。

精选列表包含你可以与 Spring Boot 一起使用的所有 Spring 模块以及精选的第三方库列表。
该列表可作为标准的物料清单（`spring-boot-dependencies`）使用，可以与 xref:using/build-systems.adoc#using.build-systems.maven[Maven] 和 xref:using/build-systems.adoc#using.build-systems.gradle[Gradle] 一起使用。

警告：每个 Spring Boot 版本都与 Spring Framework 的基础版本相关联。
我们**强烈**建议你不要指定其版本。



[[using.build-systems.maven]]
== Maven

要了解如何将 Spring Boot 与 Maven 一起使用，请参阅 Spring Boot 的 Maven 插件文档：

* xref:maven-plugin:index.adoc[参考]
* xref:maven-plugin:api/java/index.html[API]



[[using.build-systems.gradle]]
== Gradle

要了解如何将 Spring Boot 与 Gradle 一起使用，请参阅 Spring Boot 的 Gradle 插件文档：

* xref:gradle-plugin:index.adoc[参考]
* xref:gradle-plugin:api/java/index.html[API]



[[using.build-systems.ant]]
== Ant

可以使用 Apache Ant+Ivy 构建 Spring Boot 项目。
`spring-boot-antlib` "`AntLib`" 模块也可用于帮助 Ant 创建可执行 jar。

要声明依赖项，典型的 `ivy.xml` 文件如下所示：

[source,xml]
----
<ivy-module version="2.0">
	<info organisation="org.springframework.boot" module="spring-boot-sample-ant" />
	<configurations>
		<conf name="compile" description="everything needed to compile this module" />
		<conf name="runtime" extends="compile" description="everything needed to run this module" />
	</configurations>
	<dependencies>
		<dependency org="org.springframework.boot" name="spring-boot-starter"
			rev="${spring-boot.version}" conf="compile" />
	</dependencies>
</ivy-module>
----

典型的 `build.xml` 如下所示：

[source,xml,subs="verbatim,attributes"]
----
<project
	xmlns:ivy="antlib:org.apache.ivy.ant"
	xmlns:spring-boot="antlib:org.springframework.boot.ant"
	name="myapp" default="build">

	<property name="spring-boot.version" value="{version-spring-boot}" />

	<target name="resolve" description="--> retrieve dependencies with ivy">
		<ivy:retrieve pattern="lib/[conf]/[artifact]-[type]-[revision].[ext]" />
	</target>

	<target name="classpaths" depends="resolve">
		<path id="compile.classpath">
			<fileset dir="lib/compile" includes="*.jar" />
		</path>
	</target>

	<target name="init" depends="classpaths">
		<mkdir dir="build/classes" />
	</target>

	<target name="compile" depends="init" description="compile">
		<javac srcdir="src/main/java" destdir="build/classes" classpathref="compile.classpath" />
	</target>

	<target name="build" depends="compile">
		<spring-boot:exejar destfile="build/myapp.jar" classes="build/classes">
			<spring-boot:lib>
				<fileset dir="lib/runtime" />
			</spring-boot:lib>
		</spring-boot:exejar>
	</target>
</project>
----

提示：如果你不想使用 `spring-boot-antlib` 模块，请参阅 "`How-to Guides`" 中的 xref:how-to:build.adoc#howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib[] 部分。



[[using.build-systems.starters]]
== Starters

Starters 是一组方便的依赖描述符，你可以将其包含在应用程序中。
你可以一站式获取所有需要的 Spring 和相关技术，而无需在示例代码中查找和复制粘贴大量依赖描述符。
例如，如果你想开始使用 Spring 和 JPA 进行数据库访问，请在项目中包含 `spring-boot-starter-data-jpa` 依赖项。

Starters 包含许多依赖项，这些依赖项可以帮助你快速启动项目，并提供一组一致的、受支持的托管传递依赖项。

.名称的含义
****
所有**官方** starters 都遵循类似的命名模式；`+spring-boot-starter-*+`，其中 `+*+` 是特定类型的应用程序。
这种命名结构旨在帮助你查找 starter。
许多 IDE 中的 Maven 集成允许你按名称搜索依赖项。
例如，安装了适当的 Eclipse 或 Spring Tools 插件后，你可以在 POM 编辑器中按 `ctrl-space` 并输入 "`spring-boot-starter`" 以获取完整列表。

如 xref:features/developing-auto-configuration.adoc#features.developing-auto-configuration.custom-starter[] 部分所述，第三方 starters 不应以 `spring-boot` 开头，因为它保留给官方 Spring Boot 构件。
相反，第三方 starter 通常以项目名称开头。
例如，一个名为 `thirdpartyproject` 的第三方 starter 项目通常会被命名为 `thirdpartyproject-spring-boot-starter`。
****

以下应用程序 starters 由 Spring Boot 在 `org.springframework.boot` 组下提供：

.Spring Boot 应用程序 starters
include::ROOT:partial$starters/application-starters.adoc[]

除了应用程序 starters 之外，以下 starters 可用于添加 xref:how-to:actuator.adoc[生产就绪] 功能：

.Spring Boot 生产 starters
include::ROOT:partial$starters/production-starters.adoc[]

最后，Spring Boot 还包括以下 starters，如果你想排除或交换特定的技术方面，可以使用它们：

.Spring Boot 技术 starters
include::ROOT:partial$starters/technical-starters.adoc[]

要了解如何交换技术方面，请参阅有关 xref:how-to:webserver.adoc#howto.webserver.use-another[交换 Web 服务器] 和 xref:how-to:logging.adoc#howto.logging.log4j[日志系统] 的 how-to 文档。

提示：有关其他社区贡献的 starters 列表，请参阅 GitHub 上 `spring-boot-starters` 模块中的 {code-spring-boot-latest}/spring-boot-project/spring-boot-starters/README.adoc[README 文件]。
