[[using.configuration-classes]]
= 配置类

Spring Boot 倾向于使用基于 Java 的配置。
虽然可以使用 javadoc:org.springframework.boot.SpringApplication[] 和 XML 源，但我们通常建议你的主要源是一个单一的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类。
通常，定义 `main` 方法的类是作为主要 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 的良好候选。

TIP: 互联网上已经发布了许多使用 XML 配置的 Spring 配置示例。
如果可能，始终尝试使用等效的基于 Java 的配置。
搜索 `+Enable*+` 注解可能是一个好的起点。



[[using.configuration-classes.importing-additional-configuration]]
== 导入其他配置类

你不必将所有 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 都放在一个类中。
可以使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 注解导入其他配置类。
或者，你可以使用 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] 自动获取所有 Spring 组件，包括 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类。



[[using.configuration-classes.importing-xml-configuration]]
== 导入 XML 配置

如果你必须使用基于 XML 的配置，我们建议你仍然从 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类开始。
然后你可以使用 javadoc:org.springframework.context.annotation.ImportResource[format=annotation] 注解来加载 XML 配置文件。
