[[using.configuration-classes]]
= 配置类

Spring Boot 倾向于基于 Java 的配置。
虽然可以将 javadoc:org.springframework.boot.SpringApplication[] 与 XML 源一起使用，但我们通常建议你的主要源是单个 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类。
通常，定义 `main` 方法的类是作为主要 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 的良好候选者。

提示：互联网上已经发布了许多使用 XML 配置的 Spring 配置示例。
如果可能，始终尝试使用等效的基于 Java 的配置。
搜索 `+Enable*+` 注解可能是一个好的起点。



[[using.configuration-classes.importing-additional-configuration]]
== 导入其他配置类

你不必将所有 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 都放在单个类中。
可以使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 注解导入其他配置类。
或者，你可以使用 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] 自动获取所有 Spring 组件，包括 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类。



[[using.configuration-classes.importing-xml-configuration]]
== 导入 XML 配置

如果你绝对必须使用基于 XML 的配置，我们仍然建议你从 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类开始。
然后，你可以使用 javadoc:org.springframework.context.annotation.ImportResource[format=annotation] 注解加载 XML 配置文件。
