[[using.running-your-application]]
= 运行您的应用程序

将应用程序打包为 jar 并使用嵌入式 HTTP 服务器的最大优势之一是，您可以像运行其他程序一样运行您的应用程序。
这也适用于调试 Spring Boot 应用程序。
您不需要任何特殊的 IDE 插件或扩展。

注意：以下选项最适合在本地开发环境中运行应用程序。
对于生产环境部署，请参见 xref:reference:using/packaging-for-production.adoc[]。

注意：本节仅涵盖基于 jar 的打包。
如果您选择将应用程序打包为 war 文件，请参阅您的服务器和 IDE 文档。



[[using.running-your-application.from-an-ide]]
== 从 IDE 运行

您可以从 IDE 中将 Spring Boot 应用程序作为 Java 应用程序运行。
但是，您首先需要导入您的项目。
导入步骤因您的 IDE 和构建系统而异。
大多数 IDE 可以直接导入 Maven 项目。
例如，Eclipse 用户可以从 `File` 菜单中选择 `Import...` -> `Existing Maven Projects`。

如果您无法直接将项目导入到 IDE 中，您可以使用构建插件生成 IDE 元数据。
Maven 包含 https://maven.apache.org/plugins/maven-eclipse-plugin/[Eclipse] 和 https://maven.apache.org/plugins/maven-idea-plugin/[IDEA] 的插件。
Gradle 为 {url-gradle-docs}/userguide.html[各种 IDE] 提供插件。

提示：如果您不小心运行了两次 Web 应用程序，您会看到"`Port already in use`"错误。
Spring Tools 用户可以使用 `Relaunch` 按钮而不是 `Run` 按钮，以确保关闭任何现有实例。



[[using.running-your-application.as-a-packaged-application]]
== 作为打包应用程序运行

如果您使用 Spring Boot Maven 或 Gradle 插件创建可执行 jar，您可以使用 `java -jar` 运行您的应用程序，如下例所示：

[source,shell]
----
$ java -jar target/myapplication-0.0.1-SNAPSHOT.jar
----

还可以在启用远程调试支持的情况下运行打包的应用程序。
这样做可以让您将调试器附加到打包的应用程序，如下例所示：

[source,shell]
----
$ java -agentlib:jdwp=server=y,transport=dt_socket,address=8000,suspend=n \
       -jar target/myapplication-0.0.1-SNAPSHOT.jar
----



[[using.running-your-application.with-the-maven-plugin]]
== 使用 Maven 插件

Spring Boot Maven 插件包含一个 `run` 目标，可用于快速编译和运行您的应用程序。
应用程序以展开形式运行，就像在 IDE 中一样。
以下示例显示了运行 Spring Boot 应用程序的典型 Maven 命令：

[source,shell]
----
$ mvn spring-boot:run
----

您可能还想使用 `MAVEN_OPTS` 操作系统环境变量，如下例所示：

[source,shell]
----
$ export MAVEN_OPTS=-Xmx1024m
----



[[using.running-your-application.with-the-gradle-plugin]]
== 使用 Gradle 插件

Spring Boot Gradle 插件还包含一个 `bootRun` 任务，可用于以展开形式运行您的应用程序。
每当您应用 `org.springframework.boot` 和 `java` 插件时，都会添加 `bootRun` 任务，如下例所示：

[source,shell]
----
$ gradle bootRun
----

您可能还想使用 `JAVA_OPTS` 操作系统环境变量，如下例所示：

[source,shell]
----
$ export JAVA_OPTS=-Xmx1024m
----



[[using.running-your-application.hot-swapping]]
== 热交换

由于 Spring Boot 应用程序是普通的 Java 应用程序，JVM 热交换应该可以开箱即用。
JVM 热交换在可以替换的字节码方面有些限制。
对于更完整的解决方案，可以使用 https://www.jrebel.com/products/jrebel[JRebel]。

`spring-boot-devtools` 模块还包括对快速应用程序重启的支持。
有关详细信息，请参见 "`How-to Guides`" 中的 xref:how-to:hotswapping.adoc[] 部分。
