[[using.spring-beans-and-dependency-injection]]
= Spring Beans 和依赖注入

您可以自由使用任何标准的 Spring Framework 技术来定义您的 bean 和它们的注入依赖。
我们通常建议使用构造函数注入来连接依赖，并使用 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] 来查找 bean。

如果您按照上述建议构建代码（将应用程序类放在顶层包中），您可以添加不带任何参数的 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]，或使用隐式包含它的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解。
您的所有应用程序组件（javadoc:org.springframework.stereotype.Component[format=annotation]、javadoc:org.springframework.stereotype.Service[format=annotation]、javadoc:org.springframework.stereotype.Repository[format=annotation]、javadoc:org.springframework.stereotype.Controller[format=annotation] 等）都会自动注册为 Spring Bean。

以下示例显示了一个 javadoc:org.springframework.stereotype.Service[format=annotation] Bean，它使用构造函数注入来获取所需的 `RiskAssessor` bean：

include-code::singleconstructor/MyAccountService[]

如果一个 bean 有多个构造函数，您需要使用 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 标记您希望 Spring 使用的那个：

include-code::multipleconstructors/MyAccountService[]

提示：注意使用构造函数注入如何让 `riskAssessor` 字段被标记为 `final`，表明它之后不能被更改。
