[[using.structuring-your-code]]
= 构建您的代码

Spring Boot 不需要任何特定的代码布局就能工作。
但是，有一些最佳实践可以提供帮助。

提示：如果您希望基于领域强制执行结构，请查看 https://spring.io/projects/spring-modulith#overview[Spring Modulith]。



[[using.structuring-your-code.using-the-default-package]]
== 使用"default"包

当一个类不包含 `package` 声明时，它被认为是在"`default package`"中。
通常不鼓励使用"`default package`"，应该避免使用。
它可能会对使用 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]、javadoc:org.springframework.boot.context.properties.ConfigurationPropertiesScan[format=annotation]、javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 或 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解的 Spring Boot 应用程序造成特殊问题，因为会读取每个 jar 中的每个类。

提示：我们建议您遵循 Java 推荐的包命名约定，并使用反向域名（例如，`com.example.project`）。



[[using.structuring-your-code.locating-the-main-class]]
== 定位主应用程序类

我们通常建议您将主应用程序类放在其他类的根包之上。
xref:using/using-the-springbootapplication-annotation.adoc[`@SpringBootApplication` 注解] 通常放在您的主类上，它隐式地为某些项目定义了基础"`search package`"。
例如，如果您正在编写 JPA 应用程序，则使用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解的类的包来搜索 javadoc:jakarta.persistence.Entity[format=annotation] 项目。
使用根包还允许组件扫描仅应用于您的项目。

提示：如果您不想使用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]，它导入的 javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation] 和 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] 注解定义了该行为，因此您也可以使用这些注解代替。

以下列表显示了一个典型的布局：

[source]
----
com
 +- example
     +- myapplication
         +- MyApplication.java
         |
         +- customer
         |   +- Customer.java
         |   +- CustomerController.java
         |   +- CustomerService.java
         |   +- CustomerRepository.java
         |
         +- order
             +- Order.java
             +- OrderController.java
             +- OrderService.java
             +- OrderRepository.java
----

`MyApplication.java` 文件将声明 `main` 方法，以及基本的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]，如下所示：

include-code::MyApplication[]
