[[using.using-the-springbootapplication-annotation]]
= 使用 @SpringBootApplication 注解

许多 Spring Boot 开发者喜欢他们的应用程序使用自动配置、组件扫描，并能够在他们的 "application class" 上定义额外的配置。
一个 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解就可以启用这三个功能，即：

* javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation]：启用 xref:using/auto-configuration.adoc[Spring Boot 的自动配置机制]
* javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]：在应用程序所在的包上启用 javadoc:org.springframework.stereotype.Component[format=annotation] 扫描（参见 xref:using/structuring-your-code.adoc[最佳实践]）
* javadoc:org.springframework.boot.SpringBootConfiguration[format=annotation]：启用在上下文中注册额外的 beans 或导入额外的配置类。
这是 Spring 标准的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 的替代方案，它有助于在你的集成测试中进行 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[配置检测]。

include-code::springapplication/MyApplication[]

NOTE: javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 还提供了别名来自定义 javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation] 和 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] 的属性。

[NOTE]
====
这些功能都不是强制性的，你可以选择用它所启用的任何功能来替换这个单一注解。
例如，你可能不想在你的应用程序中使用组件扫描或配置属性扫描：

include-code::individualannotations/MyApplication[]

在这个例子中，`MyApplication` 就像任何其他 Spring Boot 应用程序一样，只是 javadoc:org.springframework.stereotype.Component[format=annotation] 注解的类和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] 注解的类不会被自动检测，用户定义的 beans 会被显式导入（参见 javadoc:org.springframework.context.annotation.Import[format=annotation]）。
====
