[[build-tool-plugins.antlib]]
= Spring Boot AntLib 模块

Spring Boot AntLib 模块为 Apache Ant 提供基本的 Spring Boot 支持。
您可以使用该模块创建可执行的 jar 文件。
要使用该模块，您需要在 `build.xml` 中声明一个额外的 `spring-boot` 命名空间，如下例所示：

[source,xml]
----
<project xmlns:ivy="antlib:org.apache.ivy.ant"
    xmlns:spring-boot="antlib:org.springframework.boot.ant"
    name="myapp" default="build">
    ...
</project>
----

您需要记住使用 `-lib` 选项启动 Ant，如下例所示：

[source,shell,subs="verbatim,attributes"]
----
$ ant -lib <directory containing spring-boot-antlib-{version spring-boot}.jar>
----

TIP: "`Using Spring Boot`" 部分包含一个更完整的 xref:reference:using/build-systems.adoc#using.build-systems.ant[使用 Apache Ant 与 `spring-boot-antlib`] 的示例。



[[build-tool-plugins.antlib.tasks]]
== Spring Boot Ant 任务

一旦声明了 `spring-boot-antlib` 命名空间，以下额外的任务将可用：

* xref:antlib.adoc#build-tool-plugins.antlib.tasks.exejar[]
* xref:antlib.adoc#build-tool-plugins.antlib.findmainclass[]



[[build-tool-plugins.antlib.tasks.exejar]]
=== 使用 "`exejar`" 任务

您可以使用 `exejar` 任务创建 Spring Boot 可执行 jar 文件。
该任务支持以下属性：

[cols="1,2,2"]
|====
| Attribute | Description | Required

| `destfile`
| 要创建的目标 jar 文件
| Yes

| `classes`
| Java 类文件的根目录
| Yes

| `start-class`
| 要运行的主应用程序类
| No _(默认值为找到的第一个声明 `main` 方法的类)_
|====

该任务支持以下嵌套元素：

[cols="1,4"]
|====
| Element | Description

| `resources`
| 一个或多个 {url-ant-docs}/Types/resources.html#collection[Resource Collections]，描述应添加到创建的 +jar+ 文件内容中的 {url-ant-docs}/Types/resources.html[Resources] 集合。

| `lib`
| 一个或多个 {url-ant-docs}/Types/resources.html#collection[Resource Collections]，应添加到构成应用程序运行时依赖类路径的 jar 库集合中。
|====



[[build-tool-plugins.antlib.tasks.examples]]
=== 示例

本节展示两个 Ant 任务的示例。

.指定 +start-class+
[source,xml]
----
<spring-boot:exejar destfile="target/my-application.jar"
        classes="target/classes" start-class="com.example.MyApplication">
    <resources>
        <fileset dir="src/main/resources" />
    </resources>
    <lib>
        <fileset dir="lib" />
    </lib>
</spring-boot:exejar>
----

.检测 +start-class+
[source,xml]
----
<exejar destfile="target/my-application.jar" classes="target/classes">
    <lib>
        <fileset dir="lib" />
    </lib>
</exejar>
----



[[build-tool-plugins.antlib.findmainclass]]
== 使用 "`findmainclass`" 任务

`findmainclass` 任务由 `exejar` 内部使用，以定位声明 `main` 方法的类。
如有需要，您也可以在构建中直接使用此任务。
支持以下属性：

[cols="1,2,2"]
|====
| Attribute | Description | Required

| `classesroot`
| Java 类文件的根目录
| Yes _(除非指定了 `mainclass`)_

| `mainclass`
| 可用于短路 `main` 类搜索
| No

| `property`
| 应设置结果的 Ant 属性
| No _(如果未指定，结果将记录到日志)_
|====



[[build-tool-plugins.antlib.findmainclass.examples]]
=== 示例

本节包含三个使用 `findmainclass` 的示例。

.查找并记录
[source,xml]
----
<findmainclass classesroot="target/classes" />
----

.查找并设置
[source,xml]
----
<findmainclass classesroot="target/classes" property="main-class" />
----

.覆盖并设置
[source,xml]
----
<findmainclass mainclass="com.example.MainClass" property="main-class" />
----
