[[build-tool-plugins.other-build-systems]]
= 支持其他构建系统

如果您想使用除 Maven、Gradle 或 Ant 之外的其他构建工具，您可能需要开发自己的插件。
可执行 JAR 文件需要遵循特定格式，并且某些条目需要以未压缩的形式写入（详见附录中的 xref:specification:/executable-jar/index.adoc[可执行 JAR 格式] 部分）。

Spring Boot 的 Maven 和 Gradle 插件都使用 `spring-boot-loader-tools` 来实际生成 JAR 文件。
如果需要，您可以直接使用此库。



[[build-tool-plugins.other-build-systems.repackaging-archives]]
== 重新打包存档

要将现有存档重新打包为自包含的可执行存档，请使用 javadoc:org.springframework.boot.loader.tools.Repackager[]。
javadoc:org.springframework.boot.loader.tools.Repackager[] 类接受一个构造函数参数，指向现有的 JAR 或 WAR 存档。
使用两个可用的 `repackage()` 方法之一，可以替换原始文件或写入新目标。
在运行重新打包器之前，还可以配置各种设置。



[[build-tool-plugins.other-build-systems.nested-libraries]]
== 嵌套库

在重新打包存档时，您可以使用 javadoc:org.springframework.boot.loader.tools.Libraries[] 接口来包含对依赖文件的引用。
我们在这里不提供 javadoc:org.springframework.boot.loader.tools.Libraries[] 的具体实现，因为它们通常与构建系统相关。

如果您的存档已经包含库，您可以使用 javadoc:org.springframework.boot.loader.tools.Libraries#NONE[]。



[[build-tool-plugins.other-build-systems.finding-main-class]]
== 查找主类

如果您不使用 `Repackager.setMainClass()` 指定主类，重新打包器将使用 https://asm.ow2.io/[ASM] 读取类文件，并尝试找到一个合适的类，该类具有 `public static void main(String[] args)` 方法。
如果找到多个候选类，将抛出异常。



[[build-tool-plugins.other-build-systems.example-repackage-implementation]]
== 示例重新打包实现

以下示例展示了一个典型的重新打包实现：

include-code::MyBuildTool[]
