[[io.caching]]
= 缓存

Spring Framework 提供了对应用程序透明添加缓存的支持。
在其核心，抽象将缓存应用于方法，从而根据缓存中可用的信息减少执行次数。
缓存逻辑被透明地应用，不会对调用者造成任何干扰。
只要通过使用 javadoc:org.springframework.cache.annotation.EnableCaching[format=annotation] 注解启用缓存支持，Spring Boot 就会自动配置缓存基础设施。

NOTE: 有关更多详细信息，请查看 Spring Framework 参考文档的 {url-spring-framework-docs}/integration/cache.html[相关部分]。

简而言之，要向服务的操作添加缓存，只需向其方法添加相关注解，如下例所示：

include-code::MyMathService[]

此示例演示了对潜在耗时操作的缓存使用。
在调用 `computePiDecimal` 之前，抽象会在 `piDecimals` 缓存中查找与 `precision` 参数匹配的条目。
如果找到条目，缓存中的内容会立即返回给调用者，并且不会调用该方法。
否则，将调用该方法，并在返回该值之前更新缓存。

CAUTION: 您也可以透明地使用标准 JSR-107 (JCache) 注解（如 javadoc:javax.cache.annotation.CacheResult[format=annotation]）。
但是，我们强烈建议不要混合使用 Spring Cache 和 JCache 注解。

如果您不添加任何特定的缓存库，Spring Boot 会自动配置一个使用内存中并发映射的 xref:io/caching.adoc#io.caching.provider.simple[简单提供程序]。
当需要缓存时（如前面示例中的 `piDecimals`），此提供程序会为您创建它。
简单提供程序并不真正推荐用于生产环境，但它非常适合入门和确保您理解这些功能。
当您决定使用哪个缓存提供程序时，请确保阅读其文档以了解如何配置应用程序使用的缓存。
几乎所有提供程序都要求您显式配置应用程序中使用的每个缓存。
一些提供程序提供了一种方法来自定义由 configprop:spring.cache.cache-names[] 属性定义的默认缓存。

TIP: 还可以透明地 {url-spring-framework-docs}/integration/cache/annotations.html#cache-annotations-put[更新] 或 {url-spring-framework-docs}/integration/cache/annotations.html#cache-annotations-evict[清除] 缓存中的数据。



[[io.caching.provider]]
== 支持的缓存提供程序

缓存抽象不提供实际的存储，而是依赖于由 javadoc:org.springframework.cache.Cache[] 和 javadoc:org.springframework.cache.CacheManager[] 接口实现的抽象。

如果您没有定义类型为 javadoc:org.springframework.cache.CacheManager[] 的 bean 或名为 `cacheResolver` 的 javadoc:org.springframework.cache.interceptor.CacheResolver[]（请参阅 javadoc:org.springframework.cache.annotation.CachingConfigurer[]），Spring Boot 会尝试按以下顺序检测提供程序：

. xref:io/caching.adoc#io.caching.provider.generic[]
. xref:io/caching.adoc#io.caching.provider.jcache[]（EhCache 3、Hazelcast、Infinispan 等）
. xref:io/caching.adoc#io.caching.provider.hazelcast[]
. xref:io/caching.adoc#io.caching.provider.infinispan[]
. xref:io/caching.adoc#io.caching.provider.couchbase[]
. xref:io/caching.adoc#io.caching.provider.redis[]
. xref:io/caching.adoc#io.caching.provider.caffeine[]
. xref:io/caching.adoc#io.caching.provider.cache2k[]
. xref:io/caching.adoc#io.caching.provider.simple[]

此外，{url-spring-boot-for-apache-geode-site}[Spring Boot for Apache Geode] 提供了 {url-spring-boot-for-apache-geode-docs}#geode-caching-provider[使用 Apache Geode 作为缓存提供程序的自动配置]。

TIP: 如果 javadoc:org.springframework.cache.CacheManager[] 由 Spring Boot 自动配置，可以通过设置 configprop:spring.cache.type[] 属性来强制使用特定的缓存提供程序。
如果您需要在某些环境（如测试）中 xref:io/caching.adoc#io.caching.provider.none[使用无操作缓存]，请使用此属性。

TIP: 使用 `spring-boot-starter-cache` starter 可以快速添加基本缓存依赖项。
该 starter 引入了 `spring-context-support`。
如果您手动添加依赖项，则必须包含 `spring-context-support` 才能使用 JCache 或 Caffeine 支持。

如果 javadoc:org.springframework.cache.CacheManager[] 由 Spring Boot 自动配置，您可以通过暴露一个实现 javadoc:org.springframework.boot.autoconfigure.cache.CacheManagerCustomizer[] 接口的 bean 来在完全初始化之前进一步调整其配置。
以下示例设置了一个标志，表示不应将 `null` 值传递到底层映射：

include-code::MyCacheManagerConfiguration[]

NOTE: 在前面的示例中，期望有一个自动配置的 javadoc:org.springframework.cache.concurrent.ConcurrentMapCacheManager[]。
如果不是这种情况（您提供了自己的配置或自动配置了不同的缓存提供程序），则不会调用自定义器。
您可以根据需要拥有任意数量的自定义器，还可以使用 javadoc:org.springframework.core.annotation.Order[format=annotation] 或 javadoc:org.springframework.core.Ordered[] 对它们进行排序。



[[io.caching.provider.generic]]
=== 通用

如果上下文定义了至少一个 javadoc:org.springframework.cache.Cache[] bean，则使用通用缓存。
创建一个包装该类型的所有 bean 的 javadoc:org.springframework.cache.CacheManager[]。



[[io.caching.provider.jcache]]
=== JCache (JSR-107)

https://jcp.org/en/jsr/detail?id=107[JCache] 通过类路径上存在 javadoc:javax.cache.spi.CachingProvider[]（即类路径上存在符合 JSR-107 的缓存库）来引导，并且 javadoc:org.springframework.cache.jcache.JCacheCacheManager[] 由 `spring-boot-starter-cache` starter 提供。
有各种符合规范的库可用，Spring Boot 为 Ehcache 3、Hazelcast 和 Infinispan 提供了依赖管理。
也可以添加任何其他符合规范的库。

可能会出现多个提供程序的情况，在这种情况下，必须明确指定提供程序。
即使 JSR-107 标准没有强制规定定义配置文件位置的标准方式，Spring Boot 也会尽最大努力适应使用实现细节设置缓存，如下例所示：

[configprops,yaml]
----
    # 仅在有多个提供程序时必要
	spring:
	  cache:
	    jcache:
	      provider: "com.example.MyCachingProvider"
	      config: "classpath:example.xml"
----

NOTE: 当缓存库同时提供本机实现和 JSR-107 支持时，Spring Boot 优先使用 JSR-107 支持，这样如果您切换到不同的 JSR-107 实现，相同的功能仍然可用。

TIP: Spring Boot 对 Hazelcast 有 xref:io/hazelcast.adoc[通用支持]。
如果有一个 javadoc:com.hazelcast.core.HazelcastInstance[] 可用，除非指定了 configprop:spring.cache.jcache.config[] 属性，否则它也会自动重用于 javadoc:javax.cache.CacheManager[]。

有两种方法可以自定义底层 javadoc:javax.cache.CacheManager[]：

* 可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存。
如果定义了自定义的 javadoc:javax.cache.configuration.Configuration[] bean，则使用它来自定义它们。
* javadoc:org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer[] bean 使用 javadoc:javax.cache.CacheManager[] 的引用来调用，以进行完全自定义。

TIP: 如果定义了标准的 javadoc:javax.cache.CacheManager[] bean，它会自动包装在抽象期望的 javadoc:org.springframework.cache.CacheManager[] 实现中。
不会对其应用进一步的自定义。



[[io.caching.provider.hazelcast]]
=== Hazelcast

Spring Boot 对 Hazelcast 有 xref:io/hazelcast.adoc[通用支持]。
如果已自动配置 javadoc:com.hazelcast.core.HazelcastInstance[] 并且类路径上有 `com.hazelcast:hazelcast-spring`，它会自动包装在 javadoc:org.springframework.cache.CacheManager[] 中。

NOTE: Hazelcast 可以用作符合 JCache 的缓存或符合 Spring javadoc:org.springframework.cache.CacheManager[] 的缓存。
当将 configprop:spring.cache.type[] 设置为 `hazelcast` 时，Spring Boot 将使用基于 javadoc:org.springframework.cache.CacheManager[] 的实现。
如果您想将 Hazelcast 用作符合 JCache 的缓存，请将 configprop:spring.cache.type[] 设置为 `jcache`。
如果您有多个符合 JCache 的缓存提供程序并想强制使用 Hazelcast，您必须 xref:io/caching.adoc#io.caching.provider.jcache[显式设置 JCache 提供程序]。



[[io.caching.provider.infinispan]]
=== Infinispan

https://infinispan.org/[Infinispan] 没有默认的配置文件位置，因此必须明确指定。
否则，使用默认引导。

[configprops,yaml]
----
spring:
  cache:
    infinispan:
      config: "infinispan.xml"
----

可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存。
如果定义了自定义的 javadoc:org.infinispan.configuration.cache.ConfigurationBuilder[] bean，则使用它来自定义缓存。

为了与 Spring Boot 的 Jakarta EE 9 基准兼容，必须使用 Infinispan 的 `-jakarta` 模块。
对于每个具有 `-jakarta` 变体的模块，必须使用该变体代替标准模块。
例如，必须使用 `infinispan-core-jakarta` 和 `infinispan-commons-jakarta` 代替 `infinispan-core` 和 `infinispan-commons`。



[[io.caching.provider.couchbase]]
=== Couchbase

如果 Spring Data Couchbase 可用并且已 xref:data/nosql.adoc#data.nosql.couchbase[配置] Couchbase，则会自动配置 javadoc:org.springframework.data.couchbase.cache.CouchbaseCacheManager[]。
可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建其他缓存，并且可以使用 `spring.cache.couchbase.*` 属性配置缓存默认值。
例如，以下配置创建了 `cache1` 和 `cache2` 缓存，条目过期时间为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    couchbase:
      expiration: "10m"
----

如果您需要对配置进行更多控制，请考虑注册一个 javadoc:org.springframework.boot.autoconfigure.cache.CouchbaseCacheManagerBuilderCustomizer[] bean。
以下示例显示了一个自定义器，它为 `cache1` 和 `cache2` 配置了特定的条目过期时间：

include-code::MyCouchbaseCacheManagerConfiguration[]



[[io.caching.provider.redis]]
=== Redis

如果 https://redis.io/[Redis] 可用并已配置，则会自动配置 javadoc:org.springframework.data.redis.cache.RedisCacheManager[]。
可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建其他缓存，并且可以使用 `spring.cache.redis.*` 属性配置缓存默认值。
例如，以下配置创建了 `cache1` 和 `cache2` 缓存，生存时间为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    redis:
      time-to-live: "10m"
----

NOTE: 默认情况下，会添加键前缀，这样如果两个单独的缓存使用相同的键，Redis 就不会有重叠的键，也不会返回无效的值。
如果您创建自己的 javadoc:org.springframework.data.redis.cache.RedisCacheManager[]，我们强烈建议保持此设置启用。

TIP: 您可以通过添加自己的 javadoc:org.springframework.data.redis.cache.RedisCacheConfiguration[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 来完全控制默认配置。
如果您需要自定义默认序列化策略，这可能很有用。

如果您需要对配置进行更多控制，请考虑注册一个 javadoc:org.springframework.boot.autoconfigure.cache.RedisCacheManagerBuilderCustomizer[] bean。
以下示例显示了一个自定义器，它为 `cache1` 和 `cache2` 配置了特定的生存时间：

include-code::MyRedisCacheManagerConfiguration[]



[[io.caching.provider.caffeine]]
=== Caffeine

https://github.com/ben-manes/caffeine[Caffeine] 是 Guava 缓存的 Java 8 重写版本，它取代了对 Guava 的支持。
如果存在 Caffeine，则会自动配置 javadoc:org.springframework.cache.caffeine.CaffeineCacheManager[]（由 `spring-boot-starter-cache` starter 提供）。
可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存，并可以通过以下方式之一（按指示顺序）进行自定义：

. 由 `spring.cache.caffeine.spec` 定义的缓存规范
. 定义了 javadoc:com.github.benmanes.caffeine.cache.CaffeineSpec[] bean
. 定义了 javadoc:com.github.benmanes.caffeine.cache.Caffeine[] bean

例如，以下配置创建了 `cache1` 和 `cache2` 缓存，最大大小为 500，生存时间为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=600s"
----

如果定义了 javadoc:com.github.benmanes.caffeine.cache.CacheLoader[] bean，它会自动关联到 javadoc:org.springframework.cache.caffeine.CaffeineCacheManager[]。
由于 javadoc:com.github.benmanes.caffeine.cache.CacheLoader[] 将关联到缓存管理器管理的所有缓存，因此必须将其定义为 `CacheLoader<Object, Object>`。
自动配置会忽略任何其他泛型类型。



[[io.caching.provider.cache2k]]
=== Cache2k

https://cache2k.org/[Cache2k] 是一个内存缓存。
如果存在 Cache2k spring 集成，则会自动配置 `SpringCache2kCacheManager`。

可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存。
可以使用 javadoc:org.springframework.boot.autoconfigure.cache.Cache2kBuilderCustomizer[] bean 自定义缓存默认值。
以下示例显示了一个自定义器，它将缓存的容量配置为 200 个条目，过期时间为 5 分钟：

include-code::MyCache2kDefaultsConfiguration[]



[[io.caching.provider.simple]]
=== 简单

如果找不到其他提供程序，则配置一个使用 javadoc:java.util.concurrent.ConcurrentHashMap[] 作为缓存存储的简单实现。
如果您的应用程序中不存在缓存库，这是默认设置。
默认情况下，缓存是按需创建的，但您可以通过设置 `cache-names` 属性来限制可用缓存的列表。
例如，如果您只想要 `cache1` 和 `cache2` 缓存，请按如下方式设置 `cache-names` 属性：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
----

如果您这样做，并且您的应用程序使用了未列出的缓存，则当需要缓存但未在启动时声明时，它会在运行时失败。
这与"真实"缓存提供程序在您使用未声明的缓存时的行为类似。



[[io.caching.provider.none]]
=== 无

当配置中存在 javadoc:org.springframework.cache.annotation.EnableCaching[format=annotation] 时，也需要合适的缓存配置。
如果您有自定义的 `org.springframework.cache.CacheManager`，请考虑在单独的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类中定义它，以便在必要时可以覆盖它。
None 使用无操作实现，这在测试中很有用，切片测试通过 javadoc:org.springframework.boot.test.autoconfigure.core.AutoConfigureCache[format=annotation] 默认使用它。

如果您需要在特定环境中使用无操作缓存而不是自动配置的缓存管理器，请将缓存类型设置为 `none`，如下例所示：

[configprops,yaml]
----
spring:
  cache:
    type: "none"
----
