[[io.caching]]
= 缓存

Spring Framework 提供了为应用透明添加缓存的支持。
其核心是将缓存应用于方法，从而根据缓存中的信息减少方法的实际执行次数。
缓存逻辑是透明应用的，对调用方无任何干扰。
只要通过 javadoc:org.springframework.cache.annotation.EnableCaching[format=annotation] 注解启用缓存支持，Spring Boot 会自动配置缓存基础设施。

NOTE: 详细内容请查阅 Spring Framework 参考文档的 {url-spring-framework-docs}/integration/cache.html[相关章节]。

简而言之，要为服务的某个操作添加缓存，只需在方法上添加相应注解，如下例所示：

include-code::MyMathService[]

该示例演示了在可能开销较大的操作上使用缓存。
在调用 `computePiDecimal` 前，抽象层会在 `piDecimals` 缓存中查找与 `precision` 参数匹配的条目。
如果找到，则立即返回缓存内容，方法不会被调用。
否则将调用方法，并在返回值前更新缓存。

CAUTION: 你也可以透明地使用标准 JSR-107 (JCache) 注解（如 javadoc:javax.cache.annotation.CacheResult[format=annotation]）。但强烈建议不要混用 Spring Cache 与 JCache 注解。

如果未添加任何特定缓存库，Spring Boot 会自动配置一个 xref:io/caching.adoc#io.caching.provider.simple[简单提供者]，其在内存中使用并发 Map。当需要缓存（如上述示例中的 `piDecimals`）时，该提供者会为你创建缓存。简单提供者不推荐用于生产环境，但非常适合入门和理解特性。当你决定使用哪种缓存提供者后，请务必阅读其文档，了解如何配置应用所用缓存。几乎所有提供者都要求你显式配置应用中用到的每个缓存。有些还支持通过 configprop:spring.cache.cache-names[] 属性自定义默认缓存。

TIP: 还可以透明地 {url-spring-framework-docs}/integration/cache/annotations.html#cache-annotations-put[更新] 或 {url-spring-framework-docs}/integration/cache/annotations.html#cache-annotations-evict[驱逐] 缓存中的数据。


[[io.caching.provider]]
== 支持的缓存提供者

缓存抽象本身不提供实际存储，而是依赖 javadoc:org.springframework.cache.Cache[] 和 javadoc:org.springframework.cache.CacheManager[] 接口实现。

如果你没有定义类型为 javadoc:org.springframework.cache.CacheManager[] 的 bean，或没有名为 `cacheResolver` 的 javadoc:org.springframework.cache.interceptor.CacheResolver[]（见 javadoc:org.springframework.cache.annotation.CachingConfigurer[]），Spring Boot 会按如下顺序尝试检测以下提供者：

. xref:io/caching.adoc#io.caching.provider.generic[]
. xref:io/caching.adoc#io.caching.provider.jcache[]（EhCache 3、Hazelcast、Infinispan 等）
. xref:io/caching.adoc#io.caching.provider.hazelcast[]
. xref:io/caching.adoc#io.caching.provider.infinispan[]
. xref:io/caching.adoc#io.caching.provider.couchbase[]
. xref:io/caching.adoc#io.caching.provider.redis[]
. xref:io/caching.adoc#io.caching.provider.caffeine[]
. xref:io/caching.adoc#io.caching.provider.cache2k[]
. xref:io/caching.adoc#io.caching.provider.simple[]

此外，{url-spring-boot-for-apache-geode-site}[Spring Boot for Apache Geode] 提供了 {url-spring-boot-for-apache-geode-docs}#geode-caching-provider[使用 Apache Geode 作为缓存提供者的自动配置]。

TIP: 如果 javadoc:org.springframework.cache.CacheManager[] 由 Spring Boot 自动配置，可以通过设置 configprop:spring.cache.type[] 属性 _强制_ 使用特定缓存提供者。如果你需要在某些环境（如测试）下 xref:io/caching.adoc#io.caching.provider.none[使用 no-op 缓存]，可用此属性。

TIP: 使用 `spring-boot-starter-cache` starter 可快速添加基础缓存依赖。该 starter 会引入 `spring-context-support`。如果手动添加依赖，需确保包含 `spring-context-support` 才能使用 JCache 或 Caffeine 支持。

如果 javadoc:org.springframework.cache.CacheManager[] 由 Spring Boot 自动配置，还可以在其完全初始化前通过暴露实现了 javadoc:org.springframework.boot.autoconfigure.cache.CacheManagerCustomizer[] 接口的 bean 进一步调整配置。如下示例设置了一个标志，表示不应将 `null` 值传递给底层 map：

include-code::MyCacheManagerConfiguration[]

NOTE: 上述示例预期自动配置了 javadoc:org.springframework.cache.concurrent.ConcurrentMapCacheManager[]。如果不是（如你自定义了配置或自动配置了其他缓存提供者），则不会调用该定制器。你可以定义任意多个定制器，也可通过 javadoc:org.springframework.core.annotation.Order[format=annotation] 或 javadoc:org.springframework.core.Ordered[] 排序。


[[io.caching.provider.generic]]
=== 通用

如果上下文中定义了 _至少_ 一个 javadoc:org.springframework.cache.Cache[] bean，则会创建一个包装所有该类型 bean 的 javadoc:org.springframework.cache.CacheManager[]。


[[io.caching.provider.jcache]]
=== JCache (JSR-107)

https://jcp.org/en/jsr/detail?id=107[JCache] 通过 classpath 上存在 javadoc:javax.cache.spi.CachingProvider[]（即存在 JSR-107 兼容缓存库）引导，`spring-boot-starter-cache` starter 提供 javadoc:org.springframework.cache.jcache.JCacheCacheManager[]。Spring Boot 为 Ehcache 3、Hazelcast 和 Infinispan 提供依赖管理，也可添加其他兼容库。

如果存在多个提供者，必须显式指定。
即使 JSR-107 标准未强制规定配置文件位置，Spring Boot 也会尽力支持通过实现细节设置缓存，示例如下：

[configprops,yaml]
----
    # 仅当存在多个提供者时才需要
	spring:
	  cache:
	    jcache:
	      provider: "com.example.MyCachingProvider"
	      config: "classpath:example.xml"
----

NOTE: 当缓存库同时提供原生实现和 JSR-107 支持时，Spring Boot 优先使用 JSR-107 支持，这样切换到其他 JSR-107 实现时也能获得相同特性。

TIP: Spring Boot 对 Hazelcast 有 xref:io/hazelcast.adoc[通用支持]。如果有单个 javadoc:com.hazelcast.core.HazelcastInstance[]，也会自动用于 javadoc:javax.cache.CacheManager[]，除非指定了 configprop:spring.cache.jcache.config[] 属性。

自定义底层 javadoc:javax.cache.CacheManager[] 有两种方式：

* 通过设置 configprop:spring.cache.cache-names[] 属性可在启动时创建缓存。如果定义了自定义 javadoc:javax.cache.configuration.Configuration[] bean，则用于定制缓存。
* javadoc:org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer[] bean 会以 javadoc:javax.cache.CacheManager[] 引用进行回调，实现完全自定义。

TIP: 如果定义了标准 javadoc:javax.cache.CacheManager[] bean，会自动包装为缓存抽象所需的 javadoc:org.springframework.cache.CacheManager[] 实现，不再应用其他自定义。


[[io.caching.provider.hazelcast]]
=== Hazelcast

Spring Boot 对 Hazelcast 有 xref:io/hazelcast.adoc[通用支持]。
如果自动配置了 javadoc:com.hazelcast.core.HazelcastInstance[] 且 classpath 上有 `com.hazelcast:hazelcast-spring`，则会自动包装为 javadoc:org.springframework.cache.CacheManager[]。

NOTE: Hazelcast 可作为 JCache 兼容缓存或 Spring javadoc:org.springframework.cache.CacheManager[] 兼容缓存使用。将 configprop:spring.cache.type[] 设为 `hazelcast` 时，Spring Boot 会使用基于 javadoc:org.springframework.cache.CacheManager[] 的实现。如需将 Hazelcast 用作 JCache 兼容缓存，将 configprop:spring.cache.type[] 设为 `jcache`。如有多个 JCache 兼容缓存提供者且需强制使用 Hazelcast，需 xref:io/caching.adoc#io.caching.provider.jcache[显式设置 JCache 提供者]。


[[io.caching.provider.infinispan]]
=== Infinispan

https://infinispan.org/[Infinispan] 没有默认配置文件位置，需显式指定，否则使用默认引导。

[configprops,yaml]
----
spring:
  cache:
    infinispan:
      config: "infinispan.xml"
----

可通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存。如果定义了自定义 javadoc:org.infinispan.configuration.cache.ConfigurationBuilder[] bean，则用于定制缓存。

为兼容 Spring Boot 的 Jakarta EE 9 基线，Infinispan 必须使用 `-jakarta` 变体模块。对于有 `-jakarta` 变体的模块，必须用变体替换标准模块。例如，`infinispan-core-jakarta` 和 `infinispan-commons-jakarta` 必须分别替换 `infinispan-core` 和 `infinispan-commons`。


[[io.caching.provider.couchbase]]
=== Couchbase

如果可用 Spring Data Couchbase 且已 xref:data/nosql.adoc#data.nosql.couchbase[配置] Couchbase，则会自动配置 javadoc:org.springframework.data.couchbase.cache.CouchbaseCacheManager[]。可通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建额外缓存，并可通过 `spring.cache.couchbase.*` 属性配置缓存默认值。例如，以下配置创建了 `cache1` 和 `cache2`，条目过期时间为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    couchbase:
      expiration: "10m"
----

如需更细致的配置，可注册 javadoc:org.springframework.boot.autoconfigure.cache.CouchbaseCacheManagerBuilderCustomizer[] bean。如下示例展示了为 `cache1` 和 `cache2` 配置特定过期时间的定制器：

include-code::MyCouchbaseCacheManagerConfiguration[]


[[io.caching.provider.redis]]
=== Redis

如果 https://redis.io/[Redis] 可用且已配置，则会自动配置 javadoc:org.springframework.data.redis.cache.RedisCacheManager[]。可通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建额外缓存，并可通过 `spring.cache.redis.*` 属性配置缓存默认值。例如，以下配置创建了 `cache1` 和 `cache2`，其存活时间为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    redis:
      time-to-live: "10m"
----

NOTE: 默认会添加 key 前缀，确保两个不同缓存使用相同 key 时，Redis 不会出现键冲突导致返回无效值。强烈建议自定义 javadoc:org.springframework.data.redis.cache.RedisCacheManager[] 时保持此设置开启。

TIP: 通过自定义 javadoc:org.springframework.data.redis.cache.RedisCacheConfiguration[] javadoc:org.springframework.context.annotation.Bean[format=annotation]，可完全控制默认配置。这对于自定义序列化策略很有用。

如需更细致的配置，可注册 javadoc:org.springframework.boot.autoconfigure.cache.RedisCacheManagerBuilderCustomizer[] bean。如下示例展示了为 `cache1` 和 `cache2` 配置特定存活时间的定制器：

include-code::MyRedisCacheManagerConfiguration[]


[[io.caching.provider.caffeine]]
=== Caffeine

https://github.com/ben-manes/caffeine[Caffeine] 是 Guava 缓存的 Java 8 重写版，取代了对 Guava 的支持。如果存在 Caffeine，则会自动配置 javadoc:org.springframework.cache.caffeine.CaffeineCacheManager[]（由 `spring-boot-starter-cache` starter 提供）。可通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存，并可按如下顺序之一自定义：

. 通过 `spring.cache.caffeine.spec` 定义缓存规格
. 定义 javadoc:com.github.benmanes.caffeine.cache.CaffeineSpec[] bean
. 定义 javadoc:com.github.benmanes.caffeine.cache.Caffeine[] bean

例如，以下配置创建了 `cache1` 和 `cache2`，最大容量为 500，存活时间为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=600s"
----

如果定义了 javadoc:com.github.benmanes.caffeine.cache.CacheLoader[] bean，会自动关联到 javadoc:org.springframework.cache.caffeine.CaffeineCacheManager[]。由于该 CacheLoader 会关联到所有缓存，必须定义为 `CacheLoader<Object, Object>`。自动配置会忽略其他泛型类型。


[[io.caching.provider.cache2k]]
=== Cache2k

https://cache2k.org/[Cache2k] 是内存缓存。如果存在 Cache2k Spring 集成，则会自动配置 `SpringCache2kCacheManager`。

可通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存。可通过 javadoc:org.springframework.boot.autoconfigure.cache.Cache2kBuilderCustomizer[] bean 自定义缓存默认值。如下示例展示了为缓存配置容量为 200 条、过期时间为 5 分钟的定制器：

include-code::MyCache2kDefaultsConfiguration[]


[[io.caching.provider.simple]]
=== 简单

如果未检测到其他提供者，则会配置一个基于 javadoc:java.util.concurrent.ConcurrentHashMap[] 的简单实现。若应用中未引入任何缓存库，则为默认实现。默认情况下，缓存按需创建，但可通过设置 `cache-names` 属性限制可用缓存列表。例如，仅允许 `cache1` 和 `cache2`：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
----

如果这样设置，应用使用未声明的缓存时会在运行时失败（而非启动时），这与“真实”缓存提供者的行为一致。


[[io.caching.provider.none]]
=== 无

当配置中存在 javadoc:org.springframework.cache.annotation.EnableCaching[format=annotation] 时，也应有合适的缓存配置。如果有自定义 `org.springframework.cache.CacheManager`，建议在单独的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类中定义，以便必要时覆盖。None 使用 no-op 实现，适用于测试，切片测试默认通过 javadoc:org.springframework.boot.test.autoconfigure.core.AutoConfigureCache[format=annotation] 使用该实现。

如需在某些环境下使用 no-op 缓存而非自动配置的缓存管理器，可将缓存类型设为 `none`，如下所示：

[configprops,yaml]
----
spring:
  cache:
    type: "none"
----
