[[io.email]]
= 发送电子邮件

Spring Framework 通过使用 javadoc:org.springframework.mail.javamail.JavaMailSender[] 接口提供了发送电子邮件的抽象，Spring Boot 也为其提供了自动配置以及一个 starter 模块。

TIP: 有关如何使用 javadoc:org.springframework.mail.javamail.JavaMailSender[] 的详细说明，请参阅 {url-spring-framework-docs}/integration/email.html[参考文档]。

如果 `spring.mail.host` 和相关的库（由 `spring-boot-starter-mail` 定义）可用，并且不存在默认的 javadoc:org.springframework.mail.javamail.JavaMailSender[]，则会创建一个默认的发送器。
可以通过 `spring.mail` 命名空间中的配置项进一步自定义发送器。
有关更多详细信息，请参阅 javadoc:org.springframework.boot.autoconfigure.mail.MailProperties[]。

特别是，某些默认超时值是无限的，您可能想要更改这些值以避免线程被无响应的邮件服务器阻塞，如下例所示：

[configprops,yaml]
----
spring:
  mail:
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
----

也可以通过 JNDI 使用现有的 javadoc:jakarta.mail.Session[] 来配置 javadoc:org.springframework.mail.javamail.JavaMailSender[]：

[configprops,yaml]
----
spring:
  mail:
    jndi-name: "mail/Session"
----

当设置了 `jndi-name` 时，它会优先于所有其他 Session 相关的设置。
