[[howto.actuator]]
= Actuator

Spring Boot 包含 Spring Boot Actuator。
本节回答了其使用中经常出现的问题。


[[howto.actuator.change-http-port-or-address]]
== 更改 Actuator 端点的 HTTP 端口或地址

在独立应用程序中，Actuator HTTP 端口默认为与主 HTTP 端口相同。
要使应用程序监听不同的端口，请设置外部属性：configprop:management.server.port[]。
要监听完全不同的网络地址（例如，当您有一个用于管理的内部网络和一个用于用户应用程序的外部网络时），您还可以将 `management.server.address` 设置为服务器能够绑定的有效 IP 地址。

有关详细信息，请参阅 javadoc:org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties[] 源代码和 xref:reference:actuator/monitoring.adoc#actuator.monitoring.customizing-management-server-port[自定义管理服务器端口] 在“`生产就绪功能`”部分。


[[howto.actuator.customizing-sanitization]]
== 自定义清理

要控制清理，请定义一个 javadoc:org.springframework.boot.actuate.endpoint.SanitizingFunction[] bean。
调用该函数的 javadoc:org.springframework.boot.actuate.endpoint.SanitizableData[] 提供对键和值以及它们来自的 javadoc:org.springframework.core.env.PropertySource[] 的访问。
这使您可以，例如，清理来自特定属性源的每个值。
每个 javadoc:org.springframework.boot.actuate.endpoint.SanitizingFunction[] 按顺序调用，直到函数更改可清理数据的值。


[[howto.actuator.map-health-indicators-to-metrics]]
== 将健康指示器映射到 Micrometer 指标

Spring Boot 健康指示器返回一个 javadoc:org.springframework.boot.actuate.health.Status[] 类型以指示整体系统健康状况。
如果您想监控或警报特定应用程序的健康水平，您可以使用 Micrometer 将这些状态导出为指标。
默认情况下，Spring Boot 使用状态代码“`UP`”、“`DOWN`”、“`OUT_OF_SERVICE`”和“`UNKNOWN`”。
要导出这些，您需要将这些状态转换为一组数字，以便可以与 Micrometer javadoc:io.micrometer.core.instrument.Gauge[] 一起使用。

以下示例显示了一种编写此类导出器的方法：

include-code::MyHealthMetricsExportConfiguration[]
