[[howto.actuator]]
= Actuator

Spring Boot 包含了 Spring Boot Actuator。
本节回答了使用 Actuator 时经常出现的问题。



[[howto.actuator.change-http-port-or-address]]
== 更改 Actuator 端点的 HTTP 端口或地址

在独立应用程序中，Actuator 的 HTTP 端口默认与主 HTTP 端口相同。
要使应用程序监听不同的端口，请设置外部属性：configprop:management.server.port[]。
要监听完全不同的网络地址（例如，当您有用于管理的内部网络和用于用户应用程序的外部网络时），您还可以将 `management.server.address` 设置为服务器能够绑定的有效 IP 地址。

有关更多详细信息，请参阅 javadoc:org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties[] 源代码以及“生产就绪功能”部分中的 xref:reference:actuator/monitoring.adoc#actuator.monitoring.customizing-management-server-port[自定义管理服务器端口]。



[[howto.actuator.customizing-sanitization]]
== 自定义数据清理

要控制数据清理，请定义一个 javadoc:org.springframework.boot.actuate.endpoint.SanitizingFunction[] bean。
调用该函数的 javadoc:org.springframework.boot.actuate.endpoint.SanitizableData[] 提供了对键和值的访问，以及它们来自的 javadoc:org.springframework.core.env.PropertySource[]。
这允许您例如清理来自特定属性源的所有值。
每个 javadoc:org.springframework.boot.actuate.endpoint.SanitizingFunction[] 将按顺序调用，直到某个函数更改了可清理数据的值为止。



[[howto.actuator.map-health-indicators-to-metrics]]
== 将健康指示器映射到 Micrometer 指标

Spring Boot 健康指示器返回 javadoc:org.springframework.boot.actuate.health.Status[] 类型，以指示整体系统健康状况。
如果您想为特定应用程序监控或警告健康级别，可以使用 Micrometer 将这些状态导出为指标。
默认情况下，Spring Boot 使用状态码 "`UP`"、"`DOWN`"、"`OUT_OF_SERVICE`" 和 "`UNKNOWN`"。
要导出这些状态，您需要将这些状态转换为一组数字，以便它们可以与 Micrometer 的 javadoc:io.micrometer.core.instrument.Gauge[] 一起使用。

以下示例展示了一种编写此类导出器的方法：

include-code::MyHealthMetricsExportConfiguration[]
