[[howto.actuator]]
= Actuator

Spring Boot 包含了 Spring Boot Actuator。
本节将解答使用过程中经常遇到的问题。



[[howto.actuator.change-http-port-or-address]]
== 更改 Actuator 端点的 HTTP 端口或地址

在独立应用程序中，Actuator HTTP 端口默认与主 HTTP 端口相同。
要使应用程序在不同的端口上监听，请设置外部属性：configprop:management.server.port[]。
要监听完全不同的网络地址（例如，当你有一个用于管理的内部网络和一个用于用户应用程序的外部网络时），你还可以将 `management.server.address` 设置为服务器能够绑定的有效 IP 地址。

有关更多详细信息，请参阅 javadoc:org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties[] 源代码和 xref:reference:actuator/monitoring.adoc#actuator.monitoring.customizing-management-server-port[自定义管理服务器端口] 在"生产就绪功能"部分。



[[howto.actuator.customizing-sanitization]]
== 自定义清理

要控制清理过程，请定义一个 javadoc:org.springframework.boot.actuate.endpoint.SanitizingFunction[] bean。
调用该函数时使用的 javadoc:org.springframework.boot.actuate.endpoint.SanitizableData[] 提供了对键和值的访问，以及它们来自的 javadoc:org.springframework.core.env.PropertySource[]。
这允许你，例如，清理来自特定属性源的每个值。
每个 javadoc:org.springframework.boot.actuate.endpoint.SanitizingFunction[] 按顺序调用，直到函数更改可清理数据的值。



[[howto.actuator.map-health-indicators-to-metrics]]
== 将健康指标映射到 Micrometer 指标

Spring Boot 健康指标返回 javadoc:org.springframework.boot.actuate.health.Status[] 类型以指示整体系统健康状态。
如果你想监控或提醒特定应用程序的健康级别，你可以使用 Micrometer 将这些状态导出为指标。
默认情况下，Spring Boot 使用状态码 "`UP`"、"`DOWN`"、"`OUT_OF_SERVICE`" 和 "`UNKNOWN`"。
要导出这些状态，你需要将这些状态转换为一些数字，以便它们可以与 Micrometer javadoc:io.micrometer.core.instrument.Gauge[] 一起使用。

以下示例展示了一种编写此类导出器的方法：

include-code::MyHealthMetricsExportConfiguration[]
