[[howto.application]]
= Spring Boot 应用程序

本节包含直接与 Spring Boot 应用程序相关的主题。


[[howto.application.failure-analyzer]]
== 创建您自己的 FailureAnalyzer

javadoc:org.springframework.boot.diagnostics.FailureAnalyzer[] 是一种很好的方法，可以在启动时拦截异常并将其转换为可读消息，包装在 javadoc:org.springframework.boot.diagnostics.FailureAnalysis[] 中。
Spring Boot 为应用程序上下文相关的异常、JSR-303 验证等提供了这样的分析器。
您也可以创建自己的分析器。

javadoc:org.springframework.boot.diagnostics.AbstractFailureAnalyzer[] 是 javadoc:org.springframework.boot.diagnostics.FailureAnalyzer[] 的便捷扩展，它检查异常中指定异常类型的存在。
您可以从中扩展，以便您的实现仅在实际存在异常时才有机会处理异常。
如果由于某种原因您无法处理异常，请返回 `null` 以便另一个实现有机会处理异常。

javadoc:org.springframework.boot.diagnostics.FailureAnalyzer[] 实现必须在 `META-INF/spring.factories` 中注册。
以下示例注册 `ProjectConstraintViolationFailureAnalyzer`：

[source,properties]
----
org.springframework.boot.diagnostics.FailureAnalyzer=\
com.example.ProjectConstraintViolationFailureAnalyzer
----

注意：如果您需要访问 javadoc:org.springframework.beans.factory.BeanFactory[] 或 javadoc:org.springframework.core.env.Environment[]，请在 javadoc:org.springframework.boot.diagnostics.FailureAnalyzer[] 实现中将它们声明为构造函数参数。


[[howto.application.troubleshoot-auto-configuration]]
== 排查自动配置问题

Spring Boot 自动配置尽力而为，但有时事情会失败，可能很难知道原因。

在任何 Spring Boot javadoc:org.springframework.context.ApplicationContext[] 中都有一个非常有用的 javadoc:org.springframework.boot.autoconfigure.condition.ConditionEvaluationReport[]。
如果启用 `DEBUG` 日志输出，您可以看到它。
如果您使用 `spring-boot-actuator`（请参阅 xref:actuator.adoc[] 部分），还有一个 `conditions` 端点以 JSON 格式呈现报告。
使用该端点调试应用程序，查看 Spring Boot 在运行时添加了哪些功能（以及哪些未添加）。

通过查看源代码和 API 文档可以回答更多问题。
阅读代码时，请记住以下经验法则：

* 查找名为 `+*AutoConfiguration+` 的类并阅读其源代码。
  特别注意 `+@Conditional*+` 注释，以了解它们启用的功能以及何时启用。
  在命令行中添加 `--debug` 或使用系统属性 `-Ddebug`，以在控制台上获取应用程序中所有自动配置决策的日志。
  在启用了 actuator 的运行应用程序中，查看 `conditions` 端点（`/actuator/conditions` 或 JMX 等效项）以获取相同信息。
* 查找 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation]（例如 javadoc:org.springframework.boot.autoconfigure.web.ServerProperties[]）的类，并从中读取可用的外部配置选项。
  javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] 注释具有作为外部属性前缀的 `name` 属性。
  因此，javadoc:org.springframework.boot.autoconfigure.web.ServerProperties[] 具有 `prefix="server"`，其配置属性为 `server.port`、`server.address` 等。
  在启用了 actuator 的运行应用程序中，查看 `configprops` 端点。
* 查找 javadoc:org.springframework.boot.context.properties.bind.Binder[] 上的 `bind` 方法的使用，以在宽松的方式下从 javadoc:org.springframework.core.env.Environment[] 中显式提取配置值。
  通常与前缀一起使用。
* 查找 javadoc:org.springframework.beans.factory.annotation.Value[format=annotation] 注释，这些注释直接绑定到 javadoc:org.springframework.core.env.Environment[]。
* 查找 javadoc:org.springframework.boot.autoconfigure.condition.ConditionalOnExpression[format=annotation] 注释，这些注释根据 SpEL 表达式切换功能，通常使用从 javadoc:org.springframework.core.env.Environment[] 解析的占位符进行评估。


[[howto.application.customize-the-environment-or-application-context]]
== 在启动之前自定义环境或 ApplicationContext

javadoc:org.springframework.boot.SpringApplication[] 具有 javadoc:org.springframework.context.ApplicationListener[] 和 javadoc:org.springframework.context.ApplicationContextInitializer[] 实现，用于对上下文或环境进行自定义。
Spring Boot 从 `META-INF/spring.factories` 加载许多此类自定义以供内部使用。
有多种方法可以注册其他自定义：

* 每个应用程序以编程方式，通过在运行 javadoc:org.springframework.boot.SpringApplication[] 之前调用 `addListeners` 和 `addInitializers` 方法。
* 对于所有应用程序，通过添加 `META-INF/spring.factories` 并打包应用程序都用作库的 jar 文件以声明方式。

javadoc:org.springframework.boot.SpringApplication[] 向监听器发送一些特殊的 javadoc:org.springframework.test.context.event.ApplicationEvents[]（有些甚至在上下文创建之前），然后注册监听器以接收 javadoc:org.springframework.context.ApplicationContext[] 发布的事件。
有关完整列表，请参阅 xref:reference:features/spring-application.adoc#features.spring-application.application-events-and-listeners[] 在“`Spring Boot 功能`”部分。

还可以通过使用 javadoc:org.springframework.boot.env.EnvironmentPostProcessor[] 在应用程序上下文刷新之前自定义 javadoc:org.springframework.core.env.Environment[]。
每个实现都应在 `META-INF/spring.factories` 中注册，如以下示例所示：

[source]
----
org.springframework.boot.env.EnvironmentPostProcessor=com.example.YourEnvironmentPostProcessor
----

该实现可以加载任意文件并将其添加到 javadoc:org.springframework.core.env.Environment[]。
例如，以下示例从类路径加载 YAML 配置文件：

include-code::MyEnvironmentPostProcessor[]

提示：javadoc:org.springframework.core.env.Environment[] 已经准备好所有 Spring Boot 默认加载的常用属性源。
因此，可以从环境中获取文件的位置。
前面的示例在列表末尾添加 `custom-resource` 属性源，以便在任何通常的其他位置定义的键优先。
自定义实现可以定义其他顺序。

注意：虽然在 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 上使用 javadoc:org.springframework.context.annotation.PropertySource[format=annotation] 似乎是将自定义资源加载到 javadoc:org.springframework.core.env.Environment[] 的便捷方法，但我们不推荐这样做。
此类属性源在应用程序上下文刷新之前不会添加到 javadoc:org.springframework.core.env.Environment[]。
这对于某些属性（如 `+logging.*+` 和 `+spring.main.*+`）的配置来说太晚了，这些属性在刷新开始之前读取。


[[howto.application.context-hierarchy]]
== 构建 ApplicationContext 层次结构（添加父或根上下文）

您可以使用 javadoc:org.springframework.boot.builder.SpringApplicationBuilder[] 类创建父/子 javadoc:org.springframework.context.ApplicationContext[] 层次结构。
有关更多信息，请参阅 xref:reference:features/spring-application.adoc#features.spring-application.fluent-builder-api[] 在“`Spring Boot 功能`”部分。


[[howto.application.non-web-application]]
== 创建非 Web 应用程序

并非所有 Spring 应用程序都必须是 Web 应用程序（或 Web 服务）。
如果您想在 `main` 方法中执行一些代码，但也想引导 Spring 应用程序以设置要使用的基础设施，您可以使用 Spring Boot 的 javadoc:org.springframework.boot.SpringApplication[] 功能。
javadoc:org.springframework.boot.SpringApplication[] 根据它是否认为需要 Web 应用程序来更改其 javadoc:org.springframework.context.ApplicationContext[] 类。
您可以做的第一件事是将与服务器相关的依赖项（例如 servlet API）从类路径中删除。
如果您不能这样做（例如，如果您从同一代码库运行两个应用程序），那么您可以显式调用 javadoc:org.springframework.boot.SpringApplication[] 实例上的 `setWebApplicationType(WebApplicationType.NONE)` 或设置 `applicationContextClass` 属性（通过 Java API 或外部属性）。
您希望作为业务逻辑运行的应用程序代码可以实现为 javadoc:org.springframework.boot.CommandLineRunner[] 并作为 javadoc:org.springframework.context.annotation.Bean[format=annotation] 定义放入上下文中。
