[[howto.batch]]
= 批处理应用程序

在从 Spring Boot 应用程序中使用 Spring Batch 时，通常会出现许多问题。
本节解决这些问题。


[[howto.batch.specifying-a-data-source]]
== 指定批处理数据源

默认情况下，批处理应用程序需要一个 javadoc:javax.sql.DataSource[] 来存储作业详细信息。
Spring Batch 默认期望一个 javadoc:javax.sql.DataSource[]。
要使用应用程序的主 javadoc:javax.sql.DataSource[] 以外的 javadoc:javax.sql.DataSource[]，请声明一个 javadoc:javax.sql.DataSource[] bean，并将其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法注释为 javadoc:org.springframework.boot.autoconfigure.batch.BatchDataSource[format=annotation]。
如果这样做并希望有两个数据源（例如保留主自动配置的 javadoc:javax.sql.DataSource[]），请将 javadoc:org.springframework.context.annotation.Bean[format=annotation] 注释的 `defaultCandidate` 属性设置为 `false`。
要获得更大的控制权，请将 javadoc:org.springframework.batch.core.configuration.annotation.EnableBatchProcessing[format=annotation] 添加到您的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类之一或扩展 javadoc:org.springframework.batch.core.configuration.support.DefaultBatchConfiguration[]。
有关更多详细信息，请参阅 javadoc:org.springframework.batch.core.configuration.annotation.EnableBatchProcessing[format=annotation] 和 javadoc:org.springframework.batch.core.configuration.support.DefaultBatchConfiguration[] 的 API 文档。

有关 Spring Batch 的更多信息，请参阅 {url-spring-batch-site}[Spring Batch 项目页面]。


[[howto.batch.specifying-a-transaction-manager]]
== 指定批处理事务管理器

类似于 xref:batch.adoc#howto.batch.specifying-a-data-source[]，您可以通过将其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法注释为 javadoc:org.springframework.boot.autoconfigure.batch.BatchTransactionManager[format=annotation] 来定义用于批处理的 javadoc:org.springframework.transaction.PlatformTransactionManager[]。
如果这样做并希望有两个事务管理器（例如保留自动配置的 javadoc:org.springframework.transaction.PlatformTransactionManager[]），请将 javadoc:org.springframework.context.annotation.Bean[format=annotation] 注释的 `defaultCandidate` 属性设置为 `false`。


[[howto.batch.specifying-a-task-executor]]
== 指定批处理任务执行器

类似于 xref:batch.adoc#howto.batch.specifying-a-data-source[]，您可以通过将其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法注释为 javadoc:org.springframework.boot.autoconfigure.batch.BatchTaskExecutor[format=annotation] 来定义用于批处理的 javadoc:org.springframework.core.task.TaskExecutor[]。
如果这样做并希望有两个任务执行器（例如保留自动配置的 javadoc:org.springframework.core.task.TaskExecutor[]），请将 javadoc:org.springframework.context.annotation.Bean[format=annotation] 注释的 `defaultCandidate` 属性设置为 `false`。


[[howto.batch.running-jobs-on-startup]]
== 在启动时运行 Spring Batch 作业

通过将 `spring-boot-starter-batch` 添加到应用程序的类路径中启用 Spring Batch 自动配置。

如果在应用程序上下文中找到单个 javadoc:org.springframework.batch.core.Job[] bean，则在启动时执行它（有关详细信息，请参阅 javadoc:org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner[]）。
如果找到多个 javadoc:org.springframework.batch.core.Job[] bean，则必须使用 configprop:spring.batch.job.name[] 指定要执行的作业。

要禁用在应用程序上下文中找到的 javadoc:org.springframework.batch.core.Job[]，请将 configprop:spring.batch.job.enabled[] 设置为 `false`。

有关更多详细信息，请参阅 {code-spring-boot-autoconfigure-src}/batch/BatchAutoConfiguration.java[`BatchAutoConfiguration`]。


[[howto.batch.running-from-the-command-line]]
== 从命令行运行

Spring Boot 将任何以 `--` 开头的命令行参数转换为要添加到 javadoc:org.springframework.core.env.Environment[] 的属性，请参阅 xref:reference:features/external-config.adoc#features.external-config.command-line-args[访问命令行属性]。
这不应用于将参数传递给批处理作业。
要在命令行上指定批处理参数，请使用常规格式（即不带 `--`），如下例所示：

[source,shell]
----
$ java -jar myapp.jar someParameter=someValue anotherParameter=anotherValue
----

如果在命令行上指定 javadoc:org.springframework.core.env.Environment[] 的属性，则作业会忽略它。
请考虑以下命令：

[source,shell]
----
$ java -jar myapp.jar --server.port=7070 someParameter=someValue
----

这仅为批处理作业提供一个参数：`someParameter=someValue`。


[[howto.batch.restarting-a-failed-job]]
== 重新启动已停止或失败的作业

要重新启动失败的 javadoc:org.springframework.batch.core.Job[]，必须在命令行上重新指定所有参数（标识和非标识）。
非标识参数不会从上一次执行中复制。
这允许它们被修改或删除。

注意：当您使用自定义 javadoc:org.springframework.batch.core.JobParametersIncrementer[] 时，您必须收集增量器管理的所有参数以重新启动失败的执行。


[[howto.batch.storing-job-repository]]
== 存储作业存储库

Spring Batch 需要一个数据存储来存储 javadoc:org.springframework.batch.core.Job[] 存储库。
如果您使用 Spring Boot，则必须使用实际数据库。
请注意，它可以是内存数据库，请参阅 {url-spring-batch-docs}/job.html#configuringJobRepository[配置作业存储库]。
