[[howto.build]]
= 构建

Spring Boot 包含用于 Maven 和 Gradle 的构建插件。
本节回答了有关这些插件的常见问题。



[[howto.build.generate-info]]
== 生成构建信息

Maven 插件和 Gradle 插件都允许生成包含项目坐标、名称和版本的构建信息。
还可以通过配置来添加其他属性。
当存在这样的文件时，Spring Boot 会自动配置一个 javadoc:org.springframework.boot.info.BuildProperties[] bean。

要使用 Maven 生成构建信息，请为 `build-info` 目标添加一个执行，如下例所示：

[source,xml,subs="verbatim,attributes"]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<version>{version-spring-boot}</version>
			<executions>
				<execution>
					<goals>
						<goal>build-info</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----

TIP: 有关更多详细信息，请参阅 xref:maven-plugin:build-info.adoc[Spring Boot Maven 插件文档]。

以下示例使用 Gradle 实现相同功能：

[source,gradle]
----
springBoot {
	buildInfo()
}
----

TIP: 有关更多详细信息，请参阅 xref:gradle-plugin:integrating-with-actuator.adoc[Spring Boot Gradle 插件文档]。



[[howto.build.generate-git-info]]
== 生成 Git 信息

Maven 和 Gradle 都允许生成一个 `git.properties` 文件，其中包含项目构建时 `git` 源代码库的状态信息。

对于 Maven 用户，`spring-boot-starter-parent` POM 包含一个预配置的插件，用于生成 `git.properties` 文件。
要使用它，请在 POM 中添加以下声明：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>io.github.git-commit-id</groupId>
			<artifactId>git-commit-id-maven-plugin</artifactId>
		</plugin>
	</plugins>
</build>
----

Gradle 用户可以使用 https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties[`gradle-git-properties`] 插件实现相同的结果，如下例所示：

[source,gradle]
----
plugins {
	id "com.gorylenko.gradle-git-properties" version "2.4.1"
}
----

Maven 和 Gradle 插件都允许配置 `git.properties` 中包含的属性。

TIP: `git.properties` 中的提交时间应符合以下格式：`yyyy-MM-dd'T'HH:mm:ssZ`。
这是上述两个插件的默认格式。
使用此格式可以将时间解析为 javadoc:java.util.Date[]，并在序列化为 JSON 时由 Jackson 的日期序列化配置设置控制其格式。



[[howto.build.generate-cyclonedx-sbom]]
== 生成 CycloneDX SBOM

Maven 和 Gradle 都允许在项目构建时生成 CycloneDX SBOM。

对于 Maven 用户，`spring-boot-starter-parent` POM 包含一个预配置的插件，用于生成 SBOM。
要使用它，请在 POM 中添加以下声明：

[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.cyclonedx</groupId>
            <artifactId>cyclonedx-maven-plugin</artifactId>
        </plugin>
    </plugins>
</build>
----

Gradle 用户可以使用 {url-cyclonedx-docs-gradle-plugin}[`cyclonedx-gradle-plugin`] 插件实现相同的结果，如下例所示：

[source,gradle]
----
plugins {
    id 'org.cyclonedx.bom' version '2.3.0'
}
----



[[howto.build.customize-dependency-versions]]
== 自定义依赖版本

`spring-boot-dependencies` POM 管理常见依赖的版本。
Spring Boot 的 Maven 和 Gradle 插件允许使用构建属性自定义这些管理的依赖版本。

WARNING: 每个 Spring Boot 版本都是针对这一特定的第三方依赖集进行设计和测试的。
覆盖版本可能会导致兼容性问题。

要使用 Maven 覆盖依赖版本，请参阅 Maven 插件文档中的 xref:maven-plugin:using.adoc[]。

要在 Gradle 中覆盖依赖版本，请参阅 Gradle 插件文档中的 xref:gradle-plugin:managing-dependencies.adoc#managing-dependencies.dependency-management-plugin.customizing[]。



[[howto.build.create-an-executable-jar-with-maven]]
== 使用 Maven 创建可执行 JAR

`spring-boot-maven-plugin` 可用于创建可执行的 "`fat`" JAR。
如果您使用 `spring-boot-starter-parent` POM，您可以声明插件并重新打包您的 jar，如下所示：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
	</plugins>
</build>
----

如果您不使用父 POM，您仍然可以使用该插件。
但是，您必须另外添加一个 `<executions>` 部分，如下所示：

[source,xml,subs="verbatim,attributes"]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<version>{version-spring-boot}</version>
			<executions>
				<execution>
					<goals>
						<goal>repackage</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----

有关完整的使用详情，请参阅 xref:maven-plugin:packaging.adoc#packaging.repackage-goal[插件文档]。



[[howto.build.use-a-spring-boot-application-as-dependency]]
== 将 Spring Boot 应用程序用作依赖

像 war 文件一样，Spring Boot 应用程序不打算用作依赖。
如果您的应用程序包含您希望与其他项目共享的类，推荐的方法是将该代码移到一个单独的模块中。
然后，您的应用程序和其他项目可以依赖于该单独的模块。

如果您无法按照上述建议重新安排代码，Spring Boot 的 Maven 和 Gradle 插件必须配置为生成一个适合用作依赖的单独工件。
可执行存档不能用作依赖，因为 xref:specification:executable-jar/nested-jars.adoc#appendix.executable-jar.nested-jars.jar-structure[可执行 jar 格式] 将应用程序类打包在 `BOOT-INF/classes` 中。
这意味着当可执行 jar 用作依赖时，它们无法被找到。

要生成两个工件，一个可用作依赖，一个可执行，必须指定一个分类器。
此分类器应用于可执行存档的名称，保留默认存档以用作依赖。

要在 Maven 中配置 `exec` 分类器，您可以使用以下配置：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<classifier>exec</classifier>
			</configuration>
		</plugin>
	</plugins>
</build>
----



[[howto.build.extract-specific-libraries-when-an-executable-jar-runs]]
== 在可执行 Jar 运行时提取特定库

大多数嵌套库在可执行 jar 中不需要解压即可运行。
然而，某些库可能会出现问题。
例如，JRuby 包含其自己的嵌套 jar 支持，假设 `jruby-complete.jar` 始终作为一个独立文件直接可用。

为了解决任何有问题的库，您可以标记特定的嵌套 jar，以便在可执行 jar 首次运行时自动解压。
这些嵌套 jar 被写入由 `java.io.tmpdir` 系统属性标识的临时目录下。

WARNING: 应注意确保您的操作系统配置不会在应用程序仍在运行时删除已解压到临时目录的 jar。

例如，要使用 Maven 插件标记 JRuby 以进行解压，您可以添加以下配置：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<requiresUnpack>
					<dependency>
						<groupId>org.jruby</groupId>
						<artifactId>jruby-complete</artifactId>
					</dependency>
				</requiresUnpack>
			</configuration>
		</plugin>
	</plugins>
</build>
----



[[howto.build.create-a-nonexecutable-jar]]
== 创建具有排除项的非可执行 JAR

通常，如果您有一个可执行和一个非可执行 jar 作为两个单独的构建产品，可执行版本具有在库 jar 中不需要的额外配置文件。
例如，`application.yaml` 配置文件可能会从非可执行 JAR 中排除。

在 Maven 中，可执行 jar 必须是主要工件，您可以为库添加一个分类 jar，如下所示：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
		<plugin>
			<artifactId>maven-jar-plugin</artifactId>
			<executions>
				<execution>
					<id>lib</id>
					<phase>package</phase>
					<goals>
						<goal>jar</goal>
					</goals>
					<configuration>
						<classifier>lib</classifier>
						<excludes>
							<exclude>application.yaml</exclude>
						</excludes>
					</configuration>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----



[[howto.build.remote-debug-maven]]
== 远程调试使用 Maven 启动的 Spring Boot 应用程序

要附加远程调试器到使用 Maven 启动的 Spring Boot 应用程序，您可以使用 xref:maven-plugin:index.adoc[maven 插件] 的 `jvmArguments` 属性。

有关更多详细信息，请参阅 xref:maven-plugin:run.adoc#run.examples.debug[此示例]。



[[howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib]]
== 使用 Ant 构建可执行存档而不使用 spring-boot-antlib

要使用 Ant 构建，您需要获取依赖项、编译，然后创建一个 jar 或 war 存档。
要使其可执行，您可以使用 `spring-boot-antlib` 模块，也可以按照以下说明进行操作：

. 如果您正在构建 jar，请将应用程序的类和资源打包在嵌套的 `BOOT-INF/classes` 目录中。
  如果您正在构建 war，请像往常一样将应用程序的类打包在嵌套的 `WEB-INF/classes` 目录中。
. 将运行时依赖项添加到 jar 的嵌套 `BOOT-INF/lib` 目录或 war 的 `WEB-INF/lib` 中。
  请记住*不要*压缩存档中的条目。
. 将 `provided`（嵌入式容器）依赖项添加到 jar 的嵌套 `BOOT-INF/lib` 目录或 war 的 `WEB-INF/lib-provided` 中。
  请记住*不要*压缩存档中的条目。
. 将 `spring-boot-loader` 类添加到存档的根目录（以便 `Main-Class` 可用）。
. 使用适当的启动器（例如 javadoc:org.springframework.boot.loader.launch.JarLauncher[] 用于 jar 文件）作为清单中的 `Main-Class` 属性，并指定它需要的其他属性作为清单条目 -- 主要是通过设置 `Start-Class` 属性。

以下示例显示了如何使用 Ant 构建可执行存档：

[source,xml]
----
<target name="build" depends="compile">
	<jar destfile="target/${ant.project.name}-${spring-boot.version}.jar" compress="false">
		<mappedresources>
			<fileset dir="target/classes" />
			<globmapper from="*" to="BOOT-INF/classes/*"/>
		</mappedresources>
		<mappedresources>
			<fileset dir="src/main/resources" erroronmissingdir="false"/>
			<globmapper from="*" to="BOOT-INF/classes/*"/>
		</mappedresources>
		<mappedresources>
			<fileset dir="${lib.dir}/runtime" />
			<globmapper from="*" to="BOOT-INF/lib/*"/>
		</mappedresources>
		<zipfileset src="${lib.dir}/loader/spring-boot-loader-jar-${spring-boot.version}.jar" />
		<manifest>
			<attribute name="Main-Class" value="org.springframework.boot.loader.launch.JarLauncher" />
			<attribute name="Start-Class" value="${start-class}" />
		</manifest>
	</jar>
</target>
----
