[[howto.build]]
= 构建

Spring Boot 包含 Maven 和 Gradle 的构建插件。
本节回答有关这些插件的常见问题。



[[howto.build.generate-info]]
== 生成构建信息

Maven 插件和 Gradle 插件都允许生成包含项目坐标、名称和版本的构建信息。
这些插件还可以通过配置添加额外的属性。
当存在这样的文件时，Spring Boot 会自动配置一个 javadoc:org.springframework.boot.info.BuildProperties[] bean。

要使用 Maven 生成构建信息，请添加 `build-info` 目标的执行，如下例所示：

[source,xml,subs="verbatim,attributes"]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<version>{version-spring-boot}</version>
			<executions>
				<execution>
					<goals>
						<goal>build-info</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----

提示：有关更多详细信息，请参阅 xref:maven-plugin:build-info.adoc[Spring Boot Maven 插件文档]。

以下示例使用 Gradle 做同样的事情：

[source,gradle]
----
springBoot {
	buildInfo()
}
----

提示：有关更多详细信息，请参阅 xref:gradle-plugin:integrating-with-actuator.adoc[Spring Boot Gradle 插件文档]。



[[howto.build.generate-git-info]]
== 生成 Git 信息

Maven 和 Gradle 都允许生成包含项目构建时 `git` 源代码仓库状态的 `git.properties` 文件。

对于 Maven 用户，`spring-boot-starter-parent` POM 包含一个预配置的插件来生成 `git.properties` 文件。
要使用它，请在您的 POM 中添加以下 https://github.com/git-commit-id/git-commit-id-maven-plugin[`Git Commit Id Plugin`] 声明：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>io.github.git-commit-id</groupId>
			<artifactId>git-commit-id-maven-plugin</artifactId>
		</plugin>
	</plugins>
</build>
----

Gradle 用户可以通过使用 https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties[`gradle-git-properties`] 插件来实现相同的结果，如下例所示：

[source,gradle]
----
plugins {
	id "com.gorylenko.gradle-git-properties" version "2.4.1"
}
----

Maven 和 Gradle 插件都允许配置包含在 `git.properties` 中的属性。

提示：`git.properties` 中的提交时间应该匹配以下格式：`yyyy-MM-dd'T'HH:mm:ssZ`。
这是上面列出的两个插件的默认格式。
使用这种格式可以让时间被解析为 javadoc:java.util.Date[]，并且当序列化为 JSON 时，其格式可以由 Jackson 的日期序列化配置设置控制。



[[howto.build.generate-cyclonedx-sbom]]
== 生成 CycloneDX SBOM

Maven 和 Gradle 都允许在项目构建时生成 CycloneDX SBOM。

对于 Maven 用户，`spring-boot-starter-parent` POM 包含一个预配置的插件来生成 SBOM。
要使用它，请在您的 POM 中添加以下 {url-cyclonedx-docs-maven-plugin}[`cyclonedx-maven-plugin`] 声明：

[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.cyclonedx</groupId>
            <artifactId>cyclonedx-maven-plugin</artifactId>
        </plugin>
    </plugins>
</build>
----

Gradle 用户可以通过使用 {url-cyclonedx-docs-gradle-plugin}[`cyclonedx-gradle-plugin`] 插件来实现相同的结果，如下例所示：

[source,gradle]
----
plugins {
    id 'org.cyclonedx.bom' version '1.10.0'
}
----



[[howto.build.customize-dependency-versions]]
== 自定义依赖版本

`spring-boot-dependencies` POM 管理常见依赖的版本。
Spring Boot 的 Maven 和 Gradle 插件允许使用构建属性自定义这些管理的依赖版本。

警告：每个 Spring Boot 版本都是针对这组特定的第三方依赖进行设计和测试的。
覆盖版本可能会导致兼容性问题。

要使用 Maven 覆盖依赖版本，请参阅 Maven 插件文档中的 xref:maven-plugin:using.adoc[]。

要在 Gradle 中覆盖依赖版本，请参阅 Gradle 插件文档中的 xref:gradle-plugin:managing-dependencies.adoc#managing-dependencies.dependency-management-plugin.customizing[]。



[[howto.build.create-an-executable-jar-with-maven]]
== 使用 Maven 创建可执行 JAR

`spring-boot-maven-plugin` 可用于创建可执行的"fat" JAR。
如果您使用 `spring-boot-starter-parent` POM，您可以声明该插件，您的 jar 将被重新打包，如下所示：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
	</plugins>
</build>
----

如果您不使用父 POM，您仍然可以使用该插件。
但是，您必须额外添加一个 `<executions>` 部分，如下所示：

[source,xml,subs="verbatim,attributes"]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<version>{version-spring-boot}</version>
			<executions>
				<execution>
					<goals>
						<goal>repackage</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----

有关完整的使用详情，请参阅 xref:maven-plugin:packaging.adoc#packaging.repackage-goal[插件文档]。



[[howto.build.use-a-spring-boot-application-as-dependency]]
== 将 Spring Boot 应用程序用作依赖项

与 war 文件一样，Spring Boot 应用程序不打算用作依赖项。
如果您的应用程序包含要与其他项目共享的类，推荐的方法是将该代码移动到单独的模块中。
然后，您的应用程序和其他项目可以依赖该模块。

如果您不能按照上述建议重新安排代码，Spring Boot 的 Maven 和 Gradle 插件必须配置为生成适合用作依赖项的单独构件。
可执行归档不能用作依赖项，因为 xref:specification:executable-jar/nested-jars.adoc#appendix.executable-jar.nested-jars.jar-structure[可执行 jar 格式] 将应用程序类打包在 `BOOT-INF/classes` 中。
这意味着当可执行 jar 用作依赖项时，它们无法被找到。

要生成两个构件，一个可以用作依赖项，一个可以执行，必须指定一个分类器。
这个分类器应用于可执行归档的名称，保留默认归档用作依赖项。

要在 Maven 中配置 `exec` 分类器，您可以使用以下配置：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<classifier>exec</classifier>
			</configuration>
		</plugin>
	</plugins>
</build>
----



[[howto.build.extract-specific-libraries-when-an-executable-jar-runs]]
== 在可执行 JAR 运行时提取特定库

可执行 jar 中的大多数嵌套库不需要解包就可以运行。
但是，某些库可能会有问题。
例如，JRuby 包含自己的嵌套 jar 支持，它假设 `jruby-complete.jar` 始终作为文件直接可用。

要处理任何有问题的库，您可以标记在可执行 jar 首次运行时应该自动解包的特定嵌套 jar。
这些嵌套 jar 被写入到由 `java.io.tmpdir` 系统属性标识的临时目录下。

警告：应该注意确保您的操作系统配置为在应用程序仍在运行时不会删除已解包到临时目录的 jar。

例如，要通过使用 Maven 插件指示 JRuby 应该被标记为解包，您需要添加以下配置：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<requiresUnpack>
					<dependency>
						<groupId>org.jruby</groupId>
						<artifactId>jruby-complete</artifactId>
					</dependency>
				</requiresUnpack>
			</configuration>
		</plugin>
	</plugins>
</build>
----



[[howto.build.create-a-nonexecutable-jar]]
== 创建带排除项的非可执行 JAR

通常，如果您有可执行和非可执行 jar 作为两个单独的构建产品，可执行版本有额外的配置文件，这些文件在库 jar 中不需要。
例如，`application.yaml` 配置文件可能从非可执行 JAR 中排除。

在 Maven 中，可执行 jar 必须是主要构件，您可以添加一个分类的 jar 作为库，如下所示：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
		<plugin>
			<artifactId>maven-jar-plugin</artifactId>
			<executions>
				<execution>
					<id>lib</id>
					<phase>package</phase>
					<goals>
						<goal>jar</goal>
					</goals>
					<configuration>
						<classifier>lib</classifier>
						<excludes>
							<exclude>application.yaml</exclude>
						</excludes>
					</configuration>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----



[[howto.build.remote-debug-maven]]
== 远程调试使用 Maven 启动的 Spring Boot 应用程序

要将远程调试器附加到使用 Maven 启动的 Spring Boot 应用程序，您可以使用 xref:maven-plugin:index.adoc[maven 插件] 的 `jvmArguments` 属性。

有关更多详细信息，请参阅 xref:maven-plugin:run.adoc#run.examples.debug[此示例]。



[[howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib]]
== 在不使用 spring-boot-antlib 的情况下使用 Ant 构建可执行归档

要使用 Ant 构建，您需要获取依赖项、编译，然后创建 jar 或 war 归档。
要使其可执行，您可以使用 `spring-boot-antlib` 模块，或者您可以按照以下说明操作：

. 如果您正在构建 jar，请在嵌套的 `BOOT-INF/classes` 目录中打包应用程序的类和资源。
  如果您正在构建 war，请像往常一样在嵌套的 `WEB-INF/classes` 目录中打包应用程序的类。
. 在嵌套的 `BOOT-INF/lib` 目录（对于 jar）或 `WEB-INF/lib`（对于 war）中添加运行时依赖项。
  记住*不要*压缩归档中的条目。
. 在嵌套的 `BOOT-INF/lib` 目录（对于 jar）或 `WEB-INF/lib-provided`（对于 war）中添加 `provided`（嵌入式容器）依赖项。
  记住*不要*压缩归档中的条目。
. 在归档的根目录添加 `spring-boot-loader` 类（以便 `Main-Class` 可用）。
. 在清单中使用适当的启动器（如 javadoc:org.springframework.boot.loader.launch.JarLauncher[] 用于 jar 文件）作为 `Main-Class` 属性，并指定它需要的其他属性作为清单条目 -- 主要是通过设置 `Start-Class` 属性。

以下示例显示如何使用 Ant 构建可执行归档：

[source,xml]
----
<target name="build" depends="compile">
	<jar destfile="target/${ant.project.name}-${spring-boot.version}.jar" compress="false">
		<mappedresources>
			<fileset dir="target/classes" />
			<globmapper from="*" to="BOOT-INF/classes/*"/>
		</mappedresources>
		<mappedresources>
			<fileset dir="src/main/resources" erroronmissingdir="false"/>
			<globmapper from="*" to="BOOT-INF/classes/*"/>
		</mappedresources>
		<mappedresources>
			<fileset dir="${lib.dir}/runtime" />
			<globmapper from="*" to="BOOT-INF/lib/*"/>
		</mappedresources>
		<zipfileset src="${lib.dir}/loader/spring-boot-loader-jar-${spring-boot.version}.jar" />
		<manifest>
			<attribute name="Main-Class" value="org.springframework.boot.loader.launch.JarLauncher" />
			<attribute name="Start-Class" value="${start-class}" />
		</manifest>
	</jar>
</target>
----
