[[howto.data-access]]
= 数据访问

Spring Boot 包含多个用于处理数据源的 starters。
本节回答与此相关的问题。



[[howto.data-access.configure-custom-datasource]]
== 配置自定义 DataSource

要配置您自己的 javadoc:javax.sql.DataSource[]，请在您的配置中定义该类型的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。
Spring Boot 在任何需要的地方重用您的 javadoc:javax.sql.DataSource[]，包括数据库初始化。
如果您需要外部化一些设置，可以将您的 javadoc:javax.sql.DataSource[] 绑定到环境（请参阅 xref:reference:features/external-config.adoc#features.external-config.typesafe-configuration-properties.third-party-configuration[]）。

以下示例显示如何在 bean 中定义数据源：

include-code::custom/MyDataSourceConfiguration[]

以下示例显示如何通过设置其属性来定义数据源：

[configprops%novalidate,yaml]
----
app:
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: "sa"
    pool-size: 30
----

假设 `SomeDataSource` 具有 URL、用户名和池大小的常规 JavaBean 属性，这些设置在 javadoc:javax.sql.DataSource[] 提供给其他组件之前会自动绑定。

Spring Boot 还提供了一个实用工具构建器类，称为 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[]，可用于创建标准数据源之一（如果在类路径上）。
构建器可以根据类路径上可用的内容检测使用哪一个。
它还根据 JDBC URL 自动检测驱动程序。

以下示例显示如何使用 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 创建数据源：

include-code::builder/MyDataSourceConfiguration[]

要使用该 javadoc:javax.sql.DataSource[] 运行应用程序，您只需要连接信息。
还可以提供池特定的设置。
有关更多详细信息，请查看运行时将要使用的实现。

以下示例显示如何通过设置属性来定义 JDBC 数据源：

[configprops%novalidate,yaml]
----
app:
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
    pool-size: 30
----

但是，由于方法的 javadoc:javax.sql.DataSource[] 返回类型，这里有一个问题。
这隐藏了连接池的实际类型，因此不会为您的自定义 javadoc:javax.sql.DataSource[] 生成配置属性元数据，并且在您的 IDE 中也没有自动完成功能。
要解决此问题，请使用构建器的 `type(Class)` 方法指定要构建的 javadoc:javax.sql.DataSource[] 类型，并更新方法的返回类型。
例如，以下显示如何使用 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 创建 javadoc:com.zaxxer.hikari.HikariDataSource[]：

include-code::simple/MyDataSourceConfiguration[]

不幸的是，这个基本设置不起作用，因为 Hikari 没有 `url` 属性。
相反，它有一个 `jdbc-url` 属性，这意味着您必须按如下方式重写配置：

[configprops%novalidate,yaml]
----
app:
  datasource:
    jdbc-url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
    pool-size: 30
----

要解决此问题，请使用 javadoc:org.springframework.boot.autoconfigure.jdbc.DataSourceProperties[]，它将为您处理 `url` 到 `jdbc-url` 的转换。
您可以使用其 `initializeDataSourceBuilder()` 方法从任何 javadoc:org.springframework.boot.autoconfigure.jdbc.DataSourceProperties[] 对象的状态初始化 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[]。
您可以注入 Spring Boot 自动创建的 javadoc:org.springframework.boot.autoconfigure.jdbc.DataSourceProperties[]，但是，这会将您的配置分散到 `+spring.datasource.*+` 和 `+app.datasource.*+` 中。
为避免这种情况，请使用自定义配置属性前缀定义自定义 javadoc:org.springframework.boot.autoconfigure.jdbc.DataSourceProperties[]，如下例所示：

include-code::configurable/MyDataSourceConfiguration[]

此设置等同于 Spring Boot 默认为您执行的操作，不同之处在于池的类型在代码中指定，其设置作为 `app.datasource.configuration.*` 属性公开。
javadoc:org.springframework.boot.autoconfigure.jdbc.DataSourceProperties[] 负责 `url` 到 `jdbc-url` 的转换，因此您可以按如下方式配置它：

[configprops%novalidate,yaml]
----
app:
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
    configuration:
      maximum-pool-size: 30
----

请注意，由于自定义配置在代码中指定使用 Hikari，`app.datasource.type` 将不起作用。

如 xref:reference:data/sql.adoc#data.sql.datasource.connection-pool[] 中所述，javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 支持几种不同的连接池。
要使用 Hikari 以外的池，请将其添加到类路径，使用 `type(Class)` 方法指定要使用的池类，并更新 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法的返回类型以匹配。
这还将为您提供您选择的特定连接池的配置属性元数据。

提示：Spring Boot 将 Hikari 特定的设置公开给 `spring.datasource.hikari`。
此示例使用更通用的 `configuration` 子命名空间，因为该示例不支持多个数据源实现。

有关更多详细信息，请参阅 xref:reference:data/sql.adoc#data.sql.datasource[] 和 {code-spring-boot-autoconfigure-src}/jdbc/DataSourceAutoConfiguration.java[`DataSourceAutoConfiguration`] 类。



[[howto.data-access.configure-two-datasources]]
== 配置两个数据源

要定义额外的 javadoc:javax.sql.DataSource[]，可以使用与前一节类似的方法。
一个关键区别是 javadoc:javax.sql.DataSource[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 必须使用 `defaultCandidate=false` 声明。
这可以防止自动配置的 javadoc:javax.sql.DataSource[] 回退。

注意：{url-spring-framework-docs}/core/beans/dependencies/factory-autowire.html#beans-factory-autowire-candidate[Spring Framework 参考文档] 更详细地描述了此功能。

要允许在需要的地方注入额外的 javadoc:javax.sql.DataSource[]，还要使用 javadoc:org.springframework.beans.factory.annotation.Qualifier[format=annotation] 对其进行注释，如下例所示：

include-code::MyAdditionalDataSourceConfiguration[]

要使用额外的 javadoc:javax.sql.DataSource[]，请使用相同的 javadoc:org.springframework.beans.factory.annotation.Qualifier[format=annotation] 注释注入点。

可以按如下方式配置自动配置和额外的数据源：

[configprops%novalidate,yaml]
----
spring:
  datasource:
    url: "jdbc:mysql://localhost/first"
    username: "dbuser"
    password: "dbpass"
    configuration:
      maximum-pool-size: 30
app:
  datasource:
    url: "jdbc:mysql://localhost/second"
    username: "dbuser"
    password: "dbpass"
    max-total: 30
----

通过 `spring.datasource.configuration.*` 属性，可以对自动配置的 javadoc:javax.sql.DataSource[] 进行更高级的、特定于实现的配置。
您也可以对额外的 javadoc:javax.sql.DataSource[] 应用相同的概念，如下例所示：

include-code::MyCompleteAdditionalDataSourceConfiguration[]

前面的示例使用与 Spring Boot 在自动配置中使用的相同逻辑配置额外的数据源。
请注意，`app.datasource.configuration.*` 属性根据所选的实现提供高级设置。

与 xref:how-to:data-access.adoc#howto.data-access.configure-custom-datasource[配置单个自定义 javadoc:javax.sql.DataSource[]] 一样，可以使用 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 上的 `type(Class)` 方法自定义一个或两个 javadoc:javax.sql.DataSource[] bean 的类型。
有关支持的类型的详细信息，请参阅 xref:reference:data/sql.adoc#data.sql.datasource.connection-pool[]。



[[howto.data-access.spring-data-repositories]]
== 使用 Spring Data Repositories

Spring Data 可以创建各种风格的 javadoc:org.springframework.data.repository.Repository[] 接口的实现。
Spring Boot 为您处理所有这些，只要这些 javadoc:org.springframework.data.repository.Repository[] 实现包含在 xref:reference:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 之一中，通常是使用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation] 注释的主应用程序类的包（或子包）。

对于许多应用程序，您只需要在类路径上放置正确的 Spring Data 依赖项。
有用于 JPA 的 `spring-boot-starter-data-jpa`，用于 Mongodb 的 `spring-boot-starter-data-mongodb`，以及用于其他支持技术的各种 starters。
要开始使用，请创建一些存储库接口来处理您的 javadoc:jakarta.persistence.Entity[format=annotation] 对象。

Spring Boot 通过扫描 xref:reference:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 来确定您的 javadoc:org.springframework.data.repository.Repository[] 实现的位置。
要获得更多控制，请使用 Spring Data 的 `@Enable…Repositories` 注释。

有关 Spring Data 的更多信息，请参阅 {url-spring-data-site}[Spring Data 项目页面]。



[[howto.data-access.separate-entity-definitions-from-spring-configuration]]
== 将 @Entity 定义与 Spring 配置分离

Spring Boot 通过扫描 xref:reference:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 来确定您的 javadoc:jakarta.persistence.Entity[format=annotation] 定义的位置。
要获得更多控制，请使用 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 注释，如下例所示：

include-code::MyApplication[]



[[howto.data-access.filter-scanned-entity-definitions]]
== 过滤扫描的 @Entity 定义

可以使用 javadoc:org.springframework.orm.jpa.persistenceunit.ManagedClassNameFilter[] bean 过滤 javadoc:jakarta.persistence.Entity[format=annotation] 定义。
这在测试中很有用，当只应考虑可用实体的子集时。
在以下示例中，只包含来自 `com.example.app.customer` 包的实体：

include-code::MyEntityScanConfiguration[]



[[howto.data-access.jpa-properties]]
== 配置 JPA 属性

Spring Data JPA 已经提供了一些与供应商无关的配置选项（例如用于 SQL 日志记录的选项），Spring Boot 将这些选项以及一些 Hibernate 特定的选项作为外部配置属性公开。
其中一些会根据上下文自动检测，因此您不必设置它们。

`spring.jpa.hibernate.ddl-auto` 是一个特殊情况，因为根据运行时条件，它有不同的默认值。
如果使用嵌入式数据库且没有模式管理器（如 Liquibase 或 Flyway）处理 javadoc:javax.sql.DataSource[]，则默认为 `create-drop`。
在所有其他情况下，它默认为 `none`。

JPA 提供程序检测要使用的方言。
如果您希望自己设置方言，请设置 configprop:spring.jpa.database-platform[] 属性。

最常见的设置选项如下例所示：

[configprops,yaml]
----
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: "com.example.MyPhysicalNamingStrategy"
    show-sql: true
----

此外，当创建本地 javadoc:jakarta.persistence.EntityManagerFactory[] 时，`+spring.jpa.properties.*+` 中的所有属性都会作为普通 JPA 属性传递（前缀被剥离）。

[警告]
====
您需要确保在 `+spring.jpa.properties.*+` 下定义的名称与 JPA 提供程序期望的名称完全匹配。
Spring Boot 不会对这些条目尝试任何类型的宽松绑定。

例如，如果要配置 Hibernate 的批处理大小，必须使用 `+spring.jpa.properties.hibernate.jdbc.batch_size+`。
如果使用其他形式，如 `batchSize` 或 `batch-size`，Hibernate 将不会应用该设置。
====

提示：如果您需要对 Hibernate 属性应用高级自定义，请考虑注册一个 javadoc:org.springframework.boot.autoconfigure.orm.jpa.HibernatePropertiesCustomizer[] bean，它将在创建 javadoc:jakarta.persistence.EntityManagerFactory[] 之前被调用。
这优先于自动配置应用的任何内容。



[[howto.data-access.configure-hibernate-naming-strategy]]
== 配置 Hibernate 命名策略

Hibernate 使用 {url-hibernate-userguide}#naming[两种不同的命名策略] 将对象模型中的名称映射到相应的数据库名称。
可以通过设置 `spring.jpa.hibernate.naming.physical-strategy` 和 `spring.jpa.hibernate.naming.implicit-strategy` 属性分别配置物理和隐式策略实现的完全限定类名。
或者，如果应用程序上下文中存在 javadoc:org.hibernate.boot.model.naming.ImplicitNamingStrategy[] 或 javadoc:org.hibernate.boot.model.naming.PhysicalNamingStrategy[] bean，Hibernate 将自动配置为使用它们。

默认情况下，Spring Boot 使用 javadoc:org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy[] 配置物理命名策略。
使用此策略，所有点都被下划线替换，驼峰命名也被下划线替换。
此外，默认情况下，所有表名都以小写形式生成。
例如，`TelephoneNumber` 实体映射到 `telephone_number` 表。
如果您的模式需要混合大小写标识符，请定义自定义 javadoc:org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy[] bean，如下例所示：

include-code::spring/MyHibernateConfiguration[]

如果您希望使用 Hibernate 的默认值，请设置以下属性：

[configprops,yaml]
----
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
----

或者，您可以配置以下 bean：

include-code::standard/MyHibernateConfiguration[]

有关更多详细信息，请参阅 {code-spring-boot-autoconfigure-src}/orm/jpa/HibernateJpaAutoConfiguration.java[`HibernateJpaAutoConfiguration`] 和 {code-spring-boot-autoconfigure-src}/orm/jpa/JpaBaseConfiguration.java[`JpaBaseConfiguration`]。



[[howto.data-access.configure-hibernate-second-level-caching]]
== 配置 Hibernate 二级缓存

Hibernate {url-hibernate-userguide}#caching[二级缓存] 可以为各种缓存提供程序配置。
与其配置 Hibernate 再次查找缓存提供程序，不如在可能的情况下提供上下文中可用的缓存提供程序。

要使用 JCache 执行此操作，首先确保类路径上有 `org.hibernate.orm:hibernate-jcache`。
然后，添加 javadoc:org.springframework.boot.autoconfigure.orm.jpa.HibernatePropertiesCustomizer[] bean，如下例所示：

include-code::MyHibernateSecondLevelCacheConfiguration[]

此自定义器将配置 Hibernate 使用与应用程序相同的 javadoc:org.springframework.cache.CacheManager[]。
也可以使用单独的 javadoc:org.springframework.cache.CacheManager[] 实例。
有关详细信息，请参阅 {url-hibernate-userguide}#caching-provider-jcache[Hibernate 用户指南]。



[[howto.data-access.dependency-injection-in-hibernate-components]]
== 在 Hibernate 组件中使用依赖注入

默认情况下，Spring Boot 注册一个 javadoc:org.hibernate.resource.beans.container.spi.BeanContainer[] 实现，它使用 javadoc:org.springframework.beans.factory.BeanFactory[]，以便转换器和实体监听器可以使用常规依赖注入。

您可以通过注册一个 javadoc:org.springframework.boot.autoconfigure.orm.jpa.HibernatePropertiesCustomizer[] 来禁用或调整此行为，该自定义器删除或更改 `hibernate.resource.beans.container` 属性。



[[howto.data-access.use-custom-entity-manager]]
== 使用自定义 EntityManagerFactory

要完全控制 javadoc:jakarta.persistence.EntityManagerFactory[] 的配置，您需要添加一个名为 '`entityManagerFactory`' 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。
Spring Boot 自动配置在存在该类型的 bean 时会关闭其实体管理器。

注意：当您自己创建 javadoc:org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean[] 的 bean 时，在创建自动配置的 javadoc:org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean[] 期间应用的任何自定义都会丢失。
确保使用自动配置的 javadoc:org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder[] 来保留 JPA 和供应商属性。
如果您依赖 `spring.jpa.*` 属性来配置命名策略或 DDL 模式等内容，这一点尤其重要。



[[howto.data-access.use-multiple-entity-managers]]
== 使用多个 EntityManagerFactories

如果您需要对多个数据源使用 JPA，您可能需要每个数据源一个 javadoc:jakarta.persistence.EntityManagerFactory[]。
Spring ORM 的 javadoc:org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean[] 允许您根据需要配置 javadoc:jakarta.persistence.EntityManagerFactory[]。
您还可以重用 javadoc:org.springframework.boot.autoconfigure.orm.jpa.JpaProperties[] 来绑定第二个 javadoc:jakarta.persistence.EntityManagerFactory[] 的设置。
基于 xref:how-to:data-access.adoc#howto.data-access.configure-two-datasources[配置第二个 javadoc:javax.sql.DataSource[] 的示例]，可以定义第二个 javadoc:jakarta.persistence.EntityManagerFactory[]，如下例所示：

include-code::MyAdditionalEntityManagerFactoryConfiguration[]

上面的示例使用带有 `@Qualifier("second")` 限定的 javadoc:javax.sql.DataSource[] bean 创建 javadoc:jakarta.persistence.EntityManagerFactory[]。
它扫描位于与 `Order` 相同包中的实体。
可以使用 `app.jpa` 命名空间映射其他 JPA 属性。
使用 `@Bean(defaultCandidate=false)` 允许定义 `secondJpaProperties` 和 `secondEntityManagerFactory` bean，而不会干扰相同类型的自动配置 bean。

注意：{url-spring-framework-docs}/core/beans/dependencies/factory-autowire.html#beans-factory-autowire-candidate[Spring Framework 参考文档] 更详细地描述了此功能。

您应该为需要 JPA 访问的任何其他数据源提供类似的配置。
要完成配置，您还需要为每个 javadoc:jakarta.persistence.EntityManagerFactory[] 配置一个 javadoc:org.springframework.orm.jpa.JpaTransactionManager[]。
或者，您可以使用跨越两者的 JTA 事务管理器。

如果您使用 Spring Data，您需要相应地配置 javadoc:org.springframework.data.jpa.repository.config.EnableJpaRepositories[format=annotation]，如下例所示：

include-code::OrderConfiguration[]

include-code::CustomerConfiguration[]



[[howto.data-access.use-traditional-persistence-xml]]
== 使用传统的 persistence.xml 文件

Spring Boot 默认不会搜索或使用 `META-INF/persistence.xml`。
如果您希望使用传统的 `persistence.xml`，您需要定义自己的类型为 javadoc:org.springframework.orm.jpa.LocalEntityManagerFactoryBean[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]（ID 为 '`entityManagerFactory`'），并在那里设置持久性单元名称。

有关默认设置，请参阅 {code-spring-boot-autoconfigure-src}/orm/jpa/JpaBaseConfiguration.java[`JpaBaseConfiguration`]。



[[howto.data-access.use-spring-data-jpa-and-mongo-repositories]]
== 使用 Spring Data JPA 和 Mongo Repositories

Spring Data JPA 和 Spring Data Mongo 都可以自动为您创建 javadoc:org.springframework.data.repository.Repository[] 实现。
如果它们都在类路径上，您可能需要进行一些额外的配置来告诉 Spring Boot 创建哪些存储库。
最明确的方法是使用标准的 Spring Data javadoc:org.springframework.data.jpa.repository.config.EnableJpaRepositories[format=annotation] 和 javadoc:org.springframework.data.mongodb.repository.config.EnableMongoRepositories[format=annotation] 注释，并提供您的 javadoc:org.springframework.data.repository.Repository[] 接口的位置。

还有一些标志（`+spring.data.*.repositories.enabled+` 和 `+spring.data.*.repositories.type+`），您可以使用它们在外部配置中打开和关闭自动配置的存储库。
例如，如果您想关闭 Mongo 存储库但仍使用自动配置的 javadoc:org.springframework.data.mongodb.core.MongoTemplate[]，这很有用。

其他自动配置的 Spring Data 存储库类型（Elasticsearch、Redis 等）也存在相同的障碍和相同的功能。
要使用它们，请相应地更改注释和标志的名称。



[[howto.data-access.customize-spring-data-web-support]]
== 自定义 Spring Data 的 Web 支持

Spring Data 提供了 Web 支持，简化了在 Web 应用程序中使用 Spring Data 存储库。
Spring Boot 在 `spring.data.web` 命名空间中提供了用于自定义其配置的属性。
请注意，如果您使用 Spring Data REST，您必须改用 `spring.data.rest` 命名空间中的属性。



[[howto.data-access.exposing-spring-data-repositories-as-rest]]
== 将 Spring Data Repositories 公开为 REST 端点

Spring Data REST 可以为您将 javadoc:org.springframework.data.repository.Repository[] 实现公开为 REST 端点，
前提是已为应用程序启用 Spring MVC。

Spring Boot 公开了一组有用的属性（来自 `spring.data.rest` 命名空间），用于自定义 javadoc:org.springframework.data.rest.core.config.RepositoryRestConfiguration[]。
如果您需要提供额外的自定义，您应该使用 javadoc:org.springframework.data.rest.webmvc.config.RepositoryRestConfigurer[] bean。

注意：如果您没有在自定义 javadoc:org.springframework.data.rest.webmvc.config.RepositoryRestConfigurer[] 上指定任何顺序，它会在 Spring Boot 内部使用的那个之后运行。
如果您需要指定顺序，请确保它高于 0。



[[howto.data-access.configure-a-component-that-is-used-by-jpa]]
== 配置 JPA 使用的组件

如果您想配置 JPA 使用的组件，则需要确保该组件在 JPA 之前初始化。
当组件是自动配置的时，Spring Boot 会为您处理这个问题。
例如，当 Flyway 是自动配置的时，Hibernate 被配置为依赖于 Flyway，以便 Flyway 有机会在 Hibernate 尝试使用数据库之前初始化数据库。

如果您自己配置组件，您可以使用 javadoc:org.springframework.boot.autoconfigure.orm.jpa.EntityManagerFactoryDependsOnPostProcessor[] 子类作为设置必要依赖项的便捷方式。
例如，如果您使用 Hibernate Search 并将 Elasticsearch 作为其索引管理器，则必须将任何 javadoc:jakarta.persistence.EntityManagerFactory[] bean 配置为依赖于 `elasticsearchClient` bean，如下例所示：

include-code::ElasticsearchEntityManagerFactoryDependsOnPostProcessor[]



[[howto.data-access.configure-jooq-with-multiple-datasources]]
== 使用两个数据源配置 jOOQ

如果您需要使用 jOOQ 处理多个数据源，您应该为每个数据源创建自己的 javadoc:org.jooq.DSLContext[]。
有关更多详细信息，请参阅 {code-spring-boot-autoconfigure-src}/jooq/JooqAutoConfiguration.java[`JooqAutoConfiguration`]。

提示：特别是，可以重用 javadoc:org.springframework.boot.autoconfigure.jooq.ExceptionTranslatorExecuteListener[] 和 javadoc:org.springframework.boot.autoconfigure.jooq.SpringTransactionProvider[] 来提供与自动配置使用单个 javadoc:javax.sql.DataSource[] 时类似的功能。
