[[howto.docker-compose]]
= Docker Compose

本节包含与 Spring Boot 中 Docker Compose 支持相关的主题。



[[howto.docker-compose.jdbc-url]]
== 自定义 JDBC URL

当使用 javadoc:org.springframework.boot.autoconfigure.jdbc.JdbcConnectionDetails[] 与 Docker Compose 时，可以通过向服务应用 `org.springframework.boot.jdbc.parameters` 标签来自定义 JDBC URL 的参数。例如：

[source,yaml]
----
services:
  postgres:
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=mydb'
    ports:
      - '5432:5432'
    labels:
      org.springframework.boot.jdbc.parameters: 'ssl=true&sslmode=require'
----

使用这个 Docker Compose 文件，使用的 JDBC URL 将是 `jdbc:postgresql://127.0.0.1:5432/mydb?ssl=true&sslmode=require`。



[[howto.docker-compose.sharing-services]]
== 在多个应用程序之间共享服务

如果您想在多个应用程序之间共享服务，请在一个应用程序中创建 `compose.yaml` 文件，然后在其他应用程序中使用配置属性 configprop:spring.docker.compose.file[] 来引用该 `compose.yaml` 文件。
您还应该将 configprop:spring.docker.compose.lifecycle-management[] 设置为 `start-only`，因为它默认为 `start-and-stop`，停止一个应用程序也会关闭其他仍在运行的应用程序的共享服务。
将其设置为 `start-only` 不会在应用程序停止时停止共享服务，但需要注意的是，如果您关闭所有应用程序，服务将保持运行。
您可以通过在包含 `compose.yaml` 文件的目录中运行 `docker compose stop` 来手动停止服务。
