[[howto.http-clients]]
= HTTP 客户端

Spring Boot 提供了许多与 HTTP 客户端一起工作的启动器。
本节回答有关使用它们的问题。



[[howto.http-clients.rest-template-proxy-configuration]]
== 配置 RestTemplate 使用代理

如 xref:reference:io/rest-client.adoc#io.rest-client.resttemplate.customization[RestTemplate 自定义]中所述，您可以使用 javadoc:org.springframework.boot.web.client.RestTemplateCustomizer[] 和 javadoc:org.springframework.boot.web.client.RestTemplateBuilder[] 来构建自定义的 javadoc:org.springframework.web.client.RestTemplate[]。
这是创建配置为使用代理的 javadoc:org.springframework.web.client.RestTemplate[] 的推荐方法。

代理配置的具体细节取决于正在使用的基础客户端请求工厂。



[[howto.http-clients.webclient-reactor-netty-customization]]
== 配置 Reactor Netty 基础的 WebClient 使用的 TcpClient

当 Reactor Netty 在类路径上时，会自动配置基于 Reactor Netty 的 javadoc:org.springframework.web.reactive.function.client.WebClient[]。
要自定义客户端对网络连接的处理，请提供 javadoc:org.springframework.http.client.reactive.ClientHttpConnector[] bean。
以下示例配置了 60 秒的连接超时并添加了 javadoc:io.netty.handler.timeout.ReadTimeoutHandler[]：

include-code::MyReactorNettyClientConfiguration[]

提示：注意使用 javadoc:org.springframework.http.client.ReactorResourceFactory[] 作为连接提供者和事件循环资源。
这确保了服务器接收请求和客户端发出请求时资源的有效共享。
