[[howto.http-clients]]
= HTTP 客户端

Spring Boot 提供了多个可用于 HTTP 客户端的 starter。
本节解答了与其使用相关的问题。



[[howto.http-clients.rest-template-proxy-configuration]]
== 配置 RestTemplate 使用代理

如 xref:reference:io/rest-client.adoc#io.rest-client.resttemplate.customization[RestTemplate Customization] 所述，你可以结合 javadoc:org.springframework.boot.web.client.RestTemplateCustomizer[] 和 javadoc:org.springframework.boot.web.client.RestTemplateBuilder[] 来构建自定义的 javadoc:org.springframework.web.client.RestTemplate[]。
这是创建配置代理的 javadoc:org.springframework.web.client.RestTemplate[] 的推荐方式。

代理配置的具体细节取决于所用的底层客户端请求工厂。



[[howto.http-clients.webclient-reactor-netty-customization]]
== 配置基于 Reactor Netty 的 WebClient 所用的 TcpClient

当 classpath 中存在 Reactor Netty 时，会自动配置基于 Reactor Netty 的 javadoc:org.springframework.web.reactive.function.client.WebClient[]。
如需自定义客户端的网络连接处理，可提供 javadoc:org.springframework.http.client.reactive.ClientHttpConnector[] bean。
以下示例配置了 60 秒连接超时，并添加了 javadoc:io.netty.handler.timeout.ReadTimeoutHandler[]：

include-code::MyReactorNettyClientConfiguration[]

TIP: 注意 javadoc:org.springframework.http.client.ReactorResourceFactory[] 的使用，用于连接提供者和事件循环资源。
这确保了服务端接收请求与客户端发起请求时资源的高效共享。
