[[howto.properties-and-configuration]]
= 属性与配置

本节包含有关设置和读取属性、配置设置及其与 Spring Boot 应用程序交互的主题。



[[howto.properties-and-configuration.expand-properties]]
== 在构建时自动扩展属性

与其硬编码一些在项目构建配置中也指定的属性，您可以通过使用现有的构建配置来自动扩展它们。
这在 Maven 和 Gradle 中都是可行的。



[[howto.properties-and-configuration.expand-properties.maven]]
=== 使用 Maven 自动扩展属性

您可以通过使用资源过滤在 Maven 项目中自动扩展属性。
如果您使用 `spring-boot-starter-parent`，则可以使用 `@..@` 占位符引用 Maven 的"项目属性"，如下例所示：

[configprops%novalidate,yaml]
----
app:
  encoding: "@project.build.sourceEncoding@"
  java:
    version: "@java.version@"
----

注意：只有生产配置才会以这种方式进行过滤（换句话说，不会对 `src/test/resources` 应用过滤）。

提示：如果您启用了 `addResources` 标志，`spring-boot:run` 目标可以将 `src/main/resources` 直接添加到类路径中（用于热重载目的）。
这样做会绕过资源过滤和此功能。
相反，您可以使用 `exec:java` 目标或自定义插件的配置。
有关更多详细信息，请参阅 xref:maven-plugin:using.adoc[插件使用页面]。

如果您不使用 starter parent，则需要在 `pom.xml` 的 `<build/>` 元素中包含以下元素：

[source,xml]
----
<resources>
	<resource>
		<directory>src/main/resources</directory>
		<filtering>true</filtering>
	</resource>
</resources>
----

您还需要在 `<plugins/>` 中包含以下元素：

[source,xml]
----
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-resources-plugin</artifactId>
	<version>2.7</version>
	<configuration>
		<delimiters>
			<delimiter>@</delimiter>
		</delimiters>
		<useDefaultDelimiters>false</useDefaultDelimiters>
	</configuration>
</plugin>
----

注意：如果您在配置中使用标准的 Spring 占位符（如 `$\{placeholder}`），`useDefaultDelimiters` 属性很重要。
如果该属性未设置为 `false`，这些占位符可能会被构建过程扩展。



[[howto.properties-and-configuration.expand-properties.gradle]]
=== 使用 Gradle 自动扩展属性

您可以通过配置 Java 插件的 `processResources` 任务来自动扩展 Gradle 项目中的属性，如下例所示：

[source,gradle]
----
tasks.named('processResources') {
	expand(project.properties)
}
----

然后，您可以使用占位符引用 Gradle 项目的属性，如下例所示：

[configprops%novalidate,yaml]
----
app:
  name: "${name}"
  description: "${description}"
----

注意：Gradle 的 `expand` 方法使用 Groovy 的 `SimpleTemplateEngine`，它会转换 `${..}` 标记。
`${..}` 样式与 Spring 自己的属性占位符机制冲突。
要将 Spring 属性占位符与自动扩展一起使用，请按如下方式转义 Spring 属性占位符：`\${..}`。



[[howto.properties-and-configuration.externalize-configuration]]
== 外部化 SpringApplication 的配置

javadoc:org.springframework.boot.SpringApplication[] 具有 bean 属性设置器，因此您可以在创建应用程序时使用其 Java API 来修改其行为。
或者，您可以通过在 `+spring.main.*+` 中设置属性来外部化配置。
例如，在 `application.properties` 中，您可能有以下设置：

[configprops,yaml]
----
spring:
  main:
    web-application-type: "none"
    banner-mode: "off"
----

然后，Spring Boot 横幅不会在启动时打印，并且应用程序不会启动嵌入式 Web 服务器。

外部配置中定义的属性会覆盖并替换使用 Java API 指定的值，但主要源除外。
主要源是提供给 javadoc:org.springframework.boot.SpringApplication[] 构造函数的源：

include-code::application/MyApplication[]

或者 javadoc:org.springframework.boot.builder.SpringApplicationBuilder[] 的 `sources(...)` 方法：

include-code::builder/MyApplication[]

根据上面的示例，如果我们有以下配置：

[configprops,yaml]
----
spring:
  main:
    sources: "com.example.MyDatabaseConfig,com.example.MyJmsConfig"
    banner-mode: "console"
----

实际应用程序将显示横幅（由配置覆盖）并使用三个源作为 javadoc:org.springframework.context.ApplicationContext[]。
应用程序源是：

. `MyApplication`（来自代码）
. `MyDatabaseConfig`（来自外部配置）
. `MyJmsConfig`（来自外部配置）



[[howto.properties-and-configuration.external-properties-location]]
== 更改应用程序外部属性的位置

默认情况下，来自不同源的属性会按照定义的顺序添加到 Spring javadoc:org.springframework.core.env.Environment[] 中（有关确切顺序，请参阅"Spring Boot 特性"部分中的 xref:reference:features/external-config.adoc[]）。

您还可以提供以下系统属性（或环境变量）来更改行为：

* configprop:spring.config.name[] (configprop:spring.config.name[format=envvar])：默认为 `application` 作为文件名的根。
* configprop:spring.config.location[] (configprop:spring.config.location[format=envvar])：要加载的文件（如类路径资源或 URL）。
  为此文档设置了一个单独的 javadoc:org.springframework.core.env.Environment[] 属性源，它可以被系统属性、环境变量或命令行覆盖。

无论您在环境中设置什么，Spring Boot 始终会如上所述加载 `application.properties`。
默认情况下，如果使用 YAML，则具有 `.yaml` 和 `.yml` 扩展名的文件也会添加到列表中。

提示：如果您想了解正在加载的文件的详细信息，可以将 `org.springframework.boot.context.config` 的 xref:reference:features/logging.adoc#features.logging.log-levels[日志级别] 设置为 `trace`。



[[howto.properties-and-configuration.short-command-line-arguments]]
== 使用"短"命令行参数

有些人喜欢使用（例如）`--port=9000` 而不是 `--server.port=9000` 来在命令行上设置配置属性。
您可以通过在 `application.properties` 中使用占位符来启用此行为，如下例所示：

[configprops,yaml]
----
server:
  port: "${port:8080}"
----

提示：如果您继承自 `spring-boot-starter-parent` POM，`maven-resources-plugins` 的默认过滤标记已从 `+${*}+` 更改为 `@`（即 `@maven.token@` 而不是 `${maven.token}`），以防止与 Spring 风格的占位符冲突。
如果您已直接为 `application.properties` 启用 Maven 过滤，您可能还想更改默认过滤标记以使用 https://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html#delimiters[其他分隔符]。

注意：在这种特定情况下，端口绑定在 PaaS 环境（如 Heroku 或 Cloud Foundry）中有效。
在这两个平台上，`PORT` 环境变量会自动设置，Spring 可以绑定到 javadoc:org.springframework.core.env.Environment[] 属性的大写同义词。



[[howto.properties-and-configuration.yaml]]
== 使用 YAML 作为外部属性

YAML 是 JSON 的超集，因此是存储分层格式外部属性的便捷语法，如下例所示：

[source,yaml]
----
spring:
  application:
    name: "cruncher"
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost/test"
server:
  port: 9000
----

创建一个名为 `application.yaml` 的文件并将其放在类路径的根目录中。
然后添加 `snakeyaml` 到您的依赖项中（Maven 坐标 `org.yaml:snakeyaml`，如果您使用 `spring-boot-starter` 则已包含）。
YAML 文件被解析为 Java `Map<String,Object>`（类似于 JSON 对象），Spring Boot 将映射展平为一级深度，并具有点分隔的键，就像许多人习惯使用 Java 中的 javadoc:java.util.Properties[] 文件一样。

前面的 YAML 示例对应于以下 `application.properties` 文件：

[source,properties,subs="verbatim",configprops]
----
spring.application.name=cruncher
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost/test
server.port=9000
----

有关 YAML 的更多信息，请参阅"Spring Boot 特性"部分中的 xref:reference:features/external-config.adoc#features.external-config.yaml[]。



[[howto.properties-and-configuration.set-active-spring-profiles]]
== 设置活动的 Spring Profiles

Spring javadoc:org.springframework.core.env.Environment[] 有一个 API 用于此目的，但您通常会设置系统属性（configprop:spring.profiles.active[]）或操作系统环境变量（configprop:spring.profiles.active[format=envvar]）。
此外，您可以使用 `-D` 参数启动应用程序（记住将其放在主类或 jar 归档文件之前），如下所示：

[source,shell]
----
$ java -jar -Dspring.profiles.active=production demo-0.0.1-SNAPSHOT.jar
----

在 Spring Boot 中，您还可以在 `application.properties` 中设置活动配置文件，如下例所示：

[configprops,yaml]
----
spring:
  profiles:
    active: "production"
----

以这种方式设置的值会被系统属性或环境变量设置替换，但不会被 `SpringApplicationBuilder.profiles()` 方法替换。
因此，后者 Java API 可用于扩充配置文件，而无需更改默认值。

有关更多信息，请参阅"Spring Boot 特性"部分中的 xref:reference:features/profiles.adoc[]。



[[howto.properties-and-configuration.set-default-spring-profile-name]]
== 设置默认 Profile 名称

默认配置文件是在没有活动配置文件时启用的配置文件。
默认情况下，默认配置文件的名称是 `default`，但可以使用系统属性（configprop:spring.profiles.default[]）或操作系统环境变量（configprop:spring.profiles.default[format=envvar]）进行更改。

在 Spring Boot 中，您还可以在 `application.properties` 中设置默认配置文件名称，如下例所示：

[configprops,yaml]
----
spring:
  profiles:
    default: "dev"
----

有关更多信息，请参阅"Spring Boot 特性"部分中的 xref:reference:features/profiles.adoc[]。



[[howto.properties-and-configuration.change-configuration-depending-on-the-environment]]
== 根据环境更改配置

Spring Boot 支持多文档 YAML 和 Properties 文件（有关详细信息，请参阅 xref:reference:features/external-config.adoc#features.external-config.files.multi-document[]），这些文件可以根据活动配置文件有条件地激活。

如果文档包含 `spring.config.activate.on-profile` 键，则配置文件值（逗号分隔的配置文件列表或配置文件表达式）将馈入 Spring `Environment.acceptsProfiles()` 方法。
如果配置文件表达式匹配，则该文档将包含在最终合并中（否则不包括），如下例所示：

[configprops,yaml]
----
server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: "development"
server:
  port: 9001
---
spring:
  config:
    activate:
      on-profile: "production"
server:
  port: 0
----

在前面的示例中，默认端口是 9000。
但是，如果名为"development"的 Spring 配置文件处于活动状态，则端口为 9001。
如果"production"处于活动状态，则端口为 0。

注意：文档按照遇到的顺序合并。
后面的值会覆盖前面的值。



[[howto.properties-and-configuration.discover-build-in-options-for-external-properties]]
== 发现外部属性的内置选项

Spring Boot 在运行时将 `application.properties`（或 YAML 文件和其他位置）中的外部属性绑定到应用程序中。
在单个位置没有（技术上也不可能）所有支持的属性的详尽列表，因为贡献可能来自类路径上的其他 jar 文件。

具有 Actuator 功能的运行应用程序有一个 `configprops` 端点，显示通过 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] 可用的所有已绑定和可绑定的属性。

附录包含一个 xref:appendix:application-properties/index.adoc[`application.properties`] 示例，其中列出了 Spring Boot 支持的最常见属性。
权威列表来自搜索源代码中的 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] 和 javadoc:org.springframework.beans.factory.annotation.Value[format=annotation] 注释，以及偶尔使用 javadoc:org.springframework.boot.context.properties.bind.Binder[]。
有关加载属性的确切顺序的更多信息，请参阅 xref:reference:features/external-config.adoc[]。
