[[testing.spring-boot-applications]]
= 测试 Spring Boot 应用程序

Spring Boot 应用程序是一个 Spring javadoc:org.springframework.context.ApplicationContext[]，所以除了你通常对普通 Spring 上下文所做的操作外，不需要做任何特殊的事情来测试它。

NOTE: 外部属性、日志记录和 Spring Boot 的其他功能只有在使用 javadoc:org.springframework.boot.SpringApplication[] 创建上下文时才会默认安装到上下文中。

Spring Boot 提供了 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 注解，当你需要 Spring Boot 功能时，它可以作为标准 `spring-test` javadoc:org.springframework.test.context.ContextConfiguration[format=annotation] 注解的替代方案。
该注解通过 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[使用 javadoc:org.springframework.boot.SpringApplication[] 创建测试中使用的 javadoc:org.springframework.context.ApplicationContext[]] 来工作。
除了 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 之外，还提供了许多其他注解用于 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[测试应用程序的特定部分]。

TIP: 如果你使用 JUnit 4，别忘了在测试中添加 `@RunWith(SpringRunner.class)`，否则注解将被忽略。
如果你使用 JUnit 5，则不需要添加等效的 `@ExtendWith(SpringExtension.class)`，因为 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 和其他 `@...Test` 注解已经用该注解进行了标注。

默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会启动服务器。
你可以使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 的 `webEnvironment` 属性来进一步优化测试的运行方式：

* `MOCK`(默认) : 加载一个 web javadoc:org.springframework.context.ApplicationContext[] 并提供模拟的 web 环境。
使用此注解时不会启动嵌入式服务器。
如果你的类路径上没有可用的 web 环境，此模式会透明地回退到创建常规的非 web javadoc:org.springframework.context.ApplicationContext[]。
它可以与 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-mock-environment[`@AutoConfigureMockMvc` 或 javadoc:org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient[format=annotation]] 结合使用，用于基于模拟的 web 应用程序测试。
* `RANDOM_PORT`: 加载一个 javadoc:org.springframework.boot.web.context.WebServerApplicationContext[] 并提供真实的 web 环境。
嵌入式服务器会启动并监听随机端口。
* `DEFINED_PORT`: 加载一个 javadoc:org.springframework.boot.web.context.WebServerApplicationContext[] 并提供真实的 web 环境。
嵌入式服务器会启动并监听定义的端口（来自你的 `application.properties`）或默认端口 `8080`。
* `NONE`: 通过使用 javadoc:org.springframework.boot.SpringApplication[] 加载 javadoc:org.springframework.context.ApplicationContext[]，但不提供任何 web 环境（模拟或其他）。

NOTE: 如果你的测试是 javadoc:org.springframework.transaction.annotation.Transactional[format=annotation]，默认情况下它会在每个测试方法结束时回滚事务。
但是，由于使用这种安排与 `RANDOM_PORT` 或 `DEFINED_PORT` 隐式提供了真实的 servlet 环境，HTTP 客户端和服务器在单独的线程中运行，因此也在单独的事务中。
在这种情况下，服务器上启动的任何事务都不会回滚。

NOTE: 如果你的应用程序为管理服务器使用不同的端口，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 与 `webEnvironment = WebEnvironment.RANDOM_PORT` 也会在单独的随机端口上启动管理服务器。



[[testing.spring-boot-applications.detecting-web-app-type]]
== 检测 Web 应用程序类型

如果 Spring MVC 可用，则配置基于 MVC 的常规应用程序上下文。
如果你只有 Spring WebFlux，我们将检测到它并配置基于 WebFlux 的应用程序上下文。

如果两者都存在，Spring MVC 优先。
如果你想在这种情况下测试响应式 web 应用程序，你必须设置 configprop:spring.main.web-application-type[] 属性：

include-code::MyWebFluxTests[]



[[testing.spring-boot-applications.detecting-configuration]]
== 检测测试配置

如果你熟悉 Spring Test Framework，你可能习惯于使用 `@ContextConfiguration(classes=...)` 来指定要加载的 Spring javadoc:org.springframework.context.annotation.Configuration[format=annotation]。
或者，你可能经常在测试中使用嵌套的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类。

在测试 Spring Boot 应用程序时，这通常不是必需的。
Spring Boot 的 `@*Test` 注解会在你没有明确定义配置时自动搜索你的主配置。

搜索算法从包含测试的包开始向上搜索，直到找到带有 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.boot.SpringBootConfiguration[format=annotation] 注解的类。
只要你以合理的方式 xref:using/structuring-your-code.adoc[组织你的代码]，通常都能找到你的主配置。

[NOTE]
====
如果你使用 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[测试注解来测试应用程序的特定部分]，你应该避免在 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.user-configuration-and-slicing[主方法的应用程序类]上添加特定于某个区域的配置设置。

javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 的底层组件扫描配置定义了排除过滤器，用于确保切片按预期工作。
如果你在带有 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解的类上使用显式的 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] 指令，请注意这些过滤器将被禁用。
如果你使用切片，你应该重新定义它们。
====

如果你想自定义主配置，你可以使用嵌套的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 类。
与嵌套的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类（它会替代你的应用程序的主配置）不同，嵌套的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 类会与你的应用程序的主配置一起使用。

NOTE: Spring 的测试框架会在测试之间缓存应用程序上下文。
因此，只要你的测试共享相同的配置（无论它是如何被发现的），加载上下文的潜在耗时过程只会发生一次。



[[testing.spring-boot-applications.using-main]]
== 使用测试配置的主方法

通常，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 发现的测试配置将是你的主 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]。
在大多数结构良好的应用程序中，这个配置类还将包含用于启动应用程序的 `main` 方法。

例如，以下是一个典型的 Spring Boot 应用程序的常见代码模式：

include-code::typical/MyApplication[]

在上面的例子中，`main` 方法除了委托给 javadoc:org.springframework.boot.SpringApplication#run(java.lang.Class,java.lang.String...)[] 之外没有做任何事情。
但是，可以在调用 javadoc:org.springframework.boot.SpringApplication#run(java.lang.Class,java.lang.String...)[] 之前应用自定义的 `main` 方法。

例如，这里是一个更改横幅模式和设置其他配置文件的应用程序：

include-code::custom/MyApplication[]

由于 `main` 方法中的自定义可能会影响生成的 javadoc:org.springframework.context.ApplicationContext[]，你可能还想使用 `main` 方法来创建测试中使用的 javadoc:org.springframework.context.ApplicationContext[]。
默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会调用你的 `main` 方法，而是直接使用类本身来创建 javadoc:org.springframework.context.ApplicationContext[]。

如果你想改变这个行为，你可以将 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 的 `useMainMethod` 属性更改为 javadoc:org.springframework.boot.test.context.SpringBootTest$UseMainMethod#ALWAYS[] 或 javadoc:org.springframework.boot.test.context.SpringBootTest$UseMainMethod#WHEN_AVAILABLE[]。
当设置为 `ALWAYS` 时，如果找不到 `main` 方法，测试将失败。
当设置为 `WHEN_AVAILABLE` 时，如果 `main` 方法可用，将使用它，否则将使用标准加载机制。

例如，以下测试将调用 `MyApplication` 的 `main` 方法来创建 javadoc:org.springframework.context.ApplicationContext[]。
如果 main 方法设置了其他配置文件，那么当 javadoc:org.springframework.context.ApplicationContext[] 启动时，这些配置文件将处于活动状态。

include-code::always/MyApplicationTests[]



[[testing.spring-boot-applications.excluding-configuration]]
== 排除测试配置

如果你的应用程序使用组件扫描（例如，如果你使用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]），你可能会发现仅为特定测试创建的顶级配置类意外地被到处拾取。

正如我们 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[之前看到的]，javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 可以用于测试的内部类来自定义主配置。
javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 也可以用于顶级类。这样做表示该类不应被扫描拾取。
然后你可以在需要的地方显式导入该类，如下例所示：

include-code::MyTests[]

NOTE: 如果你直接使用 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]（即不是通过 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]），你需要向其注册 javadoc:org.springframework.boot.context.TypeExcludeFilter[]。
有关详细信息，请参阅 javadoc:org.springframework.boot.context.TypeExcludeFilter[] API 文档。

NOTE: 导入的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 比内部类 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 更早处理，并且导入的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 会在通过组件扫描找到的任何配置之前处理。
一般来说，这种排序差异没有明显的影响，但如果你依赖 bean 覆盖，这是需要注意的。



[[testing.spring-boot-applications.using-application-arguments]]
== 使用应用程序参数

如果你的应用程序需要 xref:features/spring-application.adoc#features.spring-application.application-arguments[参数]，你可以
让 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 使用 `args` 属性注入它们。

include-code::MyApplicationArgumentTests[]



[[testing.spring-boot-applications.with-mock-environment]]
== 使用模拟环境进行测试

默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会启动服务器，而是设置一个模拟环境来测试 web 端点。

使用 Spring MVC，我们可以使用 {url-spring-framework-docs}/testing/mockmvc.html[`MockMvc`] 查询我们的 web 端点。
提供了三种集成：

* 使用 Hamcrest 的常规 {url-spring-framework-docs}/testing/mockmvc/hamcrest.html[`MockMvc`]。
* {url-spring-framework-docs}/testing/mockmvc/assertj.html[`MockMvcTester`]，它包装了 javadoc:org.springframework.test.web.servlet.MockMvc[] 并使用 AssertJ。
* {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，其中 javadoc:org.springframework.test.web.servlet.MockMvc[] 被插入作为服务器来处理请求。

以下示例展示了可用的集成：

include-code::MyMockMvcTests[]

TIP: 如果你只想关注 web 层而不想启动完整的 javadoc:org.springframework.context.ApplicationContext[]，可以考虑 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.spring-mvc-tests[使用 javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 代替]。

对于 Spring WebFlux 端点，你可以使用 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，如下例所示：

include-code::MyMockWebTestClientTests[]

[TIP]
====
在模拟环境中测试通常比使用完整的 servlet 容器运行更快。
但是，由于模拟发生在 Spring MVC 层，依赖较低级别 servlet 容器行为的代码无法直接用 MockMvc 测试。

例如，Spring Boot 的错误处理基于 servlet 容器提供的"`error page`"支持。
这意味着，虽然你可以测试你的 MVC 层按预期抛出和处理异常，但你无法直接测试是否渲染了特定的 xref:web/servlet.adoc#web.servlet.spring-mvc.error-handling.error-pages[自定义错误页面]。
如果你需要测试这些较低级别的关注点，你可以按照下一节所述启动一个完全运行的服务器。
====



[[testing.spring-boot-applications.with-running-server]]
== 使用运行中的服务器进行测试

如果你需要启动一个完全运行的服务器，我们建议你使用随机端口。
如果你使用 `@SpringBootTest(webEnvironment=WebEnvironment.RANDOM_PORT)`，每次测试运行时都会随机选择一个可用端口。

javadoc:org.springframework.boot.test.web.server.LocalServerPort[format=annotation] 注解可用于 xref:how-to:webserver.adoc#howto.webserver.discover-port[注入实际使用的端口]到你的测试中。
为了方便起见，需要对已启动的服务器进行 REST 调用的测试还可以自动装配一个 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，它会解析到运行服务器的相对链接，并带有用于验证响应的专用 API，如下例所示：

include-code::MyRandomPortWebTestClientTests[]

TIP: javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 也可以与 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-mock-environment[模拟环境]一起使用，通过用 javadoc:org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient[format=annotation] 注解你的测试类来移除对运行服务器的需求。

这种设置需要类路径上有 `spring-webflux`。
如果你不能或不想添加 webflux，Spring Boot 还提供了 javadoc:org.springframework.boot.test.web.client.TestRestTemplate[] 工具：

include-code::MyRandomPortTestRestTemplateTests[]



[[testing.spring-boot-applications.customizing-web-test-client]]
== 自定义 WebTestClient

要自定义 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] bean，可以配置一个 javadoc:org.springframework.boot.test.web.reactive.server.WebTestClientBuilderCustomizer[] bean。
任何此类 bean 都会接收用于创建 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 的 javadoc:org.springframework.test.web.reactive.server.WebTestClient$Builder[]。



[[testing.spring-boot-applications.jmx]]
== 使用 JMX

由于测试上下文框架会缓存上下文，默认情况下 JMX 是禁用的，以防止相同组件注册到同一个域。
如果此类测试需要访问 javadoc:javax.management.MBeanServer[]，可以考虑将其标记为 dirty：

include-code::MyJmxTests[]



[[testing.spring-boot-applications.observations]]
== 使用 Observations

如果你为 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[切片测试] 添加了 javadoc:org.springframework.boot.test.autoconfigure.actuate.observability.AutoConfigureObservability[format=annotation] 注解，它会自动配置一个 javadoc:io.micrometer.observation.ObservationRegistry[]。



[[testing.spring-boot-applications.metrics]]
== 使用 Metrics

无论你的类路径如何，除了内存实现外，meter registries 在使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 时都不会自动配置。

如果你需要在集成测试中将指标导出到其他后端，可以为其添加 javadoc:org.springframework.boot.test.autoconfigure.actuate.observability.AutoConfigureObservability[format=annotation] 注解。

如果你为 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[切片测试] 添加了 javadoc:org.springframework.boot.test.autoconfigure.actuate.observability.AutoConfigureObservability[format=annotation] 注解，它会自动配置一个内存实现的 javadoc:io.micrometer.core.instrument.MeterRegistry[]。
在切片测试中，数据导出不支持 javadoc:org.springframework.boot.test.autoconfigure.actuate.observability.AutoConfigureObservability[format=annotation] 注解。



[[testing.spring-boot-applications.tracing]]
== 使用 Tracing

无论你的类路径如何，数据上报相关的 tracing 组件在使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 时都不会自动配置。

如果你需要这些组件作为集成测试的一部分，可以为测试添加 javadoc:org.springframework.boot.test.autoconfigure.actuate.observability.AutoConfigureObservability[format=annotation] 注解。

如果你创建了自己的上报组件（例如自定义的 javadoc:io.opentelemetry.sdk.trace.export.SpanExporter[] 或 `brave.handler.SpanHandler`），并且你不希望它们在测试中生效，可以使用 javadoc:org.springframework.boot.actuate.autoconfigure.tracing.ConditionalOnEnabledTracing[format=annotation] 注解来禁用它们。

如果你为 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[切片测试] 添加了 javadoc:org.springframework.boot.test.autoconfigure.actuate.observability.AutoConfigureObservability[format=annotation] 注解，它会自动配置一个 no-op 的 javadoc:io.micrometer.tracing.Tracer[]。
在切片测试中，数据导出不支持 javadoc:org.springframework.boot.test.autoconfigure.actuate.observability.AutoConfigureObservability[format=annotation] 注解。



[[testing.spring-boot-applications.mocking-beans]]
== Mock 和 Spy Bean

在运行测试时，有时需要在应用上下文中 mock 某些组件。
例如，你可能有一个远程服务的 facade，在开发期间无法访问。
Mock 也可以用于模拟在真实环境中难以触发的故障。

Spring Framework 提供了 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 注解，可以用来为 javadoc:org.springframework.context.ApplicationContext[] 中的 bean 定义 Mockito mock。
此外，javadoc:org.springframework.test.context.bean.override.mockito.MockitoSpyBean[format=annotation] 可用于定义 Mockito spy。
更多关于这些特性的内容请参见 {url-spring-framework-docs}/testing/annotations/integration-spring/annotation-mockitobean.html[Spring Framework 文档]。



[[testing.spring-boot-applications.autoconfigured-tests]]
== 自动配置测试

Spring Boot 的自动配置系统对应用程序很有效，但有时对测试来说会有点过度。
通常只加载测试应用程序"切片"所需的部分配置会更有帮助。
例如，你可能只想测试 Spring MVC 控制器的 URL 映射是否正确，不希望在这些测试中涉及数据库调用，或者你想测试 JPA 实体，但在这些测试运行时不关心 web 层。

`spring-boot-test-autoconfigure` 模块包含许多注解，可用于自动配置这些"切片"。
它们的工作方式类似，提供一个 `@...Test` 注解来加载 javadoc:org.springframework.context.ApplicationContext[]，以及一个或多个 `@AutoConfigure...` 注解用于自定义自动配置设置。

NOTE: 每个切片都将组件扫描限制在合适的组件范围，并只加载非常有限的自动配置类。
如果你需要排除其中某个自动配置，大多数 `@...Test` 注解都提供了 `excludeAutoConfiguration` 属性。
或者，你可以使用 `@ImportAutoConfiguration#exclude`。

NOTE: 不支持在一个测试中通过多个 `@...Test` 注解包含多个"切片"。
如果你需要多个"切片"，请选择一个 `@...Test` 注解，并手动包含其他"切片"的 `@AutoConfigure...` 注解。

TIP: 你也可以将 `@AutoConfigure...` 注解与标准的 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 注解一起使用。
如果你不关心应用程序"切片"，但希望获得部分自动配置的测试 bean，可以使用这种组合。



[[testing.spring-boot-applications.json-tests]]
== 自动配置 JSON 测试

要测试对象的 JSON 序列化和反序列化是否按预期工作，可以使用 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 注解。
javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 会自动配置可用的 JSON 映射器，支持以下库之一：

* Jackson javadoc:com.fasterxml.jackson.databind.ObjectMapper[]，任何 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] bean 以及任何 Jackson javadoc:com.fasterxml.jackson.databind.Module[]
* `Gson`
* `Jsonb`

TIP: javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

如果你需要配置自动配置的元素，可以使用 javadoc:org.springframework.boot.test.autoconfigure.json.AutoConfigureJsonTesters[format=annotation] 注解。

Spring Boot 提供了基于 AssertJ 的辅助类，可与 JSONAssert 和 JsonPath 库配合使用，检查 JSON 是否符合预期。
javadoc:org.springframework.boot.test.json.JacksonTester[]、javadoc:org.springframework.boot.test.json.GsonTester[]、javadoc:org.springframework.boot.test.json.JsonbTester[] 和 javadoc:org.springframework.boot.test.json.BasicJsonTester[] 类分别可用于 Jackson、Gson、Jsonb 和字符串。
在使用 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 时，测试类中的任何辅助字段都可以用 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注解。
以下示例展示了 Jackson 的测试类：

include-code::MyJsonTests[]

NOTE: JSON 辅助类也可以直接在标准单元测试中使用。
如果你没有使用 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation]，可以在 javadoc:org.junit.jupiter.api.BeforeEach[format=annotation] 方法中调用辅助类的 `initFields` 方法。

如果你使用 Spring Boot 的 AssertJ 辅助类对某个 JSON 路径的数值进行断言，可能无法直接使用 `isEqualTo`，具体取决于类型。
你可以使用 AssertJ 的 `satisfies` 来断言该值符合给定条件。
例如，下面的例子断言实际数值是接近 `0.15` 的浮点数，允许偏差为 `0.01`。

include-code::MyJsonAssertJTests[tag=*]



[[testing.spring-boot-applications.spring-mvc-tests]]
== 自动配置 Spring MVC 测试

要测试 Spring MVC 控制器是否按预期工作，请使用 javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 注解。
javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 会自动配置 Spring MVC 基础设施，并将扫描的 bean 限制为 javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.web.bind.annotation.ControllerAdvice[format=annotation]、javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation]、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[]、javadoc:jakarta.servlet.Filter[]、javadoc:org.springframework.web.servlet.HandlerInterceptor[]、javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[]、javadoc:org.springframework.boot.autoconfigure.web.servlet.WebMvcRegistrations[] 和 javadoc:org.springframework.web.method.support.HandlerMethodArgumentResolver[]。
当使用 javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

TIP: 如果你需要注册额外组件，如 Jackson 的 javadoc:com.fasterxml.jackson.databind.Module[]，可以在测试上使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 导入额外的配置类。

通常，javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 只针对单个控制器，并与 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 结合使用，为所需的协作者提供 mock 实现。

javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 还会自动配置 javadoc:org.springframework.test.web.servlet.MockMvc[]。
Mock MVC 提供了一种强大的方式，可以快速测试 MVC 控制器，而无需启动完整的 HTTP 服务器。
如果可用，还会自动配置 javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[] 提供的 AssertJ 支持。

TIP: 你也可以在非 `@WebMvcTest`（如 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]）中，通过添加 javadoc:org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc[format=annotation] 注解，自动配置 javadoc:org.springframework.test.web.servlet.MockMvc[] 和 javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[]。
以下示例使用了 javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[]：

include-code::MyControllerTests[]

TIP: 如果你需要配置自动配置的元素（例如，何时应用 servlet 过滤器），可以在 javadoc:org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc[format=annotation] 注解中使用属性。

如果你使用 HtmlUnit 和 Selenium，自动配置还会提供 HtmlUnit 的 javadoc:org.springframework.web.reactive.function.client.WebClient[] bean 和/或 Selenium 的 javadoc:org.openqa.selenium.WebDriver[] bean。
以下示例使用了 HtmlUnit：

include-code::MyHtmlUnitTests[]

NOTE: 默认情况下，Spring Boot 会将 javadoc:org.openqa.selenium.WebDriver[] bean 放在一个特殊的"`scope`"中，以确保每个测试后驱动程序退出并注入新实例。
如果你不想要这种行为，可以在 javadoc:org.openqa.selenium.WebDriver[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation] 定义上添加 `@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)`。

WARNING: Spring Boot 创建的 `webDriver` scope 会替换任何用户自定义的同名 scope。
如果你自定义了 `webDriver` scope，使用 javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 时可能会发现它不再生效。

如果类路径上有 Spring Security，javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation] 还会扫描 javadoc:org.springframework.security.config.annotation.web.WebSecurityConfigurer[] bean。
对于此类测试，不必完全禁用安全性，可以使用 Spring Security 的测试支持。
关于如何使用 Spring Security 的 javadoc:org.springframework.test.web.servlet.MockMvc[] 支持的更多细节，请参见 xref:how-to:testing.adoc#howto.testing.with-spring-security[]"`How-to Guides"`部分。

TIP: 有时仅编写 Spring MVC 测试还不够；Spring Boot 可以帮助你运行 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-running-server[带有实际服务器的完整端到端测试]。



[[testing.spring-boot-applications.spring-webflux-tests]]
== 自动配置 Spring WebFlux 测试

要测试 {url-spring-framework-docs}/web-reactive.html[Spring WebFlux] 控制器是否按预期工作，可以使用 javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 注解。
javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 会自动配置 Spring WebFlux 基础设施，并将扫描的 bean 限制为 javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.web.bind.annotation.ControllerAdvice[format=annotation]、javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation]、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[] 和 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[]。
当使用 javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

TIP: 如果你需要注册额外组件，如 Jackson 的 javadoc:com.fasterxml.jackson.databind.Module[]，可以在测试上使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 导入额外的配置类。

通常，javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 只针对单个控制器，并与 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 注解结合使用，为所需的协作者提供 mock 实现。

javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 还会自动配置 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，它为 WebFlux 控制器提供了一种强大的快速测试方式，无需启动完整的 HTTP 服务器。

TIP: 你也可以在非 `@WebFluxTest`（如 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]）中，通过添加 javadoc:org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient[format=annotation] 注解，自动配置 javadoc:org.springframework.test.web.reactive.server.WebTestClient[]。
以下示例展示了同时使用 javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 和 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 的类：

include-code::MyControllerTests[]

TIP: 这种设置目前仅支持 WebFlux 应用，因为在模拟 web 应用中使用 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 目前只适用于 WebFlux。

NOTE: javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 无法检测通过函数式 web 框架注册的路由。
要在上下文中测试 javadoc:org.springframework.web.reactive.function.server.RouterFunction[] bean，可以通过 javadoc:org.springframework.context.annotation.Import[format=annotation] 或 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 自行导入。

NOTE: javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 无法检测作为 javadoc:org.springframework.context.annotation.Bean[format=annotation] 类型 javadoc:org.springframework.security.web.server.SecurityWebFilterChain[] 注册的自定义安全配置。
要在测试中包含该配置，需要通过 javadoc:org.springframework.context.annotation.Import[format=annotation] 或 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 导入注册该 bean 的配置。

TIP: 有时仅编写 Spring WebFlux 测试还不够；Spring Boot 可以帮助你运行 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-running-server[带有实际服务器的完整端到端测试]。



[[testing.spring-boot-applications.spring-graphql-tests]]
== 自动配置 Spring GraphQL 测试

Spring GraphQL 提供了专门的测试支持模块；你需要将其添加到你的项目中：

.Maven
[source,xml]
----
<dependencies>
	<dependency>
		<groupId>org.springframework.graphql</groupId>
		<artifactId>spring-graphql-test</artifactId>
		<scope>test</scope>
	</dependency>
	<!-- 如果已在 compile scope 中存在则无需再添加 -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-webflux</artifactId>
		<scope>test</scope>
	</dependency>
</dependencies>
----

.Gradle
[source,gradle]
----
dependencies {
	testImplementation("org.springframework.graphql:spring-graphql-test")
	// 如果已在 implementation 配置中存在则无需再添加
	testImplementation("org.springframework.boot:spring-boot-starter-webflux")
}
----

该测试模块提供了 {url-spring-graphql-docs}/testing.html#testing.graphqltester[GraphQlTester]。
该测试器在测试中被大量使用，请务必熟悉其用法。
有多种 javadoc:org.springframework.graphql.test.tester.GraphQlTester[] 变体，Spring Boot 会根据测试类型自动配置它们：

* javadoc:org.springframework.graphql.test.tester.ExecutionGraphQlServiceTester[] 在服务端执行测试，无需客户端和传输层
* javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[] 使用客户端连接到服务器进行测试，可以有或没有真实服务器

Spring Boot 通过 javadoc:org.springframework.boot.test.autoconfigure.graphql.GraphQlTest[format=annotation] 注解帮助你测试 {url-spring-graphql-docs}/controllers.html[Spring GraphQL Controllers]。
javadoc:org.springframework.boot.test.autoconfigure.graphql.GraphQlTest[format=annotation] 会自动配置 Spring GraphQL 基础设施，不涉及任何传输层或服务器。
它将扫描的 bean 限制为 javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.graphql.execution.RuntimeWiringConfigurer[]、javadoc:org.springframework.boot.jackson.JsonComponent[]、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[]、javadoc:org.springframework.graphql.execution.DataFetcherExceptionResolver[]、javadoc:graphql.execution.instrumentation.Instrumentation[] 和 javadoc:org.springframework.boot.autoconfigure.graphql.GraphQlSourceBuilderCustomizer[]。
当使用 javadoc:org.springframework.boot.test.autoconfigure.graphql.GraphQlTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.graphql.GraphQlTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

通常，javadoc:org.springframework.boot.test.autoconfigure.graphql.GraphQlTest[format=annotation] 只针对一组控制器，并与 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 注解结合使用，为所需的协作者提供 mock 实现。

include-code::GreetingControllerTests[]

javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 测试是完整的集成测试，涉及整个应用程序。
当使用随机端口或指定端口时，会配置一个真实服务器，并自动提供 javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[] bean，你可以用它来测试服务器。
当配置为 MOCK 环境时，也可以通过为测试类添加 javadoc:org.springframework.boot.test.autoconfigure.graphql.tester.AutoConfigureHttpGraphQlTester[format=annotation] 注解来请求 javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[] bean：

include-code::GraphQlIntegrationTests[]



[[testing.spring-boot-applications.autoconfigured-spring-data-cassandra]]
== 自动配置 Data Cassandra 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.data.cassandra.DataCassandraTest[format=annotation] 测试 Cassandra 应用。
默认情况下，它会配置 javadoc:org.springframework.data.cassandra.core.CassandraTemplate[]，扫描 javadoc:org.springframework.data.cassandra.core.mapping.Table[format=annotation] 类，并配置 Spring Data Cassandra 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.cassandra.DataCassandraTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（关于在 Spring Boot 中使用 Cassandra 的更多内容，见 xref:data/nosql.adoc#data.nosql.cassandra[]。）

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.cassandra.DataCassandraTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了在 Spring Boot 中使用 Cassandra 测试的典型设置：

include-code::MyDataCassandraTests[]



[[testing.spring-boot-applications.autoconfigured-spring-data-couchbase]]
== 自动配置 Data Couchbase 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.data.couchbase.DataCouchbaseTest[format=annotation] 测试 Couchbase 应用。
默认情况下，它会配置 javadoc:org.springframework.data.couchbase.core.CouchbaseTemplate[] 或 javadoc:org.springframework.data.couchbase.core.ReactiveCouchbaseTemplate[]，扫描 javadoc:org.springframework.data.couchbase.core.mapping.Document[format=annotation] 类，并配置 Spring Data Couchbase 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.couchbase.DataCouchbaseTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（关于在 Spring Boot 中使用 Couchbase 的更多内容，见 xref:data/nosql.adoc#data.nosql.couchbase[]，本章前面。）

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.couchbase.DataCouchbaseTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了在 Spring Boot 中使用 Couchbase 测试的典型设置：

include-code::MyDataCouchbaseTests[]



[[testing.spring-boot-applications.autoconfigured-spring-data-elasticsearch]]
== 自动配置 Data Elasticsearch 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.data.elasticsearch.DataElasticsearchTest[format=annotation] 测试 Elasticsearch 应用。
默认情况下，它会配置 javadoc:org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate[]，扫描 javadoc:org.springframework.data.elasticsearch.annotations.Document[format=annotation] 类，并配置 Spring Data Elasticsearch 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.elasticsearch.DataElasticsearchTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（关于在 Spring Boot 中使用 Elasticsearch 的更多内容，见 xref:data/nosql.adoc#data.nosql.elasticsearch[]，本章前面。）

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.elasticsearch.DataElasticsearchTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了在 Spring Boot 中使用 Elasticsearch 测试的典型设置：

include-code::MyDataElasticsearchTests[]



[[testing.spring-boot-applications.autoconfigured-spring-data-jpa]]
== 自动配置 Data JPA 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation] 注解测试 JPA 应用。
默认情况下，它会扫描 javadoc:jakarta.persistence.Entity[format=annotation] 类并配置 Spring Data JPA 仓库。
如果类路径上有嵌入式数据库，也会自动配置。
SQL 查询默认通过将 `spring.jpa.show-sql` 属性设置为 `true` 进行日志记录。
可以通过注解的 `showSql` 属性禁用。

当使用 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

默认情况下，data JPA 测试是事务性的，并在每个测试结束时回滚。
更多细节请参见 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[Spring Framework 参考文档相关章节]。
如果你不希望这样，可以为某个测试或整个类禁用事务管理，如下所示：

include-code::MyNonTransactionalTests[]

data JPA 测试还可以注入 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager[] bean，它是专为测试设计的标准 JPA javadoc:jakarta.persistence.EntityManager[] 的替代方案。

TIP: 你也可以通过添加 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.AutoConfigureTestEntityManager[format=annotation]，将 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager[] 自动配置到任何 Spring 测试类中。
这样做时，请确保你的测试运行在事务中，例如在测试类或方法上添加 javadoc:org.springframework.transaction.annotation.Transactional[format=annotation]。

如果需要，还可以使用 javadoc:org.springframework.jdbc.core.JdbcTemplate[]。
以下示例展示了 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation] 注解的用法：

include-code::withoutdb/MyRepositoryTests[]

内存嵌入式数据库通常非常适合测试，因为它们速度快且无需安装。
但如果你更喜欢针对真实数据库运行测试，可以使用 javadoc:org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase[format=annotation] 注解，如下例所示：

include-code::withdb/MyRepositoryTests[]



[[testing.spring-boot-applications.autoconfigured-jdbc]]
== 自动配置 JDBC 测试

javadoc:org.springframework.boot.test.autoconfigure.jdbc.JdbcTest[format=annotation] 类似于 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation]，但仅用于只需要 javadoc:javax.sql.DataSource[] 且不使用 Spring Data JDBC 的测试。
默认情况下，它会配置一个内存嵌入式数据库和一个 javadoc:org.springframework.jdbc.core.JdbcTemplate[]。
当使用 javadoc:org.springframework.boot.test.autoconfigure.jdbc.JdbcTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.jdbc.JdbcTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

默认情况下，JDBC 测试是事务性的，并在每个测试结束时回滚。
更多细节请参见 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[Spring Framework 参考文档相关章节]。
如果你不希望这样，可以为某个测试或整个类禁用事务管理，如下所示：

include-code::MyTransactionalTests[]

如果你更喜欢针对真实数据库运行测试，可以像 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation] 一样使用 javadoc:org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase[format=annotation] 注解。
（见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-spring-data-jdbc]]
== 自动配置 Data JDBC 测试

javadoc:org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest[format=annotation] 类似于 javadoc:org.springframework.boot.test.autoconfigure.jdbc.JdbcTest[format=annotation]，但用于使用 Spring Data JDBC 仓库的测试。
默认情况下，它会配置一个内存嵌入式数据库、一个 javadoc:org.springframework.jdbc.core.JdbcTemplate[]，以及 Spring Data JDBC 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest[format=annotation] 注解时，只会扫描 javadoc:org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration[] 的子类，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

默认情况下，Data JDBC 测试是事务性的，并在每个测试结束时回滚。
更多细节请参见 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[Spring Framework 参考文档相关章节]。
如果你不希望这样，可以为某个测试或整个测试类禁用事务管理，具体见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-jdbc[JDBC 示例]。

如果你更喜欢针对真实数据库运行测试，可以像 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation] 一样使用 javadoc:org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase[format=annotation] 注解。
（见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-spring-data-r2dbc]]
== 自动配置 Data R2DBC 测试

javadoc:org.springframework.boot.test.autoconfigure.data.r2dbc.DataR2dbcTest[format=annotation] 类似于 javadoc:org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest[format=annotation]，但用于使用 Spring Data R2DBC 仓库的测试。
默认情况下，它会配置一个内存嵌入式数据库、一个 javadoc:org.springframework.data.r2dbc.core.R2dbcEntityTemplate[]，以及 Spring Data R2DBC 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.r2dbc.DataR2dbcTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.r2dbc.DataR2dbcTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

默认情况下，Data R2DBC 测试不是事务性的。

如果你更喜欢针对真实数据库运行测试，可以像 javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation] 一样使用 javadoc:org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase[format=annotation] 注解。
（见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-jooq]]
== 自动配置 jOOQ 测试

你可以像使用 javadoc:org.springframework.boot.test.autoconfigure.jdbc.JdbcTest[format=annotation] 一样使用 javadoc:org.springframework.boot.test.autoconfigure.jooq.JooqTest[format=annotation] 进行 jOOQ 相关测试。
由于 jOOQ 严重依赖与数据库模式对应的 Java 模式，因此会使用现有的 javadoc:javax.sql.DataSource[]。
如果你想用内存数据库替换它，可以使用 javadoc:org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase[format=annotation] 覆盖这些设置。
（关于在 Spring Boot 中使用 jOOQ 的更多内容，见 xref:data/sql.adoc#data.sql.jooq[]。）
当使用 javadoc:org.springframework.boot.test.autoconfigure.jooq.JooqTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.jooq.JooqTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

javadoc:org.springframework.boot.test.autoconfigure.jooq.JooqTest[format=annotation] 会配置一个 javadoc:org.jooq.DSLContext[]。
以下示例展示了 javadoc:org.springframework.boot.test.autoconfigure.jooq.JooqTest[format=annotation] 注解的用法：

include-code::MyJooqTests[]

JOOQ 测试默认是事务性的，并在每个测试结束时回滚。
如果你不希望这样，可以为某个测试或整个测试类禁用事务管理，具体见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-jdbc[JDBC 示例]。



[[testing.spring-boot-applications.autoconfigured-spring-data-mongodb]]
== 自动配置 Data MongoDB 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest[format=annotation] 测试 MongoDB 应用。
默认情况下，它会配置 javadoc:org.springframework.data.mongodb.core.MongoTemplate[]，扫描 javadoc:org.springframework.data.mongodb.core.mapping.Document[format=annotation] 类，并配置 Spring Data MongoDB 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（关于在 Spring Boot 中使用 MongoDB 的更多内容，见 xref:data/nosql.adoc#data.nosql.mongodb[]。）

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了 javadoc:org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest[format=annotation] 注解的用法：

include-code::MyDataMongoDbTests[]



[[testing.spring-boot-applications.autoconfigured-spring-data-neo4j]]
== 自动配置 Data Neo4j 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.data.neo4j.DataNeo4jTest[format=annotation] 测试 Neo4j 应用。
默认情况下，它会扫描 javadoc:org.springframework.data.neo4j.core.schema.Node[format=annotation] 类，并配置 Spring Data Neo4j 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.neo4j.DataNeo4jTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（关于在 Spring Boot 中使用 Neo4J 的更多内容，见 xref:data/nosql.adoc#data.nosql.neo4j[]。）

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.neo4j.DataNeo4jTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了在 Spring Boot 中使用 Neo4J 测试的典型设置：

include-code::propagation/MyDataNeo4jTests[]

By default, Data Neo4j 测试是事务性的，并在每个测试结束时回滚。
更多细节请参见 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[Spring Framework 参考文档相关章节]。
如果你不希望这样，可以为某个测试或整个类禁用事务管理，如下所示：

include-code::nopropagation/MyDataNeo4jTests[]

NOTE: Transactional tests are not supported with reactive access.
If you are using this style, you must configure javadoc:org.springframework.boot.test.autoconfigure.data.neo4j.DataNeo4jTest[format=annotation] tests as described above.



[[testing.spring-boot-applications.autoconfigured-spring-data-redis]]
== 自动配置 Data Redis 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.data.redis.DataRedisTest[format=annotation] 测试 Redis 应用。
默认情况下，它会扫描 javadoc:org.springframework.data.redis.core.RedisHash[format=annotation] 类并配置 Spring Data Redis 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.redis.DataRedisTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（关于在 Spring Boot 中使用 Redis 的更多内容，见 xref:data/nosql.adoc#data.nosql.redis[]。）

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.redis.DataRedisTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了 javadoc:org.springframework.boot.test.autoconfigure.data.redis.DataRedisTest[format=annotation] 注解的用法：

include-code::MyDataRedisTests[]



[[testing.spring-boot-applications.autoconfigured-spring-data-ldap]]
== 自动配置 Data LDAP 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.data.ldap.DataLdapTest[format=annotation] 测试 LDAP 应用。
默认情况下，它会配置一个内存嵌入式 LDAP（如果可用），配置一个 javadoc:org.springframework.ldap.core.LdapTemplate[]，扫描 javadoc:org.springframework.ldap.odm.annotations.Entry[format=annotation] 类，并配置 Spring Data LDAP 仓库。
当使用 javadoc:org.springframework.boot.test.autoconfigure.data.ldap.DataLdapTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（关于在 Spring Boot 中使用 LDAP 的更多内容，见 xref:data/nosql.adoc#data.nosql.ldap[]。）

TIP: javadoc:org.springframework.boot.test.autoconfigure.data.ldap.DataLdapTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了 javadoc:org.springframework.boot.test.autoconfigure.data.ldap.DataLdapTest[format=annotation] 注解的用法：

include-code::inmemory/MyDataLdapTests[]

内存嵌入式 LDAP 通常非常适合测试，因为它速度快且不需要任何开发者安装。
但如果你更喜欢针对真实 LDAP 服务器运行测试，你应该排除嵌入式 LDAP 自动配置，如下例所示：

include-code::server/MyDataLdapTests[]



[[testing.spring-boot-applications.autoconfigured-rest-client]]
== 自动配置 REST 客户端

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.web.client.RestClientTest[format=annotation] 注解测试 REST 客户端。
默认情况下，它会自动配置 Jackson、GSON 和 Jsonb 支持，配置一个 javadoc:org.springframework.boot.web.client.RestTemplateBuilder[] 和一个 javadoc:org.springframework.web.client.RestClient$Builder[]，并添加对 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 的支持。
当使用 javadoc:org.springframework.boot.test.autoconfigure.web.client.RestClientTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

TIP: javadoc:org.springframework.boot.test.autoconfigure.web.client.RestClientTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

你需要测试的特定 bean 应该通过使用 javadoc:org.springframework.boot.test.autoconfigure.web.client.RestClientTest[format=annotation] 的 `value` 或 `components` 属性来指定。

当在测试中使用的 bean 上使用 javadoc:org.springframework.boot.web.client.RestTemplateBuilder[] 并且 `RestTemplateBuilder.rootUri(String rootUri)` 在构建 javadoc:org.springframework.web.client.RestTemplate[] 时被调用时，根 URI 应该从 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 期望中省略，如下例所示：

include-code::MyRestTemplateServiceTests[]

当在测试中使用的 bean 上使用 javadoc:org.springframework.web.client.RestClient$Builder[] 或在 javadoc:org.springframework.boot.web.client.RestTemplateBuilder[] 上不调用 `rootUri(String rootURI)` 时，必须使用完整的 URI 在 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 期望中，如下例所示：

include-code::MyRestClientServiceTests[]



[[testing.spring-boot-applications.autoconfigured-spring-restdocs]]
== 自动配置 Spring REST Docs 测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs[format=annotation] 注解来使用 {url-spring-restdocs-site}[Spring REST Docs] 在你的测试中与 Mock MVC、REST Assured 或 WebTestClient 一起。
它消除了 Spring REST Docs 中 JUnit 扩展的需要。

javadoc:org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs[format=annotation] 可以用来覆盖默认输出目录（如果你使用 Maven 则是 `target/generated-snippets`，如果你使用 Gradle 则是 `build/generated-snippets`）。
它还可以用来配置出现在任何文档化 URI 中的主机、方案和端口。



[[testing.spring-boot-applications.autoconfigured-spring-restdocs.with-mock-mvc]]
=== 自动配置 Spring REST Docs 测试 With Mock MVC

javadoc:org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs[format=annotation] 自定义用于测试 servlet 基础 web 应用程序的 javadoc:org.springframework.test.web.servlet.MockMvc[] bean 使用 Spring REST Docs。
你可以通过使用 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注入它，并在你的测试中像使用 Mock MVC 和 Spring REST Docs 一样正常使用它，如下例所示：

include-code::hamcrest/MyUserDocumentationTests[]

如果你更喜欢使用 AssertJ 集成，javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[] 也可以使用，如下例所示：

include-code::assertj/MyUserDocumentationTests[]

两者都使用相同的 javadoc:org.springframework.test.web.servlet.MockMvc[] 实例，因此任何配置到它的配置都适用于两者。

如果你需要比 javadoc:org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs[format=annotation] 提供的属性更多的控制 Spring REST Docs 配置，你可以使用 javadoc:org.springframework.boot.test.autoconfigure.restdocs.RestDocsMockMvcConfigurationCustomizer[] bean，如下例所示：

include-code::MyRestDocsConfiguration[]

如果你想要为参数化输出目录创建 javadoc:org.springframework.restdocs.mockmvc.RestDocumentationResultHandler[] bean。
自动配置调用 `alwaysDo` 与这个结果处理器，从而导致每次 javadoc:org.springframework.test.web.servlet.MockMvc[] 调用自动生成默认片段。
以下示例展示了 javadoc:org.springframework.restdocs.mockmvc.RestDocumentationResultHandler[] 的定义：

include-code::MyResultHandlerConfiguration[]



[[testing.spring-boot-applications.autoconfigured-spring-restdocs.with-web-test-client]]
=== 自动配置 Spring REST Docs 测试 With WebTestClient

javadoc:org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs[format=annotation] 也可以与 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 一起使用，用于测试反应性 web 应用程序。
你可以通过使用 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注入它，并在你的测试中像使用 javadoc:org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest[format=annotation] 和 Spring REST Docs 一样正常使用它，如下例所示：

include-code::MyUsersDocumentationTests[]

如果你需要比 javadoc:org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs[format=annotation] 提供的属性更多的控制 Spring REST Docs 配置，你可以使用 javadoc:org.springframework.boot.test.autoconfigure.restdocs.RestDocsWebTestClientConfigurationCustomizer[] bean，如下例所示：

include-code::MyRestDocsConfiguration[]

如果你想要为参数化输出目录创建 javadoc:org.springframework.boot.test.web.reactive.server.WebTestClientBuilderCustomizer[]，你可以使用它来配置每个实体交换结果的消费者。
以下示例展示了如何定义此类 javadoc:org.springframework.boot.test.web.reactive.server.WebTestClientBuilderCustomizer[]：

include-code::MyWebTestClientBuilderCustomizerConfiguration[]



[[testing.spring-boot-applications.autoconfigured-spring-restdocs.with-rest-assured]]
=== 自动配置 Spring REST Docs 测试 With REST Assured

javadoc:org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs[format=annotation] 制作一个 javadoc:io.restassured.specification.RequestSpecification[] bean，预配置为使用 Spring REST Docs，可供你的测试使用。
你可以通过使用 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注入它，并在你的测试中像使用 REST Assured 和 Spring REST Docs 一样正常使用它，如下例所示：

include-code::MyUserDocumentationTests[]

如果你需要比 javadoc:org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs[format=annotation] 提供的属性更多的控制 Spring REST Docs 配置，可以使用 javadoc:org.springframework.boot.test.autoconfigure.restdocs.RestDocsRestAssuredConfigurationCustomizer[] bean，如下例所示：

include-code::MyRestDocsConfiguration[]



[[testing.spring-boot-applications.autoconfigured-webservices]]
== 自动配置 Spring Web Services 测试



[[testing.spring-boot-applications.autoconfigured-webservices.client]]
=== 自动配置 Spring Web Services 客户端测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.webservices.client.WebServiceClientTest[format=annotation] 测试使用 Spring Web Services 项目调用 web 服务的应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.ws.test.client.MockWebServiceServer[] bean，并自动自定义你的 javadoc:org.springframework.boot.webservices.client.WebServiceTemplateBuilder[]。
（关于在 Spring Boot 中使用 Web Services 的更多内容，见 xref:io/webservices.adoc[]。）


TIP: javadoc:org.springframework.boot.test.autoconfigure.webservices.client.WebServiceClientTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了 javadoc:org.springframework.boot.test.autoconfigure.webservices.client.WebServiceClientTest[format=annotation] 注解的用法：

include-code::MyWebServiceClientTests[]



[[testing.spring-boot-applications.autoconfigured-webservices.server]]
=== 自动配置 Spring Web Services 服务器测试

你可以使用 javadoc:org.springframework.boot.test.autoconfigure.webservices.server.WebServiceServerTest[format=annotation] 测试使用 Spring Web Services 项目实现 web 服务的应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.ws.test.server.MockWebServiceClient[] bean，你可以使用它来调用你的 web 服务端点。
（关于在 Spring Boot 中使用 Web Services 的更多内容，见 xref:io/webservices.adoc[]。）


TIP: javadoc:org.springframework.boot.test.autoconfigure.webservices.server.WebServiceServerTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录]中找到。

以下示例展示了 javadoc:org.springframework.boot.test.autoconfigure.webservices.server.WebServiceServerTest[format=annotation] 注解的用法：

include-code::MyWebServiceServerTests[]



[[testing.spring-boot-applications.additional-autoconfiguration-and-slicing]]
== 额外自动配置和切片

每个切片提供一个或多个 `@AutoConfigure...` 注解，这些注解定义了应该作为切片一部分包含的自动配置。
额外的自动配置可以在测试的基础上通过创建自定义 `@AutoConfigure...` 注解或通过将 javadoc:org.springframework.boot.autoconfigure.ImportAutoConfiguration[format=annotation] 添加到测试中来添加，如下例所示：

include-code::MyJdbcTests[]

注意：不要使用常规的 javadoc:org.springframework.context.annotation.Import[format=annotation] 注解导入自动配置，因为它们由 Spring Boot 以特定方式处理。

或者，额外的自动配置可以为任何使用切片注解的用例通过在 `META-INF/spring` 中存储的文件来添加，如下例所示：

.META-INF/spring/org.springframework.boot.test.autoconfigure.jdbc.JdbcTest.imports
[source]
----
com.example.IntegrationAutoConfiguration
----

在此示例中，`+com.example.IntegrationAutoConfiguration+` 在每个使用 javadoc:org.springframework.boot.test.autoconfigure.jdbc.JdbcTest[format=annotation] 注解的测试上启用。

提示：你可以在文件中使用 `#` 进行注释。

提示：切片或 `@AutoConfigure...` 注解可以这样自定义，只要它被 meta-annotated 为 javadoc:org.springframework.boot.autoconfigure.ImportAutoConfiguration[format=annotation]。



[[testing.spring-boot-applications.user-configuration-and-slicing]]
== 用户配置和切片

如果你 xref:using/structuring-your-code.adoc[结构你的代码] 在合理的方式，你的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 类是 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[默认使用] 作为测试的配置。

然后，重要的是不要在应用程序的主类中添加特定于某个功能的配置设置。

假设你正在使用 Spring Data MongoDB，你依赖于它的自动配置，并且你已经启用了审计。
你可以将你的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 定义如下：

include-code::MyApplication[]

因为此类是测试的源配置，任何切片测试实际上试图启用 Mongo 审计，这绝对不是你想要的。
推荐的方法是将该区域特定的配置移动到一个单独的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类，与你的应用程序在同一级别，如下例所示：

include-code::MyMongoConfiguration[]

注意：根据你的应用程序的复杂性，你可能有一个单独的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类用于你的自定义，或者每个领域区域一个类。
后一种方法允许你在某个测试中启用它，如果必要的话，使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 注解。
请参阅 xref:how-to:testing.adoc#howto.testing.slice-tests[此如何部分]，了解何时可能希望为切片测试启用特定的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类。

测试切片排除 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类从扫描。
例如，对于 javadoc:org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest[format=annotation]，以下配置不会在测试切片加载的应用程序上下文中包含给定的 javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[] bean：

include-code::MyWebConfiguration[]

以下配置将导致测试切片加载自定义的 javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[]：

include-code::MyWebMvcConfigurer[]

另一个混淆来源是类路径扫描。
假设，虽然你以合理的方式结构你的代码，但你需要扫描一个额外的包。
你的应用程序可能类似于以下代码：

include-code::scan/MyApplication[]

这样做有效地覆盖了默认的组件扫描指令，副作用是扫描那些两个包，无论你选择哪个切片。
例如，javadoc:org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest[format=annotation] 似乎突然扫描组件和用户配置。
再次，将自定义指令移动到一个单独的类是一个很好的解决方法。

提示：如果这不是一个选项，你可以创建一个 javadoc:org.springframework.boot.SpringBootConfiguration[format=annotation] 在测试层次结构中的某个地方，以便它被使用而不是默认的。
或者，你可以指定测试的来源，这会禁用查找默认配置的行为。



[[testing.spring-boot-applications.spock]]
== 使用 Spock 测试 Spring Boot 应用程序

Spock 2.2 或更高版本可以用来测试 Spring Boot 应用程序。
为此，请在应用程序的构建中添加对 Spock 的 `-groovy-4.0` 版本的 `spock-spring` 模块的依赖。
`spock-spring` 将 Spring 的测试框架集成到 Spock 中。
请参阅 https://spockframework.org/spock/docs/2.2-M1/modules.html#_spring_module[Spock 的 Spring 模块文档]，了解更多细节。
