[[testing.testcontainers]]
= Testcontainers

https://www.testcontainers.org/[Testcontainers] 库提供了一种管理在 Docker 容器内运行的服务的方法。
它与 JUnit 集成，允许你编写一个测试类，可以在任何测试运行之前启动容器。
Testcontainers 特别适用于编写与真实后端服务（如 MySQL、MongoDB、Cassandra 等）通信的集成测试。

在以下章节中，我们将描述一些可以将 Testcontainers 与测试集成的方法。


[[testing.testcontainers.spring-beans]]
== 使用 Spring Beans

Testcontainers 提供的容器可以由 Spring Boot 作为 beans 进行管理。

要将容器声明为 bean，在你的测试配置中添加一个 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法：

include-code::MyTestConfiguration[]

然后，你可以通过在测试类中导入配置类来注入和使用容器：

include-code::MyIntegrationTests[]

提示：这种管理容器的方法通常与 xref:#testing.testcontainers.service-connections[服务连接注解] 结合使用。



[[testing.testcontainers.junit-extension]]
== 使用 JUnit 扩展

Testcontainers 提供了一个 JUnit 扩展，可用于在测试中管理容器。
通过在测试类上应用来自 Testcontainers 的 javadoc:org.testcontainers.junit.jupiter.Testcontainers[format=annotation] 注解来激活该扩展。

然后，你可以在静态容器字段上使用 javadoc:org.testcontainers.junit.jupiter.Container[format=annotation] 注解。

javadoc:org.testcontainers.junit.jupiter.Testcontainers[format=annotation] 注解可以用于普通的 JUnit 测试，或者与 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 结合使用：

include-code::MyIntegrationTests[]

上面的示例将在任何测试运行之前启动一个 Neo4j 容器。
容器实例的生命周期由 Testcontainers 管理，如 {url-testcontainers-docs}/test_framework_integration/junit_5/#extension[其官方文档] 中所述。

注意：在大多数情况下，你还需要配置应用程序以连接到在容器中运行的服务。



[[testing.testcontainers.importing-configuration-interfaces]]
== 导入容器配置接口

使用 Testcontainers 的一个常见模式是在接口中声明容器实例作为静态字段。

例如，以下接口声明了两个容器，一个名为 `mongo` 的类型为 javadoc:org.testcontainers.containers.MongoDBContainer[]，另一个名为 `neo4j` 的类型为 javadoc:org.testcontainers.containers.Neo4jContainer.Neo4jContainer[]：

include-code::MyContainers[]

当你以这种方式声明容器时，你可以通过让测试类实现接口来在多个测试中重用它们的配置。

也可以在 Spring Boot 测试中使用相同的接口配置。
为此，在你的测试配置类中添加 javadoc:org.springframework.boot.testcontainers.context.ImportTestcontainers[format=annotation]：

include-code::MyTestConfiguration[]



[[testing.testcontainers.lifecycle]]
== 托管容器的生命周期

如果你使用了 Testcontainers 提供的注解和扩展，那么容器实例的生命周期完全由 Testcontainers 管理。
请参考 {url-testcontainers-docs}[Testcontainers 官方文档] 获取相关信息。

当容器由 Spring 作为 beans 管理时，它们的生命周期由 Spring 管理：

* 容器 beans 在所有其他 beans 之前创建和启动。

* 容器 beans 在所有其他 beans 销毁后停止。

这个过程确保任何依赖容器提供的功能的 beans 都可以使用这些功能。
它还确保在容器仍然可用时进行清理。

提示：当你的应用程序 beans 依赖容器的功能时，最好将容器配置为 Spring beans 以确保正确的生命周期行为。

注意：由 Testcontainers 而不是作为 Spring beans 管理容器不能保证 beans 和容器的关闭顺序。
容器可能会在依赖容器功能的 beans 清理之前关闭。
这可能导致客户端 beans 抛出异常，例如，由于连接丢失。

容器 beans 由 Spring 的 TestContext Framework 管理的每个应用程序上下文创建和启动一次。
有关 TestContext Framework 如何管理底层应用程序上下文和其中的 beans 的详细信息，请参考 {url-spring-framework-docs}[Spring Framework 文档]。

容器 beans 作为 TestContext Framework 的标准应用程序上下文关闭过程的一部分而停止。
当应用程序上下文关闭时，容器也会关闭。
这通常发生在使用该特定缓存应用程序上下文的所有测试执行完成之后。
根据 TestContext Framework 中配置的缓存行为，也可能更早发生。

注意：单个测试容器实例可以并且经常在多个测试类的测试执行过程中保留。



[[testing.testcontainers.service-connections]]
== 服务连接

服务连接是与任何远程服务的连接。
Spring Boot 的自动配置可以使用服务连接的详细信息来建立与远程服务的连接。
这样做时，连接详细信息优先于任何与连接相关的配置属性。

使用 Testcontainers 时，可以通过在测试类中注解容器字段来自动创建在容器中运行的服务连接详细信息。

include-code::MyIntegrationTests[]

由于 javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation]，上述配置允许应用程序中的 Neo4j 相关 beans 与在 Testcontainers 管理的 Docker 容器内运行的 Neo4j 通信。
这是通过自动定义一个 javadoc:org.springframework.boot.autoconfigure.neo4j.Neo4jConnectionDetails[] bean 来实现的，然后由 Neo4j 自动配置使用，覆盖任何与连接相关的配置属性。

注意：要使用 Testcontainers 的服务连接，你需要将 `spring-boot-testcontainers` 模块添加为测试依赖项。

服务连接注解由在 `spring.factories` 中注册的 javadoc:org.springframework.boot.testcontainers.service.connection.ContainerConnectionDetailsFactory[] 类处理。
javadoc:org.springframework.boot.testcontainers.service.connection.ContainerConnectionDetailsFactory[] 可以基于特定的 javadoc:org.testcontainers.containers.Container[] 子类或 Docker 镜像名称创建 javadoc:org.springframework.boot.autoconfigure.service.connection.ConnectionDetails[] bean。

`spring-boot-testcontainers` jar 中提供了以下服务连接工厂：

|===
| 连接详细信息 | 匹配条件

| javadoc:org.springframework.boot.autoconfigure.jms.activemq.ActiveMQConnectionDetails[]
| 名为 "symptoma/activemq" 的容器或 javadoc:org.testcontainers.activemq.ActiveMQContainer[]

| javadoc:org.springframework.boot.autoconfigure.jms.artemis.ArtemisConnectionDetails[]
| 类型为 javadoc:org.testcontainers.activemq.ArtemisContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.cassandra.CassandraConnectionDetails[]
| 类型为 javadoc:org.testcontainers.cassandra.CassandraContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.couchbase.CouchbaseConnectionDetails[]
| 类型为 javadoc:org.testcontainers.couchbase.CouchbaseContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchConnectionDetails[]
| 类型为 javadoc:org.testcontainers.elasticsearch.ElasticsearchContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.flyway.FlywayConnectionDetails[]
| 类型为 javadoc:{url-testcontainers-jdbc-javadoc}/org.testcontainers.containers.JdbcDatabaseContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.jdbc.JdbcConnectionDetails[]
| 类型为 javadoc:{url-testcontainers-jdbc-javadoc}/org.testcontainers.containers.JdbcDatabaseContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.kafka.KafkaConnectionDetails[]
| 类型为 javadoc:org.testcontainers.kafka.KafkaContainer[]、javadoc:org.testcontainers.kafka.ConfluentKafkaContainer[] 或 javadoc:org.testcontainers.redpanda.RedpandaContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.ldap.LdapConnectionDetails[]
| 名为 "osixia/openldap" 的容器或类型为 javadoc:org.testcontainers.ldap.LLdapContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.liquibase.LiquibaseConnectionDetails[]
| 类型为 javadoc:{url-testcontainers-jdbc-javadoc}/org.testcontainers.containers.JdbcDatabaseContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.mongo.MongoConnectionDetails[]
| 类型为 javadoc:{url-testcontainers-mongodb-javadoc}/org.testcontainers.containers.MongoDBContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.neo4j.Neo4jConnectionDetails[]
| 类型为 javadoc:{url-testcontainers-neo4j-javadoc}/org.testcontainers.containers.Neo4jContainer[] 的容器

| javadoc:org.springframework.boot.actuate.autoconfigure.logging.otlp.OtlpLoggingConnectionDetails[]
| 名为 "otel/opentelemetry-collector-contrib" 的容器或类型为 `LgtmStackContainer` 的容器

| javadoc:org.springframework.boot.actuate.autoconfigure.metrics.export.otlp.OtlpMetricsConnectionDetails[]
| 名为 "otel/opentelemetry-collector-contrib" 的容器或类型为 `LgtmStackContainer` 的容器

| javadoc:org.springframework.boot.actuate.autoconfigure.tracing.otlp.OtlpTracingConnectionDetails[]
| 名为 "otel/opentelemetry-collector-contrib" 的容器或类型为 `LgtmStackContainer` 的容器

| javadoc:org.springframework.boot.autoconfigure.pulsar.PulsarConnectionDetails[]
| 类型为 javadoc:{url-testcontainers-pulsar-javadoc}/org.testcontainers.containers.PulsarContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.r2dbc.R2dbcConnectionDetails[]
| 类型为 `ClickHouseContainer`、javadoc:{url-testcontainers-mariadb-javadoc}/org.testcontainers.containers.MariaDBContainer[]、javadoc:{url-testcontainers-mssqlserver-javadoc}/org.testcontainers.containers.MSSQLServerContainer[]、javadoc:{url-testcontainers-mysql-javadoc}/org.testcontainers.containers.MySQLContainer[]、javadoc:{url-testcontainers-oracle-free-javadoc}/org.testcontainers.OracleContainer[OracleContainer (free)]、javadoc:{url-testcontainers-oracle-xe-javadoc}/org.testcontainers.oracle.OracleContainer[OracleContainer (XE)] 或 javadoc:{url-testcontainers-postgresql-javadoc}/org.testcontainers.containers.PostgreSQLContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.amqp.RabbitConnectionDetails[]
| 类型为 javadoc:{url-testcontainers-rabbitmq-javadoc}/org.testcontainers.containers.RabbitMQContainer[] 的容器

| javadoc:org.springframework.boot.autoconfigure.data.redis.RedisConnectionDetails[]
| 类型为 javadoc:com.redis.testcontainers.RedisContainer[] 或 javadoc:com.redis.testcontainers.RedisStackContainer[] 的容器，或名为 "redis"、"redis/redis-stack" 或 "redis/redis-stack-server" 的容器

| javadoc:org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinConnectionDetails[]
| 名为 "openzipkin/zipkin" 的容器
|===

[TIP]
====
默认情况下，将为给定的 javadoc:org.testcontainers.containers.Container[] 创建所有适用的连接详细信息 beans。
例如，一个 javadoc:{url-testcontainers-postgresql-javadoc}/org.testcontainers.containers.PostgreSQLContainer[] 将同时创建 javadoc:org.springframework.boot.autoconfigure.jdbc.JdbcConnectionDetails[] 和 javadoc:org.springframework.boot.autoconfigure.r2dbc.R2dbcConnectionDetails[]。

如果你只想创建适用类型的子集，可以使用 javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] 的 `type` 属性。
====

默认情况下，使用 `Container.getDockerImageName().getRepository()` 获取用于查找连接详细信息的名称。
Docker 镜像名称的仓库部分忽略任何注册表和版本。
只要 Spring Boot 能够获取 javadoc:org.testcontainers.containers.Container[] 的实例，这就可以工作，就像上面的示例中使用 `static` 字段一样。

如果你使用 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法，Spring Boot 不会调用 bean 方法来获取 Docker 镜像名称，因为这会导致急切初始化问题。
相反，使用 bean 方法的返回类型来确定应该使用哪个连接详细信息。
只要你使用类型化的容器，如 javadoc:{url-testcontainers-neo4j-javadoc}/org.testcontainers.containers.Neo4jContainer[] 或 javadoc:{url-testcontainers-rabbitmq-javadoc}/org.testcontainers.containers.RabbitMQContainer[]，这就可以工作。
如果你使用 javadoc:org.testcontainers.containers.GenericContainer[]，例如使用 Redis，如下例所示，这将停止工作：

include-code::MyRedisConfiguration[]

Spring Boot 无法从 javadoc:org.testcontainers.containers.GenericContainer[] 判断使用了哪个容器镜像，因此必须使用 javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] 的 `name` 属性来提供该提示。

你也可以使用 javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] 的 `name` 属性来覆盖将使用的连接详细信息，例如在使用自定义镜像时。
如果你使用 Docker 镜像 `registry.mycompany.com/mirror/myredis`，你将使用 `@ServiceConnection(name="redis")` 来确保创建 javadoc:org.springframework.boot.autoconfigure.data.redis.RedisConnectionDetails[]。



[[testing.testcontainers.service-connections.ssl]]
=== 服务连接的 SSL

你可以使用 javadoc:org.springframework.boot.testcontainers.service.connection.Ssl[format=annotation]、javadoc:org.springframework.boot.testcontainers.service.connection.JksKeyStore[format=annotation]、javadoc:org.springframework.boot.testcontainers.service.connection.JksTrustStore[format=annotation]、javadoc:org.springframework.boot.testcontainers.service.connection.PemKeyStore[format=annotation] 和 javadoc:org.springframework.boot.testcontainers.service.connection.PemTrustStore[format=annotation] 注解在支持的容器上启用该服务连接的 SSL 支持。
请注意，你仍然必须自己在 Testcontainer 内运行的服务上启用 SSL，这些注解只配置应用程序中客户端的 SSL。

include-code::MyRedisWithSslIntegrationTests[]

上面的代码使用 javadoc:org.springframework.boot.testcontainers.service.connection.PemKeyStore[format=annotation] 注解将客户端证书和密钥加载到密钥库中，并使用 javadoc:org.springframework.boot.testcontainers.service.connection.PemTrustStore[format=annotation] 注解将 CA 证书加载到信任库中。
这将使客户端对服务器进行身份验证，信任库中的 CA 证书确保服务器证书有效且受信任。

此示例中的 `SecureRedisContainer` 是 `RedisContainer` 的自定义子类，它将证书复制到正确的位置并使用启用 SSL 的命令行参数调用 `redis-server`。

以下服务连接支持 SSL 注解：

* Cassandra
* Couchbase
* Elasticsearch
* Kafka
* MongoDB
* RabbitMQ
* Redis

`ElasticsearchContainer` 还支持自动检测服务器端 SSL。
要使用此功能，请使用 javadoc:org.springframework.boot.testcontainers.service.connection.Ssl[format=annotation] 注解容器，如下例所示，Spring Boot 将为你处理客户端 SSL 配置：

include-code::MyElasticsearchWithSslIntegrationTests[]



[[testing.testcontainers.dynamic-properties]]
== 动态属性

服务连接的一个稍微更冗长但更灵活的替代方案是 javadoc:org.springframework.test.context.DynamicPropertySource[format=annotation]。
静态 javadoc:org.springframework.test.context.DynamicPropertySource[format=annotation] 方法允许向 Spring Environment 添加动态属性值。

include-code::MyIntegrationTests[]

上述配置允许应用程序中的 Neo4j 相关 beans 与在 Testcontainers 管理的 Docker 容器内运行的 Neo4j 通信。
