[[testing.utilities]]
= 测试工具

一些在测试应用程序时通常有用的测试工具类被打包为 `spring-boot` 的一部分。



[[testing.utilities.config-data-application-context-initializer]]
== ConfigDataApplicationContextInitializer

javadoc:org.springframework.boot.test.context.ConfigDataApplicationContextInitializer[] 是一个 javadoc:org.springframework.context.ApplicationContextInitializer[]，您可以将其应用于测试以加载Spring Boot `application.properties` 文件。
当您不需要 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 提供的完整功能集时，可以使用它，如下例所示：

include-code::MyConfigFileTests[]

注意：单独使用 javadoc:org.springframework.boot.test.context.ConfigDataApplicationContextInitializer[] 不提供对 `@Value("${...}")` 注入的支持。
它的唯一工作是确保 `application.properties` 文件被加载到Spring的 javadoc:org.springframework.core.env.Environment[] 中。
对于 javadoc:org.springframework.beans.factory.annotation.Value[format=annotation] 支持，您需要额外配置 javadoc:org.springframework.context.support.PropertySourcesPlaceholderConfigurer[] 或使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]，它会自动为您配置一个。



[[testing.utilities.test-property-values]]
== TestPropertyValues

javadoc:org.springframework.boot.test.util.TestPropertyValues[] 允许您快速向 javadoc:org.springframework.core.env.ConfigurableEnvironment[] 或 javadoc:org.springframework.context.ConfigurableApplicationContext[] 添加属性。
您可以使用 `key=value` 字符串调用它，如下所示：

include-code::MyEnvironmentTests[]



[[testing.utilities.output-capture]]
== OutputCaptureExtension

javadoc:org.springframework.boot.test.system.OutputCaptureExtension[] 是一个JUnit javadoc:org.junit.jupiter.api.extension.Extension[]，您可以使用它来捕获 javadoc:java.lang.System#out[] 和 javadoc:java.lang.System#err[] 输出。
要使用它，添加 `@ExtendWith(OutputCaptureExtension.class)` 并将 javadoc:org.springframework.boot.test.system.CapturedOutput[] 作为参数注入到测试类构造函数或测试方法中，如下所示：

include-code::MyOutputCaptureTests[]



[[testing.utilities.test-rest-template]]
== TestRestTemplate

javadoc:org.springframework.boot.test.web.client.TestRestTemplate[] 是Spring的 javadoc:org.springframework.web.client.RestTemplate[] 的一个便捷替代品，在集成测试中很有用。
您可以获取一个普通模板或一个发送Basic HTTP认证（带用户名和密码）的模板。
在这两种情况下，模板都是容错的。
这意味着它的行为对测试友好，不会在4xx和5xx错误时抛出异常。
相反，可以通过返回的 javadoc:org.springframework.http.ResponseEntity[] 及其状态码来检测此类错误。

提示：Spring Framework 5.0提供了一个新的 javadoc:org.springframework.test.web.reactive.server.WebTestClient[]，它适用于 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.spring-webflux-tests[WebFlux集成测试]和 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-running-server[WebFlux和MVC端到端测试]。
与 javadoc:org.springframework.boot.test.web.client.TestRestTemplate[] 不同，它提供了一个用于断言的流畅API。

建议但不强制使用Apache HTTP Client（5.1或更高版本）。
如果您的类路径中有它，javadoc:org.springframework.boot.test.web.client.TestRestTemplate[] 会通过适当配置客户端来响应。
如果您确实使用Apache的HTTP客户端，则会启用一些额外的测试友好功能：

* 不跟踪重定向（因此您可以断言响应位置）。
* 忽略Cookie（因此模板是无状态的）。

javadoc:org.springframework.boot.test.web.client.TestRestTemplate[] 可以直接在集成测试中实例化，如下例所示：

include-code::MyTests[]

或者，如果您使用带有 `WebEnvironment.RANDOM_PORT` 或 `WebEnvironment.DEFINED_PORT` 的 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 注解，您可以注入一个完全配置的 javadoc:org.springframework.boot.test.web.client.TestRestTemplate[] 并开始使用它。
如有必要，可以通过 javadoc:org.springframework.boot.web.client.RestTemplateBuilder[] bean应用其他自定义。
任何未指定主机和端口的URL都会自动连接到嵌入式服务器，如下例所示：

include-code::MySpringBootTests[]
