[[appendix.configuration-metadata.manual-hints]]
= 提供手动提示

为了改善用户体验并进一步帮助用户配置给定属性，你可以提供额外的元数据：

* 描述属性的潜在值列表。
* 关联一个提供者，为属性附加明确定义的语义，以便工具可以根据项目的上下文发现潜在值列表。



[[appendix.configuration-metadata.manual-hints.value-hint]]
== 值提示

每个提示的 `name` 属性引用属性的 `name`。
在 xref:configuration-metadata/format.adoc[前面显示的初始示例]中，我们为 `spring.jpa.hibernate.ddl-auto` 属性提供了五个值：`none`、`validate`、`update`、`create` 和 `create-drop`。
每个值也可能有描述。

如果你的属性是 javadoc:java.util.Map[] 类型，你可以为键和值提供提示（但不能为映射本身提供）。
特殊的 `.keys` 和 `.values` 后缀必须分别引用键和值。

假设 `my.contexts` 将魔法 javadoc:java.lang.String[] 值映射到整数，如下例所示：

include-code::MyProperties[]

魔法值（在此示例中）是 `sample1` 和 `sample2`。
为了为键提供额外的内容帮助，你可以将以下 JSON 添加到 xref:configuration-metadata/annotation-processor.adoc#appendix.configuration-metadata.annotation-processor.adding-additional-metadata[模块的手动元数据]中：

[source,json]
----
{"hints": [
	{
		"name": "my.contexts.keys",
		"values": [
			{
				"value": "sample1"
			},
			{
				"value": "sample2"
			}
		]
	}
]}
----

提示：我们建议你改用 javadoc:java.lang.Enum[] 来表示这两个值。
如果你的 IDE 支持，这是迄今为止最有效的自动完成方法。



[[appendix.configuration-metadata.manual-hints.value-providers]]
== 值提供者

提供者是为属性附加语义的强大方式。
在本节中，我们定义了你可以在自己的提示中使用的官方提供者。
但是，你喜欢的 IDE 可能实现了其中的一些或一个都没有。
此外，它最终可能会提供自己的提供者。

注意：由于这是一个新功能，IDE 供应商必须跟上它的工作方式。
采用时间自然各不相同。

下表总结了支持的提供者列表：

[cols="2,4"]
|===
| 名称 | 描述

| `any`
| 允许提供任何额外的值。

| `class-reference`
| 自动完成项目中可用的类。
  通常受 `target` 参数指定的基类约束。

| `handle-as`
| 将属性视为由强制 `target` 参数定义的类型定义。

| `logger-name`
| 自动完成有效的日志记录器名称和 xref:reference:features/logging.adoc#features.logging.log-groups[日志记录器组]。
  通常，当前项目中可用的包和类名以及已定义的组都可以自动完成。

| `spring-bean-reference`
| 自动完成当前项目中可用的 bean 名称。
  通常受 `target` 参数指定的基类约束。

| `spring-profile-name`
| 自动完成项目中定义的 Spring profile 名称。
|===

提示：对于给定属性，只能激活一个提供者，但如果它们都能以某种方式管理属性，你可以指定多个提供者。
确保将最强大的提供者放在首位，因为 IDE 必须使用 JSON 部分中它可以处理的第一个。
如果不支持给定属性的提供者，则不提供特殊内容帮助。



[[appendix.configuration-metadata.manual-hints.value-providers.any]]
=== Any

特殊的 **any** 提供者值允许提供任何额外的值。
如果支持，应该应用基于属性类型的常规值验证。

如果你有一个值列表，并且任何额外的值仍应被视为有效，则通常使用此提供者。

以下示例为 `system.state` 提供 `on` 和 `off` 作为自动完成值：

[source,json]
----
{"hints": [
	{
		"name": "system.state",
		"values": [
			{
				"value": "on"
			},
			{
				"value": "off"
			}
		],
		"providers": [
			{
				"name": "any"
			}
		]
	}
]}
----

注意，在前面的示例中，也允许任何其他值。



[[appendix.configuration-metadata.manual-hints.value-providers.class-reference]]
=== 类引用

**class-reference** 提供者自动完成项目中可用的类。
此提供者支持以下参数：

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `target`
| javadoc:java.lang.String[] (`Class`)
| _none_
| 应该可分配给所选值的类的完全限定名。
  通常用于过滤掉非候选类。
  注意，此信息可以由类型本身通过暴露具有适当上限的类来提供。

| `concrete`
| `boolean`
| true
| 指定是否只将具体类视为有效候选。
|===


以下元数据片段对应于定义要使用的类名的标准 `server.servlet.jsp.class-name` 属性，必须是 javadoc:jakarta.servlet.http.HttpServlet[]：

[source,json]
----
{"hints": [
	{
		"name": "server.servlet.jsp.class-name",
		"providers": [
			{
				"name": "class-reference",
				"parameters": {
					"target": "jakarta.servlet.http.HttpServlet"
				}
			}
		]
	}
]}
----



[[appendix.configuration-metadata.manual-hints.value-providers.handle-as]]
=== 处理为

**handle-as** 提供者允许你将属性的类型替换为更高级别的类型。
这通常发生在属性具有 javadoc:java.lang.String[] 类型时，因为你不想让你的配置类依赖于可能不在类路径上的类。
此提供者支持以下参数：

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| **`target`**
| javadoc:java.lang.String[] (`Class`)
| _none_
| 要考虑的属性的类型的完全限定名。
  此参数是必需的。
|===

可以使用以下类型：

* 任何 javadoc:java.lang.Enum[]: 列出属性的可能值。
  （我们建议使用 javadoc:java.lang.Enum[] 类型定义属性，因为不需要进一步提示 IDE 自动完成值）
* javadoc:java.nio.charset.Charset[]: 支持字符集/编码值的自动完成（例如 `UTF-8`）
* javadoc:java.util.Locale[]: 自动完成区域设置（例如 `en_US`）
* javadoc:org.springframework.util.MimeType[]: 支持内容类型值的自动完成（例如 `text/plain`）
* javadoc:org.springframework.core.io.Resource[]: 支持 Spring 的资源抽象的自动完成，以引用文件系统或类路径上的文件（例如 `classpath:/sample.properties`）

提示：如果可以提供多个值，请使用 javadoc:java.util.Collection[] 或 _Array_ 类型来教 IDE。

以下元数据片段对应于定义要使用的变更日志路径的标准 `spring.liquibase.change-log` 属性。
它实际上在内部用作 javadoc:org.springframework.core.io.Resource[]，但不能以这种方式公开，因为我们需要保留原始字符串值以传递给 Liquibase API。

[source,json]
----
{"hints": [
	{
		"name": "spring.liquibase.change-log",
		"providers": [
			{
				"name": "handle-as",
				"parameters": {
					"target": "org.springframework.core.io.Resource"
				}
			}
		]
	}
]}
----



[[appendix.configuration-metadata.manual-hints.value-providers.logger-name]]
=== 日志记录器名称

**logger-name** 提供者自动完成有效的日志记录器名称和 xref:reference:features/logging.adoc#features.logging.log-groups[日志记录器组]。
通常，当前项目中可用的包和类名可以自动完成。
如果启用了组（默认）并且在配置中识别了自定义日志记录器组，则应提供其自动完成。
特定框架可能也有可以支持的额外魔法日志记录器名称。

此提供者支持以下参数：

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `group`
| `boolean`
| `true`
| 指定是否应考虑已知组。
|===

由于日志记录器名称可以是任意名称，此提供者应允许任何值，但可以突出显示项目类路径中不可用的有效包和类名。

以下元数据片段对应于标准 `logging.level` 属性。
键是 _logger names_，值对应于标准日志级别或任何自定义级别。
由于 Spring Boot 开箱即用地定义了一些日志记录器组，因此为这些组添加了专用值提示。

[source,json]
----
{"hints": [
	{
		"name": "logging.level.keys",
		"values": [
			{
				"value": "root",
				"description": "Root logger used to assign the default logging level."
			},
			{
				"value": "sql",
				"description": "SQL logging group including Hibernate SQL logger."
			},
			{
				"value": "web",
				"description": "Web logging group including codecs."
			}
		],
		"providers": [
			{
				"name": "logger-name"
			}
		]
	},
	{
		"name": "logging.level.values",
		"values": [
			{
				"value": "trace"
			},
			{
				"value": "debug"
			},
			{
				"value": "info"
			},
			{
				"value": "warn"
			},
			{
				"value": "error"
			},
			{
				"value": "fatal"
			},
			{
				"value": "off"
			}

		],
		"providers": [
			{
				"name": "any"
			}
		]
	}
]}
----



[[appendix.configuration-metadata.manual-hints.value-providers.spring-bean-reference]]
=== Spring Bean 引用

**spring-bean-reference** 提供者自动完成当前项目配置中定义的 bean。
此提供者支持以下参数：

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `target`
| javadoc:java.lang.String[] (`Class`)
| _none_
| 应该可分配给候选者的 bean 类的完全限定名。
  通常用于过滤掉非候选 bean。
|===

以下元数据片段对应于定义要使用的 javadoc:javax.management.MBeanServer[] bean 名称的标准 `spring.jmx.server` 属性：

[source,json]
----
{"hints": [
	{
		"name": "spring.jmx.server",
		"providers": [
			{
				"name": "spring-bean-reference",
				"parameters": {
					"target": "javax.management.MBeanServer"
				}
			}
		]
	}
]}
----



[[appendix.configuration-metadata.manual-hints.value-providers.spring-profile-name]]
=== Spring Profile 名称

**spring-profile-name** 提供者自动完成当前项目配置中定义的 Spring profile。

以下元数据片段对应于定义要启用的 Spring profile 名称的标准 `spring.profiles.active` 属性：

[source,json]
----
{"hints": [
	{
		"name": "spring.profiles.active",
		"providers": [
			{
				"name": "spring-profile-name"
			}
		]
	}
]}
----
