[[appendix.configuration-metadata.manual-hints]]
= Providing Manual Hints

为了改善用户体验并进一步帮助用户配置给定属性，你可以提供额外的元数据：

* 描述属性的潜在值列表。
* 关联一个提供者，为属性附加明确定义的语义，以便工具可以根据项目的上下文发现潜在值列表。



[[appendix.configuration-metadata.manual-hints.value-hint]]
== Value Hint

每个提示的 `name` 属性引用属性的 `name`。
在 xref:configuration-metadata/format.adoc[前面显示的初始示例]中，我们为 `spring.jpa.hibernate.ddl-auto` 属性提供了五个值：`none`、`validate`、`update`、`create` 和 `create-drop`。
每个值也可能有描述。

如果你的属性是 javadoc:java.util.Map[] 类型，你可以为键和值提供提示（但不能为映射本身提供）。
特殊的 `.keys` 和 `.values` 后缀必须分别引用键和值。

假设 `my.contexts` 将魔法 javadoc:java.lang.String[] 值映射到整数，如下例所示：

include-code::MyProperties[]

魔法值（在此示例中）是 `sample1` 和 `sample2`。
为了为键提供额外的内容帮助，你可以将以下 JSON 添加到 xref:configuration-metadata/annotation-processor.adoc#appendix.configuration-metadata.annotation-processor.adding-additional-metadata[模块的手动元数据]中：

[source,json]
----
{"hints": [
	{
		"name": "my.contexts.keys",
		"values": [
			{
				"value": "sample1"
			},
			{
				"value": "sample2"
			}
		]
	}
]}
----

提示：我们建议你改用 javadoc:java.lang.Enum[] 来表示这两个值。
如果你的 IDE 支持，这是迄今为止最有效的自动完成方法。



[[appendix.configuration-metadata.manual-hints.value-providers]]
== Value Providers

提供者是为属性附加语义的强大方式。
在本节中，我们定义了你可以在自己的提示中使用的官方提供者。
但是，你喜欢的 IDE 可能实现了其中的一些或一个都没有。
此外，它最终可能会提供自己的提供者。

注意：由于这是一个新功能，IDE 供应商必须跟上它的工作方式。
采用时间自然各不相同。

下表总结了支持的提供者列表：

[cols="2,4"]
|===
| Name | Description

| `any`
| 允许提供任何额外的值。

| `class-reference`
| 自动完成项目中可用的类。
  通常受 `target` 参数指定的基类约束。

| `handle-as`
| 将属性视为由强制 `target` 参数定义的类型定义。

| `logger-name`
| 自动完成有效的日志记录器名称和 xref:reference:features/logging.adoc#features.logging.log-groups[日志记录器组]。
  通常，当前项目中可用的包和类名以及已定义的组都可以自动完成。

| `spring-bean-reference`
| 自动完成当前项目中可用的 bean 名称。
  通常受 `target` 参数指定的基类约束。

| `spring-profile-name`
| 自动完成项目中定义的 Spring profile 名称。
|===

TIP: Only one provider can be active for a given property, but you can specify several providers if they can all manage the property _in some way_.
Make sure to place the most powerful provider first, as the IDE must use the first one in the JSON section that it can handle.
If no provider for a given property is supported, no special content assistance is provided, either.



[[appendix.configuration-metadata.manual-hints.value-providers.any]]
=== Any

特殊的 **any** 提供者值允许提供任何额外的值。
如果支持，应该应用基于属性类型的常规值验证。

如果你有一个值列表，并且任何额外的值仍应被视为有效，则通常使用此提供者。

以下示例为 `system.state` 提供 `on` 和 `off` 作为自动完成值：

[source,json]
----
{"hints": [
	{
		"name": "system.state",
		"values": [
			{
				"value": "on"
			},
			{
				"value": "off"
			}
		],
		"providers": [
			{
				"name": "any"
			}
		]
	}
]}
----

注意，在前面的示例中，也允许任何其他值。



[[appendix.configuration-metadata.manual-hints.value-providers.class-reference]]
=== Class Reference

**class-reference** 提供者自动完成项目中可用的类。
此提供者支持以下参数：

[cols="1,1,2,4"]
|===
| Parameter | Type | Default value | Description

| `target`
| javadoc:java.lang.String[] (`Class`)
| _none_
| 应该可分配给所选值的类的完全限定名。
  通常用于过滤掉非候选类。
  注意，此信息可以由类型本身通过暴露具有适当上限的类来提供。

| `concrete`
| `boolean`
| true
| 指定是否只将具体类视为有效候选。
|===


The following metadata snippet corresponds to the standard `server.servlet.jsp.class-name` property that defines the class name to use must be an javadoc:jakarta.servlet.http.HttpServlet[]:

[source,json]
----
{"hints": [
	{
		"name": "server.servlet.jsp.class-name",
		"providers": [
			{
				"name": "class-reference",
				"parameters": {
					"target": "jakarta.servlet.http.HttpServlet"
				}
			}
		]
	}
]}
----



[[appendix.configuration-metadata.manual-hints.value-providers.handle-as]]
=== Handle As

**handle-as** 提供者允许你将属性的类型替换为更高级别的类型。
这通常发生在属性具有 javadoc:java.lang.String[] 类型时，因为你不想让你的配置类依赖于可能不在类路径上的类。
此提供者支持以下参数：

[cols="1,1,2,4"]
|===
| Parameter | Type | Default value | Description

| **`target`**
| javadoc:java.lang.String[] (`Class`)
| _none_
| 要考虑的属性的类型的完全限定名。
  此参数是必需的。
|===

The following types can be used:

* Any javadoc:java.lang.Enum[]: Lists the possible values for the property.
  (We recommend defining the property with the javadoc:java.lang.Enum[] type, as no further hint should be required for the IDE to auto-complete the values)
* javadoc:java.nio.charset.Charset[]: Supports auto-completion of charset/encoding values (such as `UTF-8`)
* javadoc:java.util.Locale[]: auto-completion of locales (such as `en_US`)
* javadoc:org.springframework.util.MimeType[]: Supports auto-completion of content type values (such as `text/plain`)
* javadoc:org.springframework.core.io.Resource[]: Supports auto-completion of Spring's Resource abstraction to refer to a file on the filesystem or on the classpath (such as `classpath:/sample.properties`)

TIP: If multiple values can be provided, use a javadoc:java.util.Collection[] or _Array_ type to teach the IDE about it.

The following metadata snippet corresponds to the standard `spring.liquibase.change-log` property that defines the path to the changelog to use.
It is actually used internally as a javadoc:org.springframework.core.io.Resource[] but cannot be exposed as such, because we need to keep the original String value to pass it to the Liquibase API.

[source,json]
----
{"hints": [
	{
		"name": "spring.liquibase.change-log",
		"providers": [
			{
				"name": "handle-as",
				"parameters": {
					"target": "org.springframework.core.io.Resource"
				}
			}
		]
	}
]}
----



[[appendix.configuration-metadata.manual-hints.value-providers.logger-name]]
=== Logger Name

**logger-name** 提供者自动完成有效的日志记录器名称和 xref:reference:features/logging.adoc#features.logging.log-groups[日志记录器组]。
通常，当前项目中可用的包和类名可以自动完成。
如果启用了组（默认）并且在配置中识别了自定义日志记录器组，则应提供其自动完成。
特定框架可能也有可以支持的额外魔法日志记录器名称。

此提供者支持以下参数：

[cols="1,1,2,4"]
|===
| Parameter | Type | Default value | Description

| `group`
| `boolean`
| `true`
| 指定是否应考虑已知组。
|===

Since a logger name can be any arbitrary name, this provider should allow any value but could highlight valid package and class names that are not available in the project's classpath.

The following metadata snippet corresponds to the standard `logging.level` property.
Keys are _logger names_, and values correspond to the standard log levels or any custom level.
As Spring Boot defines a few logger groups out-of-the-box, dedicated value hints have been added for those.

[source,json]
----
{"hints": [
	{
		"name": "logging.level.keys",
		"values": [
			{
				"value": "root",
				"description": "Root logger used to assign the default logging level."
			},
			{
				"value": "sql",
				"description": "SQL logging group including Hibernate SQL logger."
			},
			{
				"value": "web",
				"description": "Web logging group including codecs."
			}
		],
		"providers": [
			{
				"name": "logger-name"
			}
		]
	},
	{
		"name": "logging.level.values",
		"values": [
			{
				"value": "trace"
			},
			{
				"value": "debug"
			},
			{
				"value": "info"
			},
			{
				"value": "warn"
			},
			{
				"value": "error"
			},
			{
				"value": "fatal"
			},
			{
				"value": "off"
			}

		],
		"providers": [
			{
				"name": "any"
			}
		]
	}
]}
----



[[appendix.configuration-metadata.manual-hints.value-providers.spring-bean-reference]]
=== Spring Bean Reference

**spring-bean-reference** 提供者自动完成当前项目配置中定义的 bean。
此提供者支持以下参数：

[cols="1,1,2,4"]
|===
| Parameter | Type | Default value | Description

| `target`
| javadoc:java.lang.String[] (`Class`)
| _none_
| 应该可分配给候选者的 bean 类的完全限定名。
  通常用于过滤掉非候选 bean。
|===

The following metadata snippet corresponds to the standard `spring.jmx.server` property that defines the name of the javadoc:javax.management.MBeanServer[] bean to use:

[source,json]
----
{"hints": [
	{
		"name": "spring.jmx.server",
		"providers": [
			{
				"name": "spring-bean-reference",
				"parameters": {
					"target": "javax.management.MBeanServer"
				}
			}
		]
	}
]}
----

NOTE: The binder is not aware of the metadata.
If you provide that hint, you still need to transform the bean name into an actual Bean reference using by the javadoc:org.springframework.context.ApplicationContext[].



[[appendix.configuration-metadata.manual-hints.value-providers.spring-profile-name]]
=== Spring Profile Name

**spring-profile-name** 提供者自动完成当前项目配置中定义的 Spring profile。

The following metadata snippet corresponds to the standard `spring.profiles.active` property that defines the name of the Spring profile(s) to enable:

[source,json]
----
{"hints": [
	{
		"name": "spring.profiles.active",
		"providers": [
			{
				"name": "spring-profile-name"
			}
		]
	}
]}
----
