[[packaging.container-images.dockerfiles]]
= Dockerfiles

虽然只需在 `Dockerfile` 中使用几行代码就可以将 Spring Boot uber jar 转换为 Docker 镜像，但使用 xref:packaging/container-images/efficient-images.adoc#packaging.container-images.efficient-images.layering[分层功能] 将产生一个优化的镜像。
当您创建一个包含层索引文件的 jar 时，`spring-boot-jarmode-tools` jar 将作为依赖项添加到您的 jar 中。
有了这个 jar 在类路径上，您可以在特殊模式下启动应用程序，这允许引导代码运行与您的应用程序完全不同的内容，例如，提取层的内容。

CAUTION: `tools` 模式不能与包含启动脚本的 xref:how-to:deployment/installing.adoc[完全可执行的 Spring Boot 归档文件] 一起使用。
在构建打算与 `extract` tools 模式命令一起使用的 jar 文件时，请禁用启动脚本配置。

以下是如何使用 `tools` jar 模式启动您的 jar：

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar
----

这将提供以下输出：

[subs="verbatim"]
----
Usage:
  java -Djarmode=tools -jar my-app.jar

Available commands:
  extract      Extract the contents from the jar
  list-layers  List layers from the jar that can be extracted
  help         Help about any command
----

`extract` 命令可用于轻松地将应用程序拆分为要添加到 `Dockerfile` 的层。
以下是使用 `jarmode` 的 `Dockerfile` 示例。

[source,dockerfile]
----
include::reference:partial$dockerfile[]
# Start the application jar - this is not the uber jar used by the builder
# This jar only contains application code and references to the extracted jar files
# This layout is efficient to start up and CDS/AOT cache friendly
ENTRYPOINT ["java", "-jar", "application.jar"]
----

假设上述 `Dockerfile` 在当前目录中，您可以使用 `docker build .` 构建 Docker 镜像，或者可选地指定应用程序 jar 的路径，如下例所示：

[source,shell]
----
$ docker build --build-arg JAR_FILE=path/to/myapp.jar .
----

这是一个多阶段 `Dockerfile`。
构建器阶段提取稍后需要的目录。
每个 `COPY` 命令都与 jarmode 提取的层相关。

当然，`Dockerfile` 也可以不使用 `jarmode` 编写。
您可以使用 `unzip` 和 `mv` 的组合将内容移动到正确的层，但 `jarmode` 简化了这个过程。
此外，`jarmode` 创建的布局默认就是 CDS 和 AOT 缓存友好的。



[[packaging.container-images.dockerfiles.cds]]
== CDS

如果您想额外启用 xref:reference:packaging/class-data-sharing.adoc#packaging.class-data-sharing.cds[CDS]，您可以使用这个 `Dockerfile`：
[source,dockerfile]
----
include::reference:partial$dockerfile[]
# Execute the CDS training run
RUN java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar application.jar
# Start the application jar with CDS enabled - this is not the uber jar used by the builder
# This jar only contains application code and references to the extracted jar files
# This layout is efficient to start up and CDS friendly
ENTRYPOINT ["java", "-XX:SharedArchiveFile=application.jsa", "-jar", "application.jar"]
----

这与上面的 `Dockerfile` 基本相同。
作为最后步骤，它通过执行训练运行来创建 CDS 归档，并将 CDS 参数传递给 `java -jar`。

[[packaging.container-images.dockerfiles.aot-cache]]
== AOT cache

如果您想额外启用 xref:reference:packaging/class-data-sharing.adoc#packaging.class-data-sharing.aot-cache[AOT cache]，您可以使用这个 `Dockerfile`：
[source,dockerfile]
----
include::reference:partial$dockerfile[]
# Execute the AOT cache training run
RUN java -XX:AOTMode=record -XX:AOTConfiguration=app.aotconf -Dspring.context.exit=onRefresh -jar application.jar
RUN java -XX:AOTMode=create -XX:AOTConfiguration=app.aotconf -XX:AOTCache=app.aot -jar application.jar && rm app.aotconf
# Start the application jar with AOT cache enabled - this is not the uber jar used by the builder
# This jar only contains application code and references to the extracted jar files
# This layout is efficient to start up and AOT cache friendly
ENTRYPOINT ["java", "-XX:AOTCache=app.aot", "-jar", "application.jar"]
----

这与上面的 `Dockerfile` 基本相同。
作为最后步骤，它通过执行训练运行来创建 AOT 缓存文件，并将 AOT 缓存参数传递给 `java -jar`。
