[[getting-started.installing]]
= 安装 Spring Boot

Spring Boot 可以配合“经典”Java开发工具使用，也可以作为命令行工具安装。
无论哪种方式，你都需要 https://www.java.com[Java SDK v17] 或更高版本。
在开始之前，你应通过以下命令检查当前的 Java 安装：

[source,shell]
----
$ java -version
----

如果你是 Java 开发新手，或想要尝试 Spring Boot，建议优先体验 xref:installing.adoc#getting-started.installing.cli[Spring Boot CLI]（命令行界面）。
否则，请继续阅读“经典”安装说明。



[[getting-started.installing.java]]
== Java 开发者安装指南

你可以像使用标准 Java 库一样使用 Spring Boot。
只需将相应的 `+spring-boot-*.jar+` 文件加入 classpath 即可。
Spring Boot 不需要任何特殊工具集成，因此你可以使用任意 IDE 或文本编辑器。
此外，Spring Boot 应用本身没有特殊之处，你可以像调试普通 Java 程序一样运行和调试 Spring Boot 应用。

虽然你 _可以_ 直接复制 Spring Boot 的 jar 包，但我们更推荐使用支持依赖管理的构建工具（如 Maven 或 Gradle）。



[[getting-started.installing.java.maven]]
=== Maven 安装

Spring Boot 兼容 Apache Maven 3.6.3 及以上版本。
如果尚未安装 Maven，可参考 https://maven.apache.org 上的说明。

TIP: 在许多操作系统中，可以通过包管理器安装 Maven。
如果你使用 OSX Homebrew，可执行 `brew install maven`。
Ubuntu 用户可运行 `sudo apt-get install maven`。
Windows 用户可通过 https://chocolatey.org/[Chocolatey] 在提升权限（管理员）命令行下运行 `choco install maven`。

Spring Boot 依赖使用 `org.springframework.boot` 作为 group id。
通常，你的 Maven POM 文件会继承自 `spring-boot-starter-parent` 项目，并声明对一个或多个 xref:reference:using/build-systems.adoc#using.build-systems.starters[starters] 的依赖。
Spring Boot 还提供了可选的 xref:maven-plugin:index.adoc[Maven 插件]，用于创建可执行 jar 包。

关于 Spring Boot 与 Maven 的入门详情，请参见 Maven 插件参考指南中的 xref:maven-plugin:getting-started.adoc[] 部分。



[[getting-started.installing.java.gradle]]
=== Gradle 安装

Spring Boot 兼容 Gradle 7.x（7.6.4 及以上）或 8.x（8.4 及以上）。
如果尚未安装 Gradle，可参考 https://gradle.org 上的说明。

Spring Boot 依赖可通过 `org.springframework.boot` `group` 声明。
通常，项目会声明对一个或多个 xref:reference:using/build-systems.adoc#using.build-systems.starters[starters] 的依赖。
Spring Boot 提供了实用的 xref:gradle-plugin:index.adoc[Gradle 插件]，可简化依赖声明并创建可执行 jar 包。

.Gradle Wrapper
****
Gradle Wrapper 提供了一种便捷的方式，在需要构建项目时“获取”Gradle。
它是一个小型脚本和库，你可以将其与代码一同提交，用于引导构建流程。
详见 {url-gradle-docs}/gradle_wrapper.html。
****

关于 Spring Boot 与 Gradle 的入门详情，请参见 Gradle 插件参考指南中的 xref:gradle-plugin:getting-started.adoc[] 部分。



[[getting-started.installing.cli]]
== 安装 Spring Boot CLI

Spring Boot CLI（命令行界面）是一款可用于快速原型开发 Spring 应用的命令行工具。

你无需使用 CLI 也能开发 Spring Boot，但 CLI 是无需 IDE 快速启动 Spring 应用的便捷方式。



[[getting-started.installing.cli.manual-installation]]
=== 手动安装

ifeval::["{artifact-release-type}" == "snapshot"]
你可以从 {url-artifact-repository}/org/springframework/boot/spring-boot-cli/{version-spring-boot}/[Spring 软件仓库] 下载 `spring-boot-cli-*-bin.zip` 或 `spring-boot-cli-*-bin.tar.gz` 文件。
endif::[]
ifeval::["{artifact-release-type}" != "snapshot"]
你可以从以下位置下载 Spring CLI 分发包：

* {url-artifact-repository}/org/springframework/boot/spring-boot-cli/{version-spring-boot}/spring-boot-cli-{version-spring-boot}-bin.zip[spring-boot-cli-{version-spring-boot}-bin.zip]
* {url-artifact-repository}/org/springframework/boot/spring-boot-cli/{version-spring-boot}/spring-boot-cli-{version-spring-boot}-bin.tar.gz[spring-boot-cli-{version-spring-boot}-bin.tar.gz]
endif::[]


下载后，请按照解压包中的 {url-github-raw}/spring-boot-project/spring-boot-tools/spring-boot-cli/src/main/content/INSTALL.txt[INSTALL.txt] 说明操作。
简而言之，`.zip` 文件的 `bin/` 目录下有一个 `spring` 脚本（Windows 下为 `spring.bat`）。
你也可以用 `java -jar` 运行 `.jar` 文件（脚本可帮助你正确设置 classpath）。



[[getting-started.installing.cli.sdkman]]
=== 使用 SDKMAN! 安装

SDKMAN!（软件开发工具包管理器）可用于管理多种二进制 SDK 的多个版本，包括 Groovy 和 Spring Boot CLI。
访问 https://sdkman.io 获取 SDKMAN!，并通过以下命令安装 Spring Boot：

[source,shell,subs="verbatim,attributes"]
----
$ sdk install springboot
$ spring --version
Spring CLI v{version-spring-boot}
----

如果你需要为 CLI 开发功能并希望访问自己构建的版本，可执行以下命令：

[source,shell,subs="verbatim,attributes"]
----
$ sdk install springboot dev /path/to/spring-boot/spring-boot-cli/target/spring-boot-cli-{version-spring-boot}-bin/spring-{version-spring-boot}/
$ sdk default springboot dev
$ spring --version
Spring CLI v{version-spring-boot}
----

上述命令会安装一个名为 `dev` 的本地 `spring` 实例。
它指向你的目标构建目录，因此每次重新构建 Spring Boot 时，`spring` 都会保持最新。

你可以通过以下命令查看：

[source,shell,subs="verbatim,attributes"]
----
$ sdk ls springboot

================================================================================
Available Springboot Versions
================================================================================
> + dev
* {version-spring-boot}

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
----



[[getting-started.installing.cli.homebrew]]
=== OSX Homebrew 安装

如果你在 Mac 上并使用 https://brew.sh/[Homebrew]，可通过以下命令安装 Spring Boot CLI：

[source,shell]
----
$ brew tap spring-io/tap
$ brew install spring-boot
----

Homebrew 会将 `spring` 安装到 `/usr/local/bin`。

NOTE: 如果未找到该 formula，可能是 brew 版本过旧。
此时请运行 `brew update` 后重试。



[[getting-started.installing.cli.macports]]
=== MacPorts 安装

如果你在 Mac 上并使用 https://www.macports.org/[MacPorts]，可通过以下命令安装 Spring Boot CLI：

[source,shell]
----
$ sudo port install spring-boot-cli
----



[[getting-started.installing.cli.completion]]
=== 命令行补全

Spring Boot CLI 包含为 https://en.wikipedia.org/wiki/Bash_%28Unix_shell%29[BASH] 和 https://en.wikipedia.org/wiki/Z_shell[zsh] shell 提供命令补全的脚本。
你可以 `source` 名为 `spring`（zsh 下为 `_spring`）的脚本，或将其放入个人或系统级 bash 补全初始化目录。
在 Debian 系统中，系统级脚本位于 `<installation location>/shell-completion/<bash|zsh>`，该目录下所有脚本在新 shell 启动时都会执行。
例如，若通过 SDKMAN! 安装，可手动运行以下命令：

[source,shell]
----
$ . ~/.sdkman/candidates/springboot/current/shell-completion/bash/spring
$ spring <HIT TAB HERE>
  encodepassword  help  init  shell  version
----

NOTE: 如果通过 Homebrew 或 MacPorts 安装 Spring Boot CLI，命令行补全脚本会自动注册到你的 shell。



[[getting-started.installing.cli.scoop]]
=== Windows Scoop 安装

如果你在 Windows 上并使用 https://scoop.sh/[Scoop]，可通过以下命令安装 Spring Boot CLI：

[source,shell]
----
$ scoop bucket add extras
$ scoop install springboot
----

Scoop 会将 `spring` 安装到 `~/scoop/apps/springboot/current/bin`。

NOTE: 如果未找到该 app manifest，可能是 scoop 版本过旧。
此时请运行 `scoop update` 后重试。
