[[upgrading]]
= 升级 Spring Boot

如何从旧版本升级 Spring Boot 的说明已在项目 {url-github-wiki}[wiki] 提供。
请在 {url-github-wiki}#release-notes[发行说明] 部分查找你要升级到的版本。

升级说明总是位于发行说明的首项。
如果你落后多个版本，请务必同时查阅你所跨越版本的发行说明。



[[upgrading.from-1x]]
== 从 1.x 升级

如果你从 Spring Boot 的 `1.x` 版本升级，请查阅项目 wiki 上的 {url-github-wiki}/Spring-Boot-2.0-Migration-Guide[迁移指南]，该指南提供了详细的升级到 Spring Boot 2.x 的说明。
同时也请查阅 {url-github-wiki}[发行说明]，了解每个版本的“新特性与亮点”。



[[upgrading.from-2x]]
== 从 2.x 升级

如果你从 Spring Boot 的 `2.x` 版本升级，请查阅项目 wiki 上的 {url-github-wiki}/Spring-Boot-3.0-Migration-Guide[迁移指南]，该指南提供了详细的升级说明。
同时也请查阅 {url-github-wiki}[发行说明]，了解每个版本的“新特性与亮点”。



[[upgrading.to-feature]]
== 升级到新特性版本

升级到新特性版本时，部分属性可能被重命名或移除。
Spring Boot 提供了一种方式，可在启动时分析你的应用环境并打印诊断信息，同时还能在运行时临时迁移属性。
如需启用该功能，请在项目中添加如下依赖：

[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-properties-migrator</artifactId>
	<scope>runtime</scope>
</dependency>
----

WARNING: 那些在环境后期添加的属性（如使用 javadoc:org.springframework.context.annotation.PropertySource[format=annotation] 时）不会被考虑在内。

NOTE: 迁移完成后，请务必将该模块从项目依赖中移除。



[[upgrading.cli]]
== 升级 Spring Boot CLI

如需升级已安装的 CLI，请使用相应的包管理器命令（如 `brew upgrade`）。
如果你是手动安装 CLI，请按照 xref:installing.adoc#getting-started.installing.cli.manual-installation[标准说明] 操作，并记得更新你的 `PATH` 环境变量，移除任何旧版本引用。
