[[web.reactive]]
= 响应式 Web 应用程序

Spring Boot 通过为 Spring Webflux 提供自动配置，简化了响应式 Web 应用程序的开发。



[[web.reactive.webflux]]
== "`Spring WebFlux Framework`"

Spring WebFlux 是 Spring Framework 5.0 中引入的新响应式 Web 框架。
与 Spring MVC 不同，它不需要 servlet API，完全异步和非阻塞，并通过 https://projectreactor.io/[Reactor 项目] 实现了 https://www.reactive-streams.org/[Reactive Streams] 规范。

Spring WebFlux 有两种风格：函数式和基于注解的。
基于注解的方式与 Spring MVC 模型非常接近，如下例所示：

include-code::MyRestController[]

WebFlux 是 Spring Framework 的一部分，详细信息可在其 {url-spring-framework-docs}/web/webflux.html[参考文档] 中找到。

"`WebFlux.fn`"，函数式变体，将路由配置与实际请求处理分开，如下例所示：

include-code::MyRoutingConfiguration[]

include-code::MyUserHandler[]

"`WebFlux.fn`" 是 Spring Framework 的一部分，详细信息可在其 {url-spring-framework-docs}/web/webflux-functional.html[参考文档] 中找到。

TIP: 你可以定义任意数量的 javadoc:org.springframework.web.reactive.function.server.RouterFunction[] beans 来模块化路由器的定义。
如果需要应用优先级，beans 可以排序。

要开始使用，请将 `spring-boot-starter-webflux` 模块添加到你的应用程序中。

NOTE: 在应用程序中同时添加 `spring-boot-starter-web` 和 `spring-boot-starter-webflux` 模块会导致 Spring Boot 自动配置 Spring MVC，而不是 WebFlux。
选择这种行为是因为许多 Spring 开发者在他们的 Spring MVC 应用程序中添加 `spring-boot-starter-webflux` 来使用响应式 javadoc:org.springframework.web.reactive.function.client.WebClient[]。
你仍然可以通过设置所选应用程序类型为 `SpringApplication.setWebApplicationType(WebApplicationType.REACTIVE)` 来强制执行你的选择。



[[web.reactive.webflux.auto-configuration]]
=== Spring WebFlux 自动配置

Spring Boot 为 Spring WebFlux 提供了自动配置，适用于大多数应用程序。

自动配置在 Spring 的默认值之上添加了以下功能：

* 为 javadoc:org.springframework.http.codec.HttpMessageReader[] 和 javadoc:org.springframework.http.codec.HttpMessageWriter[] 实例配置编解码器（在本文档后面描述）。
* 支持提供静态资源，包括 WebJars 支持（在本文档后面描述）。

如果你想保留 Spring Boot WebFlux 功能并添加额外的 {url-spring-framework-docs}/web/webflux/config.html[WebFlux 配置]，你可以添加自己的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类，类型为 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[]，但*不要*使用 javadoc:org.springframework.web.reactive.config.EnableWebFlux[format=annotation]。

如果你想对自动配置的 javadoc:org.springframework.http.server.reactive.HttpHandler[] 进行额外的自定义，你可以定义类型为 javadoc:org.springframework.boot.autoconfigure.web.reactive.WebHttpHandlerBuilderCustomizer[] 的 beans，并使用它们来修改 javadoc:org.springframework.web.server.adapter.WebHttpHandlerBuilder[]。

如果你想完全控制 Spring WebFlux，你可以添加自己的 javadoc:org.springframework.context.annotation.Configuration[format=annotation]，并用 javadoc:org.springframework.web.reactive.config.EnableWebFlux[format=annotation] 注解。



[[web.reactive.webflux.conversion-service]]
=== Spring WebFlux 转换服务

如果你想自定义 Spring WebFlux 使用的 javadoc:org.springframework.core.convert.ConversionService[]，你可以提供一个带有 `addFormatters` 方法的 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[] bean。

转换也可以通过 `spring.webflux.format.*` 配置属性进行自定义。
当未配置时，使用以下默认值：

|===
|属性 |`DateTimeFormatter` |格式

|configprop:spring.webflux.format.date[]
|`ofLocalizedDate(FormatStyle.SHORT)`
|`java.util.Date` 和 javadoc:java.time.LocalDate[]

|configprop:spring.webflux.format.time[]
|`ofLocalizedTime(FormatStyle.SHORT)`
|java.time 的 javadoc:java.time.LocalTime[] 和 javadoc:java.time.OffsetTime[]

|configprop:spring.webflux.format.date-time[]
|`ofLocalizedDateTime(FormatStyle.SHORT)`
|java.time 的 javadoc:java.time.LocalDateTime[]、javadoc:java.time.OffsetDateTime[] 和 javadoc:java.time.ZonedDateTime[]
|===



[[web.reactive.webflux.httpcodecs]]
=== 使用 HttpMessageReaders 和 HttpMessageWriters 的 HTTP 编解码器

Spring WebFlux 使用 javadoc:org.springframework.http.codec.HttpMessageReader[] 和 javadoc:org.springframework.http.codec.HttpMessageWriter[] 接口来转换 HTTP 请求和响应。
它们通过 javadoc:org.springframework.http.codec.CodecConfigurer[] 配置，通过查看类路径中可用的库来设置合理的默认值。

Spring Boot 为编解码器提供了专门的配置属性 `+spring.codec.*+`。
它还通过使用 javadoc:org.springframework.boot.web.codec.CodecCustomizer[] 实例进行进一步的自定义。
例如，`+spring.jackson.*+` 配置键应用于 Jackson 编解码器。

如果你需要添加或自定义编解码器，你可以创建一个自定义的 javadoc:org.springframework.boot.web.codec.CodecCustomizer[] 组件，如下例所示：

include-code::MyCodecsConfiguration[]

你还可以利用 xref:features/json.adoc#features.json.jackson.custom-serializers-and-deserializers[Boot 的自定义 JSON 序列化器和反序列化器]。



[[web.reactive.webflux.static-content]]
=== 静态内容

默认情况下，Spring Boot 从类路径中名为 `/static`（或 `/public` 或 `/resources` 或 `/META-INF/resources`）的目录提供静态内容。
它使用 Spring WebFlux 的 javadoc:org.springframework.web.reactive.resource.ResourceWebHandler[]，因此你可以通过添加自己的 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[] 并重写 `addResourceHandlers` 方法来修改该行为。

默认情况下，资源映射在 `+/**+` 上，但你可以通过设置 configprop:spring.webflux.static-path-pattern[] 属性来调整它。
例如，可以通过以下方式将所有资源重新定位到 `/resources/**`：

[configprops,yaml]
----
spring:
  webflux:
    static-path-pattern: "/resources/**"
----

你还可以使用 `spring.web.resources.static-locations` 自定义静态资源位置。
这样做会用目录位置列表替换默认值。
如果你这样做，默认欢迎页面检测会切换到你的自定义位置。
因此，如果在启动时你的任何位置中有 `index.html`，它就是应用程序的主页。

除了前面列出的 "`标准`" 静态资源位置外，还对 https://www.webjars.org/[Webjars 内容] 进行了特殊处理。
默认情况下，如果资源以 Webjars 格式打包，则从 jar 文件中提供路径为 `+/webjars/**+` 的任何资源。
可以使用 configprop:spring.webflux.webjars-path-pattern[] 属性自定义路径。

TIP: Spring WebFlux 应用程序不严格依赖 servlet API，因此它们不能作为 war 文件部署，也不使用 `src/main/webapp` 目录。



[[web.reactive.webflux.welcome-page]]
=== 欢迎页面

Spring Boot 支持静态和模板化的欢迎页面。
它首先在配置的静态内容位置中查找 `index.html` 文件。
如果找不到，则查找 `index` 模板。
如果找到任何一个，它会自动用作应用程序的欢迎页面。

这仅作为应用程序定义的实际索引路由的后备。
顺序由 javadoc:org.springframework.web.reactive.HandlerMapping[] beans 的顺序定义，默认为以下顺序：

[cols="1,1"]
|===
|`org.springframework.web.reactive.function.server.support.RouterFunctionMapping`
|使用 javadoc:org.springframework.web.reactive.function.server.RouterFunction[] beans 声明的端点

|`org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping`
|在 javadoc:org.springframework.stereotype.Controller[format=annotation] beans 中声明的端点

|`RouterFunctionMapping` 用于欢迎页面
|欢迎页面支持
|===



[[web.reactive.webflux.template-engines]]
=== 模板引擎

除了 REST Web 服务外，你还可以使用 Spring WebFlux 来提供动态 HTML 内容。
Spring WebFlux 支持各种模板技术，包括 Thymeleaf、FreeMarker 和 Mustache。

Spring Boot 包含以下模板引擎的自动配置支持：

* https://freemarker.apache.org/docs/[FreeMarker]
* https://www.thymeleaf.org[Thymeleaf]
* https://mustache.github.io/[Mustache]

NOTE: 并非所有 FreeMarker 功能都支持 WebFlux。
有关更多详细信息，请查看每个属性的描述。

当你使用这些模板引擎之一并采用默认配置时，你的模板会自动从 `src/main/resources/templates` 中获取。



[[web.reactive.webflux.error-handling]]
=== 错误处理

Spring Boot 提供了一个 javadoc:org.springframework.web.server.WebExceptionHandler[]，它以合理的方式处理所有错误。
它在处理顺序中的位置紧接在 WebFlux 提供的处理程序之前，这些处理程序被视为最后。
对于机器客户端，它生成一个包含错误详情、HTTP 状态和异常消息的 JSON 响应。
对于浏览器客户端，有一个 "`whitelabel`" 错误处理程序，它以 HTML 格式渲染相同的数据。
你还可以提供自己的 HTML 模板来显示错误（参见 xref:web/reactive.adoc#web.reactive.webflux.error-handling.error-pages[下一节]）。

在直接在 Spring Boot 中自定义错误处理之前，你可以利用 Spring WebFlux 中的 {url-spring-framework-docs}/web/webflux/ann-rest-exceptions.html[RFC 9457 Problem Details] 支持。
Spring WebFlux 可以生成带有 `application/problem+json` 媒体类型的自定义错误消息，如：

[source,json]
----
{
	"type": "https://example.org/problems/unknown-project",
	"title": "Unknown project",
	"status": 404,
	"detail": "No project found for id 'spring-unknown'",
	"instance": "/projects/spring-unknown"
}
----

可以通过将 configprop:spring.webflux.problemdetails.enabled[] 设置为 `true` 来启用此支持。


自定义此功能的第一步通常涉及使用现有机制但替换或增强错误内容。
为此，你可以添加一个类型为 javadoc:org.springframework.boot.web.reactive.error.ErrorAttributes[] 的 bean。

要更改错误处理行为，你可以实现 javadoc:org.springframework.boot.web.reactive.error.ErrorWebExceptionHandler[] 并注册该类型的 bean 定义。
因为 javadoc:org.springframework.boot.web.reactive.error.ErrorWebExceptionHandler[] 相当底层，Spring Boot 还提供了一个方便的 javadoc:org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler[]，让你以 WebFlux 函数式方式处理错误，如下例所示：

include-code::MyErrorWebExceptionHandler[]

为了更完整的画面，你也可以直接子类化 javadoc:org.springframework.boot.autoconfigure.web.reactive.error.DefaultErrorWebExceptionHandler[] 并重写特定方法。

在某些情况下，控制器级别处理的错误不会被 Web 观察或 xref:actuator/metrics.adoc#actuator.metrics.supported.spring-webflux[指标基础设施]记录。
应用程序可以通过 {url-spring-framework-docs}/integration/observability.html#observability.http-server.reactive[在观察上下文中设置已处理的异常]来确保记录此类异常。



[[web.reactive.webflux.error-handling.error-pages]]
==== 自定义错误页面

如果你想为给定的状态代码显示自定义 HTML 错误页面，你可以添加从 `error/*` 解析的视图，例如通过将文件添加到 `/error` 目录。
错误页面可以是静态 HTML（即添加在任何静态资源目录下）或使用模板构建。
文件名应该是确切的状态代码、状态代码系列掩码，或者如果没有其他匹配项，则为 `error`。
注意，默认错误视图的路径是 `error/error`，而 Spring MVC 的默认错误视图是 `error`。

例如，要将 `404` 映射到静态 HTML 文件，你的目录结构如下：

[source]
----
src/
 +- main/
     +- java/
     |   + <source code>
     +- resources/
         +- public/
             +- error/
             |   +- 404.html
             +- <other public assets>
----

要使用 Mustache 模板映射所有 `5xx` 错误，你的目录结构如下：

[source]
----
src/
 +- main/
     +- java/
     |   + <source code>
     +- resources/
         +- templates/
             +- error/
             |   +- 5xx.mustache
             +- <other templates>
----



[[web.reactive.webflux.web-filters]]
=== Web 过滤器

Spring WebFlux 提供了一个 javadoc:org.springframework.web.server.WebFilter[] 接口，可以实现它来过滤 HTTP 请求-响应交换。
在应用程序上下文中找到的 javadoc:org.springframework.web.server.WebFilter[] beans 将自动用于过滤每个交换。

当过滤器的顺序很重要时，它们可以实现 javadoc:org.springframework.core.Ordered[] 或用 javadoc:org.springframework.core.annotation.Order[format=annotation] 注解。
Spring Boot 自动配置可能会为你配置 Web 过滤器。
当它这样做时，将使用下表中显示的顺序：

|===
| Web 过滤器 | 顺序

| javadoc:org.springframework.security.web.server.WebFilterChainProxy[] (Spring Security)
| `-100`

| javadoc:org.springframework.boot.actuate.web.exchanges.reactive.HttpExchangesWebFilter[]
| `Ordered.LOWEST_PRECEDENCE - 10`
|===



[[web.reactive.reactive-server]]
== 嵌入式响应式服务器支持

Spring Boot 包括对以下嵌入式响应式 Web 服务器的支持：Reactor Netty、Tomcat、Jetty 和 Undertow。
大多数开发者使用适当的 starter 来获得完全配置的实例。
默认情况下，嵌入式服务器在端口 8080 上监听 HTTP 请求。



[[web.reactive.reactive-server.customizing]]
=== 自定义响应式服务器

可以通过使用 Spring javadoc:org.springframework.core.env.Environment[] 属性来配置常见的响应式 Web 服务器设置。
通常，你会在 `application.properties` 或 `application.yaml` 文件中定义这些属性。

常见的服务器设置包括：

* 网络设置：传入 HTTP 请求的监听端口（`server.port`）、要绑定的接口地址（`server.address`）等。
* 错误管理：错误页面的位置（`server.error.path`）等。
* xref:how-to:webserver.adoc#howto.webserver.configure-ssl[SSL]
* xref:how-to:webserver.adoc#howto.webserver.enable-response-compression[HTTP 压缩]

Spring Boot 尽可能多地暴露常见设置，但这并不总是可能的。
对于这些情况，`server.netty.*` 等专用命名空间提供服务器特定的自定义。

TIP: 有关完整列表，请参见 javadoc:org.springframework.boot.autoconfigure.web.ServerProperties[] 类。



[[web.reactive.reactive-server.customizing.programmatic]]
==== 编程式自定义

如果你需要以编程方式配置响应式 Web 服务器，你可以注册一个实现 javadoc:org.springframework.boot.web.server.WebServerFactoryCustomizer[] 接口的 Spring bean。
javadoc:org.springframework.boot.web.server.WebServerFactoryCustomizer[] 提供对 javadoc:org.springframework.boot.web.reactive.server.ConfigurableReactiveWebServerFactory[] 的访问，它包含许多自定义 setter 方法。
以下示例显示以编程方式设置端口：

include-code::MyWebServerFactoryCustomizer[]

javadoc:org.springframework.boot.web.embedded.jetty.JettyReactiveWebServerFactory[]、javadoc:org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory[]、javadoc:org.springframework.boot.web.embedded.tomcat.TomcatReactiveWebServerFactory[] 和 javadoc:org.springframework.boot.web.embedded.undertow.UndertowReactiveWebServerFactory[] 是 javadoc:org.springframework.boot.web.reactive.server.ConfigurableReactiveWebServerFactory[] 的专用变体，它们分别具有 Jetty、Reactor Netty、Tomcat 和 Undertow 的额外自定义 setter 方法。
以下示例显示如何自定义 javadoc:org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory[]，它提供对 Reactor Netty 特定配置选项的访问：

include-code::MyNettyWebServerFactoryCustomizer[]



[[web.reactive.reactive-server.customizing.direct]]
==== 直接自定义 ConfigurableReactiveWebServerFactory

对于需要从 javadoc:org.springframework.boot.web.reactive.server.ReactiveWebServerFactory[] 扩展的更高级用例，你可以自己暴露这种类型的 bean。

为许多配置选项提供了 setter。
如果你需要做一些更奇特的事情，还提供了几个受保护的 "`hooks`" 方法。
有关详细信息，请参见 javadoc:org.springframework.boot.web.reactive.server.ConfigurableReactiveWebServerFactory[] API 文档。

NOTE: 自动配置的自定义器仍然应用于你的自定义工厂，所以要谨慎使用该选项。



[[web.reactive.reactive-server-resources-configuration]]
== 响应式服务器资源配置

当自动配置 Reactor Netty 或 Jetty 服务器时，Spring Boot 将创建特定的 beans，这些 beans 将为服务器实例提供 HTTP 资源：javadoc:org.springframework.http.client.ReactorResourceFactory[] 或 javadoc:org.springframework.http.client.reactive.JettyResourceFactory[]。

默认情况下，这些资源也会与 Reactor Netty 和 Jetty 客户端共享，以获得最佳性能，条件是：

* 服务器和客户端使用相同的技术
* 客户端实例是使用 Spring Boot 自动配置的 javadoc:org.springframework.web.reactive.function.client.WebClient$Builder[] bean 构建的

开发者可以通过提供自定义的 javadoc:org.springframework.http.client.ReactorResourceFactory[] 或 javadoc:org.springframework.http.client.reactive.JettyResourceFactory[] bean 来覆盖 Jetty 和 Reactor Netty 的资源配置 - 这将应用于客户端和服务器。

你可以在 xref:io/rest-client.adoc#io.rest-client.webclient.runtime[] 部分了解有关客户端资源配置的更多信息。


