[[web.security]]
= Spring Security

如果类路径中包含 {url-spring-security-site}[Spring Security]，则 Web 应用程序默认是安全的。
Spring Boot 依赖 Spring Security 的内容协商策略来决定是使用 `httpBasic` 还是 `formLogin`。
要为 Web 应用程序添加方法级安全性，你还可以添加 javadoc:org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity[format=annotation] 并设置所需的配置。
更多信息可以在 {url-spring-security-docs}/servlet/authorization/method-security.html[Spring Security 参考指南] 中找到。

默认的 javadoc:org.springframework.security.core.userdetails.UserDetailsService[] 只有一个用户。
用户名为 `user`，密码是随机的，在应用程序启动时会以 WARN 级别打印，如下例所示：

[source]
----
Using generated security password: 78fa095d-3f4c-48b1-ad50-e24c31d5cf35

This generated password is for development use only. Your security configuration must be updated before running your application in production.
----

注意：如果你调整了日志配置，请确保 `org.springframework.boot.autoconfigure.security` 类别设置为记录 `WARN` 级别的消息。
否则，默认密码将不会被打印。

你可以通过提供 `spring.security.user.name` 和 `spring.security.user.password` 来更改用户名和密码。

Web 应用程序默认提供的基本功能包括：

* 一个 javadoc:org.springframework.security.core.userdetails.UserDetailsService[]（或在 WebFlux 应用程序中是 javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[]）bean，具有内存存储和单个用户，该用户具有生成的密码（有关用户属性的详细信息，请参见 javadoc:org.springframework.boot.autoconfigure.security.SecurityProperties$User[]）。
* 基于表单的登录或 HTTP Basic 安全性（取决于请求中的 `Accept` 头）用于整个应用程序（如果类路径中包含 actuator，则包括 actuator 端点）。
* 一个 javadoc:org.springframework.security.authentication.DefaultAuthenticationEventPublisher[] 用于发布身份验证事件。

你可以通过添加一个 bean 来提供不同的 javadoc:org.springframework.security.authentication.AuthenticationEventPublisher[]。



[[web.security.spring-mvc]]
== MVC Security

默认的安全配置在 javadoc:org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration[] 和 javadoc:org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration[] 中实现。
javadoc:org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration[] 导入 `SpringBootWebSecurityConfiguration` 用于 Web 安全性，javadoc:org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration[] 用于身份验证。

要完全关闭默认的 Web 应用程序安全配置（包括 Actuator 安全性），或组合多个 Spring Security 组件（如 OAuth2 Client 和 Resource Server），添加一个类型为 javadoc:org.springframework.security.web.SecurityFilterChain[] 的 bean（这样做不会禁用 javadoc:org.springframework.security.core.userdetails.UserDetailsService[] 配置）。
要同时关闭 javadoc:org.springframework.security.core.userdetails.UserDetailsService[] 配置，添加一个类型为 javadoc:org.springframework.security.core.userdetails.UserDetailsService[]、javadoc:org.springframework.security.authentication.AuthenticationProvider[] 或 javadoc:org.springframework.security.authentication.AuthenticationManager[] 的 bean。

当类路径中包含以下任何 Spring Security 模块时，javadoc:org.springframework.security.core.userdetails.UserDetailsService[] 的自动配置也会退出：

- `spring-security-oauth2-client`
- `spring-security-oauth2-resource-server`
- `spring-security-saml2-service-provider`

要在这些依赖项之外使用 javadoc:org.springframework.security.core.userdetails.UserDetailsService[]，请定义你自己的 javadoc:org.springframework.security.provisioning.InMemoryUserDetailsManager[] bean。

可以通过添加自定义的 javadoc:org.springframework.security.web.SecurityFilterChain[] bean 来覆盖访问规则。
Spring Boot 提供了便捷方法，可用于覆盖 actuator 端点和静态资源的访问规则。
javadoc:org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest[] 可用于创建基于 configprop:management.endpoints.web.base-path[] 属性的 javadoc:org.springframework.security.web.util.matcher.RequestMatcher[]。
javadoc:org.springframework.boot.autoconfigure.security.servlet.PathRequest[] 可用于为常用位置的资源创建 javadoc:org.springframework.security.web.util.matcher.RequestMatcher[]。



[[web.security.spring-webflux]]
== WebFlux Security

与 Spring MVC 应用程序类似，你可以通过添加 `spring-boot-starter-security` 依赖项来保护你的 WebFlux 应用程序。
默认的安全配置在 javadoc:org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration[] 和 javadoc:org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration[] 中实现。
javadoc:org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration[] 导入 `WebFluxSecurityConfiguration` 用于 Web 安全性，javadoc:org.springframework.boot.autoconfigure.security.reactive.UserDetailsServiceAutoConfiguration[] 用于身份验证。
除了响应式 Web 应用程序外，当使用 RSocket 时，后者也会自动配置。

要完全关闭默认的 Web 应用程序安全配置（包括 Actuator 安全性），添加一个类型为 javadoc:org.springframework.security.web.server.WebFilterChainProxy[] 的 bean（这样做不会禁用 javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[] 配置）。
要同时关闭 javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[] 配置，添加一个类型为 javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[] 或 javadoc:org.springframework.security.authentication.ReactiveAuthenticationManager[] 的 bean。

当类路径中包含以下任何 Spring Security 模块时，自动配置也会退出：

- `spring-security-oauth2-client`
- `spring-security-oauth2-resource-server`

要在这些依赖项之外使用 javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[]，请定义你自己的 javadoc:org.springframework.security.core.userdetails.MapReactiveUserDetailsService[] bean。

可以通过添加自定义的 javadoc:org.springframework.security.web.server.SecurityWebFilterChain[] bean 来配置访问规则和使用多个 Spring Security 组件（如 OAuth 2 Client 和 Resource Server）。
Spring Boot 提供了便捷方法，可用于覆盖 actuator 端点和静态资源的访问规则。
javadoc:org.springframework.boot.actuate.autoconfigure.security.reactive.EndpointRequest[] 可用于创建基于 configprop:management.endpoints.web.base-path[] 属性的 javadoc:org.springframework.security.web.server.util.matcher.ServerWebExchangeMatcher[]。

javadoc:org.springframework.boot.autoconfigure.security.reactive.PathRequest[] 可用于为常用位置的资源创建 javadoc:org.springframework.security.web.server.util.matcher.ServerWebExchangeMatcher[]。

例如，你可以通过添加如下内容来自定义安全配置：

include-code::MyWebFluxSecurityConfiguration[]



[[web.security.oauth2]]
== OAuth2

https://oauth.net/2/[OAuth2] 是一个广泛使用的授权框架，Spring 对其提供了支持。



[[web.security.oauth2.client]]
=== Client

如果你的类路径中有 `spring-security-oauth2-client`，你可以利用一些自动配置来设置 OAuth2/Open ID Connect 客户端。
此配置使用 javadoc:org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientProperties[] 下的属性。
相同的属性适用于 servlet 和响应式应用程序。

你可以在 `spring.security.oauth2.client` 前缀下注册多个 OAuth2 客户端和提供者，如下例所示：

[configprops,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-login-client:
            client-id: "abcd"
            client-secret: "password"
            client-name: "Client for OpenID Connect"
            provider: "my-oauth-provider"
            scope: "openid,profile,email,phone,address"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"

          my-client-1:
            client-id: "abcd"
            client-secret: "password"
            client-name: "Client for user scope"
            provider: "my-oauth-provider"
            scope: "user"
            redirect-uri: "{baseUrl}/authorized/user"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"

          my-client-2:
            client-id: "abcd"
            client-secret: "password"
            client-name: "Client for email scope"
            provider: "my-oauth-provider"
            scope: "email"
            redirect-uri: "{baseUrl}/authorized/email"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"

        provider:
          my-oauth-provider:
            authorization-uri: "https://my-auth-server.com/oauth2/authorize"
            token-uri: "https://my-auth-server.com/oauth2/token"
            user-info-uri: "https://my-auth-server.com/userinfo"
            user-info-authentication-method: "header"
            jwk-set-uri: "https://my-auth-server.com/oauth2/jwks"
            user-name-attribute: "name"
----

对于支持 https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect discovery] 的 OpenID Connect 提供者，配置可以进一步简化。
提供者需要配置一个 `issuer-uri`，这是它声明的 Issuer Identifier URI。
例如，如果提供的 `issuer-uri` 是 "https://example.com"，则将向 "https://example.com/.well-known/openid-configuration" 发出 "OpenID Provider Configuration Request"。
预期结果是一个 "OpenID Provider Configuration Response"。
以下示例显示了如何使用 `issuer-uri` 配置 OpenID Connect Provider：

[configprops,yaml]
----
spring:
  security:
    oauth2:
      client:
        provider:
          oidc-provider:
            issuer-uri: "https://dev-123456.oktapreview.com/oauth2/default/"
----

默认情况下，Spring Security 的 javadoc:org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter[] 只处理匹配 `/login/oauth2/code/*` 的 URL。
如果你想自定义 `redirect-uri` 以使用不同的模式，你需要提供配置来处理该自定义模式。
例如，对于 servlet 应用程序，你可以添加自己的 javadoc:org.springframework.security.web.SecurityFilterChain[]，类似于以下内容：

include-code::MyOAuthClientConfiguration[]

提示：Spring Boot 自动配置了一个 javadoc:org.springframework.security.oauth2.client.InMemoryOAuth2AuthorizedClientService[]，Spring Security 使用它来管理客户端注册。
javadoc:org.springframework.security.oauth2.client.InMemoryOAuth2AuthorizedClientService[] 功能有限，我们建议仅在开发环境中使用它。
对于生产环境，考虑使用 javadoc:org.springframework.security.oauth2.client.JdbcOAuth2AuthorizedClientService[] 或创建你自己的 javadoc:org.springframework.security.oauth2.client.OAuth2AuthorizedClientService[] 实现。



[[web.security.oauth2.client.common-providers]]
==== OAuth2 Client Registration for Common Providers

对于常见的 OAuth2 和 OpenID 提供者，包括 Google、Github、Facebook 和 Okta，我们提供了一组提供者默认值（分别为 `google`、`github`、`facebook` 和 `okta`）。

如果你不需要自定义这些提供者，你可以将 `provider` 属性设置为需要推断默认值的提供者。
此外，如果客户端注册的键与默认支持的提供者匹配，Spring Boot 也会推断它。

换句话说，以下示例中的两个配置都使用 Google 提供者：

[configprops,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: "abcd"
            client-secret: "password"
            provider: "google"
          google:
            client-id: "abcd"
            client-secret: "password"
----



[[web.security.oauth2.server]]
=== Resource Server

如果你的类路径中有 `spring-security-oauth2-resource-server`，Spring Boot 可以设置 OAuth2 Resource Server。
对于 JWT 配置，需要指定 JWK Set URI 或 OIDC Issuer URI，如下例所示：

[configprops,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://example.com/oauth2/default/v1/keys"
----

[configprops,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-123456.oktapreview.com/oauth2/default/"
----

注意：如果授权服务器不支持 JWK Set URI，你可以使用用于验证 JWT 签名的公钥来配置资源服务器。
这可以使用 configprop:spring.security.oauth2.resourceserver.jwt.public-key-location[] 属性来完成，其中值需要指向包含 PEM 编码的 x509 格式公钥的文件。

configprop:spring.security.oauth2.resourceserver.jwt.audiences[] 属性可用于指定 JWT 中 aud 声明的预期值。
例如，要求 JWT 包含值为 `my-audience` 的 aud 声明：

[configprops,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
            - "my-audience"
----

相同的属性适用于 servlet 和响应式应用程序。
或者，你可以为 servlet 应用程序定义自己的 javadoc:org.springframework.security.oauth2.jwt.JwtDecoder[] bean，或为响应式应用程序定义 javadoc:org.springframework.security.oauth2.jwt.ReactiveJwtDecoder[]。

在使用不透明令牌而不是 JWT 的情况下，你可以配置以下属性以通过内省验证令牌：

[configprops,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: "https://example.com/check-token"
          client-id: "my-client-id"
          client-secret: "my-client-secret"
----

同样，相同的属性适用于 servlet 和响应式应用程序。
或者，你可以为 servlet 应用程序定义自己的 javadoc:org.springframework.security.oauth2.server.resource.introspection.OpaqueTokenIntrospector[] bean，或为响应式应用程序定义 javadoc:org.springframework.security.oauth2.server.resource.introspection.ReactiveOpaqueTokenIntrospector[]。



[[web.security.oauth2.authorization-server]]
=== Authorization Server

如果你的类路径中有 `spring-security-oauth2-authorization-server`，你可以利用一些自动配置来设置基于 Servlet 的 OAuth2 Authorization Server。

你可以在 `spring.security.oauth2.authorizationserver.client` 前缀下注册多个 OAuth2 客户端，如下例所示：

[configprops,yaml]
----
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          my-client-1:
            registration:
              client-id: "abcd"
              client-secret: "{noop}secret1"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "https://my-client-1.com/login/oauth2/code/abcd"
                - "https://my-client-1.com/authorized"
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "phone"
                - "address"
            require-authorization-consent: true
            token:
              authorization-code-time-to-live: 5m
              access-token-time-to-live: 10m
              access-token-format: "reference"
              reuse-refresh-tokens: false
              refresh-token-time-to-live: 30m
          my-client-2:
            registration:
              client-id: "efgh"
              client-secret: "{noop}secret2"
              client-authentication-methods:
                - "client_secret_jwt"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "user.read"
                - "user.write"
            jwk-set-uri: "https://my-client-2.com/jwks"
	        token-endpoint-authentication-signing-algorithm: "RS256"
----

注意：`client-secret` 属性必须采用可由配置的 javadoc:org.springframework.security.crypto.password.PasswordEncoder[] 匹配的格式。
javadoc:org.springframework.security.crypto.password.PasswordEncoder[] 的默认实例是通过 `PasswordEncoderFactories.createDelegatingPasswordEncoder()` 创建的。

Spring Boot 为 Spring Authorization Server 提供的自动配置旨在快速入门。
大多数应用程序都需要自定义，并且需要定义几个 bean 来覆盖自动配置。

以下组件可以定义为 bean 来覆盖特定于 Spring Authorization Server 的自动配置：

* javadoc:org.springframework.security.oauth2.server.authorization.client.RegisteredClientRepository[]
* javadoc:org.springframework.security.oauth2.server.authorization.settings.AuthorizationServerSettings[]
* javadoc:org.springframework.security.web.SecurityFilterChain[]
* `com.nimbusds.jose.jwk.source.JWKSource<com.nimbusds.jose.proc.SecurityContext>`
* javadoc:org.springframework.security.oauth2.jwt.JwtDecoder[]

提示：Spring Boot 自动配置了一个 javadoc:org.springframework.security.oauth2.server.authorization.client.InMemoryRegisteredClientRepository[]，Spring Authorization Server 使用它来管理注册的客户端。
javadoc:org.springframework.security.oauth2.server.authorization.client.InMemoryRegisteredClientRepository[] 功能有限，我们建议仅在开发环境中使用它。
对于生产环境，考虑使用 javadoc:org.springframework.security.oauth2.server.authorization.client.JdbcRegisteredClientRepository[] 或创建你自己的 javadoc:org.springframework.security.oauth2.server.authorization.client.RegisteredClientRepository[] 实现。

更多信息可以在 {url-spring-authorization-server-docs}/getting-started.html[入门] 章节中找到，该章节位于 {url-spring-authorization-server-docs}[Spring Authorization Server 参考指南] 中。



[[web.security.saml2]]
== SAML 2.0



[[web.security.saml2.relying-party]]
=== Relying Party

如果你的类路径中有 `spring-security-saml2-service-provider`，你可以利用一些自动配置来设置 SAML 2.0 Relying Party。
此配置使用 javadoc:org.springframework.boot.autoconfigure.security.saml2.Saml2RelyingPartyProperties[] 下的属性。

一个依赖方注册表示身份提供者（IDP）和服务提供者（SP）之间的配对配置。
你可以在 `spring.security.saml2.relyingparty` 前缀下注册多个依赖方，如下例所示：

[configprops,yaml]
----
spring:
  security:
    saml2:
      relyingparty:
        registration:
          my-relying-party1:
            signing:
              credentials:
              - private-key-location: "path-to-private-key"
                certificate-location: "path-to-certificate"
            decryption:
              credentials:
              - private-key-location: "path-to-private-key"
                certificate-location: "path-to-certificate"
            singlelogout:
               url: "https://myapp/logout/saml2/slo"
               response-url: "https://remoteidp2.slo.url"
               binding: "POST"
            assertingparty:
              verification:
                credentials:
                - certificate-location: "path-to-verification-cert"
              entity-id: "remote-idp-entity-id1"
              sso-url: "https://remoteidp1.sso.url"

          my-relying-party2:
            signing:
              credentials:
              - private-key-location: "path-to-private-key"
                certificate-location: "path-to-certificate"
            decryption:
              credentials:
              - private-key-location: "path-to-private-key"
                certificate-location: "path-to-certificate"
            assertingparty:
              verification:
                credentials:
                - certificate-location: "path-to-other-verification-cert"
              entity-id: "remote-idp-entity-id2"
              sso-url: "https://remoteidp2.sso.url"
              singlelogout:
                url: "https://remoteidp2.slo.url"
                response-url: "https://myapp/logout/saml2/slo"
                binding: "POST"
----

对于 SAML2 注销，默认情况下，Spring Security 的 javadoc:org.springframework.security.saml2.provider.service.web.authentication.logout.Saml2LogoutRequestFilter[] 和 javadoc:org.springframework.security.saml2.provider.service.web.authentication.logout.Saml2LogoutResponseFilter[] 只处理匹配 `/logout/saml2/slo` 的 URL。
如果你想自定义 AP 发起的注销请求发送到的 `url` 或 AP 发送注销响应到的 `response-url`，以使用不同的模式，你需要提供配置来处理该自定义模式。
例如，对于 servlet 应用程序，你可以添加自己的 javadoc:org.springframework.security.web.SecurityFilterChain[]，类似于以下内容：

include-code::MySamlRelyingPartyConfiguration[]
