[[actuator.cloud-foundry]]
= Cloud Foundry 支持

Spring Boot 的 actuator 模块在部署到兼容的 Cloud Foundry 实例时会激活额外支持。
`/cloudfoundryapplication` 路径为所有 javadoc:org.springframework.boot.actuate.endpoint.annotation.Endpoint[format=annotation] bean 提供了一条额外的安全访问通道。

该扩展支持让 Cloud Foundry 管理 UI（如用于查看已部署应用的 Web 应用）能够集成 Spring Boot actuator 信息。
例如，应用状态页可以显示完整健康信息，而不仅仅是常见的“`running`”或“`stopped`”状态。

NOTE: `/cloudfoundryapplication` 路径普通用户无法直接访问。
如需使用该端点，必须在请求中携带有效的 UAA token。



[[actuator.cloud-foundry.disable]]
== 禁用 Cloud Foundry 扩展 Actuator 支持

如需完全禁用 `/cloudfoundryapplication` 端点，可在 `application.properties` 文件中添加如下配置：

[configprops,yaml]
----
management:
  cloudfoundry:
    enabled: false
----



[[actuator.cloud-foundry.ssl]]
== Cloud Foundry 自签名证书

默认情况下，`/cloudfoundryapplication` 端点的安全校验会对多个 Cloud Foundry 服务发起 SSL 调用。
如果 Cloud Foundry UAA 或 Cloud Controller 服务使用自签名证书，则需设置如下属性：

[configprops,yaml]
----
management:
  cloudfoundry:
    skip-ssl-validation: true
----



[[actuator.cloud-foundry.custom-context-path]]
== 自定义 Context Path

如果服务器的 context-path 配置为非 `/`，Cloud Foundry 端点不会出现在应用根路径。
例如，若 `server.servlet.context-path=/app`，Cloud Foundry 端点将位于 `/app/cloudfoundryapplication/*`。

如需无论 context-path 如何配置都始终通过 `/cloudfoundryapplication/*` 访问 Cloud Foundry 端点，则需在应用中显式配置。
具体配置方式取决于所用 Web 服务器。
对于 Tomcat，可添加如下配置：

include-code::MyCloudFoundryConfiguration[]

若为基于 Webflux 的应用，可使用如下配置：

include-code::MyReactiveCloudFoundryConfiguration[]
