[[actuator.metrics]]
= 指标

Spring Boot Actuator 为 {url-micrometer-site}[Micrometer] 提供依赖管理和自动配置，Micrometer 是一个应用程序指标门面，支持 {url-micrometer-docs}[众多监控系统]，包括：

- xref:actuator/metrics.adoc#actuator.metrics.export.appoptics[]
- xref:actuator/metrics.adoc#actuator.metrics.export.atlas[]
- xref:actuator/metrics.adoc#actuator.metrics.export.datadog[]
- xref:actuator/metrics.adoc#actuator.metrics.export.dynatrace[]
- xref:actuator/metrics.adoc#actuator.metrics.export.elastic[]
- xref:actuator/metrics.adoc#actuator.metrics.export.ganglia[]
- xref:actuator/metrics.adoc#actuator.metrics.export.graphite[]
- xref:actuator/metrics.adoc#actuator.metrics.export.humio[]
- xref:actuator/metrics.adoc#actuator.metrics.export.influx[]
- xref:actuator/metrics.adoc#actuator.metrics.export.jmx[]
- xref:actuator/metrics.adoc#actuator.metrics.export.kairos[]
- xref:actuator/metrics.adoc#actuator.metrics.export.newrelic[]
- xref:actuator/metrics.adoc#actuator.metrics.export.otlp[]
- xref:actuator/metrics.adoc#actuator.metrics.export.prometheus[]
- xref:actuator/metrics.adoc#actuator.metrics.export.simple[] (in-memory)
- xref:actuator/metrics.adoc#actuator.metrics.export.stackdriver[]
- xref:actuator/metrics.adoc#actuator.metrics.export.statsd[]
- xref:actuator/metrics.adoc#actuator.metrics.export.wavefront[]

TIP: 要了解更多关于 Micrometer 功能的信息，请参阅其 {url-micrometer-docs}[参考文档]，特别是 {url-micrometer-docs-concepts}[概念部分]。



[[actuator.metrics.getting-started]]
== 入门

Spring Boot 自动配置一个复合 javadoc:io.micrometer.core.instrument.MeterRegistry[]，并为类路径上找到的每个支持的实现添加一个注册表到复合中。
在运行时类路径中具有 `micrometer-registry-\{system}` 依赖就足以让 Spring Boot 配置注册表。

大多数注册表共享常见功能。
例如，即使 Micrometer 注册表实现存在于类路径中，您也可以禁用特定注册表。
以下示例禁用 Datadog：

[configprops,yaml]
----
management:
  datadog:
    metrics:
      export:
        enabled: false
----

您还可以禁用所有注册表，除非通过特定于注册表的属性另行指定，如下例所示：

[configprops,yaml]
----
management:
  defaults:
    metrics:
      export:
        enabled: false
----

Spring Boot 还会将任何自动配置的注册表添加到 javadoc:io.micrometer.core.instrument.Metrics[] 类上的全局静态复合注册表，除非您明确指示不要这样做：

[configprops,yaml]
----
management:
  metrics:
    use-global-registry: false
----

您可以注册任意数量的 javadoc:org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryCustomizer[] bean，以在任何仪表注册到注册表之前进一步配置注册表，例如应用通用标签：

include-code::commontags/MyMeterRegistryConfiguration[]

您可以通过对泛型类型更具体地指定来对特定注册表实现应用自定义：

include-code::specifictype/MyMeterRegistryConfiguration[]

Spring Boot 还 xref:actuator/metrics.adoc#actuator.metrics.supported[配置内置仪表]，您可以通过配置或专用注解标记控制这些仪表。



[[actuator.metrics.export]]
== 支持的监控系统

本节简要描述每个支持的监控系统。



[[actuator.metrics.export.appoptics]]
=== AppOptics

默认情况下，AppOptics 注册表定期将指标推送到 `https://api.appoptics.com/v1/measurements`。
要将指标导出到 SaaS {url-micrometer-docs-implementations}/appOptics[AppOptics]，必须提供您的 API 令牌：

[configprops,yaml]
----
management:
  appoptics:
    metrics:
      export:
        api-token: "YOUR_TOKEN"
----



[[actuator.metrics.export.atlas]]
=== Atlas

默认情况下，指标导出到在本地机器上运行的 {url-micrometer-docs-implementations}/atlas[Atlas]。
您可以提供 https://github.com/Netflix/atlas[Atlas 服务器] 的位置：

[configprops,yaml]
----
management:
  atlas:
    metrics:
      export:
        uri: "https://atlas.example.com:7101/api/v1/publish"
----



[[actuator.metrics.export.datadog]]
=== Datadog

Datadog 注册表定期将指标推送到 https://www.datadoghq.com[datadoghq]。
要将指标导出到 {url-micrometer-docs-implementations}/datadog[Datadog]，您必须提供您的 API 密钥：

[configprops,yaml]
----
management:
  datadog:
    metrics:
      export:
        api-key: "YOUR_KEY"
----

如果您额外提供一个应用程序密钥（可选），则元数据（如仪表描述、类型和基本单位）也将被导出：

[configprops,yaml]
----
management:
  datadog:
    metrics:
      export:
        api-key: "YOUR_API_KEY"
        application-key: "YOUR_APPLICATION_KEY"
----

默认情况下，指标发送到 Datadog 美国 https://docs.datadoghq.com/getting_started/site[站点]（`https://api.datadoghq.com`）。
如果您的 Datadog 项目托管在其他站点上，或者您需要通过代理发送指标，请相应配置 URI：

[configprops,yaml]
----
management:
  datadog:
    metrics:
      export:
        uri: "https://api.datadoghq.eu"
----

您还可以更改发送指标到 Datadog 的间隔：

[configprops,yaml]
----
management:
  datadog:
    metrics:
      export:
        step: "30s"
----



[[actuator.metrics.export.dynatrace]]
=== Dynatrace

Dynatrace 提供两种指标摄取 API，两种都为 {url-micrometer-docs-implementations}/dynatrace[Micrometer] 实现。
您可以在 {url-dynatrace-docs-shortlink}/micrometer-metrics-ingest[这里] 找到 Dynatrace 关于 Micrometer 指标摄取的文档。
`v1` 命名空间中的配置属性仅在导出到 {url-dynatrace-docs-shortlink}/api-metrics[Timeseries v1 API] 时适用。
`v2` 命名空间中的配置属性仅在导出到 {url-dynatrace-docs-shortlink}/api-metrics-v2-post-datapoints[Metrics v2 API] 时适用。
请注意，此集成一次只能导出到 API 的 `v1` 或 `v2` 版本，推荐使用 `v2`。
如果在 `v1` 命名空间中设置了 `device-id`（v1 必需，v2 不使用），指标将导出到 `v1` 端点。
否则，假定为 `v2`。



[[actuator.metrics.export.dynatrace.v2-api]]
==== v2 API

您可以通过两种方式使用 v2 API。



[[actuator.metrics.export.dynatrace.v2-api.auto-config]]
===== 自动配置

对于由 OneAgent 或 Kubernetes 的 Dynatrace Operator 监控的主机，Dynatrace 提供自动配置。

**本地 OneAgent：** 如果主机上运行 OneAgent，指标将自动导出到 {url-dynatrace-docs-shortlink}/local-api[本地 OneAgent 摄取端点]。
摄取端点将指标转发到 Dynatrace 后端。

**Dynatrace Kubernetes Operator：** 在安装了 Dynatrace Operator 的 Kubernetes 中运行时，注册表将自动从 Operator 获取您的端点 URI 和 API 令牌。

这是默认行为，只需依赖 `io.micrometer:micrometer-registry-dynatrace` 即可，无需特殊设置。



[[actuator.metrics.export.dynatrace.v2-api.manual-config]]
===== 手动配置

如果没有自动配置可用，则需要 {url-dynatrace-docs-shortlink}/api-metrics-v2-post-datapoints[Metrics v2 API] 的端点和 API 令牌。
{url-dynatrace-docs-shortlink}/api-authentication[API 令牌] 必须具有 "`Ingest metrics`" (`metrics.ingest`) 权限。
我们建议将令牌的范围限制为这一权限。
您必须确保端点 URI 包含路径（例如，`/api/v2/metrics/ingest`）：

Metrics API v2 摄取端点的 URL 根据您的部署选项不同：

* SaaS：`+https://{your-environment-id}.live.dynatrace.com/api/v2/metrics/ingest+`
* 托管部署：`+https://{your-domain}/e/{your-environment-id}/api/v2/metrics/ingest+`

以下示例使用 `example` 环境 ID 配置指标导出：

[configprops,yaml]
----
management:
  dynatrace:
    metrics:
      export:
        uri: "https://example.live.dynatrace.com/api/v2/metrics/ingest"
        api-token: "YOUR_TOKEN"
----

使用 Dynatrace v2 API 时，以下可选功能可用（更多详情请参阅 {url-dynatrace-docs-shortlink}/micrometer-metrics-ingest#dt-configuration-properties[Dynatrace 文档]）：

* 指标键前缀：设置一个前缀，添加到所有导出的指标键前。
* 使用 Dynatrace 元数据丰富：如果运行了 OneAgent 或 Dynatrace Operator，使用额外的元数据（例如，主机、进程或 Pod）丰富指标。
* 默认维度：指定添加到所有导出指标的键值对。
如果使用 Micrometer 指定了相同键的标签，它们将覆盖默认维度。
* 使用 Dynatrace 摘要仪表：在某些情况下，Micrometer Dynatrace 注册表创建的指标被拒绝。
在 Micrometer 1.9.x 中，通过引入特定于 Dynatrace 的摘要仪表修复了此问题。
将此开关设置为 `false` 会强制 Micrometer 回退到 1.9.x 之前的默认行为。
仅在从 Micrometer 1.8.x 迁移到 1.9.x 时遇到问题时使用。
* 导出仪表元数据：从 Micrometer 1.12.0 开始，Dynatrace 导出器默认还会导出仪表元数据，例如单位和描述。
使用 `export-meter-metadata` 开关关闭此功能。

可以不指定 URI 和 API 令牌，如下例所示。
在这种情况下，将使用自动配置的端点：

[configprops,yaml]
----
management:
  dynatrace:
    metrics:
      export:
        # 如果不使用本地 OneAgent 端点，请在此指定 uri 和 api-token。
        v2:
          metric-key-prefix: "your.key.prefix"
          enrich-with-dynatrace-metadata: true
          default-dimensions:
            key1: "value1"
            key2: "value2"
          use-dynatrace-summary-instruments: true #（默认：true）
          export-meter-metadata: true             #（默认：true）
----



[[actuator.metrics.export.dynatrace.v1-api]]
==== v1 API（遗留）

Dynatrace v1 API 指标注册表通过 {url-dynatrace-docs-shortlink}/api-metrics[Timeseries v1 API] 定期将指标推送到配置的 URI。
为了与现有设置向后兼容，当设置了 `device-id`（v1 必需，v2 不使用）时，指标将导出到 Timeseries v1 端点。
要将指标导出到 {url-micrometer-docs-implementations}/dynatrace[Dynatrace]，必须提供您的 API 令牌、设备 ID 和 URI：

[configprops,yaml]
----
management:
  dynatrace:
    metrics:
      export:
        uri: "https://{your-environment-id}.live.dynatrace.com"
        api-token: "YOUR_TOKEN"
        v1:
          device-id: "YOUR_DEVICE_ID"
----

对于 v1 API，您必须指定不带路径的基本环境 URI，因为 v1 端点路径会自动添加。



[[actuator.metrics.export.dynatrace.version-independent-settings]]
==== 版本无关设置

除了 API 端点和令牌外，您还可以更改发送指标到 Dynatrace 的间隔。
默认导出间隔为 `60s`。
以下示例将导出间隔设置为 30 秒：

[configprops,yaml]
----
management:
  dynatrace:
    metrics:
      export:
        step: "30s"
----

您可以在 {url-micrometer-docs-implementations}/dynatrace[Micrometer 文档] 和 {url-dynatrace-docs-shortlink}/micrometer-metrics-ingest[Dynatrace 文档] 中找到更多关于如何设置 Dynatrace 导出器的信息。



[[actuator.metrics.export.elastic]]
=== Elastic

默认情况下，指标导出到在本地机器上运行的 {url-micrometer-docs-implementations}/elastic[Elastic]。
您可以使用以下属性提供要使用的 Elastic 服务器位置：

[configprops,yaml]
----
management:
  elastic:
    metrics:
      export:
        host: "https://elastic.example.com:8086"
----



[[actuator.metrics.export.ganglia]]
=== Ganglia

默认情况下，指标导出到在本地机器上运行的 {url-micrometer-docs-implementations}/ganglia[Ganglia]。
您可以提供 http://ganglia.sourceforge.net[Ganglia 服务器] 的主机和端口，如下例所示：

[configprops,yaml]
----
management:
  ganglia:
    metrics:
      export:
        host: "ganglia.example.com"
        port: 9649
----



[[actuator.metrics.export.graphite]]
=== Graphite

默认情况下，指标导出到在本地机器上运行的 {url-micrometer-docs-implementations}/graphite[Graphite]。
您可以提供 https://graphiteapp.org[Graphite 服务器] 的主机和端口，如下例所示：

[configprops,yaml]
----
management:
  graphite:
    metrics:
      export:
         host: "graphite.example.com"
         port: 9004
----

Micrometer 提供了一个默认的 javadoc:io.micrometer.core.instrument.util.HierarchicalNameMapper[]，用于控制维度仪表 ID 如何 {url-micrometer-docs-implementations}/graphite#_hierarchical_name_mapping[映射到平面层次名称]。

[TIP]
====
要控制此行为，定义您自己的 javadoc:io.micrometer.graphite.GraphiteMeterRegistry[] 并提供您自己的 javadoc:io.micrometer.core.instrument.util.HierarchicalNameMapper[]。
除非您定义了自己的，否则会提供自动配置的 javadoc:io.micrometer.graphite.GraphiteConfig[] 和 javadoc:io.micrometer.core.instrument.Clock[] bean：

include-code::MyGraphiteConfiguration[]
====



[[actuator.metrics.export.humio]]
=== Humio

默认情况下，Humio 注册表定期将指标推送到 https://cloud.humio.com。
要将指标导出到 SaaS {url-micrometer-docs-implementations}/humio[Humio]，您必须提供您的 API 令牌：

[configprops,yaml]
----
management:
  humio:
    metrics:
      export:
        api-token: "YOUR_TOKEN"
----

您还应配置一个或多个标签以标识推送指标的数据源：

[configprops,yaml]
----
management:
  humio:
    metrics:
      export:
        tags:
          alpha: "a"
          bravo: "b"
----



[[actuator.metrics.export.influx]]
=== Influx

默认情况下，指标导出到在本地机器上以默认配置运行的 {url-micrometer-docs-implementations}/influx[Influx] v1 实例。
要将指标导出到 InfluxDB v2，请配置用于写入指标的 `org`、`bucket` 和认证 `token`。
您可以使用以下方式提供要使用的 https://www.influxdata.com[Influx 服务器] 的位置：

[configprops,yaml]
----
management:
  influx:
    metrics:
      export:
        uri: "https://influx.example.com:8086"
----



[[actuator.metrics.export.jmx]]
=== JMX

Micrometer 提供到 {url-micrometer-docs-implementations}/jmx[JMX] 的层次映射，主要作为一种廉价且便携的本地查看指标的方式。
默认情况下，指标导出到 `metrics` JMX 域。
您可以使用以下方式提供要使用的域：

[configprops,yaml]
----
management:
  jmx:
    metrics:
      export:
        domain: "com.example.app.metrics"
----

Micrometer 提供了一个默认的 javadoc:io.micrometer.core.instrument.util.HierarchicalNameMapper[]，用于控制维度仪表 ID 如何 {url-micrometer-docs-implementations}/jmx#_hierarchical_name_mapping[映射到平面层次名称]。

[TIP]
====
要控制此行为，定义您自己的 javadoc:io.micrometer.jmx.JmxMeterRegistry[] 并提供您自己的 javadoc:io.micrometer.core.instrument.util.HierarchicalNameMapper[]。
除非您定义了自己的，否则会提供自动配置的 javadoc:io.micrometer.jmx.JmxConfig[] 和 javadoc:io.micrometer.core.instrument.Clock[] bean：

include-code::MyJmxConfiguration[]
====



[[actuator.metrics.export.kairos]]
=== KairosDB

默认情况下，指标导出到在本地机器上运行的 {url-micrometer-docs-implementations}/kairos[KairosDB]。
您可以使用以下方式提供要使用的 https://kairosdb.github.io/[KairosDB 服务器] 的位置：

[configprops,yaml]
----
management:
  kairos:
    metrics:
      export:
        uri: "https://kairosdb.example.com:8080/api/v1/datapoints"
----



[[actuator.metrics.export.newrelic]]
=== New Relic

New Relic 注册表定期将指标推送到 {url-micrometer-docs-implementations}/new-relic[New Relic]。
要将指标导出到 https://newrelic.com[New Relic]，您必须提供您的 API 密钥和账户 ID：

[configprops,yaml]
----
management:
  newrelic:
    metrics:
      export:
        api-key: "YOUR_KEY"
        account-id: "YOUR_ACCOUNT_ID"
----

您还可以更改发送指标到 New Relic 的间隔：

[configprops,yaml]
----
management:
  newrelic:
    metrics:
      export:
        step: "30s"
----

默认情况下，指标通过 REST 调用发布，但如果类路径上有 Java Agent API，您也可以使用它：

[configprops,yaml]
----
management:
  newrelic:
    metrics:
      export:
        client-provider-type: "insights-agent"
----

最后，您可以通过定义自己的 javadoc:io.micrometer.newrelic.NewRelicClientProvider[] bean 获得完全控制。



[[actuator.metrics.export.otlp]]
=== OTLP

默认情况下，指标通过 {url-micrometer-docs-implementations}/otlp[OpenTelemetry 协议 (OTLP)] 导出到在本地机器上运行的消费者。
要导出到其他位置，请使用 configprop:management.otlp.metrics.export.url[] 提供 https://opentelemetry.io/[OTLP 指标端点] 的位置：

[configprops,yaml]
----
management:
  otlp:
    metrics:
      export:
        url: "https://otlp.example.com:4318/v1/metrics"
----

还可以使用 configprop:management.otlp.metrics.export.headers.*[] 属性提供自定义头，例如用于认证。

如果有 `OtlpMetricsSender` bean 可用，它将被配置在 Spring Boot 自动配置的 `OtlpMeterRegistry` 上。



[[actuator.metrics.export.prometheus]]
=== Prometheus

{url-micrometer-docs-implementations}/prometheus[Prometheus] 期望通过抓取或轮询单个应用程序实例来获取指标。
Spring Boot 在 `/actuator/prometheus` 提供了一个 Actuator 端点，以适当格式呈现 https://prometheus.io[Prometheus 抓取]。

TIP: 默认情况下，该端点不可用，必须暴露。有关更多详细信息，请参阅 xref:actuator/endpoints.adoc#actuator.endpoints.exposing[暴露端点]。

以下示例 `scrape_config` 添加到 `prometheus.yml`：

[source,yaml]
----
scrape_configs:
- job_name: "spring"
  metrics_path: "/actuator/prometheus"
  static_configs:
  - targets: ["HOST:PORT"]
----

还支持 https://prometheus.io/docs/prometheus/latest/feature_flags/#exemplars-storage[Prometheus Exemplars]。
要启用此功能，应存在一个 javadoc:io.prometheus.metrics.tracer.common.SpanContext[] bean。
如果您使用已弃用的 Prometheus simpleclient 支持并希望启用该功能，应存在一个 javadoc:io.prometheus.client.exemplars.tracer.common.SpanContextSupplier[] bean。
如果您使用 {url-micrometer-tracing-docs}[Micrometer Tracing]，这将为您自动配置，但您也可以随时创建自己的。
请查看 https://prometheus.io/docs/prometheus/latest/feature_flags/#exemplars-storage[Prometheus 文档]，因为此功能需要在 Prometheus 端显式启用，并且仅支持使用 https://github.com/OpenObservability/OpenMetrics/blob/v1.0.0/specification/OpenMetrics.md#exemplars[OpenMetrics] 格式。

对于可能存在时间不足以被抓取的临时或批处理作业，您可以使用 https://github.com/prometheus/pushgateway[Prometheus Pushgateway] 支持将指标暴露给 Prometheus。

要启用 Prometheus Pushgateway 支持，请将以下依赖添加到您的项目：

[source,xml]
----
<dependency>
    <groupId>io.prometheus</groupId>
    <artifactId>io.prometheus:prometheus-metrics-exporter-pushgateway</artifactId>
</dependency>
----

当类路径上存在 Prometheus Pushgateway 依赖且 configprop:management.prometheus.metrics.export.pushgateway.enabled[] 属性设置为 `true` 时，将自动配置一个 javadoc:org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager[] bean。
这管理将指标推送到 Prometheus Pushgateway。

您可以通过 `management.prometheus.metrics.export.pushgateway` 下的属性调整 javadoc:org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager[]。
对于高级配置，您还可以提供自己的 javadoc:org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager[] bean。



[[actuator.metrics.export.simple]]
=== Simple

Micrometer 提供了一个简单的内存后端，如果未配置其他注册表，将自动用作回退。
这让您可以在 xref:actuator/metrics.adoc#actuator.metrics.endpoint[指标端点] 中查看收集的指标。

一旦您使用任何其他可用后端，内存后端将自行禁用。
您也可以显式禁用它：

[configprops,yaml]
----
management:
  simple:
    metrics:
      export:
        enabled: false
----



[[actuator.metrics.export.stackdriver]]
=== Stackdriver

Stackdriver 注册表定期将指标推送到 https://cloud.google.com/stackdriver/[Stackdriver]。
要将指标导出到 SaaS {url-micrometer-docs-implementations}/stackdriver[Stackdriver]，您必须提供您的 Google Cloud 项目 ID：

[configprops,yaml]
----
management:
  stackdriver:
    metrics:
      export:
        project-id: "my-project"
----

您还可以更改发送指标到 Stackdriver 的间隔：

[configprops,yaml]
----
management:
  stackdriver:
    metrics:
      export:
        step: "30s"
----



[[actuator.metrics.export.statsd]]
=== StatsD

StatsD 注册表通过 UDP 主动将指标推送到 StatsD 代理。
默认情况下，指标导出到在本地机器上运行的 {url-micrometer-docs-implementations}/statsD[StatsD] 代理。
您可以使用以下方式提供要使用的 StatsD 代理主机、端口和协议：

[configprops,yaml]
----
management:
  statsd:
    metrics:
      export:
        host: "statsd.example.com"
        port: 9125
        protocol: "udp"
----

您还可以更改使用的 StatsD 行协议（默认为 Datadog）：

[configprops,yaml]
----
management:
  statsd:
    metrics:
      export:
        flavor: "etsy"
----



[[actuator.metrics.export.wavefront]]
=== Wavefront

Wavefront 注册表定期将指标推送到 {url-micrometer-docs-implementations}/wavefront[Wavefront]。
如果您直接将指标导出到 https://www.wavefront.com/[Wavefront]，必须提供您的 API 令牌：

[configprops,yaml]
----
management:
  wavefront:
    api-token: "YOUR_API_TOKEN"
----

或者，您可以在环境中使用 Wavefront sidecar 或内部代理将指标数据转发到 Wavefront API 主机：

[configprops,yaml]
----
management:
  wavefront:
    uri: "proxy://localhost:2878"
----

NOTE: 如果您将指标发布到 Wavefront 代理（如 https://docs.wavefront.com/proxies_installing.html[Wavefront 文档] 中所述），主机必须采用 `proxy://HOST:PORT` 格式。

您还可以更改发送指标到 Wavefront 的间隔：

[configprops,yaml]
----
management:
  wavefront:
    metrics:
      export:
        step: "30s"
----



[[actuator.metrics.supported]]
== 支持的指标和仪表

Spring Boot 为多种技术提供了自动仪表注册。
在大多数情况下，默认设置提供可发布到任何支持的监控系统的合理指标。



[[actuator.metrics.supported.jvm]]
=== JVM 指标

自动配置通过使用核心 Micrometer 类启用 JVM 指标。
JVM 指标以 `jvm.` 仪表名称发布。

提供以下 JVM 指标：

* 各种内存和缓冲池详情
* 与垃圾回收相关的统计信息
* 线程利用率
* https://docs.micrometer.io/micrometer/reference/reference/jvm.html#_java_21_metrics[虚拟线程统计]（为此，`io.micrometer:micrometer-java21` 必须在类路径上）
* 加载和卸载的类数量
* JVM 版本信息
* JIT 编译时间



[[actuator.metrics.supported.system]]
=== 系统指标

自动配置通过使用核心 Micrometer 类启用系统指标。
系统指标以 `system.`、`process.` 和 `disk.` 仪表名称发布。

提供以下系统指标：

* CPU 指标
* 文件描述符指标
* 运行时间指标（应用程序运行的时间量和绝对启动时间的固定仪表）
* 可用磁盘空间



[[actuator.metrics.supported.application-startup]]
=== 应用程序启动指标

自动配置暴露应用程序启动时间指标：

* `application.started.time`：启动应用程序所需的时间。
* `application.ready.time`：应用程序准备好服务请求所需的时间。

指标通过应用程序类的完全限定名称进行标记。



[[actuator.metrics.supported.logger]]
=== 日志记录器指标

自动配置为 Logback 和 Log4J2 启用事件指标。
详情以 `log4j2.events.` 或 `logback.events.` 仪表名称发布。



[[actuator.metrics.supported.tasks]]
=== 任务执行和调度指标

自动配置启用所有可用 javadoc:org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor[] 和 javadoc:org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler[] bean 的仪表，只要底层的 javadoc:java.util.concurrent.ThreadPoolExecutor[] 可用。
指标通过执行器的名称进行标记，该名称源自 bean 名称。



[[actuator.metrics.supported.jms]]
=== JMS 指标

自动配置启用所有可用 javadoc:org.springframework.jms.core.JmsTemplate[] bean 和 javadoc:org.springframework.jms.annotation.JmsListener[format=annotation] 注解方法的仪表。
这将分别生成 `"jms.message.publish"` 和 `"jms.message.process"` 指标。
有关生成观察的更多信息，请参阅 {url spring-framework-docs}/integration/observability.html#observability.jms[Spring Framework 参考文档]。



[[actuator.metrics.supported.spring-mvc]]
=== Spring MVC 指标

自动配置启用由 Spring MVC 控制器和函数式处理程序处理的所有请求的仪表。
默认情况下，指标以名称 `http.server.requests` 生成。
您可以通过设置 configprop:management.observations.http.server.requests.name[] 属性自定义名称。

有关生成观察的更多信息，请参阅 {url spring-framework-docs}/integration/observability.html#observability.http-server.servlet[Spring Framework 参考文档]。

要添加默认标签，提供一个扩展自 `org.springframework.http.server.observation` 包中 javadoc:org.springframework.http.server.observation.DefaultServerRequestObservationConvention[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。
要替换默认标签，提供一个实现 javadoc:org.springframework.http.server.observation.ServerRequestObservationConvention[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。

TIP: 在某些情况下，Web 控制器中处理的异常不会记录为请求指标标签。
应用程序可以通过 xref:web/servlet.adoc#web.servlet.spring-mvc.error-handling[将处理的异常设置为请求属性] 来选择记录异常。

默认情况下，所有请求都会被处理。
要自定义过滤器，提供一个实现 `FilterRegistrationBean<ServerHttpObservationFilter>` 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。



[[actuator.metrics.supported.spring-webflux]]
=== Spring WebFlux 指标

自动配置启用由 Spring WebFlux 控制器和函数式处理程序处理的所有请求的仪表。
默认情况下，指标以名称 `http.server.requests` 生成。
您可以通过设置 configprop:management.observations.http.server.requests.name[] 属性自定义名称。

有关生成观察的更多信息，请参阅 {url spring-framework-docs}/integration/observability.html#observability.http-server.reactive[Spring Framework 参考文档]。

要添加默认标签，提供一个扩展自 `org.springframework.http.server.reactive.observation` 包中 javadoc:org.springframework.http.server.reactive.observation.DefaultServerRequestObservationConvention[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。
要替换默认标签，提供一个实现 javadoc:org.springframework.http.server.reactive.observation.ServerRequestObservationConvention[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。

TIP: 在某些情况下，控制器和处理函数中处理的异常不会记录为请求指标标签。
应用程序可以通过 xref:web/reactive.adoc#web.reactive.webflux.error-handling[将处理的异常设置为请求属性] 来选择记录异常。



[[actuator.metrics.supported.jersey]]
=== Jersey 服务器指标

自动配置启用由 Jersey JAX-RS 实现处理的所有请求的仪表。
默认情况下，指标以名称 `http.server.requests` 生成。
您可以通过设置 configprop:management.observations.http.server.requests.name[] 属性自定义名称。

默认情况下，Jersey 服务器指标带有以下信息标签：

|===
| Tag | Description

| `exception`
| 处理请求时抛出的任何异常的简单类名称。

| `method`
| 请求的方法（例如，`GET` 或 `POST`）

| `outcome`
| 根据响应状态码的请求结果。
  1xx 为 `INFORMATIONAL`，2xx 为 `SUCCESS`，3xx 为 `REDIRECTION`，4xx 为 `CLIENT_ERROR`，5xx 为 `SERVER_ERROR`

| `status`
| 响应的 HTTP 状态码（例如，`200` 或 `500`）

| `uri`
| 请求的 URI 模板，在变量替换之前（例如，`/api/person/\{id}`）
|===

要自定义标签，提供一个实现 javadoc:io.micrometer.core.instrument.binder.jersey.server.JerseyObservationConvention[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。



[[actuator.metrics.supported.ssl]]
=== SSL Bundle 指标

Spring Boot Actuator 发布关于 SSL bundle 的到期指标。
指标 `ssl.chain.expiry` 以秒为单位测量每个证书链的到期日期。
如果链已过期，此数字将为负值。
此指标带有以下信息标签：

|===
| Tag | Description

| `bundle`
| 包含证书链的 bundle 名称

| `certificate`
| 链中最快到期的证书的序列号（以十六进制格式）

| `chain`
| 证书链的名称。
|===



[[actuator.metrics.supported.http-clients]]
=== HTTP 客户端指标

Spring Boot Actuator 管理 javadoc:org.springframework.web.client.RestTemplate[]、javadoc:org.springframework.web.reactive.function.client.WebClient[] 和 javadoc:org.springframework.web.client.RestClient[] 的仪表。
为此，您必须注入自动配置的构建器并使用它创建实例：

* javadoc:org.springframework.boot.web.client.RestTemplateBuilder[] 用于 javadoc:org.springframework.web.client.RestTemplate[]
* javadoc:org.springframework.web.reactive.function.client.WebClient$Builder[] 用于 javadoc:org.springframework.web.reactive.function.client.WebClient[]
* javadoc:org.springframework.web.client.RestClient$Builder[] 用于 javadoc:org.springframework.web.client.RestClient[]

您还可以手动应用负责此仪表的自定义器，即 javadoc:org.springframework.boot.actuate.metrics.web.client.ObservationRestTemplateCustomizer[]、javadoc:org.springframework.boot.actuate.metrics.web.reactive.client.ObservationWebClientCustomizer[] 和 javadoc:org.springframework.boot.actuate.metrics.web.client.ObservationRestClientCustomizer[]。

默认情况下，指标以名称 `http.client.requests` 生成。
您可以通过设置 configprop:management.observations.http.client.requests.name[] 属性自定义名称。

有关生成观察的更多信息，请参阅 {url spring-framework-docs}/integration/observability.html#observability.http-client[Spring Framework 参考文档]。

要在使用 javadoc:org.springframework.web.client.RestTemplate[] 或 javadoc:org.springframework.web.client.RestClient[] 时自定义标签，提供一个实现 `org.springframework.http.client.observation` 包中 javadoc:org.springframework.http.client.observation.ClientRequestObservationConvention[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。
要在使用 javadoc:org.springframework.web.reactive.function.client.WebClient[] 时自定义标签，提供一个实现 `org.springframework.web.reactive.function.client` 包中 javadoc:org.springframework.web.reactive.function.client.ClientRequestObservationConvention[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。



[[actuator.metrics.supported.tomcat]]
=== Tomcat 指标

仅当启用了 MBean javadoc:org.apache.tomcat.util.modeler.Registry[] 时，自动配置才会启用 Tomcat 的仪表。
默认情况下，MBean 注册表是禁用的，但您可以通过将 configprop:server.tomcat.mbeanregistry.enabled[] 设置为 `true` 来启用它。

Tomcat 指标以 `tomcat.` 仪表名称发布。



[[actuator.metrics.supported.cache]]
=== 缓存指标

自动配置在启动时启用所有可用 javadoc:org.springframework.cache.Cache[] 实例的仪表，指标前缀为 `cache`。
缓存仪表为基本指标集标准化。
还提供特定于缓存的额外指标。

支持以下缓存库：

* Cache2k
* Caffeine
* Hazelcast
* 任何符合 JCache (JSR-107) 的实现
* Redis

WARNING: 必须启用指标，自动配置才会拾取它们。
有关更多详细信息，请参阅您使用的缓存库的文档。

指标通过缓存名称和 javadoc:org.springframework.cache.CacheManager[] 的名称进行标记，后者源自 bean 名称。

NOTE: 仅在启动时配置的缓存绑定到注册表。
对于未在缓存配置中定义的缓存，例如动态创建或在启动阶段后以编程方式创建的缓存，需要显式注册。
提供了一个 javadoc:org.springframework.boot.actuate.metrics.cache.CacheMetricsRegistrar[] bean 以简化此过程。



[[actuator.metrics.supported.spring-batch]]
=== Spring Batch 指标

请参阅 {url spring-batch-docs}/monitoring-and-metrics.html[Spring Batch 参考文档]。



[[actuator.metrics.supported.spring-graphql]]
=== Spring GraphQL 指标

请参阅 {url spring-graphql-docs}/observability.html[Spring GraphQL 参考文档]。



[[actuator.metrics.supported.jdbc]]
=== 数据源指标

自动配置启用所有可用 javadoc:javax.sql.DataSource[] 对象的仪表，指标前缀为 `jdbc.connections`。
数据源仪表生成表示池中当前活跃、空闲、最大允许和最小允许连接数的仪表。

指标还通过基于 bean 名称计算的 javadoc:javax.sql.DataSource[] 名称进行标记。

TIP: 默认情况下，Spring Boot 为所有支持的数据源提供元数据。
如果您喜爱的数据源不受支持，您可以添加额外的 javadoc:org.springframework.boot.jdbc.metadata.DataSourcePoolMetadataProvider[] bean。
有关示例，请参阅 javadoc:org.springframework.boot.autoconfigure.jdbc.metadata.DataSourcePoolMetadataProvidersConfiguration[]。

此外，特定于 Hikari 的指标以 `hikaricp` 前缀暴露。
每个指标通过池的名称进行标记（您可以通过 `spring.datasource.name` 控制）。



[[actuator.metrics.supported.hibernate]]
=== Hibernate 指标

如果 `org.hibernate.orm:hibernate-micrometer` 在类路径上，所有启用了统计功能的可用 Hibernate javadoc:jakarta.persistence.EntityManagerFactory[] 实例都将使用名为 `hibernate` 的指标进行仪表。

指标还通过 javadoc:jakarta.persistence.EntityManagerFactory[] 的名称进行标记，该名称源自 bean 名称。

要启用统计，必须将标准 JPA 属性 `hibernate.generate_statistics` 设置为 `true`。
您可以在自动配置的 javadoc:jakarta.persistence.EntityManagerFactory[] 上启用它：

[configprops,yaml]
----
spring:
  jpa:
    properties:
      "[hibernate.generate_statistics]": true
----



[[actuator.metrics.supported.spring-data-repository]]
=== Spring Data 存储库指标

自动配置启用所有 Spring Data javadoc:org.springframework.data.repository.Repository[] 方法调用的仪表。
默认情况下，指标以名称 `spring.data.repository.invocations` 生成。
您可以通过设置 configprop:management.metrics.data.repository.metric-name[] 属性自定义名称。

来自 `io.micrometer.core.annotation` 包的 javadoc:io.micrometer.core.annotation.Timed[format=annotation] 注解在 javadoc:org.springframework.data.repository.Repository[] 接口和方法上受支持。
如果您不想为所有 javadoc:org.springframework.data.repository.Repository[] 调用记录指标，可以将 configprop:management.metrics.data.repository.autotime.enabled[] 设置为 `false`，并仅使用 javadoc:io.micrometer.core.annotation.Timed[format=annotation] 注解。

NOTE: 带有 `longTask = true` 的 javadoc:io.micrometer.core.annotation.Timed[format=annotation] 注解为方法启用长任务计时器。
长任务计时器需要单独的指标名称，并且可以与短任务计时器堆叠。

默认情况下，存储库调用相关指标带有以下信息标签：

|===
| Tag | Description

| `repository`
| 源 javadoc:org.springframework.data.repository.Repository[] 的简单类名称。

| `method`
| 被调用的 javadoc:org.springframework.data.repository.Repository[] 方法的名称。

| `state`
| 结果状态（`SUCCESS`、`ERROR`、`CANCELED` 或 `RUNNING`）。

| `exception`
| 调用中抛出的任何异常的简单类名称。
|===

要替换默认标签，提供一个实现 javadoc:org.springframework.boot.actuate.metrics.data.RepositoryTagsProvider[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。



[[actuator.metrics.supported.rabbitmq]]
=== RabbitMQ 指标

自动配置启用所有可用 RabbitMQ 连接工厂的仪表，指标名称为 `rabbitmq`。



[[actuator.metrics.supported.spring-integration]]
=== Spring Integration 指标

只要有 javadoc:io.micrometer.core.instrument.MeterRegistry[] bean 可用，Spring Integration 就会自动提供 {url spring-integration-docs}/metrics.html#micrometer-integration[Micrometer 支持]。
指标以 `spring.integration.` 仪表名称发布。



[[actuator.metrics.supported.kafka]]
=== Kafka 指标

自动配置为自动配置的消费者工厂和生产者工厂分别注册 javadoc:org.springframework.kafka.core.MicrometerConsumerListener[] 和 javadoc:org.springframework.kafka.core.MicrometerProducerListener[]。
它还为 javadoc:org.springframework.kafka.config.StreamsBuilderFactoryBean[] 注册 javadoc:org.springframework.kafka.streams.KafkaStreamsMicrometerListener[]。
有关更多详细信息，请参阅 Spring Kafka 文档的 {url spring-kafka-docs}/kafka/micrometer.html#micrometer-native[Micrometer 原生指标] 部分。



[[actuator.metrics.supported.mongodb]]
=== MongoDB 指标

本节简要描述 MongoDB 可用的指标。



[[actuator.metrics.supported.mongodb.command]]
==== MongoDB 命令指标

自动配置为自动配置的 javadoc:{url-mongodb-driver-sync-javadoc}/com.mongodb.client.MongoClient[] 注册一个 javadoc:io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener[]。

为底层 MongoDB 驱动程序发出的每个命令创建一个名为 `mongodb.driver.commands` 的计时器指标。
默认情况下，每个指标带有以下信息标签：
|===
| Tag | Description

| `command`
| 发出的命令名称。

| `cluster.id`
| 命令发送到的集群的标识符。

| `server.address`
| 命令发送到的服务器地址。

| `status`
| 命令的结果（`SUCCESS` 或 `FAILED`）。
|===

要替换默认指标标签，定义一个 javadoc:io.micrometer.core.instrument.binder.mongodb.MongoCommandTagsProvider[] bean，如下例所示：

include-code::MyCommandTagsProviderConfiguration[]

要禁用自动配置的命令指标，请设置以下属性：

[configprops,yaml]
----
management:
  metrics:
    mongo:
      command:
        enabled: false
----



[[actuator.metrics.supported.mongodb.connection-pool]]
==== MongoDB 连接池指标

自动配置为自动配置的 javadoc:{url-mongodb-driver-sync-javadoc}/com.mongodb.client.MongoClient[] 注册一个 javadoc:io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener[]。

为连接池创建以下仪表指标：

* `mongodb.driver.pool.size` 报告连接池的当前大小，包括空闲和使用中的成员。
* `mongodb.driver.pool.checkedout` 报告当前正在使用的连接数。
* `mongodb.driver.pool.waitqueuesize` 报告从池中获取连接的等待队列的当前大小。

默认情况下，每个指标带有以下信息标签：
|===
| Tag | Description

| `cluster.id`
| 连接池对应的集群的标识符。

| `server.address`
| 连接池对应的服务器地址。
|===

要替换默认指标标签，定义一个 javadoc:io.micrometer.core.instrument.binder.mongodb.MongoConnectionPoolTagsProvider[] bean：

include-code::MyConnectionPoolTagsProviderConfiguration[]

要禁用自动配置的连接池指标，请设置以下属性：

[configprops,yaml]
----
management:
  metrics:
    mongo:
      connectionpool:
        enabled: false
----



[[actuator.metrics.supported.jetty]]
=== Jetty 指标

自动配置通过使用 Micrometer 的 javadoc:io.micrometer.core.instrument.binder.jetty.JettyServerThreadPoolMetrics[] 绑定 Jetty 的 javadoc:org.eclipse.jetty.util.thread.ThreadPool[] 指标。
通过使用 Micrometer 的 javadoc:io.micrometer.core.instrument.binder.jetty.JettyConnectionMetrics[] 绑定 Jetty 的 javadoc:org.eclipse.jetty.server.Connector[] 实例的指标，当 configprop:server.ssl.enabled[] 设置为 `true` 时，还使用 Micrometer 的 javadoc:io.micrometer.core.instrument.binder.jetty.JettySslHandshakeMetrics[]。



[[actuator.metrics.supported.redis]]
=== Redis 指标

自动配置为自动配置的 javadoc:org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory[] 注册一个 javadoc:io.lettuce.core.metrics.MicrometerCommandLatencyRecorder[]。
有关更多详细信息，请参阅 Lettuce 文档的 {url-lettuce-docs}#command.latency.metrics.micrometer[Micrometer 指标部分]。



[[actuator.metrics.registering-custom]]
== 注册自定义指标

要注册自定义指标，将 javadoc:io.micrometer.core.instrument.MeterRegistry[] 注入您的组件：

include-code::MyBean[]

如果您的指标依赖其他 bean，我们建议使用 javadoc:io.micrometer.core.instrument.binder.MeterBinder[] 注册它们：

include-code::MyMeterBinderConfiguration[]

使用 javadoc:io.micrometer.core.instrument.binder.MeterBinder[] 可确保设置正确的依赖关系，并在检索指标值时 bean 可用。
如果您发现自己在多个组件或应用程序中反复仪表一组指标，javadoc:io.micrometer.core.instrument.binder.MeterBinder[] 实现也很有用。

NOTE: 默认情况下，来自所有 javadoc:io.micrometer.core.instrument.binder.MeterBinder[] bean 的指标会自动绑定到 Spring 管理的 javadoc:io.micrometer.core.instrument.MeterRegistry[]。



[[actuator.metrics.customizing]]
== 自定义单个指标

如果您需要对特定 javadoc:io.micrometer.core.instrument.Meter[] 实例应用自定义，可以使用 javadoc:io.micrometer.core.instrument.config.MeterFilter[] 接口。

例如，如果您想将所有以 `com.example` 开头的仪表 ID 的 `mytag.region` 标签重命名为 `mytag.area`，可以这样做：

include-code::MyMetricsFilterConfiguration[]

NOTE: 默认情况下，所有 javadoc:io.micrometer.core.instrument.config.MeterFilter[] bean 会自动绑定到 Spring 管理的 javadoc:io.micrometer.core.instrument.MeterRegistry[]。
请确保使用 Spring 管理的 javadoc:io.micrometer.core.instrument.MeterRegistry[] 注册您的指标，而不是 javadoc:io.micrometer.core.instrument.Metrics[] 上的任何静态方法。
这些方法使用非 Spring 管理的全局注册表。



[[actuator.metrics.customizing.common-tags]]
=== 通用标签

通用标签通常用于对运行环境进行维度下钻，例如主机、实例、区域、堆栈等。
通用标签应用于所有仪表，可以按以下示例配置：

[configprops,yaml]
----
management:
  metrics:
    tags:
      region: "us-east-1"
      stack: "prod"
----

上述示例为所有仪表添加 `region` 和 `stack` 标签，值分别为 `us-east-1` 和 `prod`。

NOTE: 如果您使用 Graphite，通用标签的顺序很重要。
由于这种方法无法保证通用标签的顺序，建议 Graphite 用户定义一个自定义 javadoc:io.micrometer.core.instrument.config.MeterFilter[]。



[[actuator.metrics.customizing.per-meter-properties]]
=== 每仪表属性

除了 javadoc:io.micrometer.core.instrument.config.MeterFilter[] bean，您还可以使用属性对每仪表基础进行有限的自定义。
每仪表自定义通过 Spring Boot 的 javadoc:org.springframework.boot.actuate.autoconfigure.metrics.PropertiesMeterFilter[] 应用于以给定名称开头的任何仪表 ID。
以下示例过滤掉以 `example.remote` 开头的任何仪表的 ID。

[configprops,yaml]
----
management:
  metrics:
    enable:
      example:
        remote: false
----

以下属性允许每仪表自定义：

.每仪表自定义
|===
| Property | Description

| configprop:management.metrics.enable[]
| 是否接受具有特定 ID 的仪表。
  未接受的仪表将从 javadoc:io.micrometer.core.instrument.MeterRegistry[] 中过滤掉。

| configprop:management.metrics.distribution.percentiles-histogram[]
| 是否发布适合计算可聚合（跨维度）百分位数近似值的直方图。

| configprop:management.metrics.distribution.minimum-expected-value[], configprop:management.metrics.distribution.maximum-expected-value[]
| 通过限制预期值的范围发布较少的直方图桶。

| configprop:management.metrics.distribution.percentiles[] 
| 在您的应用中发布计算的百分位数值。

| configprop:management.metrics.distribution.expiry[], configprop:management.metrics.distribution.buffer-length[]
| 通过在配置的可过期时间后旋转的环形缓冲区中累积样本，赋予近期样本更高的权重，配置缓冲区长度。


| configprop:management.metrics.distribution.slo[]
| 发布由您的服务级别目标定义的累积直方图桶。
|===

有关 `percentiles-histogram`、`percentiles` 和 `slo` 的概念背景的更多详细信息，请参见 Micrometer 文档的 {url-micrometer-docs-concepts}/histogram-quantiles.html[Histograms and percentiles] 部分。



[[actuator.metrics.endpoint]]
== 指标端点

Spring Boot 提供了一个 `metrics` 端点，可用于诊断检查应用程序收集的指标。
该端点默认不可用，必须暴露。
有关更多详细信息，请参见 xref:actuator/endpoints.adoc#actuator.endpoints.exposing[暴露端点]。

导航到 `/actuator/metrics` 显示可用的仪表名称列表。
您可以通过提供仪表名称作为选择器来深入查看特定仪表的信息，例如 `/actuator/metrics/jvm.memory.max`。

[TIP]
====
您在此处使用的名称应与代码中使用的名称匹配，而不是发送到监控系统后因命名约定规范化后的名称。
换句话说，如果 `jvm.memory.max` 在 Prometheus 中因其下划线命名约定而显示为 `jvm_memory_max`，您在检查 `metrics` 端点的仪表时仍应使用 `jvm.memory.max` 作为选择器。
====

您还可以在 URL 末尾添加任意数量的 `tag=KEY:VALUE` 查询参数，以在仪表上进行维度下钻，例如 `/actuator/metrics/jvm.memory.max?tag=area:nonheap`。

[TIP]
====
报告的测量值是所有匹配仪表名称和已应用的任何标签的仪表统计数据的 _总和_。
在上述示例中，返回的 `Value` 统计数据是堆的 `"Code Cache"`、`"Compressed Class Space"` 和 `"Metaspace"` 区域的最大内存占用量之和。
如果您只想查看 `"Metaspace"` 的最大大小，可以添加额外的 `tag=id:Metaspace`，即 `/actuator/metrics/jvm.memory.max?tag=area:nonheap&tag=id:Metaspace`。
====



[[actuator.metrics.micrometer-observation]]
== 与 Micrometer Observation 集成

javadoc:io.micrometer.core.instrument.observation.DefaultMeterObservationHandler[] 会在 javadoc:io.micrometer.observation.ObservationRegistry[] 上自动注册，为每个完成的观察创建指标。
