[[actuator.monitoring]]
= 通过 HTTP 进行监控和管理

如果你正在开发 Web 应用程序，Spring Boot Actuator 会自动配置所有已启用的端点，使其通过 HTTP 暴露。
默认约定是使用端点的 `id` 加上 `/actuator` 前缀作为 URL 路径。
例如，`health` 端点被暴露为 `/actuator/health`。

TIP: Actuator 原生支持 Spring MVC、Spring WebFlux 和 Jersey。
如果同时存在 Jersey 和 Spring MVC，将使用 Spring MVC。

NOTE: 为了获得 xref:api:rest/actuator/index.adoc[API 文档]中记录的正确的 JSON 响应，Jackson 是一个必需的依赖项。



[[actuator.monitoring.customizing-management-server-context-path]]
== 自定义管理端点路径

有时，自定义管理端点的前缀很有用。
例如，你的应用程序可能已经将 `/actuator` 用于其他目的。
你可以使用 configprop:management.endpoints.web.base-path[] 属性来更改管理端点的前缀，如下例所示：

[configprops,yaml]
----
management:
  endpoints:
    web:
      base-path: "/manage"
----

前面的 `application.properties` 示例将端点从 `/actuator/\{id}` 更改为 `/manage/\{id}`（例如，`/manage/info`）。

NOTE: 除非管理端口已配置为 xref:actuator/monitoring.adoc#actuator.monitoring.customizing-management-server-port[使用不同的 HTTP 端口暴露端点]，否则 `management.endpoints.web.base-path` 相对于 `server.servlet.context-path`（对于 servlet Web 应用程序）或 `spring.webflux.base-path`（对于响应式 Web 应用程序）。
如果配置了 `management.server.port`，则 `management.endpoints.web.base-path` 相对于 `management.server.base-path`。

如果你想将端点映射到不同的路径，可以使用 configprop:management.endpoints.web.path-mapping[] 属性。

以下示例将 `/actuator/health` 重新映射为 `/healthcheck`：

[configprops,yaml]
----
management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "healthcheck"
----



[[actuator.monitoring.customizing-management-server-port]]
== 自定义管理服务器端口

使用默认 HTTP 端口暴露管理端点是基于云的部署的明智选择。
但是，如果你的应用程序在数据中心内运行，你可能更希望使用不同的 HTTP 端口来暴露端点。

你可以设置 configprop:management.server.port[] 属性来更改 HTTP 端口，如下例所示：

[configprops,yaml]
----
management:
  server:
    port: 8081
----

NOTE: 在 Cloud Foundry 上，默认情况下，应用程序仅在端口 8080 上接收 HTTP 和 TCP 路由的请求。
如果你想在 Cloud Foundry 上使用自定义管理端口，需要显式设置应用程序的路由来将流量转发到自定义端口。



[[actuator.monitoring.management-specific-ssl]]
== 配置管理特定的 SSL

当配置为使用自定义端口时，你还可以使用各种 `management.server.ssl.*` 属性为管理服务器配置自己的 SSL。
例如，这样做可以让管理服务器通过 HTTP 可用，而主应用程序使用 HTTPS，如下面的属性设置所示：

[configprops,yaml]
----
server:
  port: 8443
  ssl:
    enabled: true
    key-store: "classpath:store.jks"
    key-password: "secret"
management:
  server:
    port: 8080
    ssl:
      enabled: false
----

或者，主服务器和管理服务器都可以使用 SSL，但使用不同的密钥库，如下所示：

[configprops,yaml]
----
server:
  port: 8443
  ssl:
    enabled: true
    key-store: "classpath:main.jks"
    key-password: "secret"
management:
  server:
    port: 8080
    ssl:
      enabled: true
      key-store: "classpath:management.jks"
      key-password: "secret"
----



[[actuator.monitoring.customizing-management-server-address]]
== 自定义管理服务器地址

你可以通过设置 configprop:management.server.address[] 属性来自定义管理端点可用的地址。
如果你只想监听内部或运维网络，或者只想监听来自 `localhost` 的连接，这将很有用。

NOTE: 只有当端口与主服务器端口不同时，你才能监听不同的地址。

以下 `application.properties` 示例不允许远程管理连接：

[configprops,yaml]
----
management:
  server:
    port: 8081
    address: "127.0.0.1"
----



[[actuator.monitoring.disabling-http-endpoints]]
== 禁用 HTTP 端点

如果你不想通过 HTTP 暴露端点，可以将管理端口设置为 `-1`，如下例所示：

[configprops,yaml]
----
management:
  server:
    port: -1
----

你也可以使用 configprop:management.endpoints.web.exposure.exclude[] 属性来实现这一点，如下例所示：

[configprops,yaml]
----
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
----
