[[howto.deployment.cloud]]
= 部署到云

Spring Boot 的可执行 jar 已经为大多数流行的云 PaaS（平台即服务）提供商准备好了。这些提供商通常要求您“自带容器”。他们管理应用程序进程（而不是特定的 Java 应用程序），因此他们需要一个中间层来将您的应用程序适配为云的运行进程概念。

两个流行的云提供商，Heroku 和 Cloud Foundry，采用“构建包”方法。构建包将您的已部署代码包装在启动应用程序所需的任何内容中。它可能是一个 JDK 和一个对 `java` 的调用，一个嵌入式 Web 服务器，或者一个完整的应用程序服务器。构建包是可插拔的，但理想情况下，您应该尽量减少对其的自定义。这减少了不在您控制范围内的功能的占用空间。它最小化了开发和生产环境之间的差异。

理想情况下，您的应用程序（如 Spring Boot 可执行 jar）已包含运行所需的一切。

在本节中，我们将探讨在“入门”部分开发的应用程序在云中运行所需的条件。

[[howto.deployment.cloud.cloud-foundry]]
== Cloud Foundry

Cloud Foundry 提供默认的构建包，如果没有指定其他构建包，则会使用这些默认构建包。Cloud Foundry 的 Java 构建包对 Spring 应用程序（包括 Spring Boot）提供了出色的支持。您可以部署独立的可执行 jar 应用程序以及传统的 `.war` 打包应用程序。

一旦您构建了应用程序（例如，使用 `mvn clean package`），并安装了 `cf` 命令行工具，您可以使用 `cf push` 命令部署应用程序，替换为已编译的 `.jar` 的路径。在推送应用程序之前，请确保已使用 `cf` 命令行客户端登录。以下行显示了使用 `cf push` 命令部署应用程序：

[source,shell]
----
$ cf push acloudyspringtime -p target/demo-0.0.1-SNAPSHOT.jar
----

注意：在前面的示例中，我们将 `acloudyspringtime` 替换为您给 `cf` 的应用程序名称。

有关更多选项，请参阅 `cf push` 文档。如果在同一目录中存在 Cloud Foundry 的 `manifest.yml` 文件，则会考虑该文件。

此时，`cf` 开始上传您的应用程序，产生类似于以下示例的输出：

[source,subs="verbatim,quotes"]
----
上传 acloudyspringtime... *OK*
准备启动 acloudyspringtime... *OK*
-----> 下载应用程序包 (*8.9M*)
-----> Java 构建包版本：v3.12（离线）| https://github.com/cloudfoundry/java-buildpack.git#6f25b7e
-----> 下载 Open Jdk JRE
       将 Open Jdk JRE 展开到 .java-buildpack/open_jdk_jre (1.6s)
-----> 从 https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz 下载 Open JDK Like Memory Calculator 2.0.2_RELEASE（在缓存中找到）
       内存设置：-Xss349K -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xms681574K -XX:MetaspaceSize=104857K
-----> 从 https://java-buildpack.cloudfoundry.org/container-certificate-trust-store/container-certificate-trust-store-1.0.0_RELEASE.jar 下载容器证书信任存储 1.0.0_RELEASE（在缓存中找到）
       将证书添加到 .java-buildpack/container_certificate_trust_store/truststore.jks (0.6s)
-----> 从 https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar 下载 Spring 自动重新配置 1.10.0_RELEASE（在缓存中找到）
检查应用程序 'acloudyspringtime' 的状态...
  0 个实例正在运行（1 个正在启动）
  ...
  0 个实例正在运行（1 个正在启动）
  ...
  0 个实例正在运行（1 个正在启动）
  ...
  1 个实例正在运行（1 个正在运行）

应用程序已启动
----

恭喜！应用程序现已上线！

一旦您的应用程序上线，您可以使用 `cf apps` 命令验证已部署应用程序的状态，如以下示例所示：

[source,shell]
----
$ cf apps
获取应用程序中 ...
OK

名称                 请求状态   实例   内存   磁盘   urls
...
acloudyspringtime    已启动           1/1         512M     1G     acloudyspringtime.cfapps.io
...
----

一旦 Cloud Foundry 确认您的应用程序已部署，您应该能够在给定的 URI 找到应用程序。在前面的示例中，您可以在 `\https://acloudyspringtime.cfapps.io/` 找到它。

[[howto.deployment.cloud.cloud-foundry.binding-to-services]]
=== 绑定到服务

默认情况下，关于运行应用程序的元数据以及服务连接信息作为环境变量（例如：`$VCAP_SERVICES`）暴露给应用程序。此架构决策是由于 Cloud Foundry 的多语言（任何语言和平台都可以作为构建包支持）性质。进程范围的环境变量与语言无关。

环境变量并不总是最简单的 API，因此 Spring Boot 自动提取它们并将数据展平为可以通过 Spring 的 `org.springframework.core.env.Environment` 抽象访问的属性，如以下示例所示：

include-code::MyBean[]

所有 Cloud Foundry 属性都以 `vcap` 为前缀。您可以使用 `vcap` 属性访问应用程序信息（例如应用程序的公共 URL）和服务信息（例如数据库凭据）。有关完整详细信息，请参阅 `org.springframework.boot.cloud.CloudFoundryVcapEnvironmentPostProcessor` API 文档。

提示：`Java CFEnv` 项目更适合配置数据源等任务。

[[howto.deployment.cloud.kubernetes]]
== Kubernetes

Spring Boot 通过检查环境中的 `"*_SERVICE_HOST"` 和 `"*_SERVICE_PORT"` 变量自动检测 Kubernetes 部署环境。您可以使用 `spring.main.cloud-platform` 配置属性覆盖此检测。

Spring Boot 帮助您管理应用程序的状态，并通过使用 Actuator 的 HTTP Kubernetes 探针导出它。

[[howto.deployment.cloud.kubernetes.container-lifecycle]]
=== Kubernetes 容器生命周期

当 Kubernetes 删除应用程序实例时，关闭过程涉及多个子系统并发：关闭钩子、注销服务、从负载均衡器中移除实例...由于这种关闭处理是并行发生的（并且由于分布式系统的性质），在此期间可能会将流量路由到已开始关闭处理的 pod。

您可以在 preStop 处理程序中配置睡眠执行，以避免请求被路由到已开始关闭的 pod。此睡眠时间应足够长，以便新请求停止路由到 pod，其持续时间将因部署而异。

如果您使用的是 Kubernetes 1.32 或更高版本，可以通过在 pod 的配置文件中使用 PodSpec 配置 preStop 处理程序，如下所示：

[source,yaml]
----
spec:
  containers:
  - name: "example-container"
    image: "example-image"
    lifecycle:
      preStop:
        sleep:
          seconds: 10
----

如果您尚未使用 Kubernetes 1.32，可以使用 `exec` 命令调用 `sleep`。

[source,yaml]
----
spec:
  containers:
  - name: "example-container"
    image: "example-image"
    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c", "sleep 10"]
----

注意：容器需要有一个 shell 才能工作。

一旦 pre-stop 钩子完成，SIGTERM 将被发送到容器，优雅关闭将开始，允许任何剩余的正在进行的请求完成。

注意：当 Kubernetes 向 pod 发送 SIGTERM 信号时，它会等待一个称为终止宽限期的指定时间（默认值为 30 秒）。如果容器在宽限期后仍在运行，则会发送 SIGKILL 信号并强制移除。如果 pod 关闭时间超过 30 秒，这可能是因为您增加了 `spring.lifecycle.timeout-per-shutdown-phase`，请确保通过在 Pod YAML 中设置 `terminationGracePeriodSeconds` 选项来增加终止宽限期。

[[howto.deployment.cloud.heroku]]
== Heroku

Heroku 是另一个流行的 PaaS 平台。要自定义 Heroku 构建，您需要提供一个 `Procfile`，其中提供了部署应用程序所需的咒语。Heroku 为 Java 应用程序分配一个 `port`，然后确保路由到外部 URI。

您必须配置应用程序以监听正确的端口。以下示例显示了我们入门 REST 应用程序的 `Procfile`：

[source]
----
web: java -Dserver.port=$PORT -jar target/demo-0.0.1-SNAPSHOT.jar
----

Spring Boot 使 `-D` 参数可作为属性从 Spring 的 `org.springframework.core.env.Environment` 实例访问。`server.port` 配置属性被传递给嵌入式 Tomcat、Jetty 或 Undertow 实例，然后在启动时使用该端口。`$PORT` 环境变量由 Heroku PaaS 分配给我们。

这应该是您所需的一切。Heroku 部署的最常见工作流程是将代码 `git push` 到生产环境，如以下示例所示：

[source,shell]
----
$ git push heroku main
----

这将导致以下结果：

[source,subs="verbatim,quotes"]
----
初始化存储库，*完成*。
计数对象：95，*完成*。
使用最多 8 个线程进行增量压缩。
压缩对象：100% (78/78)，*完成*。
Writing objects: 100% (95/95), 8.66 MiB | 606.00 KiB/s, *done*.
Total 95 (delta 31), reused 0 (delta 0)

-----> Java app detected
-----> Installing OpenJDK... *done*
-----> Installing Maven... *done*
-----> Installing settings.xml... *done*
-----> Executing: mvn -B -DskipTests=true clean install

       [INFO] Scanning for projects...
       Downloading: https://repo.spring.io/...
       Downloaded: https://repo.spring.io/... (818 B at 1.8 KB/sec)
		....
       Downloaded: https://s3pository.heroku.com/jvm/... (152 KB at 595.3 KB/sec)
       [INFO] Installing /tmp/build_0c35a5d2-a067-4abc-a232-14b1fb7a8229/target/...
       [INFO] Installing /tmp/build_0c35a5d2-a067-4abc-a232-14b1fb7a8229/pom.xml ...
       [INFO] ------------------------------------------------------------------------
       [INFO] *BUILD SUCCESS*
       [INFO] ------------------------------------------------------------------------
       [INFO] Total time: 59.358s
       [INFO] Finished at: Fri Mar 07 07:28:25 UTC 2014
       [INFO] Final Memory: 20M/493M
       [INFO] ------------------------------------------------------------------------

-----> Discovering process types
       Procfile declares types -> *web*

-----> Compressing... *done*, 70.4MB
-----> Launching... *done*, v6
       https://agile-sierra-1405.herokuapp.com/ *deployed to Heroku*

To git@heroku.com:agile-sierra-1405.git
 * [new branch]      main -> main
----

Your application should now be up and running on Heroku.
For more details, see https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku[Deploying Spring Boot Applications to Heroku].



[[howto.deployment.cloud.openshift]]
== OpenShift

https://www.openshift.com/[OpenShift] has many resources describing how to deploy Spring Boot applications, including:

* https://blog.openshift.com/using-openshift-enterprise-grade-spring-boot-deployments/[Using the S2I builder]
* https://blog.openshift.com/using-spring-boot-on-openshift/[Running as a traditional web application on Wildfly]
* https://blog.openshift.com/openshift-commons-briefing-96-cloud-native-applications-spring-rhoar/[OpenShift Commons Briefing]



[[howto.deployment.cloud.aws]]
== Amazon Web Services (AWS)

Amazon Web Services offers multiple ways to install Spring Boot-based applications, either as traditional web applications (war) or as executable jar files with an embedded web server.
The options include:

* AWS Elastic Beanstalk
* AWS Code Deploy
* AWS OPS Works
* AWS Cloud Formation
* AWS Container Registry

Each has different features and pricing models.
In this document, we describe to approach using AWS Elastic Beanstalk.



[[howto.deployment.cloud.aws.beanstalk]]
=== AWS Elastic Beanstalk

As described in the official https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_Java.html[Elastic Beanstalk Java guide], there are two main options to deploy a Java application.
You can either use the "`Tomcat Platform`" or the "`Java SE platform`".



[[howto.deployment.cloud.aws.beanstalk.tomcat-platform]]
==== Using the Tomcat Platform

This option applies to Spring Boot projects that produce a war file.
No special configuration is required.
You need only follow the official guide.



[[howto.deployment.cloud.aws.beanstalk.java-se-platform]]
==== Using the Java SE Platform

This option applies to Spring Boot projects that produce a jar file and run an embedded web container.
Elastic Beanstalk environments run an nginx instance on port 80 to proxy the actual application, running on port 5000.
To configure it, add the following line to your `application.properties` file:

[configprops,yaml]
----
server:
  port: 5000
----


[TIP]
.Upload binaries instead of sources
====
By default, Elastic Beanstalk uploads sources and compiles them in AWS.
However, it is best to upload the binaries instead.
To do so, add lines similar to the following to your `.elasticbeanstalk/config.yml` file:

[source,xml]
----
deploy:
	artifact: target/demo-0.0.1-SNAPSHOT.jar
----
====

[TIP]
.Reduce costs by setting the environment type
====
By default an Elastic Beanstalk environment is load balanced.
The load balancer has a significant cost.
To avoid that cost, set the environment type to "`Single instance`", as described in https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-create-wizard.html#environments-create-wizard-capacity[the Amazon documentation].
You can also create single instance environments by using the CLI and the following command:

[source]
----
eb create -s
----
====



[[howto.deployment.cloud.aws.summary]]
=== Summary

This is one of the easiest ways to get to AWS, but there are more things to cover, such as how to integrate Elastic Beanstalk into any CI / CD tool, use the Elastic Beanstalk Maven plugin instead of the CLI, and others.
There is a https://exampledriven.wordpress.com/2017/01/09/spring-boot-aws-elastic-beanstalk-example/[blog post] covering these topics more in detail.



[[howto.deployment.cloud.boxfuse]]
== CloudCaptain and Amazon Web Services

https://cloudcaptain.sh/[CloudCaptain] works by turning your Spring Boot executable jar or war into a minimal VM image that can be deployed unchanged either on VirtualBox or on AWS.
CloudCaptain comes with deep integration for Spring Boot and uses the information from your Spring Boot configuration file to automatically configure ports and health check URLs.
CloudCaptain leverages this information both for the images it produces as well as for all the resources it provisions (instances, security groups, elastic load balancers, and so on).

Once you have created a https://console.cloudcaptain.sh[CloudCaptain account], connected it to your AWS account, installed the latest version of the CloudCaptain Client, and ensured that the application has been built by Maven or Gradle (by using, for example, `mvn clean package`), you can deploy your Spring Boot application to AWS with a command similar to the following:

[source,shell]
----
$ boxfuse run myapp-1.0.jar -env=prod
----

See the https://cloudcaptain.sh/docs/commandline/run.html[`boxfuse run` documentation] for more options.
If there is a https://cloudcaptain.sh/docs/commandline/#configuration[`boxfuse.conf`] file present in the current directory, it is considered.

TIP: By default, CloudCaptain activates a Spring profile named `boxfuse` on startup.
If your executable jar or war contains an https://cloudcaptain.sh/docs/payloads/springboot.html#configuration[`application-boxfuse.properties`] file, CloudCaptain bases its configuration on the properties it contains.

At this point, CloudCaptain creates an image for your application, uploads it, and configures and starts the necessary resources on AWS, resulting in output similar to the following example:

[source]
----
Fusing Image for myapp-1.0.jar ...
Image fused in 00:06.838s (53937 K) -> axelfontaine/myapp:1.0
Creating axelfontaine/myapp ...
Pushing axelfontaine/myapp:1.0 ...
Verifying axelfontaine/myapp:1.0 ...
Creating Elastic IP ...
Mapping myapp-axelfontaine.boxfuse.io to 52.28.233.167 ...
Waiting for AWS to create an AMI for axelfontaine/myapp:1.0 in eu-central-1 (this may take up to 50 seconds) ...
AMI created in 00:23.557s -> ami-d23f38cf
Creating security group boxfuse-sg_axelfontaine/myapp:1.0 ...
Launching t2.micro instance of axelfontaine/myapp:1.0 (ami-d23f38cf) in eu-central-1 ...
Instance launched in 00:30.306s -> i-92ef9f53
Waiting for AWS to boot Instance i-92ef9f53 and Payload to start at https://52.28.235.61/ ...
Payload started in 00:29.266s -> https://52.28.235.61/
Remapping Elastic IP 52.28.233.167 to i-92ef9f53 ...
Waiting 15s for AWS to complete Elastic IP Zero Downtime transition ...
Deployment completed successfully. axelfontaine/myapp:1.0 is up and running at https://myapp-axelfontaine.boxfuse.io/
----

Your application should now be up and running on AWS.

See the blog post on https://cloudcaptain.sh/blog/spring-boot-ec2.html[deploying Spring Boot apps on EC2] as well as the https://cloudcaptain.sh/docs/payloads/springboot.html[documentation for the CloudCaptain Spring Boot integration] to get started with a Maven build to run the app.



[[howto.deployment.cloud.azure]]
== Azure

This https://spring.io/guides/gs/spring-boot-for-azure/[Getting Started guide] walks you through deploying your Spring Boot application to either https://azure.microsoft.com/en-us/services/spring-cloud/[Azure Spring Cloud] or https://docs.microsoft.com/en-us/azure/app-service/overview[Azure App Service].



[[howto.deployment.cloud.google]]
== Google Cloud

Google Cloud has several options that can be used to launch Spring Boot applications.
The easiest to get started with is probably App Engine, but you could also find ways to run Spring Boot in a container with Container Engine or on a virtual machine with Compute Engine.

To deploy your first app to App Engine standard environment, follow https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot#0[this tutorial].

Alternatively, App Engine Flex requires you to create an `app.yaml` file to describe the resources your app requires.
Normally, you put this file in `src/main/appengine`, and it should resemble the following file:

[source,yaml]
----
service: "default"

runtime: "java17"
env: "flex"

handlers:
- url: "/.*"
  script: "this field is required, but ignored"

manual_scaling:
  instances: 1

health_check:
  enable_health_check: false

env_variables:
  ENCRYPT_KEY: "your_encryption_key_here"
----

You can deploy the app (for example, with a Maven plugin) by adding the project ID to the build configuration, as shown in the following example:

[source,xml]
----
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>appengine-maven-plugin</artifactId>
	<version>2.4.4</version>
	<configuration>
		<project>myproject</project>
	</configuration>
</plugin>
----

Then deploy with `mvn appengine:deploy` (you need to authenticate first, otherwise the build fails).
