[[messaging.amqp]]
= AMQP

高级消息队列协议（AMQP）是一种平台无关的、面向消息中间件的线级协议。
Spring AMQP 项目将核心 Spring 概念应用于基于 AMQP 的消息解决方案开发。
Spring Boot 通过 RabbitMQ 提供了多种便捷方式来使用 AMQP，包括 `spring-boot-starter-amqp` 启动器。



[[messaging.amqp.rabbitmq]]
== RabbitMQ 支持

https://www.rabbitmq.com/[RabbitMQ] 是一个基于 AMQP 协议的轻量级、可靠、可扩展且可移植的消息代理。
Spring 使用 RabbitMQ 通过 AMQP 协议进行通信。

RabbitMQ 的配置通过外部配置属性 `+spring.rabbitmq.*+` 控制。
例如，你可以在 `application.properties` 中声明如下配置：

[configprops,yaml]
----
spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "secret"
----

或者，你也可以通过 `addresses` 属性配置同一个连接：

[configprops,yaml]
----
spring:
  rabbitmq:
    addresses: "amqp://admin:secret@localhost"
----

NOTE: 以这种方式指定 addresses 时，`host` 和 `port` 属性会被忽略。
如果地址使用 `amqps` 协议，则会自动启用 SSL 支持。

更多受支持的基于属性的配置选项请参见 javadoc:org.springframework.boot.autoconfigure.amqp.RabbitProperties[]。
如需配置 Spring AMQP 所用 RabbitMQ javadoc:com.rabbitmq.client.ConnectionFactory[] 的底层细节，可定义 javadoc:org.springframework.boot.autoconfigure.amqp.ConnectionFactoryCustomizer[] bean。

如果上下文中存在 javadoc:org.springframework.amqp.rabbit.connection.ConnectionNameStrategy[] bean，则会自动用于为自动配置的 javadoc:org.springframework.amqp.rabbit.connection.CachingConnectionFactory[] 创建的连接命名。

如需对 javadoc:org.springframework.amqp.rabbit.core.RabbitTemplate[] 进行全局、增量自定义，可使用 javadoc:org.springframework.boot.autoconfigure.amqp.RabbitTemplateCustomizer[] bean。

TIP: 更多详情请参见 https://spring.io/blog/2010/06/14/understanding-amqp-the-protocol-used-by-rabbitmq/[理解 RabbitMQ 所用的 AMQP 协议]。



[[messaging.amqp.sending]]
== 发送消息

Spring 的 javadoc:org.springframework.amqp.core.AmqpTemplate[] 和 javadoc:org.springframework.amqp.core.AmqpAdmin[] 已自动配置，你可以像下面这样直接注入到自己的 bean 中：

include-code::MyBean[]

NOTE: javadoc:org.springframework.amqp.rabbit.core.RabbitMessagingTemplate[] 也可以以类似方式注入。
如果定义了 javadoc:org.springframework.amqp.support.converter.MessageConverter[] bean，则会自动关联到自动配置的 javadoc:org.springframework.amqp.core.AmqpTemplate[]。

如有需要，任何作为 bean 定义的 javadoc:org.springframework.amqp.core.Queue[] 都会自动用于在 RabbitMQ 实例上声明对应队列。

如需重试操作，可以在 javadoc:org.springframework.amqp.core.AmqpTemplate[] 上启用重试（例如在 broker 连接丢失时）：

[configprops,yaml]
----
spring:
  rabbitmq:
    template:
      retry:
        enabled: true
        initial-interval: "2s"
----

重试默认是关闭的。
你也可以通过声明 javadoc:org.springframework.boot.autoconfigure.amqp.RabbitRetryTemplateCustomizer[] bean，编程方式自定义 javadoc:org.springframework.retry.support.RetryTemplate[]。

如果你需要创建更多 javadoc:org.springframework.amqp.rabbit.core.RabbitTemplate[] 实例，或想覆盖默认配置，Spring Boot 提供了 javadoc:org.springframework.boot.autoconfigure.amqp.RabbitTemplateConfigurer[] bean，可用来以与自动配置工厂相同的设置初始化 javadoc:org.springframework.amqp.rabbit.core.RabbitTemplate[]。



[[messaging.amqp.sending-stream]]
== 发送消息到流

如需向特定流发送消息，只需指定流的名称，如下例所示：

[configprops,yaml]
----
spring:
  rabbitmq:
    stream:
      name: "my-stream"
----

如果定义了 javadoc:org.springframework.amqp.support.converter.MessageConverter[]、javadoc:org.springframework.rabbit.stream.support.converter.StreamMessageConverter[] 或 javadoc:org.springframework.rabbit.stream.producer.ProducerCustomizer[] bean，则会自动关联到自动配置的 javadoc:org.springframework.rabbit.stream.producer.RabbitStreamTemplate[]。

如果你需要创建更多 javadoc:org.springframework.rabbit.stream.producer.RabbitStreamTemplate[] 实例，或想覆盖默认配置，Spring Boot 提供了 javadoc:org.springframework.boot.autoconfigure.amqp.RabbitStreamTemplateConfigurer[] bean，可用来以与自动配置工厂相同的设置初始化 javadoc:org.springframework.rabbit.stream.producer.RabbitStreamTemplate[]。



[[messaging.amqp.receiving]]
== 接收消息

当 Rabbit 基础设施存在时，任何 bean 都可以通过注解 javadoc:org.springframework.amqp.rabbit.annotation.RabbitListener[format=annotation] 创建监听端点。
如果未定义 javadoc:org.springframework.amqp.rabbit.listener.RabbitListenerContainerFactory[]，则会自动配置一个默认的 javadoc:org.springframework.amqp.rabbit.config.SimpleRabbitListenerContainerFactory[]，你可以通过 configprop:spring.rabbitmq.listener.type[] 属性切换为 direct 容器。
如果定义了 javadoc:org.springframework.amqp.support.converter.MessageConverter[] 或 javadoc:org.springframework.amqp.rabbit.retry.MessageRecoverer[] bean，则会自动关联到默认工厂。

以下示例组件会在 `someQueue` 队列上创建一个监听端点：

include-code::MyBean[]

TIP: 更多详情请参见 javadoc:org.springframework.amqp.rabbit.annotation.EnableRabbit[format=annotation]。

如果你需要创建更多 javadoc:org.springframework.amqp.rabbit.listener.RabbitListenerContainerFactory[] 实例，或想覆盖默认配置，Spring Boot 提供了 javadoc:org.springframework.boot.autoconfigure.amqp.SimpleRabbitListenerContainerFactoryConfigurer[] 和 javadoc:org.springframework.boot.autoconfigure.amqp.DirectRabbitListenerContainerFactoryConfigurer[]，可用来以与自动配置工厂相同的设置初始化 javadoc:org.springframework.amqp.rabbit.config.SimpleRabbitListenerContainerFactory[] 和 javadoc:org.springframework.amqp.rabbit.config.DirectRabbitListenerContainerFactory[]。

TIP: 你选择哪种容器类型并不重要。
这两个 bean 都由自动配置暴露。

例如，下面的配置类暴露了一个使用特定 javadoc:org.springframework.amqp.support.converter.MessageConverter[] 的工厂：

include-code::custom/MyRabbitConfiguration[]

然后你可以在任何带有 javadoc:org.springframework.amqp.rabbit.annotation.RabbitListener[format=annotation] 注解的方法中使用该工厂，如下所示：

include-code::custom/MyBean[]

你可以启用重试来处理监听器抛出异常的情况。
默认情况下，使用 javadoc:org.springframework.amqp.rabbit.retry.RejectAndDontRequeueRecoverer[]，但你可以自定义 javadoc:org.springframework.amqp.rabbit.retry.MessageRecoverer[]。
当重试耗尽时，消息会被拒绝并丢弃，或在 broker 配置允许时路由到死信交换。
默认情况下，重试是关闭的。
你也可以通过声明 javadoc:org.springframework.boot.autoconfigure.amqp.RabbitRetryTemplateCustomizer[] bean，编程方式自定义 javadoc:org.springframework.retry.support.RetryTemplate[]。

IMPORTANT: 默认情况下，如果重试关闭且监听器抛出异常，则会无限次重投递。
你可以通过两种方式修改此行为：将 `defaultRequeueRejected` 属性设置为 `false`，这样就不会再尝试重新投递；或抛出 javadoc:org.springframework.amqp.AmqpRejectAndDontRequeueException[]，表示消息应被拒绝。
后者是启用重试并达到最大投递次数时采用的机制。
