[[messaging.jms]]
= JMS

javadoc:jakarta.jms.ConnectionFactory[] 接口为与 JMS broker 交互提供了创建 javadoc:jakarta.jms.Connection[] 的标准方法。
虽然 Spring 需要 javadoc:jakarta.jms.ConnectionFactory[] 来使用 JMS，但通常你无需直接操作它，可以依赖更高级的消息抽象。
（详见 Spring Framework 参考文档的 {url-spring-framework-docs}/integration/jms.html[相关章节]。）
Spring Boot 也会自动配置发送和接收消息所需的基础设施。



[[messaging.jms.activemq]]
== ActiveMQ "Classic" 支持

当 classpath 上存在 https://activemq.apache.org/components/classic[ActiveMQ "Classic"] 时，Spring Boot 可配置 javadoc:jakarta.jms.ConnectionFactory[]。
如果 broker 存在，且未通过配置指定 broker URL 且未禁用嵌入式 broker，则会自动启动并配置一个嵌入式 broker。

NOTE: 如果你使用 `spring-boot-starter-activemq`，则会自动提供连接 ActiveMQ "Classic" 实例所需的依赖，以及集成 JMS 的 Spring 基础设施。
向应用添加 `org.apache.activemq:activemq-broker` 可启用嵌入式 broker。

ActiveMQ "Classic" 的配置通过外部配置属性 `+spring.activemq.*+` 控制。

如果 classpath 上有 `activemq-broker`，ActiveMQ "Classic" 会自动配置为使用 https://activemq.apache.org/vm-transport-reference.html[VM transport]，即在同一 JVM 实例中启动 broker。

你可以通过如下配置 configprop:spring.activemq.embedded.enabled[] 属性禁用嵌入式 broker：

[configprops,yaml]
----
spring:
  activemq:
    embedded:
      enabled: false
----

如果你配置了 broker URL，也会禁用嵌入式 broker，例如：

[configprops,yaml]
----
spring:
  activemq:
    broker-url: "tcp://192.168.1.210:9876"
    user: "admin"
    password: "secret"
----

如需完全控制嵌入式 broker，详见 https://activemq.apache.org/how-do-i-embed-a-broker-inside-a-connection.html[ActiveMQ "Classic" 文档]。

默认情况下，javadoc:org.springframework.jms.connection.CachingConnectionFactory[] 会用合理的设置包装原生 javadoc:jakarta.jms.ConnectionFactory[]，这些设置可通过 `+spring.jms.*+` 外部配置属性控制：

[configprops,yaml]
----
spring:
  jms:
    cache:
      session-cache-size: 5
----

如需使用原生连接池，可添加 `org.messaginghub:pooled-jms` 依赖，并按如下方式配置 javadoc:org.messaginghub.pooled.jms.JmsPoolConnectionFactory[]：

[configprops,yaml]
----
spring:
  activemq:
    pool:
      enabled: true
      max-connections: 50
----

TIP: 更多支持选项请参见 javadoc:org.springframework.boot.autoconfigure.jms.activemq.ActiveMQProperties[]。
如需更高级自定义，可注册任意数量实现 javadoc:org.springframework.boot.autoconfigure.jms.activemq.ActiveMQConnectionFactoryCustomizer[] 的 bean。

默认情况下，ActiveMQ "Classic" 会在目的地不存在时自动创建目的地，因此目的地会根据提供的名称解析。



[[messaging.jms.artemis]]
== ActiveMQ Artemis 支持

当检测到 classpath 上有 https://activemq.apache.org/components/artemis/[ActiveMQ Artemis] 时，Spring Boot 可自动配置 javadoc:jakarta.jms.ConnectionFactory[]。
如果 broker 存在，且未显式设置 mode 属性，则会自动启动并配置嵌入式 broker。
支持的模式有 `embedded`（明确要求嵌入式 broker，若 classpath 上无 broker 则报错）和 `native`（通过 `netty` 协议连接 broker）。
配置为后者时，Spring Boot 会配置一个连接本地 broker 的 javadoc:jakarta.jms.ConnectionFactory[]，使用默认设置。

NOTE: 如果你使用 `spring-boot-starter-artemis`，则会自动提供连接现有 ActiveMQ Artemis 实例所需的依赖，以及集成 JMS 的 Spring 基础设施。
向应用添加 `org.apache.activemq:artemis-jakarta-server` 可启用嵌入式模式。

ActiveMQ Artemis 的配置通过外部配置属性 `+spring.artemis.*+` 控制。例如，你可以在 `application.properties` 中声明如下配置：

[configprops,yaml]
----
spring:
  artemis:
    mode: native
    broker-url: "tcp://192.168.1.210:9876"
    user: "admin"
    password: "secret"
----

嵌入 broker 时，你可以选择是否启用持久化，并列出应可用的目的地。
这些可以用逗号分隔的列表指定（以默认选项创建），也可以定义 javadoc:org.apache.activemq.artemis.jms.server.config.JMSQueueConfiguration[] 或 javadoc:org.apache.activemq.artemis.jms.server.config.TopicConfiguration[] 类型的 bean 以实现高级队列和主题配置。

默认情况下，javadoc:org.springframework.jms.connection.CachingConnectionFactory[] 会用合理的设置包装原生 javadoc:jakarta.jms.ConnectionFactory[]，这些设置可通过 `+spring.jms.*+` 外部配置属性控制：

[configprops,yaml]
----
spring:
  jms:
    cache:
      session-cache-size: 5
----

如需使用原生连接池，可添加 `org.messaginghub:pooled-jms` 依赖，并按如下方式配置 javadoc:org.messaginghub.pooled.jms.JmsPoolConnectionFactory[]：

[configprops,yaml]
----
spring:
  artemis:
    pool:
      enabled: true
      max-connections: 50
----

更多支持选项请参见 javadoc:org.springframework.boot.autoconfigure.jms.artemis.ArtemisProperties[]。

无需 JNDI 查找，目的地会根据其名称解析，名称可来自 ActiveMQ Artemis 配置的 `name` 属性或配置中提供的名称。



[[messaging.jms.jndi]]
== 使用 JNDI ConnectionFactory

如果你在应用服务器中运行应用，Spring Boot 会尝试通过 JNDI 查找 JMS javadoc:jakarta.jms.ConnectionFactory[]。
默认会检查 `java:/JmsXA` 和 `java:/XAConnectionFactory`。
如需指定其他位置，可通过 configprop:spring.jms.jndi-name[] 属性配置，例如：

[configprops,yaml]
----
spring:
  jms:
    jndi-name: "java:/MyConnectionFactory"
----



[[messaging.jms.sending]]
== 发送消息

Spring 的 javadoc:org.springframework.jms.core.JmsTemplate[] 已自动配置，你可以像下面这样直接注入到自己的 bean 中：

include-code::MyBean[]

NOTE: javadoc:org.springframework.jms.core.JmsMessagingTemplate[] 也可以以类似方式注入。
如果定义了 javadoc:org.springframework.jms.support.destination.DestinationResolver[] 或 javadoc:org.springframework.jms.support.converter.MessageConverter[] bean，则会自动关联到自动配置的 javadoc:org.springframework.jms.core.JmsTemplate[]。



[[messaging.jms.receiving]]
== 接收消息

当 JMS 基础设施存在时，任何 bean 都可以通过注解 javadoc:org.springframework.jms.annotation.JmsListener[format=annotation] 创建监听端点。
如果未定义 javadoc:org.springframework.jms.config.JmsListenerContainerFactory[]，则会自动配置一个默认工厂。
如果定义了 javadoc:org.springframework.jms.support.destination.DestinationResolver[]、javadoc:org.springframework.jms.support.converter.MessageConverter[] 或 javadoc:jakarta.jms.ExceptionListener[] bean，则会自动关联到默认工厂。

大多数场景下，消息监听容器应配置为使用原生 javadoc:jakarta.jms.ConnectionFactory[]，这样每个监听容器都有自己的连接，便于本地恢复。
自动配置会用 javadoc:org.springframework.boot.jms.ConnectionFactoryUnwrapper[] 从自动配置的连接工厂中解包原生连接工厂。

NOTE: 自动配置仅解包 `CachedConnectionFactory`。

默认情况下，默认工厂是事务性的。
如果运行环境中存在 javadoc:org.springframework.transaction.jta.JtaTransactionManager[]，则会默认关联到监听容器。
否则会启用 `sessionTransacted` 标志。
在后者场景下，你可以在监听方法（或其委托）上添加 javadoc:org.springframework.transaction.annotation.Transactional[format=annotation]，将本地数据存储事务与接收消息的处理关联起来。
这样可确保本地事务完成后再确认接收消息。
这也包括在同一 JMS 会话上执行的响应消息发送。

以下组件会在 `someQueue` 目的地上创建一个监听端点：

include-code::MyBean[]

TIP: 更多详情请参见 javadoc:org.springframework.jms.annotation.EnableJms[format=annotation] API 文档。

如果你需要创建更多 javadoc:org.springframework.jms.config.JmsListenerContainerFactory[] 实例，或想覆盖默认配置，Spring Boot 提供了 javadoc:org.springframework.boot.autoconfigure.jms.DefaultJmsListenerContainerFactoryConfigurer[]，可用来以与自动配置工厂相同的设置初始化 javadoc:org.springframework.jms.config.DefaultJmsListenerContainerFactory[]。

例如，下面的示例暴露了一个使用特定 javadoc:org.springframework.jms.support.converter.MessageConverter[] 的工厂：

include-code::custom/MyJmsConfiguration[]

NOTE: 上述示例中的自定义通过 javadoc:org.springframework.boot.jms.ConnectionFactoryUnwrapper[]，以与自动配置工厂相同的方式将原生连接工厂关联到消息监听容器。

然后你可以在任何带有 javadoc:org.springframework.jms.annotation.JmsListener[format=annotation] 注解的方法中使用该工厂，如下所示：

include-code::custom/MyBean[]
