[[features.dev-services]]
= 开发时服务

开发时服务提供运行应用程序时所需的外部依赖。
它们仅用于开发阶段，在应用程序部署时会被禁用。

Spring Boot 提供了对两种开发时服务的支持：Docker Compose 和 Testcontainers。
接下来的章节将提供更多关于它们的详细信息。

[[features.dev-services.docker-compose]]
== Docker Compose 支持

Docker Compose 是一种流行的技术，可用于定义和管理应用程序所需服务的多个容器。
通常在应用程序旁边创建一个 `compose.yml` 文件，用于定义和配置服务容器。

使用 Docker Compose 的典型工作流程是运行 `docker compose up`，让应用程序连接到已启动的服务，然后在完成时运行 `docker compose down`。

可以通过在项目中包含 `spring-boot-docker-compose` 模块来提供使用 Docker Compose 处理容器的支持。
将模块依赖添加到你的构建中，如下面的 Maven 和 Gradle 列表所示：

.Maven
[source,xml]
----
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-docker-compose</artifactId>
		<optional>true</optional>
	</dependency>
</dependencies>
----

.Gradle
[source,gradle]
----
dependencies {
	developmentOnly("org.springframework.boot:spring-boot-docker-compose")
}
----

当包含此模块作为依赖时，Spring Boot 将执行以下操作：

* 在工作目录中搜索 `compose.yml` 和其他常见的 compose 文件名
* 使用发现的 `compose.yml` 调用 `docker compose up`
* 为每个支持的容器创建服务连接 bean
* 在应用程序关闭时调用 `docker compose stop`

如果在启动应用程序时 Docker Compose 服务已经在运行，Spring Boot 将只为每个支持的容器创建服务连接 bean。
它不会再次调用 `docker compose up`，也不会在应用程序关闭时调用 `docker compose stop`。

TIP: 默认情况下，重新打包的归档文件不包含 Spring Boot 的 Docker Compose。
如果你想使用此支持，需要包含它。
使用 Maven 插件时，将 `excludeDockerCompose` 属性设置为 `false`。
使用 Gradle 插件时，xref:gradle-plugin:packaging.adoc#packaging-executable.configuring.including-development-only-dependencies[配置任务的类路径以包含 `developmentOnly` 配置]。



[[features.dev-services.docker-compose.prerequisites]]
=== 前提条件

你需要在路径上有 `docker` 和 `docker compose`（或 `docker-compose`）CLI 应用程序。
最低支持的 Docker Compose 版本是 2.2.0。



[[features.dev-services.docker-compose.service-connections]]
=== 服务连接

服务连接是到任何远程服务的连接。
Spring Boot 的自动配置可以使用服务连接的详细信息来建立到远程服务的连接。
这样做时，连接详细信息优先于任何与连接相关的配置属性。

使用 Spring Boot 的 Docker Compose 支持时，服务连接会建立到容器映射的端口。

NOTE: Docker compose 通常以容器内的端口映射到计算机上的临时端口的方式使用。
例如，Postgres 服务器可能在容器内使用端口 5432 运行，但在本地映射到完全不同的端口。
服务连接将始终发现并使用本地映射的端口。

服务连接是通过使用容器的镜像名称建立的。
目前支持以下服务连接：


|===
| 连接详细信息 | 匹配条件

| javadoc:org.springframework.boot.autoconfigure.jms.activemq.ActiveMQConnectionDetails[]
| 名为 "symptoma/activemq" 或 "apache/activemq-classic" 的容器

| javadoc:org.springframework.boot.autoconfigure.jms.artemis.ArtemisConnectionDetails[]
| 名为 "apache/activemq-artemis" 的容器

| javadoc:org.springframework.boot.autoconfigure.cassandra.CassandraConnectionDetails[]
| 名为 "cassandra" 或 "bitnami/cassandra" 的容器

| javadoc:org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchConnectionDetails[]
| 名为 "elasticsearch" 或 "bitnami/elasticsearch" 的容器

| javadoc:org.springframework.boot.autoconfigure.hazelcast.HazelcastConnectionDetails[]
| 名为 "hazelcast/hazelcast" 的容器

| javadoc:org.springframework.boot.autoconfigure.jdbc.JdbcConnectionDetails[]
| 名为 "clickhouse/clickhouse-server"、"bitnami/clickhouse"、"gvenzl/oracle-free"、"gvenzl/oracle-xe"、"mariadb"、"bitnami/mariadb"、"mssql/server"、"mysql"、"bitnami/mysql"、"postgres" 或 "bitnami/postgresql" 的容器

| javadoc:org.springframework.boot.autoconfigure.ldap.LdapConnectionDetails[]
| 名为 "osixia/openldap" 的容器

| javadoc:org.springframework.boot.autoconfigure.mongo.MongoConnectionDetails[]
| 名为 "mongo" 或 "bitnami/mongodb" 的容器

| javadoc:org.springframework.boot.autoconfigure.neo4j.Neo4jConnectionDetails[]
| 名为 "neo4j" 或 "bitnami/neo4j" 的容器

| javadoc:org.springframework.boot.actuate.autoconfigure.logging.otlp.OtlpLoggingConnectionDetails[]
| 名为 "otel/opentelemetry-collector-contrib"、"grafana/otel-lgtm" 的容器

| javadoc:org.springframework.boot.actuate.autoconfigure.metrics.export.otlp.OtlpMetricsConnectionDetails[]
| 名为 "otel/opentelemetry-collector-contrib"、"grafana/otel-lgtm" 的容器

| javadoc:org.springframework.boot.actuate.autoconfigure.tracing.otlp.OtlpTracingConnectionDetails[]
| 名为 "otel/opentelemetry-collector-contrib"、"grafana/otel-lgtm" 的容器

| javadoc:org.springframework.boot.autoconfigure.pulsar.PulsarConnectionDetails[]
| 名为 "apachepulsar/pulsar" 的容器

| javadoc:org.springframework.boot.autoconfigure.r2dbc.R2dbcConnectionDetails[]
| 名为 "clickhouse/clickhouse-server"、"bitnami/clickhouse"、"gvenzl/oracle-free"、"gvenzl/oracle-xe"、"mariadb"、"bitnami/mariadb"、"mssql/server"、"mysql"、"bitnami/mysql"、"postgres" 或 "bitnami/postgresql" 的容器

| javadoc:org.springframework.boot.autoconfigure.amqp.RabbitConnectionDetails[]
| 名为 "rabbitmq" 或 "bitnami/rabbitmq" 的容器

| javadoc:org.springframework.boot.autoconfigure.data.redis.RedisConnectionDetails[]
| 名为 "redis"、"bitnami/redis"、"redis/redis-stack" 或 "redis/redis-stack-server" 的容器

| javadoc:org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinConnectionDetails[]
| 名为 "openzipkin/zipkin" 的容器
|===



[[features.dev-services.docker-compose.custom-images]]
=== 自定义镜像

有时你可能需要使用自己的镜像版本来提供服务。
只要你的自定义镜像的行为方式与标准镜像相同，就可以使用任何自定义镜像。
具体来说，标准镜像支持的任何环境变量也必须在你的自定义镜像中使用。

如果你的镜像使用不同的名称，你可以在 `compose.yml` 文件中使用标签，以便 Spring Boot 可以提供服务连接。
使用名为 `org.springframework.boot.service-connection` 的标签来提供服务名称。

例如：

[source,yaml,]
----
services:
  redis:
    image: 'mycompany/mycustomredis:7.0'
    ports:
      - '6379'
    labels:
      org.springframework.boot.service-connection: redis
----



[[features.dev-services.docker-compose.skipping]]
=== 跳过特定容器

如果你在 `compose.yml` 中定义了一个不想连接到应用程序的容器镜像，你可以使用标签来忽略它。
任何带有 `org.springframework.boot.ignore` 标签的容器都会被 Spring Boot 忽略。

例如：

[source,yaml]
----
services:
  redis:
    image: 'redis:7.0'
    ports:
      - '6379'
    labels:
      org.springframework.boot.ignore: true
----



[[features.dev-services.docker-compose.specific-file]]
=== 使用特定的 Compose 文件

如果你的 compose 文件不在应用程序的同一目录中，或者名称不同，你可以在 `application.properties` 或 `application.yaml` 中使用 configprop:spring.docker.compose.file[] 指向不同的文件。
属性可以定义为精确路径或相对于应用程序的路径。

例如：

[configprops,yaml]
----
spring:
  docker:
    compose:
      file: "../my-compose.yml"
----



[[features.dev-services.docker-compose.readiness]]
=== 等待容器就绪

Docker Compose 启动的容器可能需要一些时间才能完全就绪。
检查就绪状态的推荐方法是在 `compose.yml` 文件的服务定义下添加 `healthcheck` 部分。

由于 `compose.yml` 文件中经常省略 `healthcheck` 配置，Spring Boot 也会直接检查服务就绪状态。
默认情况下，当可以建立到其映射端口的 TCP/IP 连接时，认为容器已就绪。

你可以通过在 `compose.yml` 文件中添加 `org.springframework.boot.readiness-check.tcp.disable` 标签来按容器禁用此功能。

例如：

[source,yaml]
----
services:
  redis:
    image: 'redis:7.0'
    ports:
      - '6379'
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
----

你也可以在 `application.properties` 或 `application.yaml` 文件中更改超时值：

[configprops,yaml]
----
spring:
  docker:
    compose:
      readiness:
        tcp:
          connect-timeout: 10s
          read-timeout: 5s
----

可以使用 configprop:spring.docker.compose.readiness.timeout[] 配置总体超时。



[[features.dev-services.docker-compose.lifecycle]]
=== 控制 Docker Compose 生命周期

默认情况下，Spring Boot 在应用程序启动时调用 `docker compose up`，在关闭时调用 `docker compose stop`。
如果你希望有不同的生命周期管理，可以使用 configprop:spring.docker.compose.lifecycle-management[] 属性。

支持以下值：

* `none` - 不启动或停止 Docker Compose
* `start-only` - 在应用程序启动时启动 Docker Compose 并保持运行
* `start-and-stop` - 在应用程序启动时启动 Docker Compose，在 JVM 退出时停止它

此外，你可以使用 configprop:spring.docker.compose.start.command[] 属性来更改是使用 `docker compose up` 还是 `docker compose start`。
configprop:spring.docker.compose.stop.command[] 允许你配置是使用 `docker compose down` 还是 `docker compose stop`。

以下示例显示了如何配置生命周期管理：

[configprops,yaml]
----
spring:
  docker:
    compose:
      lifecycle-management: start-and-stop
      start:
        command: start
      stop:
        command: down
        timeout: 1m
----



[[features.dev-services.docker-compose.profiles]]
=== 激活 Docker Compose 配置文件

Docker Compose 配置文件类似于 Spring 配置文件，它们允许你为特定环境调整 Docker Compose 配置。
如果你想激活特定的 Docker Compose 配置文件，可以在 `application.properties` 或 `application.yaml` 文件中使用 configprop:spring.docker.compose.profiles.active[] 属性：

[configprops,yaml]
----
spring:
  docker:
    compose:
      profiles:
        active: "myprofile"
----



[[features.dev-services.docker-compose.tests]]
=== 在测试中使用 Docker Compose

默认情况下，在运行测试时会禁用 Spring Boot 的 Docker Compose 支持。

要在测试中启用 Docker Compose 支持，将 configprop:spring.docker.compose.skip.in-tests[] 设置为 `false`。

使用 Gradle 时，你还需要将 `spring-boot-docker-compose` 依赖的配置从 `developmentOnly` 更改为 `testAndDevelopmentOnly`：

.Gradle
[source,gradle,indent=0,subs="verbatim"]
----
	dependencies {
		testAndDevelopmentOnly("org.springframework.boot:spring-boot-docker-compose")
	}
----



[[features.dev-services.testcontainers]]
== Testcontainers 支持

除了 xref:testing/testcontainers.adoc#testing.testcontainers[使用 Testcontainers 进行集成测试]之外，还可以在开发时使用它们。
接下来的章节将提供更多关于这方面的详细信息。



[[features.dev-services.testcontainers.at-development-time]]
=== 在开发时使用 Testcontainers

这种方法允许开发人员快速启动应用程序依赖的服务容器，无需手动配置数据库服务器等。
以这种方式使用 Testcontainers 提供了类似于 Docker Compose 的功能，只是你的容器配置是在 Java 中而不是 YAML 中。

要在开发时使用 Testcontainers，你需要使用"`test`"类路径而不是"`main`"来启动应用程序。
这将允许你访问所有声明的测试依赖，并为你提供一个编写测试配置的自然位置。

要创建应用程序的测试可启动版本，你应该在 `src/test` 目录中创建一个"`Application`"类。
例如，如果你的主应用程序在 `src/main/java/com/example/MyApplication.java`，你应该创建 `src/test/java/com/example/TestMyApplication.java`

`TestMyApplication` 类可以使用 `SpringApplication.from(...)` 方法来启动真正的应用程序：

include-code::launch/TestMyApplication[]

你还需要定义要与应用程序一起启动的 javadoc:org.testcontainers.containers.Container[] 实例。
为此，你需要确保已将 `spring-boot-testcontainers` 模块添加为 `test` 依赖。
完成后，你可以创建一个 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 类，该类为要启动的容器声明 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法。

你还可以用 javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] 注解你的 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法，以创建 javadoc:org.springframework.boot.autoconfigure.service.connection.ConnectionDetails[] bean。
有关支持的技术详情，请参阅 xref:testing/testcontainers.adoc#testing.testcontainers.service-connections[服务连接]部分。

典型的 Testcontainers 配置如下所示：

include-code::test/MyContainersConfiguration[]

NOTE: javadoc:org.testcontainers.containers.Container[] bean 的生命周期由 Spring Boot 自动管理。
容器将自动启动和停止。

TIP: 你可以使用 configprop:spring.testcontainers.beans.startup[] 属性来更改容器的启动方式。
默认使用 `sequential` 启动，但如果你希望并行启动多个容器，也可以选择 `parallel`。

定义测试配置后，你可以使用 `with(...)` 方法将其附加到测试启动器：

include-code::test/TestMyApplication[]

现在你可以像启动任何常规 Java `main` 方法应用程序一样启动 `TestMyApplication`，以启动应用程序及其运行所需的容器。

TIP: 你可以使用 Maven 目标 `spring-boot:test-run` 或 Gradle 任务 `bootTestRun` 从命令行执行此操作。



[[features.dev-services.testcontainers.at-development-time.dynamic-properties]]
==== 在开发时贡献动态属性

如果你想从 javadoc:org.testcontainers.containers.Container[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法在开发时贡献动态属性，请定义一个额外的 javadoc:org.springframework.test.context.DynamicPropertyRegistrar[] bean。
注册器应该使用 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法定义，该方法将从中获取属性的容器作为参数注入。
这种安排确保在使用属性之前容器已经启动。

典型的配置如下所示：

include-code::MyContainersConfiguration[]

NOTE: 尽可能使用 javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] 是推荐的，但是，对于尚未支持 javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] 的技术，动态属性可以是一个有用的后备方案。



[[features.dev-services.testcontainers.at-development-time.importing-container-declarations]]
==== 导入 Testcontainers 声明类

使用 Testcontainers 时的一个常见模式是将 javadoc:org.testcontainers.containers.Container[] 实例声明为静态字段。
这些字段通常直接定义在测试类上。
它们也可以声明在父类或测试实现的接口上。

例如，以下 `MyContainers` 接口声明了 `mongo` 和 `neo4j` 容器：

include-code::MyContainers[]

如果你已经有以这种方式定义的容器，或者你只是更喜欢这种风格，你可以导入这些声明类，而不是将容器定义为 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法。
为此，将 javadoc:org.springframework.boot.testcontainers.context.ImportTestcontainers[format=annotation] 注解添加到你的测试配置类：

include-code::MyContainersConfiguration[]

TIP: 如果你不打算使用 xref:testing/testcontainers.adoc#testing.testcontainers.service-connections[服务连接功能]但想使用 xref:testing/testcontainers.adoc#testing.testcontainers.dynamic-properties[`@DynamicPropertySource`]，请从 javadoc:org.testcontainers.containers.Container[] 字段中删除 javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] 注解。
你还可以将 javadoc:org.springframework.test.context.DynamicPropertySource[format=annotation] 注解的方法添加到你的声明类中。



[[features.dev-services.testcontainers.at-development-time.devtools]]
==== 在开发时使用 DevTools 和 Testcontainers

使用 devtools 时，你可以用 javadoc:org.springframework.boot.devtools.restart.RestartScope[format=annotation] 注解 bean 和 bean 方法。
这样的 bean 在 devtools 重启应用程序时不会被重新创建。
这对于 javadoc:org.testcontainers.containers.Container[] bean 特别有用，因为它们在应用程序重启时保持其状态。

include-code::MyContainersConfiguration[]

WARNING: 如果你使用 Gradle 并想使用此功能，你需要将 `spring-boot-devtools` 依赖的配置从 `developmentOnly` 更改为 `testAndDevelopmentOnly`。
使用默认的 `developmentOnly` 范围，`bootTestRun` 任务将不会检测代码中的更改，因为 devtools 未激活。
