[[features.json]]
= JSON

Spring Boot 集成了三种 JSON 映射库：

- Gson
- Jackson
- JSON-B

Jackson 是首选且默认的库。



[[features.json.jackson]]
== Jackson

Jackson 的自动配置已提供，且 Jackson 是 `spring-boot-starter-json` 的一部分。
当类路径中存在 Jackson 时，会自动配置一个 javadoc:com.fasterxml.jackson.databind.ObjectMapper[] bean。
提供了多个配置属性用于 xref:how-to:spring-mvc.adoc#howto.spring-mvc.customize-jackson-objectmapper[自定义 javadoc:com.fasterxml.jackson.databind.ObjectMapper[] 的配置]。



[[features.json.jackson.custom-serializers-and-deserializers]]
=== 自定义序列化器与反序列化器

如果你使用 Jackson 进行 JSON 数据的序列化与反序列化，可能需要编写自己的 javadoc:com.fasterxml.jackson.databind.JsonSerializer[] 和 javadoc:com.fasterxml.jackson.databind.JsonDeserializer[] 类。
自定义序列化器通常通过 https://github.com/FasterXML/jackson-docs/wiki/JacksonHowToCustomSerializers[Jackson 模块注册]，但 Spring Boot 提供了 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] 注解，使直接注册 Spring Bean 更加便捷。

你可以直接在 javadoc:com.fasterxml.jackson.databind.JsonSerializer[]、javadoc:com.fasterxml.jackson.databind.JsonDeserializer[] 或 javadoc:com.fasterxml.jackson.databind.KeyDeserializer[] 实现类上使用 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] 注解。
也可以在包含序列化器/反序列化器的内部类的外部类上使用，如下例所示：

include-code::MyJsonComponent[]

所有 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] bean 都会自动注册到 javadoc:org.springframework.context.ApplicationContext[] 中的 Jackson。
由于 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] 是由 javadoc:org.springframework.stereotype.Component[format=annotation] 元注解的，因此适用常规组件扫描规则。

Spring Boot 还提供了 javadoc:org.springframework.boot.jackson.JsonObjectSerializer[] 和 javadoc:org.springframework.boot.jackson.JsonObjectDeserializer[] 基类，在对象序列化时为标准 Jackson 版本提供了有用的替代方案。
详细信息请参见 API 文档中的 javadoc:org.springframework.boot.jackson.JsonObjectSerializer[] 和 javadoc:org.springframework.boot.jackson.JsonObjectDeserializer[]。

上述示例可改写为使用 javadoc:org.springframework.boot.jackson.JsonObjectSerializer[] 和 javadoc:org.springframework.boot.jackson.JsonObjectDeserializer[]，如下所示：

include-code::object/MyJsonComponent[]



[[features.json.jackson.mixins]]
=== Mixins

Jackson 支持 mixin，可用于为目标类混入额外注解。
Spring Boot 的 Jackson 自动配置会扫描应用包中带有 javadoc:org.springframework.boot.jackson.JsonMixin[format=annotation] 注解的类，并将其注册到自动配置的 javadoc:com.fasterxml.jackson.databind.ObjectMapper[]。
注册由 Spring Boot 的 javadoc:org.springframework.boot.jackson.JsonMixinModule[] 完成。



[[features.json.gson]]
== Gson

Gson 的自动配置已提供。
当类路径中存在 Gson 时，会自动配置一个 javadoc:com.google.gson.Gson[] bean。
可通过多个 `+spring.gson.*+` 配置属性进行自定义。
如需更细致的控制，可使用一个或多个 javadoc:org.springframework.boot.autoconfigure.gson.GsonBuilderCustomizer[] bean。



[[features.json.json-b]]
== JSON-B

JSON-B 的自动配置已提供。
当类路径中存在 JSON-B API 及其实现时，会自动配置一个 javadoc:jakarta.json.bind.Jsonb[] bean。
首选 JSON-B 实现为 Eclipse Yasson，Spring Boot 已为其提供依赖管理。
