[[features.json]]
= JSON

Spring Boot 提供了与三个 JSON 映射库的集成：

- Gson
- Jackson
- JSON-B

Jackson 是首选和默认的库。



[[features.json.jackson]]
== Jackson

提供了 Jackson 的自动配置，并且 Jackson 是 `spring-boot-starter-json` 的一部分。
当 Jackson 在类路径上时，会自动配置一个 javadoc:com.fasterxml.jackson.databind.ObjectMapper[] bean。
提供了多个配置属性用于 xref:how-to:spring-mvc.adoc#howto.spring-mvc.customize-jackson-objectmapper[自定义 javadoc:com.fasterxml.jackson.databind.ObjectMapper[] 的配置]。



[[features.json.jackson.custom-serializers-and-deserializers]]
=== 自定义序列化器和反序列化器

如果你使用 Jackson 来序列化和反序列化 JSON 数据，你可能想要编写自己的 javadoc:com.fasterxml.jackson.databind.JsonSerializer[] 和 javadoc:com.fasterxml.jackson.databind.JsonDeserializer[] 类。
自定义序列化器通常通过 https://github.com/FasterXML/jackson-docs/wiki/JacksonHowToCustomSerializers[模块注册到 Jackson]，但 Spring Boot 提供了一个替代方案 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] 注解，使得直接注册 Spring Bean 变得更加容易。

你可以直接在 javadoc:com.fasterxml.jackson.databind.JsonSerializer[]、javadoc:com.fasterxml.jackson.databind.JsonDeserializer[] 或 javadoc:com.fasterxml.jackson.databind.KeyDeserializer[] 实现上使用 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] 注解。
你也可以在包含序列化器/反序列化器作为内部类的类上使用它，如下例所示：

include-code::MyJsonComponent[]

javadoc:org.springframework.context.ApplicationContext[] 中的所有 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] bean 都会自动注册到 Jackson。
因为 javadoc:org.springframework.boot.jackson.JsonComponent[format=annotation] 被元注解为 javadoc:org.springframework.stereotype.Component[format=annotation]，所以通常的组件扫描规则适用。

Spring Boot 还提供了 javadoc:org.springframework.boot.jackson.JsonObjectSerializer[] 和 javadoc:org.springframework.boot.jackson.JsonObjectDeserializer[] 基类，它们在序列化对象时提供了比标准 Jackson 版本更有用的替代方案。
有关详细信息，请参阅 API 文档中的 javadoc:org.springframework.boot.jackson.JsonObjectSerializer[] 和 javadoc:org.springframework.boot.jackson.JsonObjectDeserializer[]。

上面的示例可以重写为使用 javadoc:org.springframework.boot.jackson.JsonObjectSerializer[] 和 javadoc:org.springframework.boot.jackson.JsonObjectDeserializer[]，如下所示：

include-code::object/MyJsonComponent[]



[[features.json.jackson.mixins]]
=== Mixins

Jackson 支持 mixins，可用于将额外的注解混合到目标类已声明的注解中。
Spring Boot 的 Jackson 自动配置将扫描应用程序的包中带有 javadoc:org.springframework.boot.jackson.JsonMixin[format=annotation] 注解的类，并将它们注册到自动配置的 javadoc:com.fasterxml.jackson.databind.ObjectMapper[]。
注册是通过 Spring Boot 的 javadoc:org.springframework.boot.jackson.JsonMixinModule[] 执行的。



[[features.json.gson]]
== Gson

提供了 Gson 的自动配置。
当 Gson 在类路径上时，会自动配置一个 javadoc:com.google.gson.Gson[] bean。
提供了多个 `+spring.gson.*+` 配置属性用于自定义配置。
要获得更多控制，可以使用一个或多个 javadoc:org.springframework.boot.autoconfigure.gson.GsonBuilderCustomizer[] bean。



[[features.json.json-b]]
== JSON-B

提供了 JSON-B 的自动配置。
当 JSON-B API 和实现都在类路径上时，将自动配置一个 javadoc:jakarta.json.bind.Jsonb[] bean。
首选的 JSON-B 实现是 Eclipse Yasson，为其提供了依赖管理。
