[[features.kotlin]]
= Kotlin 支持

https://kotlinlang.org[Kotlin] 是一种针对 JVM（和其他平台）的静态类型语言，它允许编写简洁优雅的代码，同时提供与现有 Java 库的 {url-kotlin-docs}/java-interop.html[互操作性]。

Spring Boot 通过利用其他 Spring 项目（如 Spring Framework、Spring Data 和 Reactor）中的支持来提供 Kotlin 支持。
有关更多信息，请参阅 {url-spring-framework-docs}/languages/kotlin.html[Spring Framework Kotlin 支持文档]。

开始使用 Spring Boot 和 Kotlin 最简单的方法是遵循 https://spring.io/guides/tutorials/spring-boot-kotlin/[这个全面的教程]。
你可以使用 https://start.spring.io/#!language=kotlin[start.spring.io] 创建新的 Kotlin 项目。
如果你需要支持，可以加入 https://slack.kotlinlang.org/[Kotlin Slack] 的 #spring 频道，或在 https://stackoverflow.com/questions/tagged/spring+kotlin[Stack Overflow] 上使用 `spring` 和 `kotlin` 标签提问。



[[features.kotlin.requirements]]
== 要求

Spring Boot 需要至少 Kotlin 1.7.x，并通过依赖管理来管理合适的 Kotlin 版本。
要使用 Kotlin，必须在类路径上存在 `org.jetbrains.kotlin:kotlin-stdlib` 和 `org.jetbrains.kotlin:kotlin-reflect`。
也可以使用 `kotlin-stdlib` 变体 `kotlin-stdlib-jdk7` 和 `kotlin-stdlib-jdk8`。

由于 https://discuss.kotlinlang.org/t/classes-final-by-default/166[Kotlin 类默认是 final 的]，你可能需要配置 {url-kotlin-docs}/compiler-plugins.html#spring-support[kotlin-spring] 插件，以便自动打开带有 Spring 注解的类，使它们可以被代理。

https://github.com/FasterXML/jackson-module-kotlin[Jackson 的 Kotlin 模块] 是序列化/反序列化 Kotlin 中 JSON 数据所必需的。
当在类路径上找到它时，它会自动注册。
如果存在 Jackson 和 Kotlin 但缺少 Jackson Kotlin 模块，则会记录警告消息。

TIP: 如果你在 https://start.spring.io/#!language=kotlin[start.spring.io] 上引导一个 Kotlin 项目，这些依赖项和插件会默认提供。



[[features.kotlin.null-safety]]
== 空安全

Kotlin 的关键特性之一是 {url-kotlinlang.org}/null-safety.html[空安全]。
它在编译时处理 `null` 值，而不是将问题推迟到运行时并遇到 javadoc:java.lang.NullPointerException[]。
这有助于消除常见的错误来源，而无需支付像 javadoc:java.util.Optional[] 这样的包装器的成本。
Kotlin 还允许使用可空值的函数式构造，如这个 https://www.baeldung.com/kotlin-null-safety[Kotlin 空安全综合指南] 中所述。

虽然 Java 不允许在其类型系统中表达空安全，但 Spring Framework、Spring Data 和 Reactor 现在通过工具友好的注解提供其 API 的空安全。
默认情况下，在 Kotlin 中使用的 Java API 的类型被识别为 {url-kotlinlang.org}/java-interop.html#null-safety-and-platform-types[平台类型]，对这些类型的空检查是宽松的。
{url-kotlinlang.org}/java-interop.html#jsr-305-support[Kotlin 对 JSR 305 注解的支持] 结合空值注解为 Kotlin 中的相关 Spring API 提供空安全。

JSR 305 检查可以通过添加 `-Xjsr305` 编译器标志来配置，选项如下：`-Xjsr305={strict|warn|ignore}`。
默认行为与 `-Xjsr305=warn` 相同。
`strict` 值需要从 Spring API 推断的 Kotlin 类型中考虑空安全，但应该知道 Spring API 空值声明可能会在次要版本之间演变，并且将来可能会添加更多检查。

WARNING: 泛型类型参数、可变参数和数组元素的空值性尚未得到支持。
有关最新信息，请参阅 https://jira.spring.io/browse/SPR-15942[SPR-15942]。
还要注意，Spring Boot 自己的 API {url-github-issues}/10712[尚未被注解]。



[[features.kotlin.api]]
== Kotlin API



[[features.kotlin.api.run-application]]
=== runApplication

Spring Boot 提供了一种惯用的方式来运行应用程序，使用 `runApplication<MyApplication>(*args)`，如下例所示：

[source,kotlin]
----
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class MyApplication

fun main(args: Array<String>) {
	runApplication<MyApplication>(*args)
}
----

这是 `SpringApplication.run(MyApplication::class.java, *args)` 的替代品。
它还允许自定义应用程序，如下例所示：

[source,kotlin]
----
runApplication<MyApplication>(*args) {
	setBannerMode(OFF)
}
----



[[features.kotlin.api.extensions]]
=== 扩展

Kotlin {url-kotlinlang.org}/extensions.html[扩展] 提供了使用附加功能扩展现有类的能力。
Spring Boot Kotlin API 利用这些扩展为现有 API 添加新的 Kotlin 特定便利。

提供了 javadoc:org.springframework.boot.test.web.client.TestRestTemplate[] 扩展，类似于 Spring Framework 为 Spring Framework 中的 javadoc:org.springframework.web.client.RestOperations[] 提供的扩展。
其中，扩展使得利用 Kotlin 具体化类型参数成为可能。



[[features.kotlin.dependency-management]]
== 依赖管理

为了避免在类路径上混合不同版本的 Kotlin 依赖项，Spring Boot 导入了 Kotlin BOM。

使用 Maven 时，可以通过设置 `kotlin.version` 属性来自定义 Kotlin 版本，并为 `kotlin-maven-plugin` 提供插件管理。
使用 Gradle 时，Spring Boot 插件会自动将 `kotlin.version` 与 Kotlin 插件的版本对齐。

Spring Boot 还通过导入 Kotlin Coroutines BOM 来管理 Coroutines 依赖项的版本。
可以通过设置 `kotlin-coroutines.version` 属性来自定义版本。

TIP: 如果你在 https://start.spring.io/#!language=kotlin[start.spring.io] 上引导一个至少有一个响应式依赖项的 Kotlin 项目，默认会提供 `org.jetbrains.kotlinx:kotlinx-coroutines-reactor` 依赖项。



[[features.kotlin.configuration-properties]]
== @ConfigurationProperties
当与 xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.constructor-binding[构造函数绑定] 结合使用时，javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] 支持具有不可变 `val` 属性的数据类，如下例所示：

[source,kotlin]
----
@ConfigurationProperties("example.kotlin")
data class KotlinExampleProperties(
		val name: String,
		val description: String,
		val myService: MyService) {

	data class MyService(
			val apiToken: String,
			val uri: URI
	)
}
----

由于与 Java 的互操作性限制，对值类的支持有限。
特别是，依赖值类的默认值将无法与配置属性绑定一起工作。
在这种情况下，应该使用数据类。

TIP: 要使用注解处理器生成 xref:specification:configuration-metadata/annotation-processor.adoc[你自己的元数据]，应该使用 `spring-boot-configuration-processor` 依赖项配置 {url-kotlinlang.org}/kapt.html[`kapt`]。
注意，由于 kapt 提供的模型限制，某些功能（如检测默认值或已弃用项）无法工作。



[[features.kotlin.testing]]
== 测试

虽然可以使用 JUnit 4 测试 Kotlin 代码，但默认提供并推荐使用 JUnit 5。
JUnit 5 允许测试类实例化一次并重用于该类的所有测试。
这使得可以在非静态方法上使用 javadoc:org.junit.jupiter.api.BeforeAll[format=annotation] 和 javadoc:org.junit.jupiter.api.AfterAll[format=annotation] 注解，这非常适合 Kotlin。

要模拟 Kotlin 类，推荐使用 https://mockk.io/[MockK]。
如果你需要 Mockito 特定的 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.mocking-beans[`@MockitoBean` 和 javadoc:org.springframework.test.context.bean.override.mockito.MockitoSpyBean[format=annotation] 注解] 的 `MockK` 等效项，你可以使用 https://github.com/Ninja-Squad/springmockk[SpringMockK]，它提供了类似的 `@MockkBean` 和 `@SpykBean` 注解。



[[features.kotlin.resources]]
== 资源



[[features.kotlin.resources.further-reading]]
=== 进一步阅读

* {url-kotlinlang.org}[Kotlin 语言参考]
* https://kotlinlang.slack.com/[Kotlin Slack]（有专门的 #spring 频道）
* https://stackoverflow.com/questions/tagged/spring+kotlin[带有 `spring` 和 `kotlin` 标签的 Stack Overflow]
* https://try.kotlinlang.org/[在浏览器中尝试 Kotlin]
* https://blog.jetbrains.com/kotlin/[Kotlin 博客]
* https://kotlin.link/[Awesome Kotlin]
* https://spring.io/guides/tutorials/spring-boot-kotlin/[教程：使用 Spring Boot 和 Kotlin 构建 Web 应用程序]
* https://spring.io/blog/2016/02/15/developing-spring-boot-applications-with-kotlin[使用 Kotlin 开发 Spring Boot 应用程序]
* https://spring.io/blog/2016/03/20/a-geospatial-messenger-with-kotlin-spring-boot-and-postgresql[使用 Kotlin、Spring Boot 和 PostgreSQL 构建地理空间消息应用]
* https://spring.io/blog/2017/01/04/introducing-kotlin-support-in-spring-framework-5-0[在 Spring Framework 5.0 中引入 Kotlin 支持]
* https://spring.io/blog/2017/08/01/spring-framework-5-kotlin-apis-the-functional-way[Spring Framework 5 Kotlin API，函数式方式]



[[features.kotlin.resources.examples]]
=== 示例

* https://github.com/sdeleuze/spring-boot-kotlin-demo[spring-boot-kotlin-demo]：常规 Spring Boot + Spring Data JPA 项目
* https://github.com/mixitconf/mixit[mixit]：Spring Boot 2 + WebFlux + 响应式 Spring Data MongoDB
* https://github.com/sdeleuze/spring-kotlin-fullstack[spring-kotlin-fullstack]：使用 Kotlin2js 代替 JavaScript 或 TypeScript 的 WebFlux Kotlin 全栈示例
* https://github.com/spring-petclinic/spring-petclinic-kotlin[spring-petclinic-kotlin]：Spring PetClinic 示例应用程序的 Kotlin 版本
* https://github.com/sdeleuze/spring-kotlin-deepdive[spring-kotlin-deepdive]：从 Boot 1.0 + Java 到 Boot 2.0 + Kotlin 的逐步迁移
* https://github.com/sdeleuze/spring-boot-coroutines-demo[spring-boot-coroutines-demo]：协程示例项目
