[[features.logging]]
= 日志

Spring Boot 使用 https://commons.apache.org/logging[Commons Logging] 进行所有内部日志记录，但保持底层日志实现开放。
为 {apiref-openjdk}/java.logging/java/util/logging/package-summary.html[Java Util Logging]、 https://logging.apache.org/log4j/2.x/[Log4j2] 和 https://logback.qos.ch/[Logback] 提供了默认配置。
在每种情况下，日志记录器都预配置为使用控制台输出，同时也可选择文件输出。

默认情况下，如果你使用 starters，则使用 Logback 进行日志记录。
还包含了适当的 Logback 路由，以确保使用 Java Util Logging、Commons Logging、Log4J 或 SLF4J 的依赖库都能正常工作。

TIP: Java 有很多可用的日志框架。
如果上面的列表看起来令人困惑，请不要担心。
通常，你不需要更改日志依赖项，Spring Boot 的默认设置就能很好地工作。

TIP: 当你将应用程序部署到 servlet 容器或应用服务器时，使用 Java Util Logging API 执行的日志记录不会路由到应用程序的日志中。
这可以防止容器或已部署到其中的其他应用程序执行的日志记录出现在应用程序的日志中。



[[features.logging.log-format]]
== 日志格式

Spring Boot 的默认日志输出类似于以下示例：

[source]
----
include::ROOT:partial$logging/logging-format.txt[]
----

输出以下项目：

* 日期和时间：毫秒精度且易于排序。
* 日志级别：`ERROR`、`WARN`、`INFO`、`DEBUG` 或 `TRACE`。
* 进程 ID。
* `---` 分隔符，用于区分实际日志消息的开始。
* 应用程序名称：用方括号括起来（默认情况下仅在设置 configprop:spring.application.name[] 时记录）
* 应用程序组：用方括号括起来（默认情况下仅在设置 configprop:spring.application.group[] 时记录）
* 线程名称：用方括号括起来（控制台输出可能会被截断）。
* 关联 ID：如果启用了跟踪（上面的示例中未显示）
* 记录器名称：通常是源类名（通常缩写）。
* 日志消息。

NOTE: Logback 没有 `FATAL` 级别。
它被映射到 `ERROR`。

TIP: 如果你有 configprop:spring.application.name[] 属性但不想记录它，可以将 configprop:logging.include-application-name[] 设置为 `false`。

TIP: 如果你有 configprop:spring.application.group[] 属性但不想记录它，可以将 configprop:logging.include-application-group[] 设置为 `false`。

TIP: 有关关联 ID 的更多详细信息，请 xref:reference:actuator/tracing.adoc#actuator.micrometer-tracing.logging[参阅此文档]。



[[features.logging.console-output]]
== 控制台输出

默认的日志配置会在消息写入时将其回显到控制台。
默认情况下，记录 `ERROR` 级别、`WARN` 级别和 `INFO` 级别的消息。
你还可以通过使用 `--debug` 标志启动应用程序来启用"debug"模式。

[source,shell]
----
$ java -jar myapp.jar --debug
----

NOTE: 你也可以在 `application.properties` 中指定 `debug=true`。

启用调试模式时，会配置一组核心记录器（嵌入式容器、Hibernate 和 Spring Boot）以输出更多信息。
启用调试模式并_不会_配置你的应用程序以 `DEBUG` 级别记录所有消息。

或者，你可以通过使用 `--trace` 标志（或在 `application.properties` 中设置 `trace=true`）启动应用程序来启用"trace"模式。
这样做会为一组核心记录器（嵌入式容器、Hibernate 模式生成和整个 Spring 产品组合）启用跟踪日志记录。



[[features.logging.console-output.color-coded]]
=== 彩色编码输出

如果你的终端支持 ANSI，则使用彩色输出来提高可读性。
你可以将 `spring.output.ansi.enabled` 设置为 javadoc:org.springframework.boot.ansi.AnsiOutput$Enabled[支持的值] 来覆盖自动检测。

通过使用 `%clr` 转换字来配置颜色编码。
在最简单的形式中，转换器根据日志级别为输出着色，如下例所示：

[source]
----
%clr(%5p)
----

下表描述了日志级别到颜色的映射：

|===
| 级别 | 颜色

| `FATAL`
| 红色

| `ERROR`
| 红色

| `WARN`
| 黄色

| `INFO`
| 绿色

| `DEBUG`
| 绿色

| `TRACE`
| 绿色
|===

或者，你可以通过将其作为转换的选项来指定应使用的颜色或样式。
例如，要使文本变为黄色，请使用以下设置：

[source]
----
%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){yellow}
----

支持以下颜色和样式：

* `blue`
* `cyan`
* `faint`
* `green`
* `magenta`
* `red`
* `yellow`



[[features.logging.file-output]]
== 文件输出

默认情况下，Spring Boot 仅记录到控制台，不写入日志文件。
如果你想在控制台输出之外写入日志文件，需要设置 configprop:logging.file.name[] 或 configprop:logging.file.path[] 属性（例如，在你的 `application.properties` 中）。
如果同时设置了这两个属性，则忽略 `logging.file.path`，仅使用 `logging.file.name`。

下表显示了如何一起使用 `logging.*` 属性：

.日志属性
[cols="1,1,4"]
|===
| configprop:logging.file.name[] | configprop:logging.file.path[] | 描述

| _(无)_
| _(无)_
| 仅控制台日志记录。

| 特定文件（例如，`my.log`）
| _(无)_
| 写入到 `logging.file.name` 指定的位置。
  位置可以是绝对路径或相对于当前目录。

| _(无)_
| 特定目录（例如，`/var/log`）
| 将 `spring.log` 写入到 `logging.file.path` 指定的目录。
  目录可以是绝对路径或相对于当前目录。

| 特定文件
| 特定目录
| 写入到 `logging.file.name` 指定的位置，忽略 `logging.file.path`。
  位置可以是绝对路径或相对于当前目录。
|===

当日志文件达到 10 MB 时会进行轮转，与控制台输出一样，默认记录 `ERROR` 级别、`WARN` 级别和 `INFO` 级别的消息。

TIP: 日志属性与实际日志基础设施无关。
因此，Spring Boot 不管理特定的配置键（例如 Logback 的 `logback.configurationFile`）。



[[features.logging.file-rotation]]
== 文件轮转

如果你使用 Logback，可以通过 `application.properties` 或 `application.yaml` 文件微调日志轮转设置。
对于所有其他日志系统，你需要直接自己配置轮转设置（例如，如果你使用 Log4j2，则可以添加 `log4j2.xml` 或 `log4j2-spring.xml` 文件）。

支持以下轮转策略属性：

|===
| 名称 | 描述

| configprop:logging.logback.rollingpolicy.file-name-pattern[]
| 用于创建日志归档的文件名模式。

| configprop:logging.logback.rollingpolicy.clean-history-on-start[]
| 是否在应用程序启动时清理日志归档。

| configprop:logging.logback.rollingpolicy.max-file-size[]
| 归档前的日志文件最大大小。

| configprop:logging.logback.rollingpolicy.total-size-cap[]
| 删除前日志归档可以占用的最大大小。

| configprop:logging.logback.rollingpolicy.max-history[]
| 保留的归档日志文件的最大数量（默认为 7）。
|===



[[features.logging.log-levels]]
== 日志级别

所有支持的日志系统都可以在 Spring javadoc:org.springframework.core.env.Environment[] 中设置记录器级别（例如，在 `application.properties` 中），方法是使用 `+logging.level.<logger-name>=<level>+`，其中 `level` 是 TRACE、DEBUG、INFO、WARN、ERROR、FATAL 或 OFF 之一。
可以通过使用 `logging.level.root` 来配置 `root` 记录器。

以下示例显示了 `application.properties` 中可能的日志设置：

[configprops,yaml]
----
logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"
----

也可以使用环境变量设置日志级别。
例如，`LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG` 会将 `org.springframework.web` 设置为 `DEBUG`。

NOTE: 上述方法仅适用于包级别的日志记录。
由于宽松绑定 xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.relaxed-binding.maps-from-environment-variables[总是将环境变量转换为小写]，因此无法以这种方式为单个类配置日志记录。
如果你需要为类配置日志记录，可以使用 xref:features/external-config.adoc#features.external-config.application-json[`SPRING_APPLICATION_JSON`] 变量。



[[features.logging.log-groups]]
== 日志组

通常能够将相关的记录器分组在一起，以便可以同时配置它们，这很有用。
例如，你可能经常更改_所有_ Tomcat 相关记录器的日志级别，但你很难记住顶级包。

为了帮助解决这个问题，Spring Boot 允许你在 Spring javadoc:org.springframework.core.env.Environment[] 中定义日志组。
例如，以下是如何通过将其添加到 `application.properties` 来定义"`tomcat`"组：

[configprops,yaml]
----
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
----

定义后，你可以用一行代码更改组中所有记录器的级别：

[configprops,yaml]
----
logging:
  level:
    tomcat: "trace"
----

Spring Boot 包含以下预定义的日志组，可以直接使用：

[cols="1,4"]
|===
| 名称 | 记录器

| web
| `org.springframework.core.codec`, `org.springframework.http`, `org.springframework.web`, `org.springframework.boot.actuate.endpoint.web`, `org.springframework.boot.web.servlet.ServletContextInitializerBeans`

| sql
| `org.springframework.jdbc.core`, `org.hibernate.SQL`, javadoc:org.jooq.tools.LoggerListener[]
|===



[[features.logging.shutdown-hook]]
== 使用日志关闭钩子

为了在应用程序终止时释放日志资源，提供了一个关闭钩子，它将在 JVM 退出时触发日志系统清理。
除非你的应用程序部署为 war 文件，否则会自动注册此关闭钩子。
如果你的应用程序具有复杂的上下文层次结构，关闭钩子可能无法满足你的需求。
如果确实如此，请禁用关闭钩子并直接研究底层日志系统提供的选项。
例如，Logback 提供 https://logback.qos.ch/manual/loggingSeparation.html[上下文选择器]，允许每个 Logger 在其自己的上下文中创建。
你可以使用 configprop:logging.register-shutdown-hook[] 属性禁用关闭钩子。
将其设置为 `false` 将禁用注册。
你可以在 `application.properties` 或 `application.yaml` 文件中设置该属性：

[configprops,yaml]
----
logging:
  register-shutdown-hook: false
----



[[features.logging.custom-log-configuration]]
== 自定义日志配置

通过在类路径上包含适当的库可以激活各种日志系统，并且可以通过在类路径的根目录或由以下 Spring javadoc:org.springframework.core.env.Environment[] 属性指定的位置提供适当的配置文件来进一步自定义：configprop:logging.config[]。

你可以通过使用 `org.springframework.boot.logging.LoggingSystem` 系统属性强制 Spring Boot 使用特定的日志系统。
该值应该是 javadoc:org.springframework.boot.logging.LoggingSystem[] 实现的完全限定类名。
你还可以通过使用值 `none` 完全禁用 Spring Boot 的日志配置。

NOTE: 由于日志记录是在创建 javadoc:org.springframework.context.ApplicationContext[] *之前*初始化的，因此无法从 Spring javadoc:org.springframework.context.annotation.Configuration[format=annotation] 文件中的 javadoc:org.springframework.context.annotation.PropertySources[format=annotation] 控制日志记录。
更改日志系统或完全禁用它只能通过系统属性来实现。

根据你的日志系统，加载以下文件：

|===
| 日志系统 | 自定义

| Logback
| `logback-spring.xml`、`logback-spring.groovy`、`logback.xml` 或 `logback.groovy`

| Log4j2
| `log4j2-spring.xml` 或 `log4j2.xml`

| JDK (Java Util Logging)
| `logging.properties`
|===

NOTE: 如果可能，我们建议你使用日志配置的 `-spring` 变体（例如，使用 `logback-spring.xml` 而不是 `logback.xml`）。
如果你使用标准配置位置，Spring 无法完全控制日志初始化。

WARNING: Java Util Logging 存在已知的类加载问题，在从"可执行 jar"运行时会导致问题。
如果可能，我们建议你在从"可执行 jar"运行时避免使用它。

为了帮助自定义，一些其他属性从 Spring javadoc:org.springframework.core.env.Environment[] 传输到系统属性。
这允许日志系统配置使用这些属性。例如，在 `application.properties` 中设置 `logging.file.name` 或设置环境变量 `LOGGING_FILE_NAME` 将导致设置 `LOG_FILE` 系统属性。
下表描述了传输的属性：

|===
| Spring Environment | 系统属性 | 注释

| configprop:logging.exception-conversion-word[]
| `LOG_EXCEPTION_CONVERSION_WORD`
| 记录异常时使用的转换字。

| configprop:logging.file.name[]
| `LOG_FILE`
| 如果定义，则在默认日志配置中使用。

| configprop:logging.file.path[]
| `LOG_PATH`
| 如果定义，则在默认日志配置中使用。

| configprop:logging.pattern.console[]
| `CONSOLE_LOG_PATTERN`
| 在控制台（stdout）上使用的日志模式。

| configprop:logging.pattern.dateformat[]
| `LOG_DATEFORMAT_PATTERN`
| 日志日期格式的追加器模式。

| configprop:logging.charset.console[]
| `CONSOLE_LOG_CHARSET`
| 用于控制台日志记录的字符集。

| configprop:logging.threshold.console[]
| `CONSOLE_LOG_THRESHOLD`
| 用于控制台日志记录的日志级别阈值。

| configprop:logging.pattern.file[]
| `FILE_LOG_PATTERN`
| 在文件中使用的日志模式（如果启用了 `LOG_FILE`）。

| configprop:logging.charset.file[]
| `FILE_LOG_CHARSET`
| 用于文件日志记录的字符集（如果启用了 `LOG_FILE`）。

| configprop:logging.threshold.file[]
| `FILE_LOG_THRESHOLD`
| 用于文件日志记录的日志级别阈值。

| configprop:logging.pattern.level[]
| `LOG_LEVEL_PATTERN`
| 渲染日志级别时使用的格式（默认为 `%5p`）。

| configprop:logging.structured.format.console[]
| `CONSOLE_LOG_STRUCTURED_FORMAT`
| 用于控制台日志记录的结构化日志格式。

| configprop:logging.structured.format.file[]
| `FILE_LOG_STRUCTURED_FORMAT`
| 用于文件日志记录的结构化日志格式。

| `PID`
| `PID`
| 当前进程 ID（如果可能且尚未定义为 OS 环境变量，则会被发现）。
|===

如果你使用 Logback，还会传输以下属性：

|===
| Spring Environment | 系统属性 | 注释

| configprop:logging.logback.rollingpolicy.file-name-pattern[]
| `LOGBACK_ROLLINGPOLICY_FILE_NAME_PATTERN`
| 轮转日志文件名的模式（默认为 `$\{LOG_FILE}.%d\{yyyy-MM-dd}.%i.gz`）。

| configprop:logging.logback.rollingpolicy.clean-history-on-start[]
| `LOGBACK_ROLLINGPOLICY_CLEAN_HISTORY_ON_START`
| 是否在启动时清理归档日志文件。

| configprop:logging.logback.rollingpolicy.max-file-size[]
| `LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE`
| 最大日志文件大小。

| configprop:logging.logback.rollingpolicy.total-size-cap[]
| `LOGBACK_ROLLINGPOLICY_TOTAL_SIZE_CAP`
| 要保留的日志备份的总大小。

| configprop:logging.logback.rollingpolicy.max-history[]
| `LOGBACK_ROLLINGPOLICY_MAX_HISTORY`
| 要保留的归档日志文件的最大数量。
|===

所有支持的日志系统在解析其配置文件时都可以查询系统属性。
有关示例，请参阅 `spring-boot.jar` 中的默认配置：

* {code-spring-boot}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml[Logback]
* {code-spring-boot}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml[Log4j 2]
* {code-spring-boot}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/java/logging-file.properties[Java Util logging]

[TIP]
====
如果你想在日志属性中使用占位符，应该使用 xref:features/external-config.adoc#features.external-config.files.property-placeholders[Spring Boot 的语法]，而不是底层框架的语法。
特别是，如果你使用 Logback，应该使用 `:` 作为属性名和其默认值之间的分隔符，而不是使用 `:-`。
====

[TIP]
====
你可以通过仅覆盖 `LOG_LEVEL_PATTERN`（或使用 Logback 的 `logging.pattern.level`）来添加 MDC 和其他临时内容到日志行。
例如，如果你使用 `logging.pattern.level=user:%X\{user} %5p`，则默认日志格式包含"user"的 MDC 条目（如果存在），如下例所示。

[source]
----
2019-08-30 12:30:04.031 user:someone INFO 22174 --- [  nio-8080-exec-0] demo.Controller
Handling authenticated request
----
====



[[features.logging.structured]]
== 结构化日志

结构化日志是一种将日志输出以明确定义的、通常机器可读的格式写入的技术。
Spring Boot 支持结构化日志，并默认支持以下 JSON 格式：

* xref:#features.logging.structured.ecs[Elastic Common Schema (ECS)]
* xref:#features.logging.structured.gelf[Graylog Extended Log Format (GELF)]
* xref:#features.logging.structured.logstash[Logstash]

要启用结构化日志，请将 configprop:logging.structured.format.console[]（用于控制台输出）或 configprop:logging.structured.format.file[]（用于文件输出）属性设置为你想要使用的格式的 id。

如果你使用 xref:#features.logging.custom-log-configuration[自定义日志配置]，请更新你的配置以支持 `CONSOLE_LOG_STRUCTURED_FORMAT` 和 `FILE_LOG_STRUCTURED_FORMAT` 系统属性。
以 `CONSOLE_LOG_STRUCTURED_FORMAT` 为例：
[tabs]
======
Logback::
+
[source,xml]
----
<!-- replace your encoder with StructuredLogEncoder -->
<encoder class="org.springframework.boot.logging.logback.StructuredLogEncoder">
	<format>${CONSOLE_LOG_STRUCTURED_FORMAT}</format>
	<charset>${CONSOLE_LOG_CHARSET}</charset>
</encoder>
----
+
你还可以参考 Spring Boot 中包含的默认配置：
+
* {code-spring-boot}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/structured-console-appender.xml[Logback Structured Console Appender]
* {code-spring-boot}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/structured-file-appender.xml[Logback Structured File Appender]
Log4j2::
+
[source,xml]
----
<!-- replace your PatternLayout with StructuredLogLayout -->
<StructuredLogLayout format="${sys:CONSOLE_LOG_STRUCTURED_FORMAT}" charset="${sys:CONSOLE_LOG_CHARSET}"/>
----
+
你还可以参考 Spring Boot 中包含的默认配置：
+
* {code-spring-boot}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml[Log4j2 Console Appender]
* {code-spring-boot}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2-file.xml[Log4j2 Console and File Appender]
======


[[features.logging.structured.ecs]]
=== Elastic Common Schema

https://www.elastic.co/guide/en/ecs/8.11/ecs-reference.html[Elastic Common Schema] 是一种基于 JSON 的日志格式。

要启用 Elastic Common Schema 日志格式，请将相应的 `format` 属性设置为 `ecs`：

[configprops,yaml]
----
logging:
  structured:
    format:
      console: ecs
      file: ecs
----

日志行看起来像这样：

[source,json]
----
{"@timestamp":"2024-01-01T10:15:00.067462556Z","log":{"level":"INFO","logger":"org.example.Application"},"process":{"pid":39599,"thread":{"name":"main"}},"service":{"name":"simple"},"message":"No active profile set, falling back to 1 default profile: \"default\"","ecs":{"version":"8.11"}}
----

此格式还会将 MDC 中包含的每个键值对添加到 JSON 对象中。
你还可以使用 https://www.slf4j.org/manual.html#fluent[SLF4J fluent logging API] 通过 https://www.slf4j.org/apidocs/org/slf4j/spi/LoggingEventBuilder.html#addKeyValue(java.lang.String,java.lang.Object)[addKeyValue] 方法将键值对添加到记录的 JSON 对象中。

可以使用 `logging.structured.ecs.service` 属性自定义 `service` 值：

[configprops,yaml]
----
logging:
  structured:
    ecs:
      service:
        name: MyService
        version: 1.0
        environment: Production
        node-name: Primary
----

NOTE: 如果未指定，configprop:logging.structured.ecs.service.name[] 将默认为 configprop:spring.application.name[]。

NOTE: 如果未指定，configprop:logging.structured.ecs.service.version[] 将默认为 configprop:spring.application.version[]。



[[features.logging.structured.gelf]]
=== Graylog Extended Log Format (GELF)

https://go2docs.graylog.org/current/getting_in_log_data/gelf.html[Graylog Extended Log Format] 是 Graylog 日志分析平台的基于 JSON 的日志格式。

要启用 Graylog Extended Log Format，请将相应的 `format` 属性设置为 `gelf`：

[configprops,yaml]
----
logging:
  structured:
    format:
      console: gelf
      file: gelf
----

日志行看起来像这样：

[source,json]
----
{"version":"1.1","short_message":"No active profile set, falling back to 1 default profile: \"default\"","timestamp":1725958035.857,"level":6,"_level_name":"INFO","_process_pid":47649,"_process_thread_name":"main","_log_logger":"org.example.Application"}
----

此格式还会将 MDC 中包含的每个键值对添加到 JSON 对象中。
你还可以使用 https://www.slf4j.org/manual.html#fluent[SLF4J fluent logging API] 通过 https://www.slf4j.org/apidocs/org/slf4j/spi/LoggingEventBuilder.html#addKeyValue(java.lang.String,java.lang.Object)[addKeyValue] 方法将键值对添加到记录的 JSON 对象中。

可以使用 `logging.structured.gelf` 属性自定义多个字段：

[configprops,yaml]
----
logging:
  structured:
    gelf:
      host: MyService
      service:
        version: 1.0
----

NOTE: 如果未指定，configprop:logging.structured.gelf.host[] 将默认为 configprop:spring.application.name[]。

NOTE: 如果未指定，configprop:logging.structured.gelf.service.version[] 将默认为 configprop:spring.application.version[]。



[[features.logging.structured.logstash]]
=== Logstash JSON 格式

https://github.com/logfellow/logstash-logback-encoder?tab=readme-ov-file#standard-fields[Logstash JSON 格式] 是一种基于 JSON 的日志格式。

要启用 Logstash JSON 日志格式，请将相应的 `format` 属性设置为 `logstash`：

[configprops,yaml]
----
logging:
  structured:
    format:
      console: logstash
      file: logstash
----

日志行看起来像这样：

[source,json]
----
{"@timestamp":"2024-01-01T10:15:00.111037681+02:00","@version":"1","message":"No active profile set, falling back to 1 default profile: \"default\"","logger_name":"org.example.Application","thread_name":"main","level":"INFO","level_value":20000}
----

此格式还会将 MDC 中包含的每个键值对添加到 JSON 对象中。
你还可以使用 https://www.slf4j.org/manual.html#fluent[SLF4J fluent logging API] 通过 https://www.slf4j.org/apidocs/org/slf4j/spi/LoggingEventBuilder.html#addKeyValue(java.lang.String,java.lang.Object)[addKeyValue] 方法将键值对添加到记录的 JSON 对象中。

如果你添加 https://www.slf4j.org/api/org/slf4j/Marker.html[markers]，这些将显示在 JSON 的 `tags` 字符串数组中。



[[features.logging.structured.customizing-json]]
=== 自定义结构化日志 JSON

Spring Boot 尝试为结构化日志输出的 JSON 名称和值选择合理的默认值。
但是，有时你可能需要根据自己的需求对 JSON 进行小的调整。
例如，你可能想要更改一些名称以匹配你的日志摄取系统的期望。
你可能还想过滤掉某些成员，因为你发现它们没有用。

以下属性允许你更改结构化日志 JSON 的写入方式：

|===
| 属性 | 描述

| configprop:logging.structured.json.include[] & configprop:logging.structured.json.exclude[]
| 从 JSON 中过滤特定路径

| configprop:logging.structured.json.rename[]
| 重命名 JSON 中的特定成员

| configprop:logging.structured.json.add[]
| 向 JSON 添加其他成员
|===

例如，以下将排除 `log.level`，将 `process.id` 重命名为 `procid` 并添加固定的 `corpname` 字段：

[configprops,yaml]
----
logging:
  structured:
    json:
      exclude: log.level
      rename:
        process.id: procid
      add:
        corpname: mycorp
----

TIP: 对于更高级的自定义，你可以使用 javadoc:org.springframework.boot.logging.structured.StructuredLoggingJsonMembersCustomizer[] 接口。
你可以使用 configprop:logging.structured.json.customizer[] 属性引用一个或多个实现。
你还可以通过在 `META-INF/spring.factories` 文件中列出它们来声明实现。



[[features.logging.structured.customizing-stack-traces]]
=== 自定义结构化日志堆栈跟踪

每当使用异常记录消息时，完整的堆栈跟踪都会包含在 JSON 输出中。
这些信息量可能对你的日志摄取系统来说处理成本很高，因此你可能想要调整堆栈跟踪的打印方式。

为此，你可以使用以下一个或多个属性：

|===
| 属性 | 描述

| configprop:logging.structured.json.stacktrace.root[]
| 使用 `last` 最后打印根项（与 Java 相同）或使用 `first` 首先打印根项。

| configprop:logging.structured.json.stacktrace.max-length[]
| 应该打印的最大长度

| configprop:logging.structured.json.stacktrace.max-throwable-depth[]
| 每个堆栈跟踪要打印的最大帧数（包括公共帧和抑制帧）

| configprop:logging.structured.json.stacktrace.include-common-frames[]
| 是否应该包含或删除公共帧

| configprop:logging.structured.json.stacktrace.include-hashes[]
| 是否应该包含堆栈跟踪的哈希值
|===

例如，以下将使用根优先堆栈跟踪，限制其长度，并包含哈希值。

[configprops,yaml]
----
logging:
  structured:
    json:
      stacktrace:
        root: first
        max-length: 1024
        include-common-frames: true
        include-hashes: true
----

[TIP]
====
如果你需要完全控制堆栈跟踪打印，可以将 configprop:logging.structured.json.stacktrace.printer[] 设置为 javadoc:org.springframework.boot.logging.StackTracePrinter[] 实现的名称。
你还可以将其设置为 `logging-system` 以强制使用常规日志系统堆栈跟踪输出。

如果你的 `StackTracePrinter` 实现希望进一步自定义从属性创建的堆栈跟踪打印机，它还可以包含一个接受 javadoc:org.springframework.boot.logging.StandardStackTracePrinter[] 的构造函数参数。
====



[[features.logging.structured.other-formats]]
=== 支持其他结构化日志格式

Spring Boot 中的结构化日志支持是可扩展的，允许你定义自己的自定义格式。
为此，实现 javadoc:org.springframework.boot.logging.structured.StructuredLogFormatter[] 接口。使用 Logback 时，泛型类型参数必须是 javadoc:ch.qos.logback.classic.spi.ILoggingEvent[]，使用 Log4j2 时必须是 javadoc:org.apache.logging.log4j.core.LogEvent[]（这意味着你的实现与特定的日志系统绑定）。
然后使用日志事件调用你的实现，并返回要记录的 javadoc:java.lang.String[]，如下例所示：

include-code::MyCustomFormat[]

如你在示例中所见，你可以返回任何格式，不必是 JSON。

要启用你的自定义格式，请将 configprop:logging.structured.format.console[] 或 configprop:logging.structured.format.file[] 属性设置为你实现的完全限定类名。

你的实现可以使用一些构造函数参数，这些参数会自动注入。
有关更多详细信息，请参阅 javadoc:org.springframework.boot.logging.structured.StructuredLogFormatter[] 的 JavaDoc。



[[features.logging.logback-extensions]]
== Logback 扩展

Spring Boot 包含许多 Logback 扩展，可以帮助进行高级配置。
你可以在 `logback-spring.xml` 配置文件中使用这些扩展。

NOTE: 由于标准 `logback.xml` 配置文件加载太早，你不能在其中使用扩展。
你需要使用 `logback-spring.xml` 或定义 configprop:logging.config[] 属性。

WARNING: 这些扩展不能与 Logback 的 https://logback.qos.ch/manual/configuration.html#autoScan[配置扫描]一起使用。
如果你尝试这样做，对配置文件进行更改会导致记录类似于以下之一的错误：

[source]
----
ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:71 - no applicable action for [springProperty], current ElementPath is [[configuration][springProperty]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:71 - no applicable action for [springProfile], current ElementPath is [[configuration][springProfile]]
----



[[features.logging.logback-extensions.profile-specific]]
=== 特定配置文件配置

`<springProfile>` 标签允许你根据活动的 Spring profiles 选择性地包含或排除配置部分。
配置文件部分在 `<configuration>` 元素内的任何位置都受支持。
使用 `name` 属性指定哪个配置文件接受配置。
`<springProfile>` 标签可以包含配置文件名称（例如 `staging`）或配置文件表达式。
配置文件表达式允许表达更复杂的配置文件逻辑，例如 `production & (eu-central | eu-west)`。
有关更多详细信息，请查看 {url-spring-framework-docs}/core/beans/environment.html#beans-definition-profiles-java[Spring Framework 参考指南]。
以下列表显示了三个示例配置文件：

[source,xml]
----
<springProfile name="staging">
	<!-- configuration to be enabled when the "staging" profile is active -->
</springProfile>

<springProfile name="dev | staging">
	<!-- configuration to be enabled when the "dev" or "staging" profiles are active -->
</springProfile>

<springProfile name="!production">
	<!-- configuration to be enabled when the "production" profile is not active -->
</springProfile>
----



[[features.logging.logback-extensions.environment-properties]]
=== 环境属性

`<springProperty>` 标签允许你暴露 Spring javadoc:org.springframework.core.env.Environment[] 中的属性以供 Logback 使用。
如果你想在 Logback 配置中访问 `application.properties` 文件中的值，这很有用。
该标签的工作方式与 Logback 的标准 `<property>` 标签类似。
但是，不是指定直接的 `value`，而是指定属性的 `source`（来自 javadoc:org.springframework.core.env.Environment[]）。
如果你需要将属性存储在 `local` 作用域之外，可以使用 `scope` 属性。
如果你需要一个后备值（以防属性未在 javadoc:org.springframework.core.env.Environment[] 中设置），可以使用 `defaultValue` 属性。
以下示例显示了如何暴露属性以供 Logback 使用：

[source,xml]
----
<springProperty scope="context" name="fluentHost" source="myapp.fluentd.host"
		defaultValue="localhost"/>
<appender name="FLUENT" class="ch.qos.logback.more.appenders.DataFluentAppender">
	<remoteHost>${fluentHost}</remoteHost>
	...
</appender>
----

NOTE: `source` 必须使用 kebab case 指定（例如 `my.property-name`）。
但是，可以使用宽松规则将属性添加到 javadoc:org.springframework.core.env.Environment[] 中。



[[features.logging.log4j2-extensions]]
== Log4j2 扩展

Spring Boot 包含许多 Log4j2 扩展，可以帮助进行高级配置。
你可以在任何 `log4j2-spring.xml` 配置文件中使用这些扩展。

NOTE: 由于标准 `log4j2.xml` 配置文件加载太早，你不能在其中使用扩展。
你需要使用 `log4j2-spring.xml` 或定义 configprop:logging.config[] 属性。

NOTE: 这些扩展取代了 Log4J 提供的 https://logging.apache.org/log4j/2.x/log4j-spring-boot.html[Spring Boot 支持]。
你应该确保不要在构建中包含 `org.apache.logging.log4j:log4j-spring-boot` 模块。



[[features.logging.log4j2-extensions.profile-specific]]
=== 特定配置文件配置

`<SpringProfile>` 标签允许你根据活动的 Spring profiles 选择性地包含或排除配置部分。
配置文件部分在 `<Configuration>` 元素内的任何位置都受支持。
使用 `name` 属性指定哪个配置文件接受配置。
`<SpringProfile>` 标签可以包含配置文件名称（例如 `staging`）或配置文件表达式。
配置文件表达式允许表达更复杂的配置文件逻辑，例如 `production & (eu-central | eu-west)`。
有关更多详细信息，请查看 {url-spring-framework-docs}/core/beans/environment.html#beans-definition-profiles-java[Spring Framework 参考指南]。
以下列表显示了三个示例配置文件：

[source,xml]
----
<SpringProfile name="staging">
	<!-- configuration to be enabled when the "staging" profile is active -->
</SpringProfile>

<SpringProfile name="dev | staging">
	<!-- configuration to be enabled when the "dev" or "staging" profiles are active -->
</SpringProfile>

<SpringProfile name="!production">
	<!-- configuration to be enabled when the "production" profile is not active -->
</SpringProfile>
----



[[features.logging.log4j2-extensions.environment-properties-lookup]]
=== 环境属性查找

如果你想在 Log4j2 配置中引用 Spring javadoc:org.springframework.core.env.Environment[] 中的属性，可以使用带有 `spring:` 前缀的 https://logging.apache.org/log4j/2.x/manual/lookups.html[lookups]。
如果你想在 Log4j2 配置中访问 `application.properties` 文件中的值，这很有用。

以下示例显示了如何设置名为 `applicationName` 和 `applicationGroup` 的 Log4j2 属性，这些属性从 Spring javadoc:org.springframework.core.env.Environment[] 中读取 `spring.application.name` 和 `spring.application.group`：

[source,xml]
----
<Properties>
	<Property name="applicationName">${spring:spring.application.name}</Property>
	<Property name="applicationGroup">${spring:spring.application.group}</Property>
</Properties>
----

NOTE: 查找键应该使用 kebab case 指定（例如 `my.property-name`）。



[[features.logging.log4j2-extensions.environment-property-source]]
=== Log4j2 系统属性

Log4j2 支持许多 https://logging.apache.org/log4j/2.x/manual/systemproperties.html[系统属性]，可用于配置各种项目。
例如，`log4j2.skipJansi` 系统属性可用于配置 javadoc:org.apache.logging.log4j.core.appender.ConsoleAppender[] 是否尝试在 Windows 上使用 https://github.com/fusesource/jansi[Jansi] 输出流。

在 Log4j2 初始化之后加载的所有系统属性都可以从 Spring javadoc:org.springframework.core.env.Environment[] 中获取。
例如，你可以在 `application.properties` 文件中添加 `log4j2.skipJansi=false`，以使 javadoc:org.apache.logging.log4j.core.appender.ConsoleAppender[] 在 Windows 上使用 Jansi。

NOTE: 仅当系统属性和操作系统环境变量不包含正在加载的值时，才会考虑 Spring javadoc:org.springframework.core.env.Environment[]。

WARNING: 在 Log4j2 早期初始化期间加载的系统属性不能引用 Spring javadoc:org.springframework.core.env.Environment[]。
例如，Log4j2 用于选择默认 Log4j2 实现的属性在 Spring Environment 可用之前就被使用了。
