[[features.task-execution-and-scheduling]]
= 任务执行与调度

如果上下文中没有 javadoc:java.util.concurrent.Executor[] bean，Spring Boot 会自动配置一个 javadoc:org.springframework.core.task.AsyncTaskExecutor[]。
当启用虚拟线程（使用 Java 21+ 且 configprop:spring.threads.virtual.enabled[] 设置为 `true`）时，将使用基于虚拟线程的 javadoc:org.springframework.core.task.SimpleAsyncTaskExecutor[]。
否则，将使用带有合理默认值的 javadoc:org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor[]。

除非定义了自定义 javadoc:java.util.concurrent.Executor[] bean，否则自动配置的 javadoc:org.springframework.core.task.AsyncTaskExecutor[] 会用于以下集成场景：

- 使用 javadoc:org.springframework.scheduling.annotation.EnableAsync[format=annotation] 执行异步任务，除非定义了 javadoc:org.springframework.scheduling.annotation.AsyncConfigurer[] 类型的 bean。
- Spring for GraphQL 中控制器方法返回 javadoc:java.util.concurrent.Callable[] 的异步处理。
- Spring MVC 的异步请求处理。
- Spring WebFlux 的阻塞执行支持。
- Spring WebSocket 的入站和出站消息通道。
- JPA 的引导执行器，基于 JPA 仓库的引导模式。
- `ApplicationContext` 中 bean 的 {url-spring-framework-docs}/core/beans/java/composing-configuration-classes.html#beans-java-startup-background[后台初始化] 的引导执行器。

虽然这种方式适用于大多数场景，Spring Boot 允许你覆盖自动配置的 javadoc:org.springframework.core.task.AsyncTaskExecutor[]。
默认情况下，当注册了自定义 javadoc:java.util.concurrent.Executor[] bean 时，自动配置的 javadoc:org.springframework.core.task.AsyncTaskExecutor[] 会让位，常规任务执行（通过 javadoc:org.springframework.scheduling.annotation.EnableAsync[format=annotation]）将使用自定义 javadoc:java.util.concurrent.Executor[]。

但 Spring MVC、Spring WebFlux 和 Spring GraphQL 都要求存在名为 `applicationTaskExecutor` 的 bean。
对于 Spring MVC 和 Spring WebFlux，该 bean 必须为 javadoc:org.springframework.core.task.AsyncTaskExecutor[] 类型，而 Spring GraphQL 不强制类型要求。

Spring WebSocket 和 JPA 会在存在单个 javadoc:org.springframework.core.task.AsyncTaskExecutor[] 类型 bean 或定义了名为 `applicationTaskExecutor` 的 bean 时使用该类型。

最后，`ApplicationContext` 的引导执行器会使用名为 `applicationTaskExecutor` 的 bean，除非定义了名为 `bootstrapExecutor` 的 bean。

以下代码片段演示了如何注册自定义 javadoc:org.springframework.core.task.AsyncTaskExecutor[]，以供 Spring MVC、Spring WebFlux、Spring GraphQL、Spring WebSocket、JPA 及 bean 后台初始化使用。

include-code::application/MyTaskExecutorConfiguration[]

[NOTE]
====
如果应用上下文中不存在 javadoc:org.springframework.context.annotation.Primary[format=annotation] bean 或名为 `taskExecutor` 的 javadoc:java.util.concurrent.Executor[] 或 javadoc:org.springframework.scheduling.annotation.AsyncConfigurer[] 类型 bean，则 `applicationTaskExecutor` bean 也会用于常规任务执行。
====

[WARNING]
====
如果既没有自动配置的 `AsyncTaskExecutor`，也没有定义 `applicationTaskExecutor` bean，则应用会默认使用名为 `taskExecutor` 的 bean 进行常规任务执行（javadoc:org.springframework.scheduling.annotation.EnableAsync[format=annotation]），这与 Spring Framework 的行为一致。
但该 bean 不会被 Spring MVC、Spring WebFlux、Spring GraphQL 使用。
不过，如果该 bean 类型为 javadoc:org.springframework.core.task.AsyncTaskExecutor[]，则可被 Spring WebSocket 或 JPA 使用。
====

如果你的应用需要为不同集成场景配置多个 `Executor` bean，例如为常规任务执行（javadoc:org.springframework.scheduling.annotation.EnableAsync[format=annotation]）和为 Spring MVC、Spring WebFlux、Spring WebSocket、JPA 分别配置不同的执行器，可以如下配置。

include-code::multiple/MyTaskExecutorConfiguration[]

[TIP]
====
自动配置的 javadoc:org.springframework.boot.task.ThreadPoolTaskExecutorBuilder[] 或 javadoc:org.springframework.boot.task.SimpleAsyncTaskExecutorBuilder[] 可帮助你轻松创建 javadoc:org.springframework.core.task.AsyncTaskExecutor[] 实例，复现自动配置的默认行为。

include-code::builder/MyTaskExecutorConfiguration[]
====

如果无法使用名为 `taskExecutor` 的 bean，可以将 bean 标记为 javadoc:org.springframework.context.annotation.Primary[format=annotation]，或定义 javadoc:org.springframework.scheduling.annotation.AsyncConfigurer[] bean，指定用于常规任务执行（javadoc:org.springframework.scheduling.annotation.EnableAsync[format=annotation]）的 `Executor`。
以下示例演示了如何实现。

include-code::async/MyTaskExecutorConfiguration[]

如需在保留自动配置的 javadoc:org.springframework.core.task.AsyncTaskExecutor[] 的同时注册自定义 javadoc:java.util.concurrent.Executor[]，可创建自定义 javadoc:java.util.concurrent.Executor[] bean，并在其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 注解中设置 `defaultCandidate=false`，如下所示：

include-code::defaultcandidate/MyTaskExecutorConfiguration[]

此时，你可以将自定义 javadoc:java.util.concurrent.Executor[] 自动注入到其他组件，同时保留自动配置的 javadoc:org.springframework.core.task.AsyncTaskExecutor[]。
但请记得结合使用 javadoc:org.springframework.beans.factory.annotation.Qualifier[format=annotation] 和 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注解。

如果无法满足上述条件，可以如下方式请求 Spring Boot 仍然自动配置 javadoc:org.springframework.core.task.AsyncTaskExecutor[]：

[configprops,yaml]
----
spring:
  task:
    execution:
      mode: force
----

自动配置的 javadoc:org.springframework.core.task.AsyncTaskExecutor[] 会自动用于所有集成场景，即使注册了自定义 javadoc:java.util.concurrent.Executor[] bean，包括被标记为 javadoc:org.springframework.context.annotation.Primary[format=annotation] 的 bean。
这些集成场景包括：

- 异步任务执行（javadoc:org.springframework.scheduling.annotation.EnableAsync[format=annotation]），除非存在 javadoc:org.springframework.scheduling.annotation.AsyncConfigurer[] bean。
- Spring for GraphQL 控制器方法返回 javadoc:java.util.concurrent.Callable[] 的异步处理。
- Spring MVC 的异步请求处理。
- Spring WebFlux 的阻塞执行支持。
- Spring WebSocket 的入站和出站消息通道。
- JPA 的引导执行器，基于 JPA 仓库的引导模式。
- `ApplicationContext` 中 bean 的 {url-spring-framework-docs}/core/beans/java/composing-configuration-classes.html#beans-java-startup-background[后台初始化] 的引导执行器，除非定义了名为 `bootstrapExecutor` 的 bean。

[TIP]
====
根据你的目标安排，可以将 configprop:spring.task.execution.mode[] 设置为 `force`，以自动配置 `applicationTaskExecutor`，也可以将自定义 javadoc:java.util.concurrent.Executor[] 转为 javadoc:org.springframework.core.task.AsyncTaskExecutor[]，或同时定义 javadoc:org.springframework.core.task.AsyncTaskExecutor[] 和 javadoc:org.springframework.scheduling.annotation.AsyncConfigurer[]，包装你的自定义 javadoc:java.util.concurrent.Executor[]。
====

[WARNING]
====
启用 `force` 模式后，即使存在 javadoc:org.springframework.context.annotation.Primary[format=annotation] bean 或名为 `taskExecutor` 的 javadoc:java.util.concurrent.Executor[]，`applicationTaskExecutor` 也会被配置用于常规任务执行（javadoc:org.springframework.scheduling.annotation.EnableAsync[format=annotation]）。
唯一覆盖常规任务执行 `Executor` 的方式是注册 javadoc:org.springframework.scheduling.annotation.AsyncConfigurer[] bean。
====

当自动配置 javadoc:org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor[] 时，线程池默认使用 8 个核心线程，并可根据负载动态扩展和收缩。
这些默认设置可通过 `spring.task.execution` 命名空间进行微调，如下所示：

[configprops,yaml]
----
spring:
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
        keep-alive: "10s"
----

这样配置后，线程池会使用有界队列，当队列满（100 个任务）时，线程池会扩展到最多 16 个线程。
线程池收缩更为激进，空闲线程 10 秒（默认 60 秒）后即被回收。

如需与定时任务执行相关联，也可自动配置调度器（如使用 javadoc:org.springframework.scheduling.annotation.EnableScheduling[format=annotation]）。

如果启用虚拟线程（Java 21+ 且 configprop:spring.threads.virtual.enabled[] 设置为 `true`），将使用基于虚拟线程的 javadoc:org.springframework.scheduling.concurrent.SimpleAsyncTaskScheduler[]，该调度器会忽略所有与池相关的属性。

未启用虚拟线程时，将使用带有合理默认值的 javadoc:org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler[]。
该调度器默认使用一个线程，可通过 `spring.task.scheduling` 命名空间微调设置，如下所示：

[configprops,yaml]
----
spring:
  task:
    scheduling:
      thread-name-prefix: "scheduling-"
      pool:
        size: 2
----

如需自定义执行器或调度器，容器中会自动提供 javadoc:org.springframework.boot.task.ThreadPoolTaskExecutorBuilder[]、javadoc:org.springframework.boot.task.SimpleAsyncTaskExecutorBuilder[]、javadoc:org.springframework.boot.task.ThreadPoolTaskSchedulerBuilder[] 和 javadoc:org.springframework.boot.task.SimpleAsyncTaskSchedulerBuilder[] bean。
如启用虚拟线程，javadoc:org.springframework.boot.task.SimpleAsyncTaskExecutorBuilder[] 和 javadoc:org.springframework.boot.task.SimpleAsyncTaskSchedulerBuilder[] bean 也会自动配置为使用虚拟线程（Java 21+ 且 configprop:spring.threads.virtual.enabled[] 设置为 `true`）。
