[[data.nosql]]
= 使用 NoSQL 技术

Spring Data 提供了多个附加项目，帮助您访问各种 NoSQL 技术，包括：

* {url-spring-data-cassandra-site}[Cassandra]
* {url-spring-data-couchbase-site}[Couchbase]
* {url-spring-data-elasticsearch-site}[Elasticsearch]
* {url-spring-data-geode-site}[Geode]
* {url-spring-data-ldap-site}[LDAP]
* {url-spring-data-mongodb-site}[MongoDB]
* {url-spring-data-neo4j-site}[Neo4J]
* {url-spring-data-redis-site}[Redis]

其中，Spring Boot 为 Cassandra、Couchbase、Elasticsearch、LDAP、MongoDB、Neo4J 和 Redis 提供了自动配置。
此外， {url-spring-boot-for-apache-geode-site}[Spring Boot for Apache Geode] 提供了 {url-spring-boot-for-apache-geode-docs}#geode-repositories[Apache Geode 的自动配置]。
您可以使用其他项目，但必须自行配置。
请参阅 {url-spring-data-site} 上的相应参考文档。

Spring Boot 还为 InfluxDB 客户端提供了自动配置，但已弃用，推荐使用 https://github.com/influxdata/influxdb-client-java[新的 InfluxDB Java 客户端]，它提供了自己的 Spring Boot 集成。



[[data.nosql.redis]]
== Redis

https://redis.io/[Redis] 是一个缓存、消息代理和功能丰富的键值存储。
Spring Boot 为 https://github.com/lettuce-io/lettuce-core/[Lettuce] 和 https://github.com/xetorthio/jedis/[Jedis] 客户端库以及 https://github.com/spring-projects/spring-data-redis[Spring Data Redis] 提供的抽象层提供了基本的自动配置。

有一个 `spring-boot-starter-data-redis` starter，方便地收集依赖项。
默认情况下，它使用 https://github.com/lettuce-io/lettuce-core/[Lettuce]。
该 starter 支持传统和响应式应用程序。

TIP: 我们还提供了一个 `spring-boot-starter-data-redis-reactive` starter，以与其他支持响应式的存储保持一致。



[[data.nosql.redis.connecting]]
=== 连接到 Redis

您可以像注入其他 Spring Bean 一样注入自动配置的 javadoc:org.springframework.data.redis.connection.RedisConnectionFactory[]、javadoc:org.springframework.data.redis.core.StringRedisTemplate[] 或原生的 javadoc:org.springframework.data.redis.core.RedisTemplate[] 实例。
以下列表显示了一个这样的 bean 示例：

include-code::MyBean[]

默认情况下，实例尝试连接到 `localhost:6379` 的 Redis 服务器。
您可以使用 `spring.data.redis.*` 属性指定自定义连接细节，如下例所示：

[configprops,yaml]
----
spring:
  data:
    redis:
      host: "localhost"
      port: 6379
      database: 0
      username: "user"
      password: "secret"
----

您还可以直接指定 Redis 服务器的 URL。
设置 URL 时，host、port、username 和 password 属性将被忽略。
如下例所示：

[configprops,yaml]
----
spring:
  data:
    redis:
      url: "redis://user:secret@localhost:6379"
      database: 0
----


TIP: 您还可以注册任意数量的实现 javadoc:org.springframework.boot.autoconfigure.data.redis.LettuceClientConfigurationBuilderCustomizer[] 的 bean，以进行更高级的自定义。
javadoc:io.lettuce.core.resource.ClientResources[] 也可以使用 javadoc:org.springframework.boot.autoconfigure.data.redis.ClientResourcesBuilderCustomizer[] 进行自定义。
如果您使用 Jedis，也可以使用 javadoc:org.springframework.boot.autoconfigure.data.redis.JedisClientConfigurationBuilderCustomizer[]。
或者，您可以注册 javadoc:org.springframework.data.redis.connection.RedisStandaloneConfiguration[]、javadoc:org.springframework.data.redis.connection.RedisSentinelConfiguration[] 或 javadoc:org.springframework.data.redis.connection.RedisClusterConfiguration[] 类型的 bean，以完全控制配置。

如果您添加了自己的任何自动配置类型的 javadoc:org.springframework.context.annotation.Bean[format=annotation]，它将替换默认配置（除了 javadoc:org.springframework.data.redis.core.RedisTemplate[] 的情况，排除基于 bean 名称 `redisTemplate`，而不是其类型）。

默认情况下，如果类路径上有 `commons-pool2`，会自动配置一个池化连接工厂。

通过设置以下属性，可以配置自动配置的 javadoc:org.springframework.data.redis.connection.RedisConnectionFactory[] 使用 SSL 与服务器通信，如下例所示：

[configprops,yaml]
----
spring:
  data:
    redis:
      ssl:
        enabled: true
----

可以在 xref:features/ssl.adoc[SSL bundle] 中配置自定义 SSL 信任材料，并将其应用于 javadoc:org.springframework.data.redis.connection.RedisConnectionFactory[]，如下例所示：

[configprops,yaml]
----
spring:
  data:
    redis:
      ssl:
        bundle: "example"
----



[[data.nosql.mongodb]]
== MongoDB

https://www.mongodb.com/[MongoDB] 是一个开源的 NoSQL 文档数据库，使用类似 JSON 的模式，而不是传统的基于表格的关系数据。
Spring Boot 为使用 MongoDB 提供了多种便利，包括 `spring-boot-starter-data-mongodb` 和 `spring-boot-starter-data-mongodb-reactive` starter。



[[data.nosql.mongodb.connecting]]
=== 连接到 MongoDB 数据库

要访问 MongoDB 数据库，您可以注入一个自动配置的 javadoc:org.springframework.data.mongodb.MongoDatabaseFactory[]。
默认情况下，实例尝试连接到 `mongodb://localhost/test` 的 MongoDB 服务器。
以下示例显示如何连接到 MongoDB 数据库：

include-code::MyBean[]

如果您定义了自己的 javadoc:{url-mongodb-driver-sync-javadoc}/com.mongodb.client.MongoClient[]，它将被用来自动配置一个合适的 javadoc:org.springframework.data.mongodb.MongoDatabaseFactory[]。

自动配置的 javadoc:{url-mongodb-driver-sync-javadoc}/com.mongodb.client.MongoClient[] 使用 javadoc:{url-mongodb-driver-core-javadoc}/com.mongodb.MongoClientSettings[] bean 创建。
如果您定义了自己的 javadoc:{url-mongodb-driver-core-javadoc}/com.mongodb.MongoClientSettings[]，它将不加修改地使用，`spring.data.mongodb` 属性将被忽略。
否则，将自动配置一个 javadoc:{url-mongodb-driver-core-javadoc}/com.mongodb.MongoClientSettings[]，并应用 `spring.data.mongodb` 属性。
在任一情况下，您可以声明一个或多个 javadoc:org.springframework.boot.autoconfigure.mongo.MongoClientSettingsBuilderCustomizer[] bean，以微调 javadoc:{url-mongodb-driver-core-javadoc}/com.mongodb.MongoClientSettings[] 配置。
每个 bean 将按顺序与用于构建 javadoc:{url-mongodb-driver-core-javadoc}/com.mongodb.MongoClientSettings[] 的 javadoc:{url-mongodb-driver-core-javadoc}/com.mongodb.MongoClientSettings$Builder[] 一起调用。

您可以设置 configprop:spring.data.mongodb.uri[] 属性来更改 URL 并配置其他设置，例如 _副本集_，如下例所示：

[configprops,yaml]
----
spring:
  data:
    mongodb:
      uri: "mongodb://user:secret@mongoserver1.example.com:27017,mongoserver2.example.com:23456/test"
----

或者，您可以使用单独的属性指定连接细节。
例如，您可以在 `application.properties` 中声明以下设置：

[configprops,yaml]
----
spring:
  data:
    mongodb:
      host: "mongoserver1.example.com"
      port: 27017
      additional-hosts:
      - "mongoserver2.example.com:23456"
      database: "test"
      username: "user"
      password: "secret"
----

通过设置以下属性，可以配置自动配置的 javadoc:{url-mongodb-driver-sync-javadoc}/com.mongodb.client.MongoClient[] 使用 SSL 与服务器通信，如下例所示：

[configprops,yaml]
----
spring:
  data:
    mongodb:
      uri: "mongodb://user:secret@mongoserver1.example.com:27017,mongoserver2.example.com:23456/test"
      ssl:
        enabled: true
----

可以在 xref:features/ssl.adoc[SSL bundle] 中配置自定义 SSL 信任材料，并将其应用于 javadoc:{url-mongodb-driver-sync-javadoc}/com.mongodb.client.MongoClient[]，如下例所示：

[configprops,yaml]
----
spring:
  data:
    mongodb:
      uri: "mongodb://user:secret@mongoserver1.example.com:27017,mongoserver2.example.com:23456/test"
      ssl:
        bundle: "example"
----


[TIP]
====
如果未指定 `spring.data.mongodb.port`，将使用默认值 `27017`。
您可以从前面的示例中删除此行。

您还可以使用 `host:port` 语法格式作为主机地址的一部分指定端口。
如果需要更改 `additional-hosts` 条目的端口，应使用此格式。
====

TIP: 如果您不使用 Spring Data MongoDB，可以注入 javadoc:{url-mongodb-driver-sync-javadoc}/com.mongodb.client.MongoClient[] bean，而不是使用 javadoc:org.springframework.data.mongodb.MongoDatabaseFactory[]。
如果您想完全控制建立 MongoDB 连接，还可以声明自己的 javadoc:org.springframework.data.mongodb.MongoDatabaseFactory[] 或 javadoc:{url-mongodb-driver-sync-javadoc}/com.mongodb.client.MongoClient[] bean。

NOTE: 如果使用响应式驱动程序，SSL 需要 Netty。
如果 Netty 可用且未自定义工厂，自动配置会自动配置此工厂。



[[data.nosql.mongodb.template]]
=== MongoTemplate

{url-spring-data-mongodb-site}[Spring Data MongoDB] 提供了 javadoc:org.springframework.data.mongodb.core.MongoTemplate[] 类，其设计与 Spring 的 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 非常相似。
与 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 一样，Spring Boot 为您自动配置一个 bean 以注入模板，如下所示：

include-code::MyBean[]

有关完整详情，请参阅 javadoc:org.springframework.data.mongodb.core.MongoOperations[] API 文档。



[[data.nosql.mongodb.repositories]]
=== Spring Data MongoDB 存储库

Spring Data 为 MongoDB 提供了存储库支持。
与前面讨论的 JPA 存储库一样，其基本原理是根据方法名称自动构建查询。

事实上，Spring Data JPA 和 Spring Data MongoDB 共享相同的基础设施。
您可以拿前面的 JPA 示例，假设 `City` 现在是一个 MongoDB 数据类，而不是 JPA javadoc:jakarta.persistence.Entity[format=annotation]，它以相同的方式工作，如下例所示：

include-code::CityRepository[]

通过扫描发现存储库和文档。
默认情况下，扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。
您可以分别使用 javadoc:org.springframework.data.mongodb.repository.config.EnableMongoRepositories[format=annotation] 和 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 自定义查找存储库和文档的位置。

TIP: 有关 Spring Data MongoDB 的完整详情，包括其丰富的对象映射技术，请参阅其 {url-spring-data-mongodb-docs}[参考文档]。



[[data.nosql.neo4j]]
== Neo4j

https://neo4j.com/[Neo4j] 是一个开源的 NoSQL 图数据库，使用节点通过一流关系连接的丰富数据模型，相比传统的 RDBMS 方法更适合处理连接的大数据。
Spring Boot 为使用 Neo4j 提供了多种便利，包括 `spring-boot-starter-data-neo4j` starter。



[[data.nosql.neo4j.connecting]]
=== 连接到 Neo4j 数据库

要访问 Neo4j 服务器，您可以注入一个自动配置的 javadoc:org.neo4j.driver.Driver[]。
默认情况下，实例尝试使用 Bolt 协议连接到 `localhost:7687` 的 Neo4j 服务器。
以下示例显示如何注入一个 Neo4j javadoc:org.neo4j.driver.Driver[]，它提供了对 javadoc:org.neo4j.driver.Session[] 等内容的访问：

include-code::MyBean[]

您可以使用 `spring.neo4j.*` 属性配置驱动程序的各个方面。
以下示例显示如何配置要使用的 URI 和凭据：

[configprops,yaml]
----
spring:
  neo4j:
    uri: "bolt://my-server:7687"
    authentication:
      username: "neo4j"
      password: "secret"
----

自动配置的 javadoc:org.neo4j.driver.Driver[] 使用 `org.neo4j.driver.Config$ConfigBuilder` 创建。
要微调其配置，声明一个或多个 javadoc:org.springframework.boot.autoconfigure.neo4j.ConfigBuilderCustomizer[] bean。
每个 bean 将按顺序与用于构建 javadoc:org.neo4j.driver.Driver[] 的 `org.neo4j.driver.Config$ConfigBuilder` 一起调用。



[[data.nosql.neo4j.repositories]]
=== Spring Data Neo4j 存储库

Spring Data 为 Neo4j 提供了存储库支持。
有关 Spring Data Neo4j 的完整详情，请参阅 {url-spring-data-neo4j-docs}[参考文档]。

Spring Data Neo4j 与 Spring Data JPA 等许多其他 Spring Data 模块共享相同的基础设施。
您可以拿前面的 JPA 示例，将 `City` 定义为 Spring Data Neo4j javadoc:org.springframework.data.neo4j.core.schema.Node[format=annotation]，而不是 JPA javadoc:jakarta.persistence.Entity[format=annotation]，存储库抽象以相同的方式工作，如下例所示：

include-code::CityRepository[]

`spring-boot-starter-data-neo4j` starter 启用存储库支持以及事务管理。
Spring Boot 支持使用 javadoc:org.springframework.data.neo4j.core.Neo4jTemplate[] 或 javadoc:org.springframework.data.neo4j.core.ReactiveNeo4jTemplate[] bean 的经典和响应式 Neo4j 存储库。
当类路径上有 Project Reactor 时，也会自动配置响应式风格。

通过扫描发现存储库和实体。
默认情况下，扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。
您可以分别使用 javadoc:org.springframework.data.neo4j.repository.config.EnableNeo4jRepositories[format=annotation] 和 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 自定义查找存储库和实体的位置。

[NOTE]
====
在使用响应式风格的应用程序中，不会自动配置 javadoc:org.springframework.transaction.ReactiveTransactionManager[]。
要启用事务管理，必须在配置中定义以下 bean：

include-code::MyNeo4jConfiguration[]
====



[[data.nosql.elasticsearch]]
== Elasticsearch

https://www.elastic.co/products/elasticsearch[Elasticsearch] 是一个开源的分布式 RESTful 搜索和分析引擎。
Spring Boot 为 Elasticsearch 客户端提供了基本的自动配置。

Spring Boot 支持多个客户端：

* 官方低级 REST 客户端
* 官方 Java API 客户端
* Spring Data Elasticsearch 提供的 javadoc:org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient[]

Spring Boot 提供了一个专用的 starter，`spring-boot-starter-data-elasticsearch`。



[[data.nosql.elasticsearch.connecting-using-rest]]
=== 使用 REST 客户端连接到 Elasticsearch

Elasticsearch 提供了两个不同的 REST 客户端，您可以用来查询集群：来自 `org.elasticsearch.client:elasticsearch-rest-client` 模块的 https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/java-rest-low.html[低级客户端] 和来自 `co.elastic.clients:elasticsearch-java` 模块的 https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html[Java API 客户端]。
此外，Spring Boot 支持来自 `org.springframework.data:spring-data-elasticsearch` 模块的响应式客户端。
默认情况下，客户端的目标是 `http://localhost:9200`。
您可以使用 `spring.elasticsearch.*` 属性进一步调整客户端的配置，如下例所示：

[configprops,yaml]
----
spring:
  elasticsearch:
    uris: "https://search.example.com:9200"
    socket-timeout: "10s"
    username: "user"
    password: "secret"
----



[[data.nosql.elasticsearch.connecting-using-rest.restclient]]
==== 使用 RestClient 连接到 Elasticsearch

如果类路径上有 `elasticsearch-rest-client`，Spring Boot 将自动配置并注册一个 javadoc:org.springframework.web.client.RestClient[] bean。
除了前面描述的属性外，要微调 javadoc:org.springframework.web.client.RestClient[]，您可以注册任意数量的实现 javadoc:org.springframework.boot.autoconfigure.elasticsearch.RestClientBuilderCustomizer[] 的 bean，以进行更高级的自定义。
要完全控制客户端的配置，定义一个 javadoc:org.elasticsearch.client.RestClientBuilder[] bean。



此外，如果类路径上有 `elasticsearch-rest-client-sniffer`，将自动配置一个 javadoc:org.elasticsearch.client.sniff.Sniffer[]，以从运行中的 Elasticsearch 集群自动发现节点并将其设置到 javadoc:org.springframework.web.client.RestClient[] bean 上。
您可以进一步调整 javadoc:org.elasticsearch.client.sniff.Sniffer[] 的配置，如下例所示：

[configprops,yaml]
----
spring:
  elasticsearch:
    restclient:
      sniffer:
        interval: "10m"
        delay-after-failure: "30s"
----



[[data.nosql.elasticsearch.connecting-using-rest.javaapiclient]]
==== 使用 ElasticsearchClient 连接到 Elasticsearch

如果类路径上有 `co.elastic.clients:elasticsearch-java`，Spring Boot 将自动配置并注册一个 javadoc:co.elastic.clients.elasticsearch.ElasticsearchClient[] bean。

javadoc:co.elastic.clients.elasticsearch.ElasticsearchClient[] 使用依赖于前面描述的 javadoc:org.springframework.web.client.RestClient[] 的传输。
因此，前面描述的属性可用于配置 javadoc:co.elastic.clients.elasticsearch.ElasticsearchClient[]。
此外，您可以定义一个 javadoc:co.elastic.clients.transport.rest_client.RestClientOptions[] bean，以进一步控制传输的行为。



[[data.nosql.elasticsearch.connecting-using-rest.reactiveclient]]
==== 使用 ReactiveElasticsearchClient 连接到 Elasticsearch

{url-spring-data-elasticsearch-site}[Spring Data Elasticsearch] 提供了 javadoc:org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient[]，以响应式方式查询 Elasticsearch 实例。
如果类路径上有 Spring Data Elasticsearch 和 Reactor，Spring Boot 将自动配置并注册一个 javadoc:org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient[]。

javadoc:org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient[] 使用依赖于前面描述的 javadoc:org.springframework.web.client.RestClient[] 的传输。
因此，前面描述的属性可用于配置 javadoc:org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient[]。
此外，您可以定义一个 javadoc:co.elastic.clients.transport.rest_client.RestClientOptions[] bean，以进一步控制传输的行为。



[[data.nosql.elasticsearch.connecting-using-spring-data]]
=== 使用 Spring Data 连接到 Elasticsearch

要连接到 Elasticsearch，必须定义一个 javadoc:co.elastic.clients.elasticsearch.ElasticsearchClient[] bean，由 Spring Boot 自动配置或由应用程序手动提供（参见前几节）。
在这种配置下，可以像注入其他 Spring bean 一样注入 javadoc:org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate[]，如下例所示：

include-code::MyBean[]

如果类路径上有 `spring-data-elasticsearch` 和 Reactor，Spring Boot 还可以自动配置一个 xref:data/nosql.adoc#data.nosql.elasticsearch.connecting-using-rest.reactiveclient[`ReactiveElasticsearchClient`] 和 javadoc:org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchTemplate[] 作为 bean。
它们是其他 REST 客户端的响应式等价物。



[[data.nosql.elasticsearch.repositories]]
=== Spring Data Elasticsearch 存储库

Spring Data 为 Elasticsearch 提供了存储库支持。
与前面讨论的 JPA 存储库一样，其基本原理是根据方法名称自动构建查询。

事实上，Spring Data JPA 和 Spring Data Elasticsearch 共享相同的基础设施。
您可以拿前面的 JPA 示例，假设 `City` 现在是一个 Elasticsearch javadoc:org.springframework.data.elasticsearch.annotations.Document[format=annotation] 类，而不是 JPA javadoc:jakarta.persistence.Entity[format=annotation]，它以相同的方式工作。

通过扫描发现存储库和文档。
默认情况下，扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。
您可以分别使用 javadoc:org.springframework.data.elasticsearch.repository.config.EnableElasticsearchRepositories[format=annotation] 和 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 自定义查找存储库和文档的位置。

TIP: 有关 Spring Data Elasticsearch 的完整详情，请参阅 {url-spring-data-elasticsearch-docs}[参考文档]。

Spring Boot 支持使用 javadoc:org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate[] 或 javadoc:org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchTemplate[] bean 的经典和响应式 Elasticsearch 存储库。
如果存在所需的依赖项，这些 bean 很可能是由 Spring Boot 自动配置的。

如果您希望为支持 Elasticsearch 存储库使用自己的模板，可以添加自己的 javadoc:org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate[] 或 javadoc:org.springframework.data.elasticsearch.core.ElasticsearchOperations[] javadoc:org.springframework.context.annotation.Bean[format=annotation]，只要其名称为 `"elasticsearchTemplate"`。
对于 javadoc:org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchTemplate[] 和 javadoc:org.springframework.data.elasticsearch.core.ReactiveElasticsearchOperations[]，bean 名称为 `"reactiveElasticsearchTemplate"`，同样适用。

您可以选择通过以下属性禁用存储库支持：

[configprops,yaml]
----
    spring:
      data:
        elasticsearch:
          repositories:
            enabled: false
----



[[data.nosql.cassandra]]
== Cassandra

https://cassandra.apache.org/[Cassandra] 是一个开源的分布式数据库管理系统，设计用于处理跨多个商用服务器的大量数据。
Spring Boot 为 Cassandra 提供了自动配置以及 {url-spring-data-cassandra-site}[Spring Data Cassandra] 提供的抽象层。
有一个 `spring-boot-starter-data-cassandra` starter，方便地收集依赖项。



[[data.nosql.cassandra.connecting]]
=== 连接到 Cassandra

您可以像注入其他 Spring Bean 一样注入自动配置的 javadoc:org.springframework.data.cassandra.core.cql.CqlTemplate[]、javadoc:org.springframework.data.cassandra.core.CassandraTemplate[] 或 Cassandra `CqlSession` 实例。
`spring.cassandra.*` 属性可用于自定义连接。
通常，您需要提供 `keyspace-name` 和 `contact-points` 以及本地数据中心名称，如下例所示：

[configprops,yaml]
----
spring:
  cassandra:
    keyspace-name: "mykeyspace"
    contact-points: "cassandrahost1:9042,cassandrahost2:9042"
    local-datacenter: "datacenter1"
----

如果所有联系点的端口相同，您可以使用快捷方式，仅指定主机名，如下例所示：

[configprops,yaml]
----
spring:
  cassandra:
    keyspace-name: "mykeyspace"
    contact-points: "cassandrahost1,cassandrahost2"
    local-datacenter: "datacenter1"
----

TIP: 这两个示例是相同的，因为端口默认为 `9042`。
如果需要配置端口，请使用 `spring.cassandra.port`。

通过设置以下属性，可以配置自动配置的 `CqlSession` 使用 SSL 与服务器通信，如下例所示：

[configprops,yaml]
----
spring:
  cassandra:
    keyspace-name: "mykeyspace"
    contact-points: "cassandrahost1,cassandrahost2"
    local-datacenter: "datacenter1"
    ssl:
      enabled: true
----

可以在 xref:features/ssl.adoc[SSL bundle] 中配置自定义 SSL 信任材料，并将其应用于 `CqlSession`，如下例所示：

[configprops,yaml]
----
spring:
  cassandra:
    keyspace-name: "mykeyspace"
    contact-points: "cassandrahost1,cassandrahost2"
    local-datacenter: "datacenter1"
    ssl:
      bundle: "example"
----


[NOTE]
====
Cassandra 驱动程序有自己的配置基础设施，会加载类路径根目录下的 `application.conf` 文件。

Spring Boot 默认不查找此类文件，但可以使用 `spring.cassandra.config` 加载一个。
如果 `spring.cassandra.*` 和配置文件中都存在某个属性，`spring.cassandra.*` 中的值优先。

要进行更高级的驱动程序自定义，可以注册任意数量的实现 javadoc:org.springframework.boot.autoconfigure.cassandra.DriverConfigLoaderBuilderCustomizer[] 的 bean。
可以使用 javadoc:org.springframework.boot.autoconfigure.cassandra.CqlSessionBuilderCustomizer[] 类型的 bean 自定义 `CqlSession`。
====

NOTE: 如果您使用 `CqlSessionBuilder` 创建多个 `CqlSession` bean，请注意该构建器是可变的，因此请确保为每个会话注入一个新的副本。

以下代码列表显示如何注入 Cassandra bean：

include-code::MyBean[]

如果您添加了自己的 javadoc:org.springframework.context.annotation.Bean[format=annotation] 类型为 javadoc:org.springframework.data.cassandra.core.CassandraTemplate[]，它将替换默认配置。



[[data.nosql.cassandra.repositories]]
=== Spring Data Cassandra 存储库

Spring Data 为 Cassandra 提供了基本的存储库支持。
目前，这比前面讨论的 JPA 存储库更有限，需要使用 javadoc:org.springframework.data.cassandra.repository.Query[format=annotation] 注解的查找方法。

通过扫描发现存储库和实体。
默认情况下，扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。
您可以分别使用 javadoc:org.springframework.data.cassandra.repository.config.EnableCassandraRepositories[format=annotation] 和 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 自定义查找存储库和实体的位置。

TIP: 有关 Spring Data Cassandra 的完整详情，请参阅 {url-spring-data-cassandra-docs}[参考文档]。



[[data.nosql.couchbase]]
== Couchbase

https://www.couchbase.com/[Couchbase] 是一个开源的分布式多模型 NoSQL 面向文档的数据库，优化用于交互式应用程序。
Spring Boot 为 Couchbase 提供了自动配置以及 https://github.com/spring-projects/spring-data-couchbase[Spring Data Couchbase] 提供的抽象层。
有 `spring-boot-starter-data-couchbase` 和 `spring-boot-starter-data-couchbase-reactive` starter，方便地收集依赖项。



[[data.nosql.couchbase.connecting]]
=== 连接到 Couchbase

通过添加 Couchbase SDK 和一些配置，您可以获得一个 javadoc:com.couchbase.client.java.Cluster[]。
`spring.couchbase.*` 属性可用于自定义连接。
通常，您需要提供 https://docs.couchbase.com/dotnet-sdk/current/howtos/managing-connections.html[连接字符串] 和用于认证的凭据。可以使用用户名和密码进行基本认证，如下例所示：

[configprops,yaml]
----
spring:
  couchbase:
    connection-string: "couchbase://192.168.1.123"
    username: "user"
    password: "secret"
----

https://docs.couchbase.com/server/current/manage/manage-security/configure-client-certificates.html[客户端证书] 可用于代替用户名和密码进行认证。
包含客户端证书的 Java KeyStore 的位置和密码可以按以下示例配置：

[configprops,yaml]
----
spring:
  couchbase:
    connection-string: "couchbase://192.168.1.123"
    env:
      ssl:
        enabled: true
    authentication:
      jks:
        location: "classpath:client.p12"
        password: "secret"
----

PEM 编码的证书和私钥可以按以下示例配置：

[configprops,yaml]
----
spring:
  couchbase:
    connection-string: "couchbase://192.168.1.123"
    env:
      ssl:
        enabled: true
    authentication:
      pem:
        certificates: "classpath:client.crt"
        private-key: "classpath:client.key"
----

还可以自定义 javadoc:com.couchbase.client.java.env.ClusterEnvironment[] 的一些设置。
例如，以下配置更改了打开新 javadoc:com.couchbase.client.java.Bucket[] 的超时时间，并启用对配置的 xref:features/ssl.adoc[SSL bundle] 的引用以支持 SSL：

[configprops,yaml]
----
spring:
  couchbase:
    env:
      timeouts:
        connect: "3s"
      ssl:
        bundle: "example"
----

TIP: 请查看 `spring.couchbase.env.*` 属性以获取更多详情。
要获得更多控制，可以使用一个或多个 javadoc:org.springframework.boot.autoconfigure.couchbase.ClusterEnvironmentBuilderCustomizer[] bean。



[[data.nosql.couchbase.repositories]]
=== Spring Data Couchbase 存储库

Spring Data 为 Couchbase 提供了存储库支持。

通过扫描发现存储库和文档。
默认情况下，扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。
您可以分别使用 javadoc:org.springframework.data.couchbase.repository.config.EnableCouchbaseRepositories[format=annotation] 和 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 自定义查找存储库和文档的位置。

有关 Spring Data Couchbase 的完整详情，请参阅 {url-spring-data-couchbase-docs}[参考文档]。

只要 javadoc:org.springframework.data.couchbase.CouchbaseClientFactory[] bean 可用，您就可以像注入其他 Spring Bean 一样注入自动配置的 javadoc:org.springframework.data.couchbase.core.CouchbaseTemplate[] 实例。
当 javadoc:com.couchbase.client.java.Cluster[] 可用（如上所述）且已指定桶名称时，会发生这种情况：

[configprops,yaml]
----
spring:
  data:
    couchbase:
      bucket-name: "my-bucket"
----

以下示例显示如何注入 javadoc:org.springframework.data.couchbase.core.CouchbaseTemplate[] bean：

include-code::MyBean[]

您可以在自己的配置中定义一些 bean，以覆盖自动配置提供的 bean：

* 名称为 `couchbaseMappingContext` 的 javadoc:org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。
* 名称为 `couchbaseCustomConversions` 的 javadoc:org.springframework.data.convert.CustomConversions[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。
* 名称为 `couchbaseTemplate` 的 javadoc:org.springframework.data.couchbase.core.CouchbaseTemplate[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。

为了避免在自己的配置中硬编码这些名称，您可以重用 Spring Data Couchbase 提供的 javadoc:org.springframework.data.couchbase.config.BeanNames[]。
例如，您可以按以下方式自定义要使用的转换器：

include-code::MyCouchbaseConfiguration[]



[[data.nosql.ldap]]
== LDAP

https://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol[LDAP]（轻量级目录访问协议）是一个开放的、供应商中立的行业标准应用程序协议，用于通过 IP 网络访问和维护分布式目录信息服务。
Spring Boot 为任何符合标准的 LDAP 服务器提供自动配置，并支持来自 https://ldap.com/unboundid-ldap-sdk-for-java/[UnboundID] 的嵌入式内存 LDAP 服务器。

https://github.com/spring-projects/spring-data-ldap[Spring Data LDAP] 提供了 LDAP 抽象。
有一个 `spring-boot-starter-data-ldap` starter，方便地收集依赖项。



[[data.nosql.ldap.connecting]]
=== 连接到 LDAP 服务器

要连接到 LDAP 服务器，请确保声明对 `spring-boot-starter-data-ldap` starter 或 `spring-ldap-core` 的依赖，然后在 `application.properties` 中声明服务器的 URL，如下例所示：

[configprops,yaml]
----
spring:
  ldap:
    urls: "ldap://myserver:1235"
    username: "admin"
    password: "secret"
----

如果需要自定义连接设置，可以使用 `spring.ldap.base` 和 `spring.ldap.base-environment` 属性。

根据这些设置自动配置一个 javadoc:org.springframework.ldap.core.support.LdapContextSource[]。
如果有 javadoc:org.springframework.ldap.core.support.DirContextAuthenticationStrategy[] bean 可用，它将关联到自动配置的 javadoc:org.springframework.ldap.core.support.LdapContextSource[]。
如果需要自定义它，例如使用 javadoc:org.springframework.ldap.pool2.factory.PooledContextSource[]，您仍然可以注入自动配置的 javadoc:org.springframework.ldap.core.support.LdapContextSource[]。
请确保将自定义的 javadoc:org.springframework.ldap.core.ContextSource[] 标记为 javadoc:org.springframework.context.annotation.Primary[format=annotation]，以便自动配置的 javadoc:org.springframework.ldap.core.LdapTemplate[] 使用它。



[[data.nosql.ldap.repositories]]
=== Spring Data LDAP 存储库

Spring Data 为 LDAP 提供了存储库支持。

通过扫描发现存储库和文档。
默认情况下，扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。
您可以分别使用 javadoc:org.springframework.data.ldap.repository.config.EnableLdapRepositories[format=annotation] 和 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 自定义查找存储库和文档的位置。

TIP: 有关 Spring Data LDAP 的完整详情，请参阅 {url-spring-data-ldap-docs}[参考文档]。

您还可以像注入其他 Spring Bean 一样注入自动配置的 javadoc:org.springframework.ldap.core.LdapTemplate[] 实例，如下例所示：

include-code::MyBean[]



[[data.nosql.ldap.embedded]]
=== 嵌入式内存 LDAP 服务器

为了测试目的，Spring Boot 支持来自 https://ldap.com/unboundid-ldap-sdk-for-java/[UnboundID] 的嵌入式内存 LDAP 服务器的自动配置。
要配置服务器，添加对 `com.unboundid:unboundid-ldapsdk` 的依赖，并声明 configprop:spring.ldap.embedded.base-dn[] 属性，如下所示：

[configprops,yaml]
----
spring:
  ldap:
    embedded:
      base-dn: "dc=spring,dc=io"
----

[NOTE]
====
可以定义多个 base-dn 值，但是，由于区分名称通常包含逗号，必须使用正确的表示法定义它们。

在 YAML 文件中，您可以使用 YAML 列表表示法。在属性文件中，必须将索引作为属性名称的一部分包含：

[configprops,yaml]
----
spring.ldap.embedded.base-dn:
- "dc=spring,dc=io"
- "dc=vmware,dc=com"
----
====

默认情况下，服务器在随机端口上启动，并触发常规 LDAP 支持。
无需指定 configprop:spring.ldap.urls[] 属性。

如果类路径上有 `schema.ldif` 文件，它将用于初始化服务器。
如果您想从其他资源加载初始化脚本，还可以使用 configprop:spring.ldap.embedded.ldif[] 属性。

默认情况下，使用标准模式验证 `LDIF` 文件。
您可以通过设置 configprop:spring.ldap.embedded.validation.enabled[] 属性完全关闭验证。
如果您有自定义属性，可以使用 configprop:spring.ldap.embedded.validation.schema[] 定义自定义属性类型或对象类。
