[[data.sql]]
= SQL 数据库

{url-spring-framework-site}[Spring Framework] 为处理 SQL 数据库提供了广泛的支持，从使用 javadoc:org.springframework.jdbc.core.simple.JdbcClient[] 或 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 进行直接 JDBC 访问，到像 Hibernate 这样的完整“对象关系映射”技术。
{url-spring-data-site}[Spring Data] 提供了额外的功能：直接从接口创建 javadoc:org.springframework.data.repository.Repository[] 实现，并使用约定从方法名称生成查询。



[[data.sql.datasource]]
== 配置 DataSource

Java 的 javadoc:javax.sql.DataSource[] 接口提供了一种使用数据库连接的标准方法。
传统上，javadoc:javax.sql.DataSource[] 使用 `URL` 和一些凭据来建立数据库连接。

TIP: 请参阅“操作指南”中的 xref:how-to:data-access.adoc#howto.data-access.configure-custom-datasource[] 部分，了解更高级的示例，通常用于完全控制 DataSource 的配置。



[[data.sql.datasource.embedded]]
=== 嵌入式数据库支持

使用内存嵌入式数据库开发应用程序通常很方便。
显然，内存数据库不提供持久存储。
您需要在应用程序启动时填充数据库，并准备在应用程序结束时丢弃数据。

TIP: “操作指南”部分包括一个 xref:how-to:data-initialization.adoc[关于如何初始化数据库的部分]。

Spring Boot 可以自动配置嵌入式 https://www.h2database.com[H2]、 https://hsqldb.org/[HSQL] 和 https://db.apache.org/derby/[Derby] 数据库。
您无需提供任何连接 URL。
只需在构建依赖中包含您想使用的嵌入式数据库即可。
如果类路径上有多个嵌入式数据库，请设置 configprop:spring.datasource.embedded-database-connection[] 配置属性以控制使用哪个数据库。
将该属性设置为 `none` 将禁用嵌入式数据库的自动配置。

[NOTE]
====
如果您在测试中使用此功能，您可能会注意到，无论使用多少个应用程序上下文，整个测试套件都会重用同一个数据库。
如果您想确保每个上下文都有一个独立的嵌入式数据库，应将 `spring.datasource.generate-unique-name` 设置为 `true`。
====

例如，典型的 POM 依赖如下：

[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
    <groupId>org.hsqldb</groupId>
    <artifactId>hsqldb</artifactId>
    <scope>runtime</scope>
</dependency>
----

NOTE: 要使嵌入式数据库自动配置，需要依赖 `spring-jdbc`。
在此示例中，它通过 `spring-boot-starter-data-jpa` 间接引入。

TIP: 如果出于某种原因，您为嵌入式数据库配置了连接 URL，请注意确保禁用数据库的自动关闭。
如果使用 H2，应使用 `DB_CLOSE_ON_EXIT=FALSE`。
如果使用 HSQLDB，应确保不使用 `shutdown=true`。
禁用数据库的自动关闭让 Spring Boot 控制数据库的关闭时间，从而确保在不再需要访问数据库时进行关闭。



[[data.sql.datasource.production]]
=== 连接到生产数据库

生产数据库连接也可以通过使用池化 javadoc:javax.sql.DataSource[] 自动配置。



[[data.sql.datasource.configuration]]
=== DataSource 配置

DataSource 配置由 `+spring.datasource.*+` 中的外部配置属性控制。
例如，您可以在 `application.properties` 中声明以下部分：

[configprops,yaml]
----
spring:
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
----

NOTE: 您至少应通过设置 configprop:spring.datasource.url[] 属性指定 URL。
否则，Spring Boot 会尝试自动配置嵌入式数据库。

TIP: Spring Boot 可以从 URL 中推断大多数数据库的 JDBC 驱动类。
如果需要指定特定类，可以使用 configprop:spring.datasource.driver-class-name[] 属性。

NOTE: 要创建池化 javadoc:javax.sql.DataSource[]，我们需要验证是否存在有效的 javadoc:java.sql.Driver[] 类，因此在执行任何操作之前会进行检查。
换句话说，如果您设置 `spring.datasource.driver-class-name=com.mysql.jdbc.Driver`，则该类必须可加载。

有关更多支持的选项，请参阅 javadoc:org.springframework.boot.autoconfigure.jdbc.DataSourceProperties[] API 文档。
这些是标准选项，无论 xref:data/sql.adoc#data.sql.datasource.connection-pool[实际实现] 如何都适用。
还可以通过各自的前缀（`+spring.datasource.hikari.*+`、`+spring.datasource.tomcat.*+`、`+spring.datasource.dbcp2.*+` 和 `+spring.datasource.oracleucp.*+`）微调特定于实现的设置。
有关更多详细信息，请参阅您使用的连接池实现的文档。

例如，如果您使用 {url-tomcat-docs}/jdbc-pool.html#Common_Attributes[Tomcat 连接池]，可以自定义许多额外的设置，如下例所示：

[configprops,yaml]
----
spring:
  datasource:
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
----

这将设置池在没有可用连接时等待 10000 毫秒后抛出异常，将最大连接数限制为 50，并在从池中借用连接之前验证连接。



[[data.sql.datasource.connection-pool]]
=== 支持的连接池

Spring Boot 使用以下算法选择特定的实现：

. 我们偏好 https://github.com/brettwooldridge/HikariCP[HikariCP]，因为其性能和并发性。
如果 HikariCP 可用，我们总是选择它。
. 否则，如果 Tomcat 池化 javadoc:javax.sql.DataSource[] 可用，我们使用它。
. 否则，如果 https://commons.apache.org/proper/commons-dbcp/[Commons DBCP2] 可用，我们使用它。
. 如果 HikariCP、Tomcat 和 DBCP2 均不可用，且 Oracle UCP 可用，我们使用它。

NOTE: 如果您使用 `spring-boot-starter-jdbc` 或 `spring-boot-starter-data-jpa` starter，您将自动获得对 HikariCP 的依赖。

您可以通过设置 configprop:spring.datasource.type[] 属性完全绕过该算法并指定要使用的连接池。
如果您在 Tomcat 容器中运行应用程序，这尤其重要，因为默认提供 `tomcat-jdbc`。

始终可以使用 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 手动配置额外的连接池。
如果您定义了自己的 javadoc:javax.sql.DataSource[] bean，自动配置不会发生。
javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 支持以下连接池：

* HikariCP
* Tomcat 池化 javadoc:javax.sql.DataSource[]
* Commons DBCP2
* Oracle UCP & `OracleDataSource`
* Spring Framework 的 javadoc:org.springframework.jdbc.datasource.SimpleDriverDataSource[]
* H2 javadoc:org.h2.jdbcx.JdbcDataSource[]
* PostgreSQL javadoc:org.postgresql.ds.PGSimpleDataSource[]
* C3P0
* Vibur



[[data.sql.datasource.jndi]]
=== 连接到 JNDI DataSource

如果您将 Spring Boot 应用程序部署到应用程序服务器，您可能希望使用应用程序服务器的内置功能配置和管理 DataSource，并通过 JNDI 访问它。

configprop:spring.datasource.jndi-name[] 属性可以作为 configprop:spring.datasource.url[]、configprop:spring.datasource.username[] 和 configprop:spring.datasource.password[] 属性的替代方法，用于从特定 JNDI 位置访问 javadoc:javax.sql.DataSource[]。
例如，以下 `application.properties` 中的部分展示了如何访问 JBoss AS 定义的 javadoc:javax.sql.DataSource[]：

[configprops,yaml]
----
spring:
  datasource:
    jndi-name: "java:jboss/datasources/customers"
----



[[data.sql.jdbc-template]]
== 使用 JdbcTemplate

Spring 的 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 和 javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 类是自动配置的，您可以直接将它们自动注入到自己的 bean 中，如下例所示：

include-code::MyBean[]

您可以使用 `spring.jdbc.template.*` 属性自定义模板的某些属性，如下例所示：

[configprops,yaml]
----
spring:
  jdbc:
    template:
      max-rows: 500
----

如果需要调整 SQL 异常的处理，可以定义自己的 `SQLExceptionTranslator` bean，以便与自动配置的 `JdbcTemplate` 关联。

NOTE: javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 在幕后重用同一个 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 实例。
如果定义了多个 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 且没有主要候选者，javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 不会自动配置。



[[data.sql.jdbc-client]]
== 使用 JdbcClient

Spring 的 javadoc:org.springframework.jdbc.core.simple.JdbcClient[] 根据 javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 的存在自动配置。
您也可以直接将其注入到自己的 bean 中，如下例所示：

include-code::MyBean[]

如果您依赖自动配置来创建底层的 javadoc:org.springframework.jdbc.core.JdbcTemplate[]，使用 `spring.jdbc.template.*` 属性进行的任何自定义也会在客户端中生效。



[[data.sql.jpa-and-spring-data]]
== JPA 和 Spring Data JPA

Java Persistence API 是一种标准技术，允许您将对象“映射”到关系数据库。
`spring-boot-starter-data-jpa` POM 提供了一种快速入门的方式。
它提供了以下关键依赖：

* Hibernate：最流行的 JPA 实现之一。
* Spring Data JPA：帮助您实现基于 JPA 的存储库。
* Spring ORM：Spring Framework 的核心 ORM 支持。

TIP: 我们不会在这里深入探讨 JPA 或 {url-spring-data-site}[Spring Data] 的太多细节。
您可以参考 https://spring.io 的 https://spring.io/guides/gs/accessing-data-jpa/[Accessing Data with JPA] 指南，并阅读 {url-spring-data-jpa-site}[Spring Data JPA] 和 https://hibernate.org/orm/documentation/[Hibernate] 参考文档。



[[data.sql.jpa-and-spring-data.entity-classes]]
=== 实体类

传统上，JPA“实体”类在 `persistence.xml` 文件中指定。
在 Spring Boot 中，这个文件不是必需的，而是使用“实体扫描”。
默认情况下，扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。

任何使用 javadoc:jakarta.persistence.Entity[format=annotation]、javadoc:jakarta.persistence.Embeddable[format=annotation] 或 javadoc:jakarta.persistence.MappedSuperclass[format=annotation] 注解的类都会被考虑。
一个典型的实体类如下例所示：

include-code::City[]

TIP: 您可以使用 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 注解自定义实体扫描位置。
请参阅“操作指南”中的 xref:how-to:data-access.adoc#howto.data-access.separate-entity-definitions-from-spring-configuration[] 部分。



[[data.sql.jpa-and-spring-data.repositories]]
=== Spring Data JPA 存储库

{url-spring-data-jpa-site}[Spring Data JPA] 存储库是您可以定义的接口，用于访问数据。
JPA 查询会根据您的方法名称自动创建。
例如，`CityRepository` 接口可能声明一个 `findAllByState(String state)` 方法来查找给定州的所有城市。

对于更复杂的查询，您可以使用 Spring Data 的 javadoc:org.springframework.data.jpa.repository.Query[] 注解来注解您的方法。

Spring Data 存储库通常从 javadoc:org.springframework.data.repository.Repository[] 或 javadoc:org.springframework.data.repository.CrudRepository[] 接口扩展。
如果您使用自动配置，会搜索 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 中的存储库。

TIP: 您可以使用 javadoc:org.springframework.data.jpa.repository.config.EnableJpaRepositories[format=annotation] 自定义查找存储库的位置。

以下示例显示了一个典型的 Spring Data 存储库接口定义：

include-code::CityRepository[]

Spring Data JPA 存储库支持三种不同的引导模式：默认、延迟和惰性。
要启用延迟或惰性引导，请分别将 configprop:spring.data.jpa.repositories.bootstrap-mode[] 属性设置为 `deferred` 或 `lazy`。
使用延迟或惰性引导时，自动配置的 javadoc:org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder[] 将使用上下文的 javadoc:org.springframework.core.task.AsyncTaskExecutor[]（如果有）作为引导执行器。
如果存在多个执行器，将使用名为 `applicationTaskExecutor` 的执行器。

[NOTE]
====
使用延迟或惰性引导时，请确保在应用程序上下文引导阶段之后延迟对 JPA 基础设施的任何访问。
您可以使用 javadoc:org.springframework.beans.factory.SmartInitializingSingleton[] 来调用需要 JPA 基础设施的任何初始化。
对于作为 Spring bean 创建的 JPA 组件（如转换器），使用 javadoc:org.springframework.beans.factory.ObjectProvider[] 来延迟依赖的解析（如果有）。
====

TIP: 我们只是浅谈了 Spring Data JPA 的表面。
有关完整详情，请参阅 {url-spring-data-jpa-docs}[Spring Data JPA 参考文档]。



[[data.sql.jpa-and-spring-data.envers-repositories]]
=== Spring Data Envers 存储库

如果 {url-spring-data-envers-site}[Spring Data Envers] 可用，JPA 存储库会自动配置以支持典型的 Envers 查询。

要使用 Spring Data Envers，请确保您的存储库扩展自 javadoc:org.springframework.data.repository.history.RevisionRepository[]，如下例所示：

include-code::CountryRepository[]

NOTE: 有关更多详情，请查看 {url-spring-data-jpa-docs}/envers.html[Spring Data Envers 参考文档]。



[[data.sql.jpa-and-spring-data.creating-and-dropping]]
=== 创建和删除 JPA 数据库

默认情况下，仅当您使用嵌入式数据库（H2、HSQL 或 Derby）时，JPA 数据库才会自动创建。
您可以使用 `+spring.jpa.*+` 属性显式配置 JPA 设置。
例如，要创建和删除表，您可以在 `application.properties` 中添加以下行：

[configprops,yaml]
----
spring:
  jpa:
    hibernate.ddl-auto: "create-drop"
----

NOTE: Hibernate 自身的内部属性名称（如果您更熟悉）是 `hibernate.hbm2ddl.auto`。
您可以通过 `+spring.jpa.properties.*+` 设置它以及其他 Hibernate 原生属性（前缀在添加到实体管理器之前会被剥离）。
以下示例展示了为 Hibernate 设置 JPA 属性的一个例子：

[configprops,yaml]
----
spring:
  jpa:
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
----

上述示例中的行将 `hibernate.globally_quoted_identifiers` 属性的值 `true` 传递给 Hibernate 实体管理器。

默认情况下，DDL 执行（或验证）会推迟到 javadoc:org.springframework.context.ApplicationContext[] 启动时。



[[data.sql.jpa-and-spring-data.open-entity-manager-in-view]]
=== 打开视图中的 EntityManager

如果您运行的是 Web 应用程序，Spring Boot 默认注册 javadoc:org.springframework.orm.jpa.support.OpenEntityManagerInViewInterceptor[]，以应用“视图中打开 EntityManager”模式，从而允许在 Web 视图中进行延迟加载。
如果您不希望这种行为，应在 `application.properties` 中将 `spring.jpa.open-in-view` 设置为 `false`。



[[data.sql.jdbc]]
== Spring Data JDBC

Spring Data 为 JDBC 提供了存储库支持，并会为 javadoc:org.springframework.data.repository.CrudRepository[] 上的方法自动生成 SQL。
对于更高级的查询，提供了 javadoc:org.springframework.data.jdbc.repository.query.Query[format=annotation] 注解。

当类路径上有必要的依赖时，Spring Boot 会自动配置 Spring Data 的 JDBC 存储库。
只需对 `spring-boot-starter-data-jdbc` 的单一依赖即可将它们添加到您的项目中。
如有必要，您可以通过在应用程序中添加 javadoc:org.springframework.data.jdbc.repository.config.EnableJdbcRepositories[format=annotation] 注解或 javadoc:org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration[] 子类来控制 Spring Data JDBC 的配置。

TIP: 有关 Spring Data JDBC 的完整详情，请参阅 {url-spring-data-jdbc-docs}[参考文档]。



[[data.sql.h2-web-console]]
== 使用 H2 的 Web 控制台

https://www.h2database.com[H2 数据库] 提供了 https://www.h2database.com/html/quickstart.html#h2_console[基于浏览器的控制台]，Spring Boot 可以为您自动配置。
当满足以下条件时，控制台会自动配置：

* 您正在开发基于 servlet 的 Web 应用程序。
* `com.h2database:h2` 在类路径上。
* 您正在使用 xref:using/devtools.adoc[Spring Boot 的开发者工具]。

TIP: 如果您不使用 Spring Boot 的开发者工具，但仍想使用 H2 的控制台，可以将 configprop:spring.h2.console.enabled[] 属性配置为 `true`。

NOTE: H2 控制台仅用于开发期间，因此应注意确保在生产环境中 `spring.h2.console.enabled` 不设置为 `true`。



[[data.sql.h2-web-console.custom-path]]
=== 更改 H2 控制台的路径

默认情况下，控制台位于 `/h2-console`。
您可以使用 configprop:spring.h2.console.path[] 属性自定义控制台的路径。



[[data.sql.h2-web-console.spring-security]]
=== 在受保护的应用程序中访问 H2 控制台

H2 控制台使用框架，并且仅用于开发，不实现 CSRF 保护措施。
如果您的应用程序使用 Spring Security，您需要配置它以：

* 对控制台的请求禁用 CSRF 保护，
* 在控制台的响应中将 `X-Frame-Options` 头设置为 `SAMEORIGIN`。

有关 {url-spring-security-docs}/features/exploits/csrf.html[CSRF] 和 {url-spring-security-docs}/features/exploits/headers.html#headers-frame-options[X-Frame-Options] 头的更多信息，请参阅 Spring Security 参考指南。

在简单设置中，可以使用如下 javadoc:org.springframework.security.web.SecurityFilterChain[]：

include-code::DevProfileSecurityConfiguration[tag=!customizer]

WARNING: H2 控制台仅用于开发期间。
在生产环境中，禁用 CSRF 保护或允许网站框架可能导致严重的安全风险。

TIP: `PathRequest.toH2Console()` 返回正确的请求匹配器，即使控制台路径已被自定义。



[[data.sql.jooq]]
== 使用 jOOQ

jOOQ 对象导向查询（ https://www.jooq.org/[jOOQ]）是 https://www.datageekery.com/[Data Geekery] 的一个流行产品，它从您的数据库生成 Java 代码，并通过其流畅的 API 让您构建类型安全的 SQL 查询。
Spring Boot 支持商业版和开源版的 jOOQ。



[[data.sql.jooq.codegen]]
=== 代码生成

要使用 jOOQ 类型安全的查询，您需要从数据库模式生成 Java 类。
您可以按照 {url-jooq-docs}/#jooq-in-7-steps-step3[jOOQ 用户手册] 中的说明进行操作。
如果您使用 `jooq-codegen-maven` 插件，并且还使用 `spring-boot-starter-parent`“父 POM”，可以安全地省略插件的 `<version>` 标签。
您还可以使用 Spring Boot 定义的版本变量（例如 `h2.version`）来声明插件的数据库依赖。
以下列表显示了一个示例：

[source,xml]
----
<plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <executions>
        ...
    </executions>
    <dependencies>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
        </dependency>
    </dependencies>
    <configuration>
        <jdbc>
            <driver>org.h2.Driver</driver>
            <url>jdbc:h2:~/yourdatabase</url>
        </jdbc>
        <generator>
            ...
        </generator>
    </configuration>
</plugin>
----



[[data.sql.jooq.dslcontext]]
=== 使用 DSLContext

jOOQ 提供的流畅 API 通过 javadoc:org.jooq.DSLContext[] 接口启动。
Spring Boot 自动配置一个 javadoc:org.jooq.DSLContext[] 作为 Spring Bean，并将其连接到您的应用程序 javadoc:javax.sql.DataSource[]。
要使用 javadoc:org.jooq.DSLContext[]，您可以注入它，如下例所示：

include-code::MyBean[tag=!method]

TIP: jOOQ 手册倾向于使用名为 `create` 的变量来持有 javadoc:org.jooq.DSLContext[]。

然后，您可以使用 javadoc:org.jooq.DSLContext[] 构建查询，如下例所示：

include-code::MyBean[tag=method]



[[data.sql.jooq.sqldialect]]
=== jOOQ SQL 方言

除非配置了 configprop:spring.jooq.sql-dialect[] 属性，否则 Spring Boot 会为您的 DataSource 确定要使用的 SQL 方言。
如果 Spring Boot 无法检测到方言，它会使用 `DEFAULT`。

NOTE: Spring Boot 只能自动配置 jOOQ 开源版支持的方言。



[[data.sql.jooq.customizing]]
=== 自定义 jOOQ

更高级的自定义可以通过定义您自己的 javadoc:org.springframework.boot.autoconfigure.jooq.DefaultConfigurationCustomizer[] bean 实现，该 bean 将在创建 javadoc:org.jooq.Configuration[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 之前调用。
这优先于自动配置应用的任何内容。

如果您想完全控制 jOOQ 配置，还可以创建自己的 javadoc:org.jooq.Configuration[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。



[[data.sql.r2dbc]]
== 使用 R2DBC

反应式关系数据库连接（ https://r2dbc.io[R2DBC]）项目将反应式编程 API 引入关系数据库。
R2DBC 的 javadoc:io.r2dbc.spi.Connection[] 提供了一种使用非阻塞数据库连接的标准方法。
通过使用 javadoc:io.r2dbc.spi.ConnectionFactory[] 提供连接，类似于使用 javadoc:javax.sql.DataSource[] 的 JDBC。

javadoc:io.r2dbc.spi.ConnectionFactory[] 配置由 `+spring.r2dbc.*+` 中的外部配置属性控制。
例如，您可以在 `application.properties` 中声明以下部分：

[configprops,yaml]
----
spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost/test"
    username: "dbuser"
    password: "dbpass"
----

TIP: 您无需指定驱动类名称，因为 Spring Boot 从 R2DBC 的 Connection Factory 发现机制中获取驱动。

NOTE: 至少应提供 URL。
URL 中指定的信息优先于单独的属性，即 `name`、`username`、`password` 和池化选项。

TIP: “操作指南”部分包括一个 xref:how-to:data-initialization.adoc#howto.data-initialization.using-basic-sql-scripts[关于如何初始化数据库的部分]。

要自定义由 javadoc:io.r2dbc.spi.ConnectionFactory[] 创建的连接，例如设置您不希望（或无法）在中央数据库配置中配置的特定参数，可以使用 javadoc:org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryOptionsBuilderCustomizer[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。
以下示例展示了如何手动覆盖数据库端口，同时其余选项从应用程序配置中获取：

include-code::MyR2dbcConfiguration[]

以下示例展示了如何设置一些 PostgreSQL 连接选项：

include-code::MyPostgresR2dbcConfiguration[]

当 javadoc:io.r2dbc.spi.ConnectionFactory[] bean 可用时，常规 JDBC javadoc:javax.sql.DataSource[] 自动配置会回退。
如果您想保留 JDBC javadoc:javax.sql.DataSource[] 自动配置，并且能够接受在反应式应用程序中使用阻塞 JDBC API 的风险，请在应用程序的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类上添加 `@Import(DataSourceAutoConfiguration.class)`，以重新启用它。



[[data.sql.r2dbc.embedded]]
=== 嵌入式数据库支持

与 xref:data/sql.adoc#data.sql.datasource.embedded[JDBC 支持] 类似，Spring Boot 可以为反应式使用自动配置嵌入式数据库。
您无需提供任何连接 URL。
只需在构建依赖中包含您想使用的嵌入式数据库，如下例所示：

[source,xml]
----
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-h2</artifactId>
    <scope>runtime</scope>
</dependency>
----

[NOTE]
====
如果您在测试中使用此功能，您可能会注意到，无论使用多少个应用程序上下文，整个测试套件都会重用同一个数据库。
如果您想确保每个上下文都有一个独立的嵌入式数据库，应将 `spring.r2dbc.generate-unique-name` 设置为 `true`。
====



[[data.sql.r2dbc.using-database-client]]
=== 使用 DatabaseClient

javadoc:org.springframework.r2dbc.core.DatabaseClient[] bean 是自动配置的，您可以直接将其自动注入到自己的 bean 中，如下例所示：

include-code::MyBean[]



[[data.sql.r2dbc.repositories]]
=== Spring Data R2DBC 存储库

https://spring.io/projects/spring-data-r2dbc[Spring Data R2DBC] 存储库是您可以定义的接口，用于访问数据。
查询会根据您的方法名称自动创建。
例如，`CityRepository` 接口可能声明一个 `findAllByState(String state)` 方法来查找给定州的所有城市。

对于更复杂的查询，您可以使用 Spring Data 的 javadoc:org.springframework.data.r2dbc.repository.Query[format=annotation] 注解来注解您的方法。

Spring Data 存储库通常从 javadoc:org.springframework.data.repository.Repository[] 或 javadoc:org.springframework.data.repository.CrudRepository[] 接口扩展。
如果您使用自动配置，会搜索 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 中的存储库。

以下示例显示了一个典型的 Spring Data 存储库接口定义：

include-code::CityRepository[]

TIP: 我们只是浅谈了 Spring Data R2DBC 的表面。有关完整详情，请参阅 {url-spring-data-r2dbc-docs}[Spring Data R2DBC 参考文档]。