[[data.sql]]
= SQL Databases

{url-spring-framework-site}[Spring Framework] 提供了广泛的支持来使用 SQL 数据库，从使用 javadoc:org.springframework.jdbc.core.simple.JdbcClient[] 或 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 的直接 JDBC 访问，到完整的"对象关系映射"技术如 Hibernate。
{url-spring-data-site}[Spring Data] 提供了额外的功能层：直接从接口创建 javadoc:org.springframework.data.repository.Repository[] 实现，并使用约定从方法名生成查询。



[[data.sql.datasource]]
== Configure a DataSource

Java 的 javadoc:javax.sql.DataSource[] 接口提供了处理数据库连接的标准方法。
传统上，javadoc:javax.sql.DataSource[] 使用 `URL` 和一些凭据来建立数据库连接。

TIP: 有关更高级的示例，请参阅"操作指南"中的 xref:how-to:data-access.adoc#howto.data-access.configure-custom-datasource[] 部分，通常用于完全控制 DataSource 的配置。



[[data.sql.datasource.embedded]]
=== Embedded Database Support

使用内存嵌入式数据库开发应用程序通常很方便。
显然，内存数据库不提供持久化存储。
您需要在应用程序启动时填充数据库，并在应用程序结束时准备丢弃数据。

TIP: "操作指南"部分包含一个关于 xref:how-to:data-initialization.adoc[如何初始化数据库]的部分。

Spring Boot 可以自动配置嵌入式 https://www.h2database.com[H2]、https://hsqldb.org/[HSQL] 和 https://db.apache.org/derby/[Derby] 数据库。
您不需要提供任何连接 URL。
您只需要包含您想要使用的嵌入式数据库的构建依赖项。
如果类路径上有多个嵌入式数据库，请设置 configprop:spring.datasource.embedded-database-connection[] 配置属性来控制使用哪一个。
将该属性设置为 `none` 将禁用嵌入式数据库的自动配置。

[NOTE]
====
如果您在测试中使用此功能，您可能会注意到，无论您使用多少个应用程序上下文，整个测试套件都会重用相同的数据库。
如果您想确保每个上下文都有单独的嵌入式数据库，您应该将 `spring.datasource.generate-unique-name` 设置为 `true`。
====

例如，典型的 POM 依赖项如下：

[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
	<groupId>org.hsqldb</groupId>
	<artifactId>hsqldb</artifactId>
	<scope>runtime</scope>
</dependency>
----

NOTE: 您需要 `spring-jdbc` 依赖项才能自动配置嵌入式数据库。
在此示例中，它是通过 `spring-boot-starter-data-jpa` 传递引入的。

TIP: 如果出于任何原因，您为嵌入式数据库配置了连接 URL，请注意确保禁用数据库的自动关闭。
如果您使用 H2，您应该使用 `DB_CLOSE_ON_EXIT=FALSE` 来做到这一点。
如果您使用 HSQLDB，您应该确保不使用 `shutdown=true`。
禁用数据库的自动关闭可以让 Spring Boot 控制数据库的关闭时间，从而确保在不再需要访问数据库时才关闭它。



[[data.sql.datasource.production]]
=== Connection to a Production Database

生产数据库连接也可以通过使用池化的 javadoc:javax.sql.DataSource[] 来自动配置。



[[data.sql.datasource.configuration]]
=== DataSource Configuration

DataSource 配置由 `+spring.datasource.*+` 中的外部配置属性控制。
例如，您可能在 `application.properties` 中声明以下部分：

[configprops,yaml]
----
spring:
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
----

NOTE: 您应该至少通过设置 configprop:spring.datasource.url[] 属性来指定 URL。
否则，Spring Boot 会尝试自动配置嵌入式数据库。

TIP: Spring Boot 可以从 URL 推断大多数数据库的 JDBC 驱动程序类。
如果您需要指定特定的类，您可以使用 configprop:spring.datasource.driver-class-name[] 属性。

NOTE: 要创建池化的 javadoc:javax.sql.DataSource[]，我们需要能够验证可用的 javadoc:java.sql.Driver[] 类，因此我们在做任何事情之前都会检查它。
换句话说，如果您设置 `spring.datasource.driver-class-name=com.mysql.jdbc.Driver`，那么该类必须可加载。

有关更多支持的选项，请参阅 javadoc:org.springframework.boot.autoconfigure.jdbc.DataSourceProperties[] API 文档。
这些是标准选项，无论 xref:data/sql.adoc#data.sql.datasource.connection-pool[实际实现]如何都能工作。
也可以通过使用各自的前缀（`+spring.datasource.hikari.*+`、`+spring.datasource.tomcat.*+`、`+spring.datasource.dbcp2.*+` 和 `+spring.datasource.oracleucp.*+`）来微调特定实现的设置。
有关更多详细信息，请参阅您使用的连接池实现的文档。

例如，如果您使用 {url-tomcat-docs}/jdbc-pool.html#Common_Attributes[Tomcat 连接池]，您可以自定义许多其他设置，如下例所示：

[configprops,yaml]
----
spring:
  datasource:
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
----

这将设置池在无连接可用时等待 10000ms 后抛出异常，将最大连接数限制为 50，并在从池中借用连接之前验证连接。



[[data.sql.datasource.connection-pool]]
=== Supported Connection Pools

Spring Boot 使用以下算法选择特定实现：

. 我们更喜欢 https://github.com/brettwooldridge/HikariCP[HikariCP]，因为它具有性能和并发性。
如果 HikariCP 可用，我们总是选择它。
. 否则，如果 Tomcat 池化的 javadoc:javax.sql.DataSource[] 可用，我们使用它。
. 否则，如果 https://commons.apache.org/proper/commons-dbcp/[Commons DBCP2] 可用，我们使用它。
. 如果 HikariCP、Tomcat 和 DBCP2 都不可用，并且如果 Oracle UCP 可用，我们使用它。

NOTE: 如果您使用 `spring-boot-starter-jdbc` 或 `spring-boot-starter-data-jpa` starters，您会自动获得 HikariCP 依赖项。

您可以通过设置 configprop:spring.datasource.type[] 属性来完全绕过该算法并指定要使用的连接池。
这在 Tomcat 容器中运行应用程序时尤其重要，因为默认提供 `tomcat-jdbc`。

始终可以使用 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 手动配置其他连接池。
如果您定义自己的 javadoc:javax.sql.DataSource[] bean，则不会发生自动配置。
javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 支持以下连接池：

* HikariCP
* Tomcat 池化的 javadoc:javax.sql.DataSource[]
* Commons DBCP2
* Oracle UCP & `OracleDataSource`
* Spring Framework 的 javadoc:org.springframework.jdbc.datasource.SimpleDriverDataSource[]
* H2 javadoc:org.h2.jdbcx.JdbcDataSource[]
* PostgreSQL javadoc:org.postgresql.ds.PGSimpleDataSource[]
* C3P0



[[data.sql.datasource.jndi]]
=== Connection to a JNDI DataSource

如果您将 Spring Boot 应用程序部署到应用程序服务器，您可能希望使用应用程序服务器的内置功能来配置和管理 DataSource，并通过 JNDI 访问它。

configprop:spring.datasource.jndi-name[] 属性可以用作 configprop:spring.datasource.url[]、configprop:spring.datasource.username[] 和 configprop:spring.datasource.password[] 属性的替代方案，以从特定 JNDI 位置访问 javadoc:javax.sql.DataSource[]。
例如，`application.properties` 中的以下部分显示了如何访问 JBoss AS 定义的 javadoc:javax.sql.DataSource[]：

[configprops,yaml]
----
spring:
  datasource:
    jndi-name: "java:jboss/datasources/customers"
----



[[data.sql.jdbc-template]]
== Using JdbcTemplate

Spring 的 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 和 javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 类是自动配置的，您可以将它们直接自动装配到您自己的 bean 中，如下例所示：

include-code::MyBean[]

您可以使用 `spring.jdbc.template.*` 属性自定义模板的某些属性，如下例所示：

[configprops,yaml]
----
spring:
  jdbc:
    template:
      max-rows: 500
----

NOTE: javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 在后台重用相同的 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 实例。
如果定义了多个 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 且不存在主要候选者，则不会自动配置 javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[]。



[[data.sql.jdbc-client]]
== Using JdbcClient

Spring 的 javadoc:org.springframework.jdbc.core.simple.JdbcClient[] 基于 javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 的存在而自动配置。
您也可以将其直接注入到您自己的 bean 中，如下例所示：

include-code::MyBean[]

如果您依赖自动配置来创建底层的 javadoc:org.springframework.jdbc.core.JdbcTemplate[]，则使用 `spring.jdbc.template.*` 属性进行的任何自定义也会在客户端中生效。



[[data.sql.jpa-and-spring-data]]
== JPA and Spring Data JPA

Java Persistence API 是一种标准技术，允许您将对象"映射"到关系数据库。
`spring-boot-starter-data-jpa` POM 提供了一种快速入门的方式。
它提供以下关键依赖项：

* Hibernate：最流行的 JPA 实现之一。
* Spring Data JPA：帮助您实现基于 JPA 的存储库。
* Spring ORM：来自 Spring Framework 的核心 ORM 支持。

TIP: 我们在这里不会过多讨论 JPA 或 {url-spring-data-site}[Spring Data]。
您可以按照 https://spring.io 的 https://spring.io/guides/gs/accessing-data-jpa/[使用 JPA 访问数据]指南，并阅读 {url-spring-data-jpa-site}[Spring Data JPA] 和 https://hibernate.org/orm/documentation/[Hibernate] 参考文档。



[[data.sql.jpa-and-spring-data.entity-classes]]
=== Entity Classes

传统上，JPA "Entity" 类在 `persistence.xml` 文件中指定。
使用 Spring Boot，不需要此文件，而是使用"Entity Scanning"。
默认情况下，会扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。

任何使用 javadoc:jakarta.persistence.Entity[format=annotation]、javadoc:jakarta.persistence.Embeddable[format=annotation] 或 javadoc:jakarta.persistence.MappedSuperclass[format=annotation] 注解的类都会被考虑。
典型的实体类类似于以下示例：

include-code::City[]

TIP: 您可以使用 javadoc:org.springframework.boot.autoconfigure.domain.EntityScan[format=annotation] 注解自定义实体扫描位置。
请参阅"操作指南"中的 xref:how-to:data-access.adoc#howto.data-access.separate-entity-definitions-from-spring-configuration[] 部分。



[[data.sql.jpa-and-spring-data.repositories]]
=== Spring Data JPA Repositories

{url-spring-data-jpa-site}[Spring Data JPA] 存储库是您可以定义用于访问数据的接口。
JPA 查询会根据您的方法名自动创建。
例如，`CityRepository` 接口可能声明 `findAllByState(String state)` 方法来查找给定州的所有城市。

对于更复杂的查询，您可以使用 Spring Data 的 javadoc:org.springframework.data.jpa.repository.Query[] 注解来注解您的方法。

Spring Data 存储库通常从 javadoc:org.springframework.data.repository.Repository[] 或 javadoc:org.springframework.data.repository.CrudRepository[] 接口扩展。
如果您使用自动配置，则会搜索 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]中的存储库。

TIP: 您可以使用 javadoc:org.springframework.data.jpa.repository.config.EnableJpaRepositories[format=annotation] 自定义查找存储库的位置。

以下示例显示了典型的 Spring Data 存储库接口定义：

include-code::CityRepository[]

Spring Data JPA 存储库支持三种不同的引导模式：默认、延迟和惰性。
要启用延迟或惰性引导，请将 configprop:spring.data.jpa.repositories.bootstrap-mode[] 属性设置为 `deferred` 或 `lazy`。
使用延迟或惰性引导时，自动配置的 javadoc:org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder[] 将使用上下文的 javadoc:org.springframework.core.task.AsyncTaskExecutor[]（如果有）作为引导执行器。
如果存在多个，将使用名为 `applicationTaskExecutor` 的执行器。

[NOTE]
====
使用延迟或惰性引导时，请确保将任何对 JPA 基础设施的访问推迟到应用程序上下文引导阶段之后。
您可以使用 javadoc:org.springframework.beans.factory.SmartInitializingSingleton[] 来调用需要 JPA 基础设施的任何初始化。
对于作为 Spring bean 创建的 JPA 组件（如转换器），如果存在任何依赖项，请使用 javadoc:org.springframework.beans.factory.ObjectProvider[] 延迟解析依赖项。
====

TIP: 我们只是简单介绍了 Spring Data JPA。
有关完整详细信息，请参阅 {url-spring-data-jpa-docs}[Spring Data JPA 参考文档]。



[[data.sql.jpa-and-spring-data.envers-repositories]]
=== Spring Data Envers Repositories

如果 {url-spring-data-envers-site}[Spring Data Envers] 可用，JPA 存储库会自动配置以支持典型的 Envers 查询。

要使用 Spring Data Envers，请确保您的存储库从 javadoc:org.springframework.data.repository.history.RevisionRepository[] 扩展，如下例所示：

include-code::CountryRepository[]

NOTE: 有关更多详细信息，请查看 {url-spring-data-jpa-docs}/envers.html[Spring Data Envers 参考文档]。



[[data.sql.jpa-and-spring-data.creating-and-dropping]]
=== Creating and Dropping JPA Databases

默认情况下，仅当您使用嵌入式数据库（H2、HSQL 或 Derby）时，才会自动创建 JPA 数据库。
您可以使用 `+spring.jpa.*+` 属性显式配置 JPA 设置。
例如，要创建和删除表，您可以在 `application.properties` 中添加以下行：

[configprops,yaml]
----
spring:
  jpa:
    hibernate.ddl-auto: "create-drop"
----

NOTE: Hibernate 自己的内部属性名称（如果您碰巧记得更好）是 `hibernate.hbm2ddl.auto`。
您可以使用 `+spring.jpa.properties.*+` 设置它以及其他 Hibernate 原生属性（在将它们添加到实体管理器之前会删除前缀）。
以下行显示了为 Hibernate 设置 JPA 属性的示例：

[configprops,yaml]
----
spring:
  jpa:
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
----

前面示例中的行将 `hibernate.globally_quoted_identifiers` 属性的值 `true` 传递给 Hibernate 实体管理器。

默认情况下，DDL 执行（或验证）会推迟到 javadoc:org.springframework.context.ApplicationContext[] 启动后。



[[data.sql.jpa-and-spring-data.open-entity-manager-in-view]]
=== Open EntityManager in View

如果您运行 Web 应用程序，Spring Boot 默认注册 javadoc:org.springframework.orm.jpa.support.OpenEntityManagerInViewInterceptor[] 以应用"Open EntityManager in View"模式，以允许在 Web 视图中进行延迟加载。
如果您不希望这种行为，您应该在 `application.properties` 中将 `spring.jpa.open-in-view` 设置为 `false`。



[[data.sql.jdbc]]
== Spring Data JDBC

Spring Data 包括对 JDBC 的存储库支持，并将自动为 javadoc:org.springframework.data.repository.CrudRepository[] 上的方法生成 SQL。
对于更高级的查询，提供了 javadoc:org.springframework.data.jdbc.repository.query.Query[format=annotation] 注解。

当必要的依赖项在类路径上时，Spring Boot 将自动配置 Spring Data 的 JDBC 存储库。
它们可以通过单个依赖项 `spring-boot-starter-data-jdbc` 添加到您的项目中。
如果需要，您可以通过添加 javadoc:org.springframework.data.jdbc.repository.config.EnableJdbcRepositories[format=annotation] 注解或 javadoc:org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration[] 子类到您的应用程序来控制 Spring Data JDBC 的配置。

TIP: 有关 Spring Data JDBC 的完整详细信息，请参阅 {url-spring-data-jdbc-docs}[参考文档]。



[[data.sql.h2-web-console]]
== Using H2's Web Console

https://www.h2database.com[H2 数据库] 提供了 https://www.h2database.com/html/quickstart.html#h2_console[基于浏览器的控制台]，Spring Boot 可以为您自动配置。
在满足以下条件时，控制台会自动配置：

* 您正在开发基于 servlet 的 Web 应用程序。
* `com.h2database:h2` 在类路径上。
* 您正在使用 xref:using/devtools.adoc[Spring Boot 的开发者工具]。

TIP: 如果您不使用 Spring Boot 的开发者工具但仍想使用 H2 的控制台，您可以将 configprop:spring.h2.console.enabled[] 属性配置为 `true`。

NOTE: H2 控制台仅用于开发，因此您应该确保在生产环境中不要将 `spring.h2.console.enabled` 设置为 `true`。



[[data.sql.h2-web-console.custom-path]]
=== Changing the H2 Console's Path

默认情况下，控制台在 `/h2-console` 可用。
您可以使用 configprop:spring.h2.console.path[] 属性自定义控制台的路径。



[[data.sql.h2-web-console.spring-security]]
=== Accessing the H2 Console in a Secured Application

H2 控制台使用框架，并且由于它仅用于开发，因此不实现 CSRF 保护措施。
如果您的应用程序使用 Spring Security，您需要配置它以

* 禁用对控制台请求的 CSRF 保护，
* 在来自控制台的响应上设置 `X-Frame-Options` 头为 `SAMEORIGIN`。

有关 {url-spring-security-docs}/features/exploits/csrf.html[CSRF] 和 {url-spring-security-docs}/features/exploits/headers.html#headers-frame-options[X-Frame-Options] 头的更多信息可以在 Spring Security 参考指南中找到。

在简单设置中，可以使用如下所示的 javadoc:org.springframework.security.web.SecurityFilterChain[]：

include-code::DevProfileSecurityConfiguration[tag=!customizer]

WARNING: H2 控制台仅用于开发。
在生产环境中，禁用 CSRF 保护或允许网站使用框架可能会造成严重的安全风险。

TIP: 即使控制台的路径已自定义，`PathRequest.toH2Console()` 也会返回正确的请求匹配器。



[[data.sql.jooq]]
== Using jOOQ

jOOQ Object Oriented Querying (https://www.jooq.org/[jOOQ]) 是 https://www.datageekery.com/[Data Geekery] 的一个流行产品，它从您的数据库生成 Java 代码，并让您通过其流畅的 API 构建类型安全的 SQL 查询。
商业版和开源版都可以与 Spring Boot 一起使用。



[[data.sql.jooq.codegen]]
=== Code Generation

为了使用 jOOQ 类型安全的查询，您需要从数据库模式生成 Java 类。
您可以按照 {url-jooq-docs}/#jooq-in-7-steps-step3[jOOQ 用户手册]中的说明进行操作。
如果您使用 `jooq-codegen-maven` 插件并且还使用 `spring-boot-starter-parent` "parent POM"，您可以安全地省略插件的 `<version>` 标签。
您还可以使用 Spring Boot 定义的版本变量（如 `h2.version`）来声明插件的数据库依赖项。
以下列表显示了一个示例：

[source,xml]
----
<plugin>
	<groupId>org.jooq</groupId>
	<artifactId>jooq-codegen-maven</artifactId>
	<executions>
		...
	</executions>
	<dependencies>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>${h2.version}</version>
		</dependency>
	</dependencies>
	<configuration>
		<jdbc>
			<driver>org.h2.Driver</driver>
			<url>jdbc:h2:~/yourdatabase</url>
		</jdbc>
		<generator>
			...
		</generator>
	</configuration>
</plugin>
----



[[data.sql.jooq.dslcontext]]
=== Using DSLContext

jOOQ 提供的流畅 API 通过 javadoc:org.jooq.DSLContext[] 接口启动。
Spring Boot 将 javadoc:org.jooq.DSLContext[] 自动配置为 Spring Bean 并将其连接到您的应用程序 javadoc:javax.sql.DataSource[]。
要使用 javadoc:org.jooq.DSLContext[]，您可以注入它，如下例所示：

include-code::MyBean[tag=!method]

TIP: jOOQ 手册倾向于使用名为 `create` 的变量来保存 javadoc:org.jooq.DSLContext[]。

然后，您可以使用 javadoc:org.jooq.DSLContext[] 来构建您的查询，如下例所示：

include-code::MyBean[tag=method]



[[data.sql.jooq.sqldialect]]
=== jOOQ SQL Dialect

除非已配置 configprop:spring.jooq.sql-dialect[] 属性，否则 Spring Boot 会确定用于您的数据源的 SQL 方言。
如果 Spring Boot 无法检测到方言，它将使用 `DEFAULT`。

NOTE: Spring Boot 只能自动配置 jOOQ 开源版本支持的方言。



[[data.sql.jooq.customizing]]
=== Customizing jOOQ

可以通过定义您自己的 javadoc:org.springframework.boot.autoconfigure.jooq.DefaultConfigurationCustomizer[] bean 来实现更高级的自定义，该 bean 将在创建 javadoc:org.jooq.Configuration[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 之前被调用。
这优先于自动配置应用的任何内容。

如果您想完全控制 jOOQ 配置，您也可以创建自己的 javadoc:org.jooq.Configuration[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。



[[data.sql.r2dbc]]
== Using R2DBC

Reactive Relational Database Connectivity (https://r2dbc.io[R2DBC]) 项目为关系数据库带来了响应式编程 API。
R2DBC 的 javadoc:io.r2dbc.spi.Connection[] 提供了一种处理非阻塞数据库连接的标准方法。
连接通过使用 javadoc:io.r2dbc.spi.ConnectionFactory[] 提供，类似于带有 jdbc 的 javadoc:javax.sql.DataSource[]。

javadoc:io.r2dbc.spi.ConnectionFactory[] 配置由 `+spring.r2dbc.*+` 中的外部配置属性控制。
例如，您可能在 `application.properties` 中声明以下部分：

[configprops,yaml]
----
spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost/test"
    username: "dbuser"
    password: "dbpass"
----

TIP: 您不需要指定驱动程序类名，因为 Spring Boot 从 R2DBC 的 Connection Factory 发现中获取驱动程序。

NOTE: 至少应该提供 url。
URL 中指定的信息优先于各个属性，即 `name`、`username`、`password` 和池选项。

TIP: "操作指南"部分包含一个关于 xref:how-to:data-initialization.adoc#howto.data-initialization.using-basic-sql-scripts[如何初始化数据库]的部分。

要自定义由 javadoc:io.r2dbc.spi.ConnectionFactory[] 创建的连接，即设置您不想（或不能）在中央数据库配置中配置的特定参数，您可以使用 javadoc:org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryOptionsBuilderCustomizer[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。
以下示例显示了如何手动覆盖数据库端口，同时其余选项从应用程序配置中获取：

include-code::MyR2dbcConfiguration[]

以下示例显示了如何设置一些 PostgreSQL 连接选项：

include-code::MyPostgresR2dbcConfiguration[]

当 javadoc:io.r2dbc.spi.ConnectionFactory[] bean 可用时，常规 JDBC javadoc:javax.sql.DataSource[] 自动配置会退出。
如果您想保留 JDBC javadoc:javax.sql.DataSource[] 自动配置，并且愿意在响应式应用程序中使用阻塞 JDBC API 的风险，请在应用程序中的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类上添加 `@Import(DataSourceAutoConfiguration.class)` 以重新启用它。



[[data.sql.r2dbc.embedded]]
=== Embedded Database Support

与 xref:data/sql.adoc#data.sql.datasource.embedded[JDBC 支持]类似，Spring Boot 可以自动配置嵌入式数据库用于响应式使用。
您不需要提供任何连接 URL。
您只需要包含您想要使用的嵌入式数据库的构建依赖项，如下例所示：

[source,xml]
----
<dependency>
	<groupId>io.r2dbc</groupId>
	<artifactId>r2dbc-h2</artifactId>
	<scope>runtime</scope>
</dependency>
----

[NOTE]
====
如果您在测试中使用此功能，您可能会注意到，无论您使用多少个应用程序上下文，整个测试套件都会重用相同的数据库。
如果您想确保每个上下文都有单独的嵌入式数据库，您应该将 `spring.r2dbc.generate-unique-name` 设置为 `true`。
====



[[data.sql.r2dbc.using-database-client]]
=== Using DatabaseClient

javadoc:org.springframework.r2dbc.core.DatabaseClient[] bean 是自动配置的，您可以将它直接自动装配到您自己的 bean 中，如下例所示：

include-code::MyBean[]



[[data.sql.r2dbc.repositories]]
=== Spring Data R2DBC Repositories

https://spring.io/projects/spring-data-r2dbc[Spring Data R2DBC] 存储库是您可以定义用于访问数据的接口。
查询会根据您的方法名自动创建。
例如，`CityRepository` 接口可能声明 `findAllByState(String state)` 方法来查找给定州的所有城市。

对于更复杂的查询，您可以使用 Spring Data 的 javadoc:org.springframework.data.r2dbc.repository.Query[format=annotation] 注解来注解您的方法。

Spring Data 存储库通常从 javadoc:org.springframework.data.repository.Repository[] 或 javadoc:org.springframework.data.repository.CrudRepository[] 接口扩展。
如果您使用自动配置，则会搜索 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]中的存储库。

以下示例显示了典型的 Spring Data 存储库接口定义：

include-code::CityRepository[]

TIP: 我们只是简单介绍了 Spring Data R2DBC。有关完整详细信息，请参阅 {url-spring-data-r2dbc-docs}[Spring Data R2DBC 参考文档]。
